elastic/detection-rules

rules/okta/credential_access_attempted_bypass_of_okta_mfa.toml, rules/okta/impact_attempt_to_revoke_okta_api_token.toml, rules/okta/impact_possible_okta_dos_attack.toml, rules/okta/initial_access_suspicious_activity_reported_by_okta_user.toml, rules/okta/okta_attempt_to_deactivate_okta_mfa_rule.toml, rules/okta/okta_attempt_to_delete_okta_policy.toml, rules/okta/okta_attempt_to_modify_okta_mfa_rule.toml, rules/okta/okta_attempt_to_modify_okta_network_zone.toml, rules/okta/okta_attempt_to_modify_okta_policy.toml, rules/okta/okta_threat_detected_by_okta_threatinsight.toml, rules/okta/persistence_administrator_privileges_assigned_to_okta_group.toml, rules/okta/persistence_attempt_to_create_okta_api_token.toml, rules/okta/persistence_attempt_to_deactivate_mfa_for_okta_user_account.toml, rules/okta/persistence_attempt_to_deactivate_okta_policy.toml, rules/okta/persistence_attempt_to_reset_mfa_factors_for_okta_user_account.toml
Resolves  #18 
Add `event.module:okta` to Okta rules for consistency with [this rule](https://github.com/elastic/detection-rules/blob/main/rules/okta/okta_attempt_to_modify_or_delete_application_sign_on_policy.toml).
=> [Rule Tuning] Add event.module value to Okta rules

rules/promotions/elastic_endpoint.toml, rules/promotions/endpoint_adversary_behavior_detected.toml, rules/promotions/endpoint_cred_dumping_detected.toml, rules/promotions/endpoint_cred_dumping_prevented.toml, rules/promotions/endpoint_cred_manipulation_detected.toml, rules/promotions/endpoint_cred_manipulation_prevented.toml, rules/promotions/endpoint_exploit_detected.toml, rules/promotions/endpoint_exploit_prevented.toml, rules/promotions/endpoint_malware_detected.toml, rules/promotions/endpoint_malware_prevented.toml, rules/promotions/endpoint_permission_theft_detected.toml, rules/promotions/endpoint_permission_theft_prevented.toml, rules/promotions/endpoint_process_injection_detected.toml, rules/promotions/endpoint_process_injection_prevented.toml, rules/promotions/endpoint_ransomware_detected.toml, rules/promotions/endpoint_ransomware_prevented.toml
resolves #71 
This PR updates the terms used in the promotion rules from the Endpoint need to be updated to account for naming conventions used in the product.
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? a/a
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)? yes
=> [Rule Tuning] Update terms in promotion rules

rules/promotions/endpoint_adversary_behavior_detected.toml, rules/promotions/endpoint_cred_dumping_detected.toml, rules/promotions/endpoint_cred_dumping_prevented.toml, rules/promotions/endpoint_cred_manipulation_detected.toml, rules/promotions/endpoint_cred_manipulation_prevented.toml, rules/promotions/endpoint_exploit_detected.toml, rules/promotions/endpoint_exploit_prevented.toml, rules/promotions/endpoint_malware_detected.toml, rules/promotions/endpoint_malware_prevented.toml, rules/promotions/endpoint_permission_theft_detected.toml, rules/promotions/endpoint_permission_theft_prevented.toml, rules/promotions/endpoint_process_injection_detected.toml, rules/promotions/endpoint_process_injection_prevented.toml, rules/promotions/endpoint_ransomware_detected.toml, rules/promotions/endpoint_ransomware_prevented.toml
This PR corrects the promotion rule descriptions to account for the references to the External alerts tab.
See https://github.com/elastic/kibana/pull/72613#issuecomment-662439006 for reference. 
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? n/a
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)? yes
=> [Rule Tuning] Correct Promotion Rule Descriptions

CONTRIBUTING.md
Resolves #218 
The community has asked various members of this repository "how can I help" and "where to get started".
This PR adds the "help wanted" label to the contributing guide.
=> Add help wanted label to contrib

etc/version.lock.json
None
lock versions from 7.9.1 changes
=> Lock rule versions for 7.9

rules/azure/persistence_azure_automation_runbook_created_or_modified.toml
Resolves #108 
Identifies when an Azure Automation runbook is created or modified. An adversary may create or modify an Azure Automation runbook to execute malicious code and maintain persistence in their target's environment.
=> [New Rule] Azure Automation Runbook Created or Modified

rules/azure/persistence_azure_automation_webhook_created.toml
Resolves #110 
Identifies when an Azure Automation webhook is created. Azure Automation runbooks can be configured to execute via a
webhook. A webhook is a custom URL passed to Azure Automation along with a data payload specific to the runbook. An
adversary may create a webhook in order to trigger a runbook that contains malicious code.
=> [New Rule] Azure Automation Webhook Created

rules/azure/defense_evasion_azure_privileged_identity_management_role_modified.toml
Resolves #144 
Azure Active Directory (AD) Privileged Identity Management (PIM) is a service that enables you to manage, control, and monitor access to important resources in an organization. PIM can be used to manage the built-in Azure resource roles such as Global Administrator and Application Administrator. An adversary may add a user to a PIM role in order to maintain persistence in their target's environment or modify a PIM role to weaken their target's security controls.
=> [New Rule] Azure Privileged Identity Management Role Modified

rules/azure/persistence_user_added_as_owner_for_azure_service_principal.toml
Resolved  #194 
Tuning a single Azure rule to amend the rule name and add ATT&CK metadata.
=> [Rule Tuning] User Added as Owner for Azure Service Principal

rules/azure/credential_access_key_vault_modified.toml, rules/azure/credential_access_key_vault_update.toml
resolves #175 
Identifies updates to a Key Vault in Azure. The Key Vault is a service that safeguards encryption keys and secrets like certificates, connection strings, and passwords. Because this data is sensitive and business critical, access to key vaults should be secured to allow only authorized applications and users.
-- 1.4.0
- detonate
=> [New Rule] Azure Key Vault Modified

rules/ml/ml_linux_anomalous_metadata_process.toml
https://github.com/elastic/mechagodzilla/issues/102
ML rule for the Linux version of the job that looks for rare process name calling the metadata service
=> [New Rule] Unusual Process Calling the Metadata Service [Linux]

rules/ml/ml_linux_anomalous_sudo_activity.toml
https://github.com/elastic/mechagodzilla/issues/106
Added T1548 to the metadata
=> Add Tags to Unusual Sudo Activity Rule

kibana/connector.py
resolves #403 
To account for changes to the login data structure while still maintaining backwards compatibility for pre-7.10, the `connector` will first attempt the old structure and if the specific failure is detected, attempt the updated structure.
=> [Bug] Fix Kibana connector to work with 7.10

CONTRIBUTING.md
Closes #519
Added a link. This look good, @fw-at-elastic?
=> Link to the Elastic contributor program

rules/windows/privilege_escalation_uac_bypass_com_ieinstal.toml
Resolves https://github.com/elastic/detection-rules/issues/449
=> [New Rule] UAC Bypass via Elevated COM IEinstall

rules/windows/execution_suspicious_short_program_name.toml
Resolves https://github.com/elastic/detection-rules/issues/535
=> [New Rule] Suspicious Execution - Short Program Name

rules/macos/credential_access_promt_for_pwd_via_osascript.toml
Resolves https://github.com/elastic/detection-rules/issues/539
=> [New Rule] Prompt for Credentials with OSASCRIPT

rules/linux/defense_evasion_timestomp_touch.toml
Resolves https://github.com/elastic/detection-rules/issues/462
=> [New Rule] Timestomping using Touch Command

rules/windows/credential_access_kerberoasting_unusual_process.toml
Resolves https://github.com/elastic/detection-rules/issues/447
=> [New Rule] Kerberos Traffic from Unusual Process

rules/windows/command_and_control_common_webservices.toml
Resolves https://github.com/elastic/detection-rules/issues/475
=> [New Rule] Connection to Commonly Abused Web Services

rules/windows/lateral_movement_suspicious_rdp_client_imageload.toml
Resolves https://github.com/elastic/detection-rules/issues/587
=> [New Rule] Suspicious RDP ActiveX Client Loaded

rules/windows/persistence_suspicious_image_load_scheduled_task_ms_office.toml
Resolves https://github.com/elastic/detection-rules/issues/560
Detects suspicious activity related to image load by COM component for task scheduler (taskschd.dll) from MS Office products
=> [New-Rule] Suspicious Task Scheduler Image Load from MS Office

rules/windows/execution_suspicious_image_load_wmi_ms_office.toml
Resolves https://github.com/elastic/detection-rules/issues/543
Detects suspicious activity related to WMI image load (wmiutils.dll) from MS Office products
=> [New-Rule] Suspicious WMI Image Load from MS Office

rules/windows/persistence_ms_outlook_vba_template.toml
Resolves https://github.com/elastic/detection-rules/issues/610
=> [New Rule] Persistence via Microsoft Outlook VBA

rules/cross-platform/defense_evasion_deleting_websvr_access_logs.toml
Resolves https://github.com/elastic/detection-rules/issues/456
=> [New Rule] WebServer Access Logs Deleted

rules/network/command_and_control_dns_directly_to_the_internet.toml, rules/network/command_and_control_ftp_file_transfer_protocol_activity_to_the_internet.toml, rules/network/command_and_control_irc_internet_relay_chat_protocol_activity_to_the_internet.toml, rules/network/command_and_control_port_8000_activity_to_the_internet.toml, rules/network/command_and_control_proxy_port_activity_to_the_internet.toml, rules/network/command_and_control_rdp_remote_desktop_protocol_from_the_internet.toml, rules/network/command_and_control_smtp_to_the_internet.toml, rules/network/command_and_control_sql_server_port_activity_to_the_internet.toml, rules/network/command_and_control_ssh_secure_shell_from_the_internet.toml, rules/network/command_and_control_ssh_secure_shell_to_the_internet.toml, rules/network/command_and_control_tor_activity_to_the_internet.toml, rules/network/command_and_control_vnc_virtual_network_computing_from_the_internet.toml, rules/network/command_and_control_vnc_virtual_network_computing_to_the_internet.toml, rules/network/initial_access_rdp_remote_desktop_protocol_to_the_internet.toml, rules/network/initial_access_rpc_remote_procedure_call_from_the_internet.toml, rules/network/initial_access_rpc_remote_procedure_call_to_the_internet.toml, rules/network/initial_access_smb_windows_file_sharing_activity_to_the_internet.toml
Resolves #409 
Add additional IP address ranges to improve efficacy of network rules. See #409 for further information.
Reformat queries to help with readability.
=> [Rule Tuning] Update IP Address Ranges in Multiple Rules

rules/macos/execution_shell_execution_via_apple_scripting.toml
Resolves https://github.com/elastic/detection-rules/issues/686
=> [New Rule] Shell Execution via Apple Scripting

rules/macos/persistence_folder_action_scripts_runtime.toml
Resolves https://github.com/elastic/detection-rules/issues/684
=> [New Rule] Persistence via Folder Action Script

detection_rules/eswrap.py, docs/ML_DGA.md
=> [Docs] Update ML_DGA.md

rules/windows/persistence_startup_folder_scripts.toml
Resolves #708 
Replace all line comments with block comments (looks like there was only a single rule).
=> [Rule Tuning] Replace line comments with block comments

rules/windows/lateral_movement_scheduled_task_powershell_source.toml
Resolves https://github.com/elastic/detection-rules/issues/724
=> [New Rule] Outbound Scheduled Tasks Activity via PowerShell

detection_rules/main.py
None
adds flattened subtechniques to `rule-search`. Primary benefit is the ability to columnize it with `-c subtechniques`
=> Add flattened subtechniques to rule-search

detection_rules/devtools.py, docs/ML_DGA.md
None
Updated ML-DGA docs and added requirement to include a readme in ML experimental detection releases
=> Update ML-DGA docs

rules/microsoft-365/initial_access_microsoft_365_exchange_safelinks_disabled.toml
Discovered in https://github.com/elastic/kibana/issues/87090
Fixed a typo
=> Fix spelling of Continuous Monitoring

rules/azure/initial_access_azure_active_directory_high_risk_signin.toml
resolves #731 
Identifies high risk Azure Active Directory (AD) sign-ins by leveraging Microsoft's Identity Protection machine learning and heuristics. Identity Protection categorizes risk into three tiers: low, medium, and high. While Microsoft does not provide specific details about how risk is calculated, each level brings higher confidence that the user or sign-in is
compromised.
=> [New Rule] Azure Active Directory High Risk Sign-in

rules/windows/persistence_evasion_hidden_local_account_creation.toml
Resolves https://github.com/elastic/detection-rules/issues/737
=> [New Rule] Creation of a Hidden Local User Account

rules/cross-platform/credential_access_cookies_chromium_browsers_debugging.toml
Resolves https://github.com/elastic/detection-rules/issues/740
=> [New Rule] Potential Cookies Theft via Browser Debugging

rules/macos/persistence_loginwindow_plist_modification.toml
Resolves https://github.com/elastic/detection-rules/issues/899
=> [New Rule] Potential Persistence via Login Hook

rules/macos/persistence_docker_shortcuts_plist_modification.toml
Resolves https://github.com/elastic/detection-rules/issues/732
=> [New Rule] Persistence via Docker Shortcut Modification

rules/cross-platform/persistence_ssh_authorized_keys_modification.toml
Resolves https://github.com/elastic/detection-rules/issues/753
=> [New Rule] SSH Authorized Keys File Modification

rules/macos/defense_evasion_tcc_bypass_mounted_apfs_access.toml
Resolves https://github.com/elastic/detection-rules/issues/774
=> [New Rule] TCC Bypass via Mounted APFS Snapshot Access

rules/macos/defense_evasion_modify_environment_launchctl.toml
Resolves https://github.com/elastic/detection-rules/issues/864
=> [New Rule] Environment Variable Modification using Launchctl

rules/windows/defense_evasion_clearing_windows_security_logs.toml, rules/windows/defense_evasion_sip_provider_mod.toml
resolves #854 
Identifies modifications to the registered Subject Interface Package (SIP) providers. SIP providers are used by the Windows cryptographic system to validate file signatures on the system. This may be an attempt to bypass signature validation checks or inject code into critical processes.
=> [New Rule] SIP Provider Modification

rules/macos/credential_access_dumping_keychain_security.toml
Resolves https://github.com/elastic/detection-rules/issues/784
=> [New Rule] Dumping of Keychain Content via Security Command

rules/windows/persistence_via_update_orchestrator_service_hijack.toml
Resolves https://github.com/elastic/detection-rules/issues/937
=> [Rule Tuning] Persistence via Update Orchestrator Service Hijack

rules/windows/persistence_user_account_added_to_privileged_group_ad.toml
#771 
The referenced issue in the #827 PR was actually created by an Elastic team member. So this PR updates the author field to reflect Elastic as the first author. 
=> [Rule Tuning] User Added to Privileged Group in Active Directory

detection_rules/devtools.py, detection_rules/misc.py, detection_rules/rule.py
None
Small tweak to `kibana-diff` command to allow specifying repo
=> [CLI] Add repo option to kibana-diff command

rules/promotions/elastic_endpoint_security.toml, rules/promotions/endgame_adversary_behavior_detected.toml, rules/promotions/endgame_cred_dumping_detected.toml, rules/promotions/endgame_cred_dumping_prevented.toml, rules/promotions/endgame_cred_manipulation_detected.toml, rules/promotions/endgame_cred_manipulation_prevented.toml, rules/promotions/endgame_exploit_detected.toml, rules/promotions/endgame_exploit_prevented.toml, rules/promotions/endgame_malware_detected.toml, rules/promotions/endgame_malware_prevented.toml, rules/promotions/endgame_permission_theft_detected.toml, rules/promotions/endgame_permission_theft_prevented.toml, rules/promotions/endgame_process_injection_detected.toml, rules/promotions/endgame_process_injection_prevented.toml, rules/promotions/endgame_ransomware_detected.toml, rules/promotions/endgame_ransomware_prevented.toml, rules/promotions/endpoint_security.toml, tests/test_all_rules.py
resolves #967 
This PR updates all the relevant Endgame promotion alerts to specifically mention Elastic Endgame to reduce confusion.
=> [Rule Tuning] Update "Endpoint Security" to "Elastic Endgame" for the relevant Endgame promotion rules

rules/azure/collection_update_event_hub_auth_rule.toml, rules/azure/credential_access_key_vault_modified.toml, rules/azure/credential_access_storage_account_key_regenerated.toml, rules/azure/defense_evasion_azure_diagnostic_settings_deletion.toml, rules/azure/defense_evasion_event_hub_deletion.toml, rules/azure/defense_evasion_firewall_policy_deletion.toml, rules/azure/defense_evasion_network_watcher_deletion.toml, rules/azure/discovery_blob_container_access_mod.toml, rules/azure/execution_command_virtual_machine.toml, rules/azure/impact_azure_automation_runbook_deleted.toml, rules/azure/impact_resource_group_deletion.toml, rules/azure/persistence_azure_automation_account_created.toml, rules/azure/persistence_azure_automation_runbook_created_or_modified.toml, rules/azure/persistence_azure_automation_webhook_created.toml
n/a
This PR wraps the Azure operation names in quotes. Without the quotes, sometimes backslashes will match on incorrect data. 
=> [Rule Tuning] Wrap Azure Operation Name in Quotes

rules/macos/initial_access_suspicious_mac_ms_office_child_process.toml
Resolves https://github.com/elastic/detection-rules/issues/1021
=> [Rule Tuning] Suspicious macOS MS Office Child Process

rules/windows/defense_evasion_masquerading_trusted_directory.toml
Resolves https://github.com/elastic/detection-rules/issues/1017
=> [Rule Tuning] Program Files Directory Masquerading

rules/macos/credential_access_mitm_localhost_webproxy.toml
Resolves https://github.com/elastic/detection-rules/issues/1007
=> [Rule Tuning] WebProxy Settings Modification

rules/windows/command_and_control_iexplore_via_com.toml
Resolves https://github.com/elastic/detection-rules/issues/1069
=> [Rule Tuning] Potential Command and Control via Internet Explorer

rules/_deprecated/defense_evasion_execution_via_trusted_developer_utilities.toml
Resolves https://github.com/elastic/detection-rules/issues/1117
=> [Deprecation] Trusted Developer Application Usage

.gitignore, detection_rules/devtools.py, detection_rules/packaging.py, detection_rules/rule.py
No issue, just small fixes to issues noticed during packaging
Bug fixes for things needed during packaging and testing
*Will need backport to 7.13 branch*
=> Fix rule filenames during packaging

.github/workflows/backport.yml
Related to #1171
Fix bugs in #1174
=> Fix backport job webhook + push

rules/windows/defense_evasion_suspicious_execution_from_mounted_device.toml
resolves #1229 
Identifies when a script interpreter process is launched via a non-standard working directory. An attacker may use this
technique to evade defenses.
=> [New Rule] Suspicious Execution from a Mounted Device

rules/windows/defense_evasion_unusual_network_connection_via_dllhost.toml
resolves #1231 
Identifies unusual instances of dllhost.exe making outbound network connections. This may indicate adversarial Command and Control activity.
=> [New Rule] Unusual Network Connection via DllHost

rules/windows/privilege_escalation_persistence_phantom_dll.toml
TBD
Add `Microsoft Corporation` as signer for `dll.code_signature.subject_name`.
=> [Rule Tuning] Suspicious DLL Loaded for Persistence or Privilege Escalation

rules/windows/defense_evasion_disabling_windows_defender_powershell.toml, rules/windows/defense_evasion_enable_network_discovery_with_netsh.toml, rules/windows/defense_evasion_execution_windefend_unusual_path.toml
Resolves https://github.com/elastic/detection-rules/issues/1328
=> [New Rule] Complementary Rules for Recent REvil TTPs

.github/workflows/backport.yml
None
Created a 7.14 branch. Add it to the list of target backports.
=> Add 7.14 to the list of target backport branches

etc/non-ecs-schema.json, rules/windows/defense_evasion_parent_process_pid_spoofing.toml
Resolves https://github.com/elastic/detection-rules/issues/1337
=> [New Rule] Parent Process PID Spoofing

rules/windows/defense_evasion_defender_exclusion_via_powershell.toml
Resolves https://github.com/elastic/detection-rules/issues/1367
=> [New Rule] Windows Defender Exclusions Added via PowerShell

rules/google-workspace/google_workspace_mfa_enforcement_disabled.toml, rules/google-workspace/google_workspace_policy_modified.toml, rules/google-workspace/mfa_disabled_for_google_workspace_organization.toml
=> [Rule Tuning] Update Google Workspace rules to use google_workspace event schema

detection_rules/devtools.py
Saw that https://github.com/elastic/detection-rules/actions/runs/1072811426 failed
I think it was missing `click.pass_context`
=> Fix kibana_pr for click.Context

detection_rules/utils.py
More things were broken. I think I refactored some code wrong in a different PR.
Ran this locally and this is what I was using.
Works because I made this https://github.com/elastic/kibana/pull/106933
=> [CI] Fix kibana PR command again

rules/_deprecated/command_and_control_ssh_secure_shell_from_the_internet.toml, rules/_deprecated/command_and_control_ssh_secure_shell_to_the_internet.toml, rules/_deprecated/initial_access_rdp_remote_desktop_protocol_to_the_internet.toml, rules/apm/apm_403_response_to_a_post.toml, rules/apm/apm_405_response_method_not_allowed.toml, rules/integrations/o365/credential_access_user_excessive_sso_logon_errors.toml, rules/network/command_and_control_cobalt_strike_default_teamserver_cert.toml, rules/network/command_and_control_dns_directly_to_the_internet.toml, rules/network/command_and_control_rdp_remote_desktop_protocol_from_the_internet.toml, rules/network/command_and_control_telnet_port_activity.toml, rules/network/command_and_control_vnc_virtual_network_computing_from_the_internet.toml, rules/network/command_and_control_vnc_virtual_network_computing_to_the_internet.toml, rules/network/initial_access_rpc_remote_procedure_call_from_the_internet.toml, rules/network/initial_access_rpc_remote_procedure_call_to_the_internet.toml, rules/network/initial_access_smb_windows_file_sharing_activity_to_the_internet.toml, rules/windows/execution_ms_office_written_file.toml
None
Resolves feedback captured in elastic/security-docs/pull/833
=> [Rule Tuning] Rule description tweaks

docs/experimental-machine-learning/host-risk-score.md, docs/experimental-machine-learning/readme.md
This PR adds docs for Host Risk Score.
=> Adding host risk score docs

docs/experimental-machine-learning/host-risk-score.md
- Updated the names of the dashboards to reflect the actual names. 
- Added a link to the GitHub releases under detection-rules so users know where to look for the package.
=> Update Host Risk Score docs

rules/windows/credential_access_copy_ntds_sam_volshadowcp_cmdline.toml
=> [Rule Tuning] NTDS or SAM Database File Copied

.github/workflows/community.yml
part of elastic/security-team/issues/1151
Fixes to changes made in #1406
=> Add revised workflow for community label

rules/windows/persistence_webshell_detection.toml
=> [New rule] Webshell Detection

.github/workflows/backport.yml
=> [CI] Notify slack on backport failure

rules/windows/initial_access_suspicious_ms_office_child_process.toml
Resolves https://github.com/elastic/detection-rules/issues/1476
=> [rule-tuning] Suspicious MS Office Child Process

rules/windows/defense_evasion_execution_control_panel_suspicious_args.toml
Resolves https://github.com/elastic/detection-rules/issues/1478
=> [New Rule] Behavior Rule for CVE-2021-40444 Exploitation

rules/ml/ml_auth_spike_in_logon_events_from_a_source_ip.toml
None
Identified in elastic/kibana/pull/112135
Fixes typos in a few ML rules
=> [Rule tuning] Fix typo in ML rule descriptions

rules/macos/credential_access_kerberosdump_kcc.toml, rules/macos/lateral_movement_credential_access_kerberos_bifrostconsole.toml, rules/windows/credential_access_cmdline_dump_tool.toml, rules/windows/credential_access_copy_ntds_sam_volshadowcp_cmdline.toml, rules/windows/credential_access_domain_backup_dpapi_private_keys.toml, rules/windows/credential_access_dump_registry_hives.toml, rules/windows/credential_access_lsass_memdump_file_created.toml, rules/windows/credential_access_mimikatz_powershell_module.toml, rules/windows/credential_access_saved_creds_vaultcmd.toml
Add sub-techniques and additional techniques to credential access related rules
=> Additional Att&ck Mappings for credential access Rules

rules/integrations/aws/persistence_ec2_security_group_configuration_change_detection.toml
None
Issues found in elastic/security-docs#1016
Update rule metadata typos
=> [Rule Tuning] Fix typos in rule metadata

rules/integrations/aws/exfiltration_rds_snapshot_export.toml, rules/integrations/aws/persistence_rds_instance_creation.toml
=> [Rule Tuning] AWS RDS Snapshot Export and AWS RDS Instance Created

rules/windows/defense_evasion_misc_lolbin_connecting_to_the_internet.toml
Solves #1600 
Ref: https://lolbas-project.github.io/lolbas/Binaries/Extrac32/
=> [Rule Tuning] Rename extrac.exe to extrac32.exe

tests/test_toml_formatter.py
=> Test to trigger workflows

detection_rules/devtools.py
None
There were some bugs in the `kibana-pr` command. This also updates the default base branch to `main` to reflect changes in Kibana
- updates base branch to main
- allows passing of fork owner for proper head branch naming
- uses commit hashes from rules repo (bug: was using kibana commits)
-
=> [bug] Fix kibana-pr command

rules/windows/defense_evasion_clearing_windows_console_history.toml
=> [New Rule] Clearing Windows Console History

docs/experimental-machine-learning/experimental-detections.md, docs/experimental-machine-learning/host-risk-score.md
This PR makes some minor updates to the docs for Host Risk Score and experimental detection rules.
=> Updating docs for Host Risk Score and experimental detection rules

docs/experimental-machine-learning/beaconing.md
This PR adds docs for the Beaconing prototype being released in 7.16.
=> Adding Beaconing docs

execution_suspicious_java_netcon_childproc.toml
Identifies an outbound network connection by JAVA to LDAP, RMI or DNS standard ports followed by a suspicious JAVA child processes. This may indicate an attempt to exploit a JAVA/DNI injection vulnerability.
=> [New Rule] Potential JAVA/JNDI Exploitation Attempt

rules/windows/command_and_control_common_webservices.toml
Added Discord domains often abused to stage malicious files.
=> [Rule Tuning] Connection to Commonly Abused Web Services

rules/macos/persistence_creation_modif_launch_deamon_sequence.toml
https://github.com/elastic/detection-rules/issues/1719
This PR resolves a syntax error in this rule that prevented it from detecting the intended activity.
=> MacOS Launch Daemon Creation Rule - Query Fix

rules/macos/persistence_folder_action_scripts_runtime.toml
https://github.com/elastic/detection-rules/issues/1721
This PR expands the process listing for this detection to ensure it will detect a broader possible use of malicious activity.
=> MacOS FolderActionScripts Process List Update

tests/test_all_rules.py
resolves #1734
Update tests to account for non-backported deprecations
=> Update tests to account for non-backported deprecations

detection_rules/devtools.py
None
Updated `integrations-pr` command to reflect change to primary branch
=> Update base branch in integrations-pr command

rules/windows/credential_access_mod_wdigest_security_provider.toml
Update the rule to support sysmon registry events
=> [Rule Tuning] Modification of WDigest Security Provider - Sysmon

rules/cross-platform/threat_intel_filebeat8x.toml
In [this pr](https://github.com/elastic/detection-rules/pull/1560/commits/193743fa84a30b5fac053aa3aaccb7237cb401b4#) eventually was merged wrong query for Filebeat indicator match rule, which will not work
=> [Rule Tuning] Fix IM query

rules/cross-platform/defense_evasion_agent_spoofing_mismatched_id.toml, rules/cross-platform/defense_evasion_agent_spoofing_multiple_hosts.toml, rules/cross-platform/threat_intel_filebeat8x.toml, rules/cross-platform/threat_intel_fleet_integrations.toml, rules/integrations/azure/defense_evasion_suppression_rule_created.toml, rules/integrations/gcp/impact_gcp_virtual_private_cloud_route_created.toml, rules/integrations/o365/defense_evasion_microsoft_365_mailboxauditbypassassociation.toml, rules/windows/collection_posh_audio_capture.toml, rules/windows/collection_posh_keylogger.toml, rules/windows/collection_posh_screen_grabber.toml, rules/windows/credential_access_kerberoasting_unusual_process.toml, rules/windows/credential_access_posh_minidump.toml, rules/windows/credential_access_suspicious_comsvcs_imageload.toml, rules/windows/credential_access_suspicious_lsass_access_memdump.toml, rules/windows/credential_access_suspicious_lsass_access_via_snapshot.toml, rules/windows/credential_access_symbolic_link_to_shadow_copy_createdcredential_access_symbolic_link_to_shadow_copy_created.toml, rules/windows/defense_evasion_posh_assembly_load.toml, rules/windows/defense_evasion_posh_compressed.toml, rules/windows/defense_evasion_posh_process_injection.toml, rules/windows/defense_evasion_powershell_windows_firewall_disabled.toml, rules/windows/discovery_posh_suspicious_api_functions.toml, rules/windows/discovery_privileged_localgroup_membership.toml, rules/windows/execution_posh_portable_executable.toml, rules/windows/execution_posh_psreflect.toml, rules/windows/privilege_escalation_group_policy_iniscript.toml, rules/windows/privilege_escalation_group_policy_privileged_groups.toml, rules/windows/privilege_escalation_group_policy_scheduled_task.toml, rules/windows/privilege_escalation_installertakeover.toml
Apply the suggestions from https://github.com/elastic/security-docs/pull/1506 review.
=> [Rule Tuning] Update rules based on docs review

rules/linux/defense_evasion_nice_binary.toml
https://github.com/elastic/detection-rules/issues/1819
nice, a common IOC, the Unix binary can be abused to breakout out of restricted shells or environments by spawning an interactive system shell. This activity is not standard use with this binary for a user or system administrator. It indicates a potentially malicious actor attempting to improve the capabilities or stability of their access.
=> nice shell evasion threat

requirements.txt
None
Pull in new EQL [updates](https://github.com/endgameinc/eql/blob/master/CHANGELOG.md#version-0912) for expanded features and syntax
=> Bump EQL to 0.9.12

rules/integrations/okta/credential_access_user_impersonation_access.toml
Adds a new rule for Okta user impersonation.
cc: @aarju
=> [New Rule] Okta User Session Impersonation

.github/ISSUE_TEMPLATE/integration-oob-updates.md, .github/ISSUE_TEMPLATE/kibana-updates.md
=> Add kibana-update and fleet-release templates

rules/linux/execution_apt_binary.toml, rules/linux/execution_awk_binary_shell.toml, rules/linux/execution_env_binary.toml, rules/linux/execution_expect_binary.toml, rules/linux/execution_find_binary.toml, rules/linux/execution_gcc_binary.toml, rules/linux/execution_mysql_binary.toml, rules/linux/execution_nice_binary.toml, rules/linux/execution_ssh_binary.toml, rules/macos/credential_access_systemkey_dumping.toml
https://github.com/elastic/detection-rules/issues/1847
The Review comments in PR https://github.com/elastic/detection-rules/pull/1840 & https://github.com/elastic/detection-rules/pull/1842 suggest adding a one-line description on the correct usage of the Linux library. This issue tracks the description updating of all merged shell evasion rules for 8.2
=> Description updation across multiple rules

rules/linux/execution_c89_c99_binary.toml
None
related to #1898 
Re adds rule to trigger backport
=> Re-add c89 rules

rules/linux/execution_apt_binary.toml, rules/linux/execution_awk_binary_shell.toml, rules/linux/execution_busybox_binary.toml, rules/linux/execution_c89_c99_binary.toml, rules/linux/execution_cpulimit_binary.toml, rules/linux/execution_crash_binary.toml, rules/linux/execution_expect_binary.toml, rules/linux/execution_find_binary.toml, rules/linux/execution_gcc_binary.toml, rules/linux/execution_mysql_binary.toml, rules/linux/execution_nice_binary.toml, rules/linux/execution_perl_tty_shell.toml, rules/linux/execution_python_tty_shell.toml, rules/linux/execution_ssh_binary.toml, rules/linux/execution_vi_binary.toml
None
related to #1878 
Resets changes from #1878 due to failed backports.  Will re-add in next PR for backporting
=> reset linux evasion rules

detection_rules/__init__.py, rules/linux/execution_apt_binary.toml, rules/linux/execution_awk_binary_shell.toml, rules/linux/execution_busybox_binary.toml, rules/linux/execution_c89_c99_binary.toml, rules/linux/execution_cpulimit_binary.toml, rules/linux/execution_crash_binary.toml, rules/linux/execution_expect_binary.toml, rules/linux/execution_find_binary.toml, rules/linux/execution_gcc_binary.toml, rules/linux/execution_mysql_binary.toml, rules/linux/execution_nice_binary.toml, rules/linux/execution_perl_tty_shell.toml, rules/linux/execution_python_tty_shell.toml, rules/linux/execution_ssh_binary.toml, rules/linux/execution_vi_binary.toml
None
related to #1878 
Reset evasion rules to trigger proper backport cherry picking
=> reset evasion rules

rules/windows/execution_command_shell_started_by_svchost.toml
Exclude noisy false positives related to common system activity.
=> [Rule Tuning] Svchost spawning Cmd

.github/workflows/backport.yml, .github/workflows/lock-versions.yml, detection_rules/schemas/__init__.py, etc/api_schemas/8.2/8.2.base.json, etc/api_schemas/8.2/8.2.eql.json, etc/api_schemas/8.2/8.2.machine_learning.json, etc/api_schemas/8.2/8.2.query.json, etc/api_schemas/8.2/8.2.threat_match.json, etc/api_schemas/8.2/8.2.threshold.json, etc/packages.yml, etc/stack-schema-map.yaml
elastic/ia-trade-team/issues/27
_merged after 8.2 branch creation_
=> Prep for Creation of 8.3 Branch

detection_rules/eswrap.py, detection_rules/misc.py, requirements.txt
None
Bumps elasticsearch module to 8.1. This also bumps requests to be compatible (and it was a bit dated)
=> Update elasticsearch dependency to 8.1

rules/windows/command_and_control_port_forwarding_added_registry.toml, rules/windows/command_and_control_rdp_tunnel_plink.toml, rules/windows/command_and_control_remote_file_copy_desktopimgdownldr.toml, rules/windows/command_and_control_remote_file_copy_mpcmdrun.toml, rules/windows/command_and_control_remote_file_copy_powershell.toml, rules/windows/command_and_control_teamviewer_remote_file_copy.toml, rules/windows/persistence_adobe_hijack_persistence.toml, rules/windows/persistence_priv_escalation_via_accessibility_features.toml, rules/windows/persistence_system_shells_via_services.toml, rules/windows/persistence_user_account_added_to_privileged_group_ad.toml
Adds Investigation Guides for the following rules:
- Port Forwarding Rule Addition
- Potential Remote Desktop Tunneling Detected
- Remote File Download via Desktopimgdownldr Utility
- Remote File Download via MpCmdRun
- Remote File Download via PowerShell
- Remote File Copy via TeamViewer
- Adobe Hijack Persistence
- Potential Modification of Accessibility Binaries
- System Shells via Services
- User Added to Privileged Group in Active Directory
=> [Security Content] Add Investigation Guides - 5

rules/windows/credential_access_dcsync_replication_rights.toml, rules/windows/credential_access_lsass_memdump_handle_access.toml, rules/windows/credential_access_mimikatz_powershell_module.toml, rules/windows/credential_access_spn_attribute_modified.toml, rules/windows/credential_access_symbolic_link_to_shadow_copy_created.toml, rules/windows/defense_evasion_defender_exclusion_via_powershell.toml, rules/windows/defense_evasion_workfolders_control_execution.toml, rules/windows/discovery_adfind_command_activity.toml, rules/windows/lateral_movement_dns_server_overflow.toml, rules/windows/lateral_movement_scheduled_task_target.toml, rules/windows/persistence_evasion_registry_startup_shell_folder_modified.toml, rules/windows/persistence_sdprop_exclusion_dsheuristics.toml, rules/windows/privilege_escalation_installertakeover.toml
Investigation guides review by the security docs team.
=> [Security Content] Current Investigation Guides Review

rules/windows/command_and_control_port_forwarding_added_registry.toml, rules/windows/command_and_control_rdp_tunnel_plink.toml, rules/windows/command_and_control_remote_file_copy_desktopimgdownldr.toml, rules/windows/command_and_control_remote_file_copy_mpcmdrun.toml, rules/windows/command_and_control_remote_file_copy_powershell.toml, rules/windows/command_and_control_remote_file_copy_scripts.toml, rules/windows/command_and_control_sunburst_c2_activity_detected.toml, rules/windows/command_and_control_teamviewer_remote_file_copy.toml, rules/windows/defense_evasion_defender_exclusion_via_powershell.toml, rules/windows/impact_deleting_backup_catalogs_with_wbadmin.toml, rules/windows/impact_modification_of_boot_config.toml, rules/windows/impact_stop_process_service_threshold.toml, rules/windows/persistence_adobe_hijack_persistence.toml, rules/windows/persistence_priv_escalation_via_accessibility_features.toml, rules/windows/persistence_system_shells_via_services.toml, rules/windows/persistence_user_account_added_to_privileged_group_ad.toml, rules/windows/privilege_escalation_installertakeover.toml
Applies suggestions from #1895 reviews
=> [Security Content] MInor changes from Investigation Guides Review

etc/non-ecs-schema.json, rules/windows/privilege_escalation_krbrelayup_service_creation.toml
This rule will catch also the suspicious service that was created leveraging the imported kerberos ticket https://gist.github.com/tyranid/c24cfd1bd141d14d4925043ee7e03c82 which makes triage easier :
DATA :
```
"sequences" : [
{
"join_keys" : [
"6a3c3ef2-208f-4d6f-90ee-b34f4e3fd160",
"0xefac5f"
],
"events" : [
{
"_index" : ".ds-logs-system.security-default-2022.04.12-000003",
"_id" : "XAy1YoABQhClK0XGpqaL",
"_source" : {
"agent" : {
"name" : "02694w-win10",
"id" : "77a829ec-a564-44d5-9bc4-61eeefbf783a",
"type" : "filebeat",
"ephemeral_id" : "6c751494-97a3-46aa-bab2-5baf01d17d04",
"version" : "8.0.0"
},
"process" : {
"name" : "-",
"pid" : 0,
"executable" : "-"
},
"winlog" : {
"computer_name" : "02694w-win10.threebeesco.com",
"process" : {
"pid" : 688,
"thread" : {
"id" : 5160
}
}, …
```
=> [New Rule] Service Creation via Local Kerberos Authentication

rules/linux/execution_abnormal_process_id_file_created.toml, rules/linux/execution_process_started_from_process_id_file.toml
* https://github.com/elastic/detection-rules/issues/1963
During our analysis of BPFDoor, the creation of empty PID and lock files in `/var/run` were found during detonation. While PID files are expected to exist in this directory, they are only expected to contain PIDs, not be executables or contain structured data, code, etc. Therefore any PID file creation as root where the PID file is in the main directory that is not expected, should be investigated.
**NOTE** - It would be good to use file size for this such as anything more than 10 bytes as a PID or the PID is not just integers, but this visibility does not exist at this time and has been passed on for potential improvements.
Reference:
https://doublepulsar.com/bpfdoor-an-active-chinese-global-surveillance-tool-54b078f1a896
<details> …
=> [New Rule] Abnormal Process ID File Creation

rules/linux/command_and_control_connection_attempt_by_non_ssh_root_session.toml
https://github.com/elastic/detection-rules/issues/1982
Updating the rule name to more accurately reflect its functionality.  
=> [Rule Tuning] Update Rule Name: Suspicious Network Connection Attempt Sequence by Root

rules/macos/persistence_emond_rules_file_creation.toml
Resolves #1976 
Checks for files in the `/private/var/db/emondClients`, which should be treated as suspicious per [www.sentinelone.com](https://www.sentinelone.com/blog/how-malware-persists-on-macos/).
=> [Rule tuning] check for anything found in the emondClient directory

rules/linux/execution_shell_evasion_linux_binary.toml
#1843 
git an IOC, the Unix binary can be abused to breakout out of restricted shells or environments by spawning an interactive system shell. This activity is not standard use with this binary for a user or system administrator. It indicates a potentially malicious actor attempting to improve the capabilities or stability of their access.
Also as part of the PR, we have added Triage and Analysis and Config areas.
=> Issue 1843

rules/windows/initial_access_suspicious_ms_office_child_process.toml
added msdt.exe as a response to this in the wild 0day (works without vba and on latest office) ->
https://twitter.com/nao_sec/status/1530196847679401984
https://www.virustotal.com/gui/file/4a24048f81afbe9fb62e7a6a49adbd1faf41f266b5f9feecdceb567aec096784/detection
=> [Rule Tuning] Suspicious MS Office Child Process

rules/windows/defense_evasion_proxy_execution_via_msdt.toml
https://lolbas-project.github.io/lolbas/Binaries/Msdt/
https://twitter.com/nao_sec/status/1530196847679401984
=> [New Rule] Suspicious Microsoft Diagnostics Wizard Execution

rules/linux/discovery_linux_hping_activity.toml
#2011 
- Add MITRE details for the rule.
- Change filename to align with unit tests
=> [Rule Tuning] Add MITRE Details to exisisting hpining activity rule.

rules/windows/discovery_remote_system_discovery_commands_windows.toml
Fix the logic so the second condition don't match on unrelated event types.
=> [Rule Tuning] Remote System Discovery Commands

CLI.md, detection_rules/kbwrap.py, detection_rules/misc.py
Resolves #2047
Updated the documentation to include the kibana `search-alerts` cli command and the table to print out fields correctly.
=> Update cli documentation for search-alerts

rules/windows/credential_access_cmdline_dump_tool.toml, rules/windows/credential_access_credential_dumping_msbuild.toml, rules/windows/defense_evasion_execution_msbuild_started_by_office_app.toml, rules/windows/defense_evasion_system_critical_proc_abnormal_file_activity.toml, rules/windows/execution_command_shell_started_by_svchost.toml, rules/windows/execution_psexec_lateral_movement_command.toml, rules/windows/initial_access_suspicious_ms_office_child_process.toml, rules/windows/initial_access_suspicious_ms_outlook_child_process.toml, rules/windows/lateral_movement_direct_outbound_smb_connection.toml, rules/windows/privilege_escalation_unusual_parentchild_relationship.toml
Adds Investigation Guides to the following rules:
- Potential Credential Access via Windows Utilities
- Potential Credential Access via Trusted Developer Utility (renamed from Microsoft Build Engine Loading Windows Credential Libraries)
- Microsoft Build Engine Started by an Office Application
- Unusual Executable File Creation by a System Critical Process
- Svchost spawning Cmd
- PsExec Network Connection
- Suspicious MS Office Child Process
- Suspicious MS Outlook Child Process
- Direct Outbound SMB Connection
- Unusual Parent-Child Relationship
=> [Security Content] 8.4 - Add Investigation Guides

rules/integrations/aws/credential_access_secretsmanager_getsecretvalue.toml, rules/integrations/aws/defense_evasion_config_service_rule_deletion.toml, rules/integrations/aws/exfiltration_ec2_snapshot_change_activity.toml, rules/integrations/aws/impact_cloudwatch_log_stream_deletion.toml, rules/integrations/aws/initial_access_via_system_manager.toml, rules/integrations/aws/ml_cloudtrail_error_message_spike.toml, rules/integrations/aws/ml_cloudtrail_rare_error_code.toml, rules/integrations/aws/ml_cloudtrail_rare_method_by_city.toml, rules/integrations/aws/ml_cloudtrail_rare_method_by_country.toml, rules/integrations/aws/ml_cloudtrail_rare_method_by_user.toml, rules/windows/collection_email_powershell_exchange_mailbox.toml, rules/windows/command_and_control_certutil_network_connection.toml, rules/windows/command_and_control_port_forwarding_added_registry.toml, rules/windows/defense_evasion_defender_disabled_via_registry.toml, rules/windows/discovery_adfind_command_activity.toml, rules/windows/discovery_post_exploitation_external_ip_lookup.toml, rules/windows/discovery_privileged_localgroup_membership.toml, rules/windows/lateral_movement_direct_outbound_smb_connection.toml
Adds Investigation Guides to the following rules:
- AWS Access Secret in Secrets Manager
- AWS Config Resource Deletion (Renamed from AWS Config Service Tampering)
- AWS EC2 Snapshot Activity
- AWS CloudWatch Log Stream Deletion
- AWS Execution via System Manager
- Spike in AWS Error Messages
- Rare AWS Error Code
- Unusual City For an AWS Command
- Unusual Country For an AWS Command
- Unusual AWS Command for a User
=> [Security Content] Add Investigation Guides to Cloud Rules - AWS

detection_rules/etc/non-ecs-schema.json, rules/windows/initial_access_evasion_suspicious_htm_file_creation.toml
=> [New Rule] Suspicious HTML File Creation

rules/macos/credential_access_access_to_browser_credentials_procargs.toml
Resolves #2097 
- Added path to chrome profile cookies
- Added threat technique T1539
=> [Rule Tuning] Access of Stored Browser Credentials

rules/macos/credential_access_credentials_keychains.toml
Resolves #2100 
- Added exception for noisy FPs (jumpcloud-agent & Microsoft Defender)
=> [Rule Tuning] Access to Keychain Credentials Directories

rules/macos/credential_access_kerberosdump_kcc.toml
Resolves #2102 
- Updated description to include threat actor utilization
=> [Rule Tuning] Kerberos Cached Credentials Dumping

rules/macos/defense_evasion_attempt_del_quarantine_attrib.toml
Resolves #2116
- Added browser exceptions
=> [Rule Tuning] Attempt to Remove File Quarantine Attribute

rules/macos/persistence_directory_services_plugins_modification.toml
Resolves #2167
- Fixes typo in the description `daemonlaunches`  -> `daemon launches`
=> [Rule Tuning] Persistence via DirectoryService Plugin Modification

rules/macos/persistence_screensaver_engine_unexpected_child_process.toml
Resolves #2183 
Add subtechnique https://attack.mitre.org/techniques/T1546/002/
=> [Rule Tuning] Unexpected Child Process of macOS Screensaver Engine

rules/_deprecated/privilege_escalation_linux_strace_activity.toml, rules/linux/command_and_control_connection_attempt_by_non_ssh_root_session.toml, rules/linux/credential_access_ssh_backdoor_log.toml, rules/linux/defense_evasion_hidden_file_dir_tmp.toml, rules/linux/defense_evasion_log_files_deleted.toml, rules/linux/execution_process_started_in_shared_memory_directory.toml, rules/linux/execution_shell_evasion_linux_binary.toml, rules/linux/persistence_credential_access_modify_ssh_binaries.toml, rules/linux/persistence_kde_autostart_modification.toml, rules/linux/persistence_shell_activity_by_web_server.toml
#2169 
1. Tuning credential_access_ssh_backdoor_log to incorporate the following changes
- Include hidden FP files such as cache viminfo and bash_history
- Include a regex to match swap file patterns other than already prevailing
- Exclusions added from telemetry analysis no additional testing is required.
2. Tuning defense_evasion_log_files_deleted to incorporate the following changes
- Exclude gzip process from detection
- Exclusions added from telemetry analysis no additional testing is required.
3. Tuning execution_process_started_in_shared_memory_directory to incorporate the following changes
- Exclude /var/run/docker/* process executables from detection 
- Exclusions added from telemetry analysis no additional testing is required.
4. Tuning …
=> Rule tuning as part of Linux Detection Rules Review

rules/windows/credential_access_mod_wdigest_security_provider.toml
excluding svchost.exe running as system (main src of FPs for this use case).
=> [Rule Tuning] Modification of WDigest Security Provider

rules/windows/persistence_via_update_orchestrator_service_hijack.toml
https://github.com/elastic/detection-rules/issues/2194
- Changed query to exclude FPs for process.executables related to MoUsoCoreWorker.exe and OfficeC2RClient.exe. 
- Updated tags to include CVE
=>  [Rule Tuning] Persistence via Update Orchestrator Service Hijack

rules/windows/credential_access_kerberoasting_unusual_process.toml
Excluding couple of FPs by process.executables to reduce FPs rate.
=> [Rule Tuning] Kerberos Traffic from Unusual Process

rules/windows/defense_evasion_process_termination_followed_by_deletion.toml
Excluded some FPs by process.executable and file.path.
=> [Rule Tuning] Process Termination followed by Deletion

rules/windows/defense_evasion_suspicious_process_access_direct_syscall.toml
Excluding some FPs by calltrace.
=> [Rule Tuning] Suspicious Process Access via Direct System Call

rules/windows/privilege_escalation_unusual_svchost_childproc_childless.toml
Excluding some noisy unique processes.
=> [Rule Tuning] Unusual Service Host Child Process - Childless Service

rules/_deprecated/defense_evasion_whitespace_padding_in_command_line.toml
very noisy and will require frequent tuning with very low TP rate.
=> [Deprecate rule] Whitespace Padding in Process Command Line

detection_rules/etc/non-ecs-schema.json, rules/windows/credential_access_lsass_memdump_file_created.toml, rules/windows/credential_access_suspicious_winreg_access_via_sebackup_priv.toml, rules/windows/defense_evasion_execution_control_panel_suspicious_args.toml, rules/windows/defense_evasion_file_creation_mult_extension.toml, rules/windows/defense_evasion_from_unusual_directory.toml, rules/windows/defense_evasion_suspicious_process_creation_calltrace.toml, rules/windows/discovery_privileged_localgroup_membership.toml, rules/windows/execution_from_unusual_path_cmdline.toml, rules/windows/execution_psexec_lateral_movement_command.toml, rules/windows/initial_access_suspicious_ms_exchange_process.toml, rules/windows/lateral_movement_via_startup_folder_rdp_smb.toml, rules/windows/persistence_remote_password_reset.toml, rules/windows/privilege_escalation_persistence_phantom_dll.toml
Excluding FP patterns while avoiding breaking compat with winlogbeat and 4688 events lack of codesign metadata.
=> [Rules Tuning] Diverse Windows Rules - FPs reduction

rules/macos/persistence_suspicious_calendar_modification.toml
Resolves #2186 
- Excludes FP for /System/Applications/Mail.app/Contents/MacOS/Mail
=> [Rule Tuning] Suspicious Calendar File Modification

rules/macos/privilege_escalation_explicit_creds_via_scripting.toml
Resolves #2188 
- Add technique https://attack.mitre.org/techniques/T1548/
- Add subtechnique https://attack.mitre.org/techniques/T1548/004/
- Add cases sensitive Python process.name
=> [Rule Tuning] Execution with Explicit Credentials via Scripting

rules/macos/persistence_modification_sublime_app_plugin_or_script.toml
Resolves #2179 
- Exclude FPs for git and plugin_host-3.3
- /Library/Developer/CommandLineTools/usr/bin/git
- /Applications/Sublime Text.app/Contents/MacOS/plugin_host-3.3
=> [Rule Tuning] Sublime Plugin or Application Script Modification

rules/macos/persistence_loginwindow_plist_modification.toml
Resolves #2175 
- Exclude FPs for `iMazing Profile Editor` and `backupd` process.name
=> [Rule Tuning] Potential Persistence via Login Hook

.github/workflows/branch-status-checks.yml
Only run branch checks on pull request to reduce the number of GH actions run and remove unnecessary check after code is merged to main.
- Since we immediately back port after merges on main, timing with checking back porting status causes failures.
=> Update Branch Checks 

rules/linux/command_and_control_connection_attempt_by_non_ssh_root_session.toml, rules/linux/execution_abnormal_process_id_file_created.toml, rules/linux/persistence_chkconfig_service_add.toml, rules/linux/persistence_dynamic_linker_backup.toml, rules/linux/persistence_etc_file_creation.toml, rules/linux/persistence_insmod_kernel_module_load.toml, rules/macos/execution_installer_package_spawned_network_event.toml, rules/windows/defense_evasion_installutil_beacon.toml, rules/windows/defense_evasion_msbuild_beacon_sequence.toml, rules/windows/defense_evasion_mshta_beacon.toml, rules/windows/defense_evasion_msxsl_beacon.toml, rules/windows/defense_evasion_network_connection_from_windows_binary.toml, rules/windows/defense_evasion_rundll32_no_arguments.toml, rules/windows/defense_evasion_suspicious_process_creation_calltrace.toml, rules/windows/defense_evasion_suspicious_wmi_script.toml, rules/windows/discovery_enumerating_domain_trusts_via_nltest.toml, rules/windows/discovery_privileged_localgroup_membership.toml, rules/windows/execution_downloaded_url_file.toml, rules/windows/execution_ms_office_written_file.toml, rules/windows/lateral_movement_mount_hidden_or_webdav_share_net.toml, rules/windows/persistence_app_compat_shim.toml, rules/windows/persistence_evasion_registry_ifeo_injection.toml, rules/windows/persistence_startup_folder_file_written_by_unsigned_process.toml
Resolves #2241 
Standardizes Risk Score according to Severity across the ruleset
=> [Rule Tuning] Standardizing Risk Score according to Severity

rules/integrations/o365/collection_microsoft_365_new_inbox_rule.toml
Resolves #2239 
Adds the missing `Set-InboxRule` event.action
=> [Rule Tuning] Microsoft 365 Inbox Forwarding Rule Created

rules/integrations/google_workspace/defense_evasion_application_removed_from_blocklist_in_google_workspace.toml
* https://github.com/elastic/detection-rules/issues/2226
Google Workspace administrators may be aware of malicious applications within the Google marketplace and block these applications for user security purposes. An adversary, with administrative privileges, may remove this application from the explicit block list to allow distribution of the application amongst users. This may also indicate the unauthorized use of an application that had been previously blocked before by a user with admin privileges.
Example Document:
<details>
```
{
"_index": ".ds-logs-google_workspace.admin-default-2022.07.25-000001",
"_id": "slCKHLysbNaOB6NHOlAlX7Qo0ho=",
"_version": 1,
"_score": 0,
"_source": {
"agent": {
"name": "ubuntu-server-tdejesus",
"id": "f4011165-a1b8-4d8e-b902-56ba8835cc28",
"type": …
```
=> [New Rule] Application Removed from Blocklist - Google Workspace

rules/integrations/google_workspace/persistence_google_workspace_admin_role_assigned_to_user.toml
* https://github.com/elastic/detection-rules/issues/2226
This rule needs tuning to identify when an admin role is delegated or assigned to a user in Google Workspace. The original rule only identifies when a Google Workspace administrator assigns a role to a user, not a specific admin role. This rule update will identify if any admin role (mobile, app, console, etc.) is assigned to a user.
Example Document:
<details>
```
{
"_index": ".ds-logs-google_workspace.admin-default-2022.07.25-000001",
"_id": "uQ5y9OnfK7QBeAqXVdORwaQsdlw=",
"_version": 1,
"_score": 0,
"_source": {
"agent": {
"name": "ubuntu-server-tdejesus",
"id": "f4011165-a1b8-4d8e-b902-56ba8835cc28",
"ephemeral_id": "3d0af180-a1ca-4a5f-9153-2e986dc98e25",
"type": "filebeat",
"version": "8.2.3"
},
"elastic_agent": {
"id": …
```
=> [Rule Tuning] Admin Role Assigned to User - Google Workspace

rules/integrations/google_workspace/collection_google_drive_ownership_transferred.toml, rules/integrations/google_workspace/collection_google_drive_ownership_transferred_via_google_workspace.toml
* https://github.com/elastic/detection-rules/issues/2226
Drive and Docs is a Google Workspace service that allows users to leverage Google Drive and Google Docs. Access to files is based on inherited permissions from the child organizational unit the user belongs to which is scoped by administrators. Typically if a user is removed their files can be transferred to another user by the administrator. This service can also be abused by adversaries to transfer files to an adversary compromised account for potential exfiltration.
Example Document:
<details>
```
{
"_index": ".ds-logs-google_workspace.admin-default-2022.07.25-000001",
"_id": "nWmZ5Q5MH/QTPgiZjAkTbfZbAPI=",
"_version": 1,
"_score": 0,
"_source": {
"agent": {
"name": "ubuntu-server-tdejesus",
"id": …
```
=> [New Rule] Google Drive Ownership Transferred

rules/integrations/google_workspace/defense_evasion_google_workspace_restrictions_for_google_marketplace_changed_to_allow_any_app.toml
* https://github.com/elastic/detection-rules/issues/2226
Malicious APKs created by adversaries may be uploaded to the Google marketplace but not installed on devices managed within Google Workspace. Administrators should set restrictions to not allow any application from the marketplace for security reasons. Adversaries may enable any app to be installed and executed on mobile devices within a Google Workspace environment prior to distributing the malicious APK to the end user.
Example Document:
<details>
```
{
"_index": ".ds-logs-google_workspace.admin-default-2022.07.25-000001",
"_id": "dbfTN5IfXEIy7XMNm/Jy1SFn59k=",
"_version": 1,
"_score": 0,
"_source": {
"agent": {
"name": "ubuntu-server-tdejesus",
"id": "f4011165-a1b8-4d8e-b902-56ba8835cc28",
"ephemeral_id": …
```
=> [New Rule] Restrictions for Google Marketplace Modified to Allow Any App - Google Workspace

rules/linux/credential_access_bruteforce_passowrd_guessing.toml, rules/linux/credential_access_potential_linux_ssh_bruteforce.toml, rules/linux/credential_access_potential_linux_ssh_bruteforce_root.toml
#2325 
Add Triage and Analysis to rules
1. rules/linux/credential_access_potential_linux_ssh_bruteforce_root.toml
2. rules/linux/credential_access_potential_linux_ssh_bruteforce.toml
3. rules/linux/credential_access_bruteforce_passowrd_guessing.toml
=> Add investigation guides

requirements.txt
None
Update click version to `~=8.1.0`
=> Update click version

requirements.txt
None
Bump eql requirements to `0.9.15`
=> [FR] bump eql to v9.15

rules/windows/persistence_via_application_shimming.toml
#2354
Rule Tuning to fix high FP on Potential Application Shimming via Sdbinst
Triage and Analysis and Example Data on the original issue.
=> Rule Tuning on Potential Application Shimming via Sdbinst

detection_rules/etc/non-ecs-schema.json, rules/windows/credential_access_ldap_attributes.toml, rules/windows/privilege_escalation_credroaming_ldap.toml
https://www.mandiant.com/resources/blog/apt29-windows-credential-roaming
=> [New Rules] CredAccess via LDAP Attributes

rules/windows/defense_evasion_persistence_temp_scheduled_task.toml
Resolves https://github.com/elastic/detection-rules/issues/2410
Excludes computer accounts to reduce the rule noise.
=> [Rule Tuning] Temporarily Scheduled Task Creation

rules/windows/credential_access_lsass_loaded_susp_dll.toml
Converted an existing ER (diag) to DR with a good initial set of known FPs filtered.
=> [New Rule] Suspicious Module Loaded by LSASS

rules/windows/collection_mailbox_export_winlog.toml
New rule similar to this [one](https://github.com/elastic/detection-rules/blob/main/rules/windows/collection_email_powershell_exchange_mailbox.toml) but using Windows powershell logs 4104.
=> [New Rule] Exchange Mailbox via PowerShell

rules/cross-platform/multiple_alerts_different_tactics_host.toml, rules/cross-platform/multiple_alerts_involving_user.toml
#2456 
Remove the timeline references from alert correlation rules
=> [Rule Tuning] Remove unreleased timeline from alert correlation rules

rules/windows/discovery_posh_suspicious_api_functions.toml
Adds more discovery-related Windows API functions
=> [Rule Tuning] PowerShell Suspicious Discovery Related Windows API Functions

rules/windows/defense_evasion_posh_encryption.toml
Identifies the use of Cmdlets and methods related to encryption/decryption of files in PowerShell scripts, which malware and offensive security tools can abuse to encrypt data or decrypt payloads to bypass security solutions.
=> [New Rule] PowerShell Script with Encryption/Decryption Capabilities

rules/windows/credential_access_suspicious_lsass_access_generic.toml
Generic detection using sysmon and excluding common FP patterns.
=> [New Rule] T1003.001 - Lsass Memory

detection_rules/etc/non-ecs-schema.json, rules/windows/persistence_service_dll_unsigned.toml
Compatible with Endpoint 8.4+ only
=> [New Rule] T1543.003 - Unsigned DLL Loaded by Svchost

detection_rules/etc/non-ecs-schema.json, rules/windows/collection_email_outlook_mailbox_via_com.toml
Detect Inter-Process communication via COM with Outlook, this could be a sign of Local Email Collection (T1114.001) from outlook or other form of code execution:
=> [New Rule] Suspicious Inter-Process Communication via Outlook

rules/windows/defense_evasion_amsi_bypass_dllhijack.toml, rules/windows/defense_evasion_amsi_bypass_powershell.toml
DLL hijack:
PowerShell Scripts:
=> [New Rules] Amsi Bypass 

rules/windows/defense_evasion_untrusted_driver_loaded.toml
Moved a diag endpoint rule to SIEM to cover T1553.006
=> [New Rule] T1553.006 - Untrusted Driver Loaded

rules/cross-platform/persistence_ssh_authorized_keys_modification.toml, rules/linux/credential_access_potential_linux_ssh_bruteforce_root.toml, rules/linux/persistence_credential_access_modify_ssh_binaries.toml, rules/windows/lateral_movement_incoming_winrm_shell_execution.toml, rules/windows/lateral_movement_powershell_remoting_target.toml
added  T1021.006 and T1563.001 to relevant rules.
=> [Tuning] added T1021.006 and T1563.001

detection_rules/etc/non-ecs-schema.json, rules/windows/command_and_control_certreq_postdata.toml, rules/windows/command_and_control_ingress_transfer_bits.toml
- Ingress tools transfer via BITS
- Exfiltration via CertReq
=> [New Rules] C2 via BITS and CertReq 

rules/windows/credential_access_remote_sam_secretsdump.toml
Switch back a change introduced in https://github.com/elastic/detection-rules/pull/2438 so the rule effectively have the data needed to sequence the events.
=> [Rule Tuning] Potential Remote Credential Access via Registry

rules/linux/execution_file_transfer_or_listener_established_via_netcat.toml, rules/linux/execution_shell_evasion_linux_binary.toml, rules/linux/persistence_chkconfig_service_add.toml, rules/windows/collection_winrar_encryption.toml, rules/windows/credential_access_cmdline_dump_tool.toml, rules/windows/defense_evasion_clearing_windows_event_logs.toml, rules/windows/defense_evasion_disabling_windows_logs.toml, rules/windows/defense_evasion_execution_windefend_unusual_path.toml, rules/windows/discovery_admin_recon.toml, rules/windows/discovery_remote_system_discovery_commands_windows.toml, rules/windows/lateral_movement_evasion_rdp_shadowing.toml
* Fix the rule conditions to trigger in the intended event types, avoiding duplicated alerts with both process start and end events.
* Add `event.type == "start"` to rules which don't specify one.
=> [Rule Tuning] Enclose Rule Conditions within Parenthesis

rules/windows/persistence_service_windows_service_winlog.toml
added couple of suspicious values.
=> [Rule Tuning] Persistence via Windows Service

rules/windows/discovery_enumerating_domain_trusts_via_dsquery.toml, rules/windows/discovery_enumerating_domain_trusts_via_nltest.toml
https://github.com/elastic/detection-rules/issues/2536
The Mitre Eval Score Analysis - 2022 [ [Refer](https://docs.google.com/document/d/1wVrhMIUS8wPqPhSgU8bf0bjLhaKFuNHv-d4AYkSQ3p0/edit?usp=sharing) ] identified the following:
[[rule.threat.technique]]
id = "T1018"
name = "Remote System Discovery"
reference = "https://attack.mitre.org/techniques/T1018/"
...to be added to the following rules for higher coverage score
https://github.com/elastic/detection-rules/blob/main/rules/windows/discovery_enumerating_domain_trusts_via_dsquery.toml 
https://github.com/elastic/detection-rules/blob/main/rules/windows/discovery_enumerating_domain_trusts_via_nltest.toml 
- Have you followed the [contributor …
=> [Rule Tuning] Add T1018 for higher coverage

rules/windows/credential_access_via_snapshot_lsass_clone_creation.toml
https://elasticstack.slack.com/archives/CRXGYCYC8/p1680696299112059
Adds the system integration to the indexes, as this is the one which collects security logs when they are not in Forwarded channel (WEF)
=> [Rule Tuning] Potential LSASS Clone Creation via PssCaptureSnapShot

rules/windows/defense_evasion_posh_compressed.toml, rules/windows/defense_evasion_posh_process_injection.toml, rules/windows/discovery_posh_suspicious_api_functions.toml, rules/windows/privilege_escalation_posh_token_impersonation.toml
Resolves #2719 
Tune the two rules mentioned in the issue and some other FPs observed related to ATP.
=> [Rule Tuning] Tune PowerShell rule FPs related to MS ATP

rules/windows/credential_access_cmdline_dump_tool.toml
Resolves #2539 
Adds compatibility with Security 4688 events.
=> [Rule Tuning] Potential Credential Access via Windows Utilities

rules/linux/execution_abnormal_process_id_file_created.toml
#2543
- /var/run is symlinked to /run
- Tune the query to include this path regex for /run.
<details>
```
{
"_index": ".ds-logs-endpoint.events.file-default-2023.04.23-000014",
"_id": "lZpluYcBZZPOCojzMCGU",
"_score": 1,
"fields": {
"file.path": [
"/run/test.pid"
],
"host.os.full.text": [
"Debian 11.6"
],
"event.category": [
"file"
],
"process.name.text": [
"touch"
],
"host.os.name.text": [
"Linux"
],
"host.os.full": [
"Debian 11.6"
],
"host.hostname": [
"instance-1"
],
"process.pid": [
100114
],
"host.mac": [
"42:01:0a:80:00:14"
],
"elastic.agent.id": [
"7e27cf6e-ba6e-49bd-ac80-3a01fd0724da"
],
"process.parent.entity_id": [
"N2UyN2NmNmUtYmE2ZS00OWJkLWFjODAtM2EwMWZkMDcyNGRhLTEwMDEwOC0xNjgyNDQyNTE3"
],
"host.os.version": [
"11.6"
],
"process.entry_leader.parent.entity_id": [ …
```
=> Update file path regex for /run

.github/workflows/release-docs.yml
Related to https://github.com/elastic/detection-rules/pull/2745
Setup base workflow for testing.
=> [FR] Add base release-docs workflow

.github/workflows/get-target-branches.yml, .github/workflows/lock-versions.yml, .github/workflows/manual-backport.yml, .github/workflows/pythonpackage.yml, .github/workflows/release-docs.yml, .github/workflows/release-fleet.yml, pyproject.toml
* https://github.com/elastic/detection-rules/actions/runs/5068845650/jobs/9101663908?pr=2777
Adds `typing-extensions==4.5.0` as a dependancy.
=> [Bug] Adding additional dependency `typing-extensions`

rules/windows/execution_suspicious_powershell_imgload.toml
- Closes #2830 
Launching SQL Server Management Studio loads "System.Management.Automation.dll". Adding an exception to the query for a process name of `Ssms.exe`.
=> [Suspicious PowerShell Engine ImageLoad] Add Ssms.exe to query exceptions

detection_rules/main.py, detection_rules/schemas/definitions.py
Related to https://github.com/elastic/detection-rules/pull/2885
Loads schemas to determine unsupported rule types.
=> [FR] Load unsupported rule type from schema

README.md
None
Fixes the etc path in the readme.
=> Update README.md to fix etc path

rules/windows/collection_posh_audio_capture.toml, rules/windows/execution_posh_hacktool_functions.toml
Include Additional HackTool keywords.
=> [Rule Tuning] Add HackTool Keywords to PowerShell Rules

rules/windows/defense_evasion_wsl_kalilinux.toml, rules_building_block/initial_access_cross_site_scripting.toml
[defense_evasion_wsl_kalilinux.toml](https://github.com/elastic/detection-rules/blob/main/rules/windows/defense_evasion_wsl_kalilinux.toml)
- Closes #2951 
There is a misspelling in the query where "AppDara" should be "AppData"
=> [Bug] Attempt to Install Kali Linux via WSL

rules/windows/persistence_service_windows_service_winlog.toml
=> fixing typo in 127.0.0.1 address

rules/windows/collection_posh_keylogger.toml
Adjusts the SentinelOne exclusion, adds the WH_MOUSE_LL hook
=> [Rule Tuning] PowerShell Keylogging Script

.github/paths-labeller.yml
#3064
Adds an entry to the github path labeler for building block rules.
Rule PRs with `building_block_rule/*.toml` changes should auto label with `bbr`
=> [FR] Auto label bbr rules

rules/linux/credential_access_bruteforce_password_guessing.toml, rules/linux/execution_shell_evasion_linux_binary.toml
This rule tuning addresses #3073, and reduces FPs slightly as well. 
Additionally, I changed the title of the Linux SSH brute forcing (with succession) rule, and bumped up the severity to high due to only TPs in telemetry.
=> [Rule Tuning] Small Linux DR Tuning

rules/cross-platform/threat_intel_indicator_match_address.toml, rules/cross-platform/threat_intel_indicator_match_hash.toml, rules/cross-platform/threat_intel_indicator_match_registry.toml, rules/cross-platform/threat_intel_indicator_match_url.toml, tests/test_all_rules.py
Related to https://github.com/elastic/detection-rules/issues/2827 & https://github.com/elastic/detection-rules/pull/3085
Adds missing osquery transforms
=> [Security Content] Add missing osquery transforms

rules_building_block/defense_evasion_download_susp_extension.toml
Identifies unusual files downloaded from outside the local network that have the potential to be abused for code execution.
=> [New Rule] [BBR] File with Suspicious Extension Downloaded

rules/linux/privilege_escalation_looney_tunables_cve_2023_4911.toml
Adjusting the query logic to catch variants of the exploit that targets other glibc functions and other SUID/GUID binaries.
=> [Tuning] CVE-2023-4911

rules/windows/collection_mailbox_export_winlog.toml, rules/windows/collection_posh_clipboard_capture.toml, rules/windows/collection_posh_mailbox.toml, rules/windows/credential_access_posh_request_ticket.toml, rules/windows/defense_evasion_posh_compressed.toml, rules/windows/execution_posh_hacktool_functions.toml, rules/windows/execution_posh_psreflect.toml, rules/windows/privilege_escalation_posh_token_impersonation.toml, rules_building_block/collection_posh_compression.toml, rules_building_block/defense_evasion_powershell_clear_logs_script.toml, rules_building_block/discovery_posh_generic.toml, rules_building_block/lateral_movement_posh_winrm_activity.toml
Adjust the rules to exclude some noisy patterns observed.
=> [Rule Tuning] PowerShell Rules Tuning

rules_building_block/persistence_tainted_kernel_module_load.toml
Copy paste error, somehow the wrong index got in there. This PR is to fix that, and add some additional mitre coverage / clean set up guide in the meanwhile.
=> [Rule Tuning] Tainted Kernel Module Load

detection_rules/schemas/definitions.py
Resolves #3220 
Adds the tag for future UEBA rule support.
=> [FR] Add UEBA Tag to Definitions

rules/windows/privilege_escalation_make_token_local.toml
=> [New] Interactive Logon by an Unusual Process

detection_rules/schemas/definitions.py, rules/network/command_and_control_fin7_c2_behavior.toml
- Closes #3284 
This PR changes the "or" operator to the required uppercase "OR" to fix an execution error. 
=> [Bug] Possible FIN7 DGA Command and Control Behavior

rules/linux/defense_evasion_binary_copied_to_suspicious_directory.toml, rules/linux/persistence_setuid_setgid_capability_set.toml, rules_building_block/defense_evasion_sus_utility_executed_via_tmux_or_screen.toml, rules_building_block/discovery_suspicious_which_command_execution.toml
Small Linux DR tuning to tackle the most common FPs in these rules.
=> [Tuning] Small Linux DR Tuning

rules/windows/defense_evasion_suspicious_managedcode_host_process.toml
Related issue https://github.com/elastic/ia-trade-team/issues/232
removed process event from the sequence, not needed (we have a rule for renamed lolbins and svchost, dllhost).
=> [Tuning] Suspicious Managed Code Hosting Process

rules/windows/defense_evasion_suspicious_scrobj_load.toml
Issue https://github.com/elastic/ia-trade-team/issues/232
- converted query to be compatible also with Sysmon EventId 7 (Image Load) 
- removed process event from the sequence
- excluded some observed FPs
=> [Tuning] Suspicious Script Object Execution

rules/windows/defense_evasion_posh_assembly_load.toml, rules/windows/defense_evasion_suspicious_wmi_script.toml, rules/windows/defense_evasion_timestomp_sysmon.toml, rules/windows/defense_evasion_unusual_system_vp_child_program.toml, rules/windows/defense_evasion_via_filter_manager.toml
Part of #3186 
* Suspicious .NET Reflection via PowerShell
* Suspicious WMIC XSL Script Execution
* Unusual Child Process from a System Virtual Process
* File Creation Time Changed
* Potential Evasion via Filter Manager
=> [Rule Tuning] Windows DR Tuning - 8

rules/windows/defense_evasion_wsl_bash_exec.toml, rules/windows/defense_evasion_wsl_child_process.toml, rules/windows/discovery_admin_recon.toml, rules/windows/discovery_command_system_account.toml, rules/windows/discovery_posh_suspicious_api_functions.toml
Part of #3186 
* Suspicious Execution via Windows Subsystem for Linux
* Execution via Windows Subsystem for Linux
* Enumeration of Administrator Accounts
* Account Discovery Command via SYSTEM Account
* PowerShell Suspicious Discovery Related Windows API Functions
=> [Rule Tuning] Windows DR Tuning - 9

rules/linux/persistence_dynamic_linker_backup.toml
While writing an investigation guide for this rule, I noticed the rule does not monitor all dynamic linker locations. I added them to this PR, and the IG will be added separately.
=> [Rule Tuning] Dynamic Linker Copy

rules/windows/execution_posh_hacktool_functions.toml, rules/windows/execution_suspicious_powershell_imgload.toml, rules/windows/impact_backup_file_deletion.toml, rules/windows/initial_access_script_executing_powershell.toml, rules/windows/initial_access_suspicious_ms_exchange_process.toml
Part of #3186 
* Potential PowerShell HackTool Script by Function Names
* Suspicious PowerShell Engine ImageLoad
* Third-party Backup Files Deleted via Unexpected Process
* Windows Script Executing PowerShell
* Microsoft Exchange Server UM Spawning Suspicious Processes
=> [Rule Tuning] Windows DR Tuning - 11

rules/windows/initial_access_suspicious_ms_office_child_process.toml, rules/windows/lateral_movement_direct_outbound_smb_connection.toml, rules/windows/lateral_movement_execution_via_file_shares_sequence.toml, rules/windows/lateral_movement_remote_file_copy_hidden_share.toml, rules/windows/lateral_movement_remote_services.toml
Part of #3186 
Resolves https://github.com/elastic/detection-rules/issues/3103
* Suspicious MS Office Child Process
* Direct Outbound SMB Connection
* Remote Execution via File Shares
* Remote File Copy to a Hidden Share
* Remotely Started Services via RPC
=> [Rule Tuning] Windows DR Tuning - 12

rules/linux/persistence_apt_package_manager_execution.toml, rules/linux/persistence_apt_package_manager_netcon.toml, rules/linux/persistence_apt_package_manager_persistence.toml
This PR adds two additional detection rules (might be promoted to endpoint rules in the future - not expecting many FPs in this one):
1. Suspicious APT Package Manager Execution
2. Suspicious APT Package Manager Network Connection
Detects suspicious process events executed by the APT package manager, potentially indicating persistence through an APT backdoor. In Linux, APT (Advanced Package Tool) is a command-line utility used for handling packages on Debian-based systems, providing functions for installing, updating, upgrading, and removing software along with managing package repositories. Attackers can backdoor APT to gain persistence by injecting malicious code into scripts that APT runs, thereby ensuring continued unauthorized access or control each time APT is used for package …
=> [New Rules] APT Package Manager Persistence

.github/ISSUE_TEMPLATE/new_kibana_feature_request.md
Related to https://github.com/elastic/ia-trade-team/discussions/294
Adds an issue template for new kibana feature schema changes.
=> [FR] Add New Kibana Schema Issue Template

rules/windows/initial_access_execution_from_inetcache.toml
=> [New] Suspicious Execution from INET Cache

rules/linux/defense_evasion_file_mod_writable_dir.toml, rules/linux/defense_evasion_hidden_file_dir_tmp.toml, rules/linux/defense_evasion_hidden_shared_object.toml, rules/linux/defense_evasion_kernel_module_removal.toml, rules/linux/defense_evasion_mount_execution.toml, rules/linux/defense_evasion_potential_proot_exploits.toml
Part 4 of the Linux DR tuning. Besides regular rule tuning, this PR added compatibility with additional data sources where possible, added correct tags/indices, fixed formatting, and checked for potential rule performance increases.
=> [Tuning] Linux DR Tuning - Part 4

.github/workflows/lock-versions.yml, Makefile
Related to the failing [ci workflow](https://github.com/elastic/detection-rules/actions/runs/8375162208/job/22931935656)
- Updates the lock versions workflow to install kql
- Updates make to rename PHONY
=> [Bug] Update lock versions dependencies

rules/windows/initial_access_exploit_jetbrains_teamcity.toml
=> [New] Suspicious JetBrains TeamCity  Child Process

rules/windows/defense_evasion_untrusted_driver_loaded.toml
small tuning request (from community slack thread, excluding `dll.code.signature.status : "errorCode_endpoint:*"` (noisy)
=> [Tuning] Untrusted Driver Loaded

rules/windows/privilege_escalation_exploit_cve_202238028.toml
https://www.microsoft.com/en-us/security/blog/2024/04/22/analyzing-forest-blizzards-custom-post-compromise-tool-for-exploiting-cve-2022-38028-to-obtain-credentials/
=> [New] Potential privilege escalation via CVE-2022-38028

rules/linux/command_and_control_linux_kworker_netcon.toml, rules/linux/command_and_control_linux_tunneling_and_port_forwarding.toml
Small tuning of 2 Linux DRs that were either noisy or had a query logic typo.
=> [Rule Tuning] Linux DRs

rules/linux/persistence_shell_configuration_modification.toml
This rule monitors the creation/alteration of a shell configuration by a previously unknown process executable using the new terms rule type. Unix systems use shell configuration files to set e.g. environment variables, create aliases, and customize the user's environment. Adversaries may modify or add a shell configuration file to execute malicious code and gain persistence onto the system. This behavior is consistent with e.g. the Kaiji malware family.
```
event.category:file and host.os.type:linux and
event.action:(creation or file_create_event or rename or file_rename_event) and file.path:(
"/etc/profile" or "/etc/profile.local" or "/etc/bashrc" or "/etc/bash.bashrc" or "/etc/bash.bashrc.local" or
"/etc/zshenv" or "/etc/zprofile" or "/etc/zlogin" or "/etc/zlogout" or "/root/.profile" …
```
=> [New Rule] Shell Configuration Modification

README.md, hunting/generate_markdown.py, hunting/index.md
Related to https://github.com/elastic/detection-rules/pull/3637 and https://github.com/elastic/detection-rules/pull/3642
- Re-adds ability to generate hunt index 
- Adds support to mitre attack urls
=> [FR] Add ability to generate hunt index

detection_rules/schemas/definitions.py, rules/integrations/aws/aws_bedrock_high_resource_consumption_detection.toml
Related to #3637 and https://github.com/elastic/detection-rules/pull/3641
Detects potential resource exhaustion or data breach attempts by monitoring for users who consistently generate high input token counts, submit numerous requests, and receive large responses. This behavior could indicate an attempt to overload the system or extract an unusually large amount of data, possibly revealing sensitive information or causing service disruptions.
Screenshot:
Note: The image has a lower threshold used for testing.
=> [New Rule] Potential Abuse of Resources by High Token Count and Large Response Sizes

README.md, Troubleshooting.md
https://github.com/elastic/detection-rules/issues/3639
This updates the README to have more information to help users who may be less familiar with python virtual environments.
Additionally this adds a Troubleshooting markdown file for walking through some specific issues users had with managing python3.12 virtual environments for using our repo.
=> [FR] Update readme with wsl instructions for py312

rules/integrations/o365/initial_access_microsoft_365_abnormal_clientappid.toml
https://elasticstack.slack.com/archives/C016E72DWDS/p1715710049183979
excluding known ClientAppIds https://github.com/MISP/misp-warninglists/blob/main/lists/microsoft-azure-appid/list.json and expanded the `history_window_start` from 10d to 25d to reduce noisy false positives.
=> [Tuning] Suspicious Microsoft 365 Mail Access by ClientAppId

detection_rules/config.py, detection_rules/custom_rules.py, detection_rules/etc/_config.yaml, detection_rules/packaging.py, detection_rules/utils.py, docs/custom-rules.md, tests/test_packages.py
Related to https://github.com/elastic/detection-rules/issues/3622
Normalizes yml to yaml extensions in the logic and docs.
=> [FR] Normalize yaml/yml extension

rules/macos/credential_access_suspicious_web_browser_sensitive_file_access.toml
https://github.com/elastic/detection-rules/issues/3690 (fix index typo) - verified no other rules with same typo.
=> [Rule Tuning] Suspicious Web Browser Sensitive File Access

rules/windows/impact_high_freq_file_renames_by_kernel.toml
https://elasticstack.slack.com/archives/C016E72DWDS/p1716449824763149
changed the rule schedule frequency from every 1m to every 9m (to improve performance) : 
- Runs every :  5m
- Additional look-back time : 4m
=> [Tuning] Potential Ransomware Behavior - High count of Readme files by System

.github/workflows/lock-versions.yml, .github/workflows/pythonpackage.yml, .github/workflows/release-fleet.yml
This pull request updates the Upload Artifact Github action to version 4 as recommended by the developer based on deprecation dates.
Ref: https://github.com/actions/upload-artifact
=> [Update] Updating `upload-artifact` to Version 4

rules/integrations/fim/persistence_suspicious_file_modifications.toml
As part of Release https://github.com/elastic/ia-trade-team/issues/378 document builds failed with [error](https://buildkite.com/elastic/docs-build-pr/builds/93000#0190087f-d80b-4e5c-ab91-1dbbf1ddad04)
- Rectify Sequence numbering in Setup.
=> Update FIM integration Setup sequence

rules/windows/defense_evasion_microsoft_defender_tampering.toml
excluding top noisy source processes (svchost.exe, ccmexec.exe and a couple).
=> [Tuning] Microsoft Windows Defender Tampering

rules/linux/persistence_ssh_key_generation.toml
Fix for rule throwing verification error
=> [Bug] Persistence ssh key generation index pattern

rules/windows/defense_evasion_sc_sdset.toml
Identifies DACL modifications to deny access to a service, making it unstoppable, or hide it from system and users.
<details>
<summary>Sample data</summary>
```
{
"_index": ".ds-logs-endpoint.events.process-default-2024.07.12-000026",
"_id": "QXEPvJABiLqpmBCYFrUr",
"_score": 1,
"_source": {
"agent": {
"id": "c725ae87-e846-4602-9a08-2c717a3a504b",
"version": "8.14.2"
},
"process": {
"Ext": {
"mitigation_policies": [
"CF Guard"
],
"ancestry": [
"YzcyNWFlODctZTg0Ni00NjAyLTlhMDgtMmM3MTdhM2E1MDRiLTEwOTM2LTE3MjExMzMwMDguMjYxNDAzNDAw",
"YzcyNWFlODctZTg0Ni00NjAyLTlhMDgtMmM3MTdhM2E1MDRiLTc5NDgtMTcyMTA4NjkwOC40MTUxODIxMDA=",
"YzcyNWFlODctZTg0Ni00NjAyLTlhMDgtMmM3MTdhM2E1MDRiLTQ4ODgtMTcyMTA4NjkwOC4zMjEzNDQ5MDA=",
"YzcyNWFlODctZTg0Ni00NjAyLTlhMDgtMmM3MTdhM2E1MDRiLTY5Mi0xNzIxMDg1MjE4 …
```
=> [New Rule] Service DACL Modification via sc.exe

rules/windows/command_and_control_common_webservices.toml
=> [tuning] Connection to Commonly Abused Web Services

rules/integrations/aws/defense_evasion_s3_bucket_server_access_logging_disabled.toml
- https://github.com/elastic/ia-trade-team/issues/346
Identifies when server access logging is disabled for an Amazon S3 bucket. Server access logs provide a detailed record of requests made to an S3 bucket. When server access logging is disabled for a bucket, it could indicate an adversary's attempt to impair defenses by disabling logs that contain evidence of malicious activity.
i've included a screenshot for both enabling and disabling server access logging. The difference in events is the inclusion vs eclusion of the `LoggingEnabled` parameter. 
```
$ cat logging.json 
{
"LoggingEnabled": {
"TargetBucket": "simulation-bucket-04-logging-zpkgm60l5dxh3f2y",
"TargetPrefix": "s3logs/"
}
}
$ aws s3api put-bucket-logging --bucket simulation-bucket-04-zpkgm60l5dxh3f2y / …
```
=> [New Rule] AWS S3 Bucket Server Access Logging Disabled

rules/_deprecated/impact_potential_linux_ransomware_file_encryption.toml, rules/linux/command_and_control_suspicious_network_activity_from_unknown_executable.toml, rules/linux/defense_evasion_binary_copied_to_suspicious_directory.toml, rules/linux/execution_suspicious_executable_running_system_commands.toml, rules/linux/execution_unknown_rwx_mem_region_binary_executed.toml, rules/linux/impact_potential_linux_ransomware_note_detected.toml, rules/linux/persistence_apt_package_manager_netcon.toml, rules/linux/persistence_cron_job_creation.toml, rules/linux/persistence_kde_autostart_modification.toml, rules/linux/persistence_kworker_file_creation.toml
=> [Rule Tuning] Misc. DR Rule Tuning

rules/windows/collection_posh_keylogger.toml, rules/windows/credential_access_posh_invoke_ninjacopy.toml, rules/windows/credential_access_posh_kerb_ticket_dump.toml, rules/windows/credential_access_posh_relay_tools.toml, rules/windows/defense_evasion_posh_assembly_load.toml, rules/windows/defense_evasion_posh_compressed.toml, rules/windows/defense_evasion_posh_encryption.toml, rules/windows/defense_evasion_posh_process_injection.toml, rules/windows/discovery_posh_suspicious_api_functions.toml, rules/windows/execution_posh_hacktool_authors.toml, rules/windows/execution_posh_psreflect.toml, rules/windows/privilege_escalation_posh_token_impersonation.toml, rules_building_block/collection_posh_compression.toml, rules_building_block/defense_evasion_powershell_clear_logs_script.toml
Exclude noisy FP patterns and bump up severity of non-noisy/high TP PowerShell rules.
=> [Rule Tuning] PowerShell Rule Review & Tuning

rules/windows/lateral_movement_via_wsus_update.toml
Part of #3544
Identifies a potential Windows Server Update Services (WSUS) abuse to execute attackers' payloads for lateral movement. WSUS is limited to executing Microsoft signed binaries, which limits the executables that can be used to tools published by Microsoft or Windows native executables.
0 hits in RS.
<details>
<summary> Data </summary>
```
{
"_index": ".ds-logs-endpoint.events.process-default-2024.07.12-000026",
"_id": "hCcpx5ABiLqpmBCYpK38",
"_score": 1,
"_source": {
"agent": {
"id": "a92e2d70-f858-45a8-8261-6fcf47064d69",
"version": "8.14.2"
},
"process": {
"Ext": {
"ancestry": [
"YTkyZTJkNzAtZjg1OC00NWE4LTgyNjEtNmZjZjQ3MDY0ZDY5LTIxNjgtMTcyMTMyODI3Ny4zOTk3NjYyMDA=",
"YTkyZTJkNzAtZjg1OC00NWE4LTgyNjEtNmZjZjQ3MDY0ZDY5LTExMzU2LTE3MjEzMjgyNjEuMTU2Mzk4OTAw", …
```
=> [New Rule] Potential WSUS Abuse for Lateral Movement

rules/windows/execution_via_mmc_console_file_unusual_path.toml
*Issue link(s)*:  Fix Double Bump in PR - https://github.com/elastic/detection-rules/pull/3924
- For Rule `Microsoft Management Console File from Unusual Path` there is a breaking change for integration `sentinel_one_cloud_funnel` at version `8.13`.
- For versions 8.13 --> main the related integrations are 
```
"related_integrations": [
{
"package": "endpoint",
"version": "^8.2.0"
},
{
"package": "windows",
"version": "^1.5.0"
},
{
"package": "sentinel_one_cloud_funnel",
"version": "^1.0.0"
},
{
"package": "m365_defender",
"version": "^2.0.0"
}
],
```
- For versions 8.12  --> 8.9  the related integrations are 
```
"related_integrations": [
{
"package": "endpoint",
"version": "^8.2.0"
},
{
"package": "windows",
"version": "^1.5.0"
},
{
"package": "sentinel_one_cloud_funnel",
"version": …
```
=> Update Rule Min stack

rules_building_block/credential_access_iis_apppoolsa_pwd_appcmd.toml
Resolves #3807 
Changes the args we look for in this rule to match the syntax that actually works and removed the `password` keyword as it is not needed to obtain passwords. I've moved this one to BBR so we can validate the noise of this change and tune it before reintroducing it as a normal DR, as we don't have any TP telemetry.
<Details>
<Summary>Sample Event</Summary>
```
{
"_index": ".ds-logs-endpoint.events.process-default-2024.07.12-000026",
"_id": "Mgl6CZEBiLqpmBCYtAJu",
"_score": 1,
"_source": {
"agent": {
"id": "c725ae87-e846-4602-9a08-2c717a3a504b",
"version": "8.14.2"
},
"process": {
"Ext": {
"mitigation_policies": [
"CF Guard"
],
"ancestry": [
"YzcyNWFlODctZTg0Ni00NjAyLTlhMDgtMmM3MTdhM2E1MDRiLTEwMTkyLTE3MjI0NDA2ODMuMzEzOTUwOTAw", …
```
=> [Rule Tuning] Microsoft IIS Service Account Password Dumped

rules/network/command_and_control_accepted_default_telnet_port_connection.toml
Resolves https://github.com/elastic/detection-rules/issues/3264
Adds `flow_denied` to the exclusion list.
=> [Rule Tuning] Accepted Default Telnet Port Connection

rules/windows/command_and_control_outlook_home_page.toml
Identifies modifications in registry keys associated with abuse of the Outlook Home Page functionality for command and control or persistence.
<Details>
<Summary> Sample Data </Summary>
```
{
"_index": ".ds-logs-endpoint.events.registry-default-2024.07.12-000025",
"_id": "ZNOtAJEBiLqpmBCYQ7MJ",
"_score": 1,
"_source": {
"registry": {
"hive": "HKEY_USERS",
"path": "HKEY_USERS\\S-1-5-21-1996809829-4272298256-871542599-1112\\SOFTWARE\\Microsoft\\Office\\16.0\\Outlook\\Webview\\Inbox\\url",
"data": {
"strings": [
"http://evil.com/plugin/search/"
],
"type": "REG_SZ"
},
"value": "url",
"key": "S-1-5-21-1996809829-4272298256-871542599-1112\\SOFTWARE\\Microsoft\\Office\\16.0\\Outlook\\Webview\\Inbox"
},
"agent": {
"id": "bc12976b-14a0-4b69-a01e-4a67d885be5a",
"version": …
```
=> [New Rule] Outlook Home Page Registry Modification

rules/cross-platform/execution_python_script_in_cmdline.toml, rules/windows/credential_access_dcsync_user_backdoor.toml, rules/windows/initial_access_evasion_suspicious_htm_file_creation.toml, rules/windows/persistence_startup_folder_scripts.toml
*Issue link(s)*: NA
Removing min stack and comments from rules as they are unecessary. These were added before we dropped support for current-5.
No testing required.
=> [Rule Tuning] Removing Minimum Stack Compatibility

rules/linux/defense_evasion_dynamic_linker_file_creation.toml
Detects the creation or modification of files related to the dynamic linker on Linux systems. The dynamic linker is a shared library that is used by the Linux kernel to load and execute programs. Attackers may attempt to hijack the execution flow of a program by modifying the dynamic linker configuration files.
A few hits in telemetry last 90d, but that is expected. This behavior is however of great importance to detect. Furthermore, only TPs in my testing stack, and several malware sample TPs from detonate:
=> [New Rule] Dynamic Linker Creation or Modification

detection_rules/config.py
This PR adds support for creating nested directories for the automatic schema generation schema file. Previously it would not created nested directories. 
To test this, first add the appropriate config variable. Also make sure that this variable used a nested directory that does not already exist. E.g. `auto_gen_schema_file: "etc/schemas/auto_gen.json"` where schemas does not already exist. Also make sure your `stack-schema-map.yaml` does not already have any custom schemas supplied (or at least not any that have the fields in the test rule). Next, run view-rule on a rule that has fields that are not currently present in a schema. The rule should validate successfully and your schema file should be updated, and the directory should be created.
Example: `python -m …
=> [FR] [DAC] Auto Gen Schema Create Nested Directories

rta/schtask_escalation.py
*Issue link(s)*:  Reported in Community Slack
- Add concatenate str to the file_path
- Run the RTA with the fix to check it executes with no errors 
```console
(venv) PS C:\Users\shashank_suryanaraya\detection-rules> python -m rta -n schtask_escalation
[+] Scheduled Task Privilege Escalation
shashank_suryanaraya @ e2e-release-windows-server-2022 > schtasks.exe /query /tn test-task-rta
ERROR: The system cannot find the file specified.
exit code = 1
shashank_suryanaraya @ e2e-release-windows-server-2022 > schtasks.exe /create /tn test-task-rta /ru system /tr "cmd.exe /c whoami.exe > task.log" /sc onlogon
SUCCESS: The scheduled task "test-task-rta" has successfully been created.
shashank_suryanaraya @ e2e-release-windows-server-2022 > schtasks.exe /run /tn test-task-rta
SUCCESS: Attempted to …
```
=> Fix Windows File Path for RTA schtask_escalation

rules/windows/credential_access_lsass_openprocess_api.toml
=> [Rule Tuning] LSASS Process Access via Windows API

detection_rules/main.py
*Issue link(s)*: https://github.com/elastic/detection-rules/issues/4011
The help text states: `Import rules from json, toml, yaml, or Kibana exported rule file(s).`, which is somewhat misleading. While it does support multiple types (json, toml, or yaml), all of these types require the rule to be the format of a Kibana exported rule (in effect a rule that is in the Kibana API format). The toml rule you are specifying has already been imported and is no longer in the Kibana API format, rather it is in the detection rules native rule format. Running the `import-rules-to-repo` command on this rule is redundant. If you would like that rule in your folder of custom rules, the recommended action is to either move the rule to a folder specified in your custom `_config.yaml` or add the folder the …
=> [FR] [DaC] Update Import Rules to Repo Help Text for Clarity

rta/linux_cron_hidden_execution.py, rta/linux_discovery_command_from_sus_dir.py, rta/linux_execution_hidden_process_unusual_execution.py, rta/linux_execution_interactive_shell_spawn_from_hidden_process.py, rta/linux_execution_setsid_nohup_unusual_execution.py, rta/linux_motd_netcon.py, rta/linux_persistence_dpkg_netcon.py, rta/linux_persistence_initd_netcon.py, rta/linux_persistence_initd_unusual_binary_execution.py, rta/linux_persistence_motd_netcon_parent_child.py, rta/linux_persistence_rpm_netcon.py, rta/linux_persistence_scheduled_task_executing_sus_located_binary.py, rta/linux_python_netcon_file_creation.py, rta/linux_sus_netcon_command_exec.py, rta/linux_sus_netcon_file_creation.py, rta/linux_systemd_netcon.py, rta/linux_unusual_scheduled_task_command_exection.py
=> react_sync_rta_updates_3916

rules/integrations/aws/discovery_ec2_multi_region_describe_instances.toml, rules/integrations/aws/discovery_ec2_multi_region_service_quota_requests.toml, rules/integrations/aws/discovery_servicequotas_multi_region_service_quota_requests.toml
*Issue link(s)*: https://github.com/elastic/ia-trade-team/issues/272
Adds two new detection rules for unusual AWS EC2 API calls `DescribeInstances` and `GetServiceQuota` across multiple-regions by a single resource. While common in both manual and programmatic practice in AWS, across all regions in a short time-window is not and typically indicates a tool being used with compromised creds or instance.
`GetServiceQuota` is also filtered for on-demand EC2 instance quota codes which are favored by adversaries for deploying on-demand infrastructure, typically for crypto miners.
script used: https://gist.github.com/terrancedejesus/5de515084b375e8b9ab50e6bb0280151 (requires aws-cli authentication already established)
- Have you signed the [contributor license …
=> [New Rule] New Rules AWS Multi-Region Discovery of EC2 Instances and Quotas

rules_building_block/command_and_control_certutil_network_connection.toml, rules_building_block/discovery_capnetraw_capability.toml, rules_building_block/discovery_signal_unusual_user_host.toml, rules_building_block/execution_aws_lambda_function_updated.toml, rules_building_block/initial_access_cross_site_scripting.toml, rules_building_block/lateral_movement_rdp_conn_unusual_process.toml, tests/test_all_rules.py
*Issue link(s)*:  https://github.com/elastic/detection-rules/pull/new/issue-4045
- Added test Case to check if Rule Type: BBR tag is present for all BBR rules
- Added a separate test case in class TestRuleTags
- Local Testing identified few rules with missing tags
<details><summary>Unit Test Failure</summary>
<p>
```console
=================================== FAILURES ===================================
__________________________ TestRuleTags.test_bbr_tags __________________________
self = <tests.test_all_rules.TestRuleTags testMethod=test_bbr_tags>
def test_bbr_tags(self):
"""Test that "Rule Type: BBR" tag is present for all BBR rules."""
invalid_bbr_rules = []
for rule in self.bbr:
if 'Rule Type: BBR' not in rule.contents.data.tags:
invalid_bbr_rules.append(self.rule_str(rule))
if …
```
=> Testcase to check if Rule Type: BBR tag is present for all BBR rules

rules/integrations/azure/credential_access_entra_signin_brute_force_microsoft_365.toml, rules/integrations/azure/credential_access_entra_signin_brute_force_microsoft_365_repeat_source.toml, rules/integrations/o365/credential_access_microsoft_365_brute_force_user_account_attempt.toml, rules/integrations/o365/credential_access_microsoft_365_potential_password_spraying_attack.toml
*Issue link(s)*: 
The following changes have been made as a result of community slack [thread](https://elasticstack.slack.com/archives/C016E72DWDS/p1725544493561649).
* Stage 1 deprecation `Potential Password Spraying of Microsoft 365 User Accounts`: This rule's query logic overlaps with `Attempts to Brute Force a Microsoft 365 User Account`, however is a threshold rule. With ES|QL we can uses the `STATS` command and `COUNT()` function to accomplish the same anomaly detection.
* Once deprecation prefix is added and rule update is released, we will move the rule to deprecation folder 
* `Attempts to Brute Force a Microsoft 365 User Account` has been tuned to count the number of …
=> [Rule Tuning] M365/Azure Brute-Forcing New Rule and Tuning; Deprecate Similar Rule

rta/linux_execution_kill_from_executable_in_unusual_location.py
=> react_sync_rta_updates_4022

rta/linux_persistence_direct_crontab_modification.py
=> react_sync_rta_updates_4023

rta/linux_execution_reverse_shell_or_listener_via_socat.py
=> react_sync_rta_updates_4032

rta/linux_command_and_control_ip_address_arg_from_hidden_executable.py
=> react_sync_rta_updates_4025

rules/windows/lateral_movement_execution_via_file_shares_sequence.toml
Resolves https://github.com/elastic/detection-rules/issues/3978
Excludes noisy FP Patterns
=> [Rule Tuning] Remote Execution via File Shares

rules/windows/defense_evasion_msiexec_child_proc_netcon.toml, rules/windows/execution_initial_access_foxmail_exploit.toml, rules/windows/execution_powershell_susp_args_via_winscript.toml, rules/windows/execution_windows_cmd_shell_susp_args.toml, rules/windows/execution_windows_powershell_susp_args.toml, rules/windows/privilege_escalation_msi_repair_via_mshelp_link.toml
Updates these rules with a min_stack condition to 8.13 to avoid double bumps in the version lock.
=> [Rule Tuning] min_stack New Rules that use the S1 Integration

rules/windows/defense_evasion_script_via_html_app.toml
*Issue link(s)*: Missed an update in PR https://github.com/elastic/detection-rules/pull/4079
Updates these rules with a min_stack condition to 8.13 to avoid double bumps in the version lock.
=> min_stack New Rules that use the S1 Integration

rules/integrations/aws_bedrock/aws_bedrock_guardrails_multiple_violations_by_single_user.toml
*Issue link(s)*: Currently the Rule fails to execute with the following Error 
- Fix the field name mapping in the ES|QL 
- Modified query fetches result 
=> Fix GenAI Request Model ID Filed

rules/windows/command_and_control_tunnel_vscode.toml
excluding normal noisy pattern: 
- process.name : code-tunnel.exe
- parent.name : code.exe
- process.args : status
=> [Tuning] Attempt to Establish VScode Remote Tunnel

rules/integrations/o365/credential_access_microsoft_365_brute_force_user_account_attempt.toml, rules/integrations/o365/initial_access_microsoft_365_impossible_travel_portal_logins.toml, rules/integrations/o365/initial_access_microsoft_365_portal_login_from_rare_location.toml
* https://github.com/elastic/detection-rules/issues/4103
* Ignore `Not Available` in Microsoft 365 login rules for impossible activity and brute forcing
* Included user only types from Entra ID regarding logins to ignore backend services
Testing requires access to the data, however, below is a screenshot of matches from previous emulation. Note that both rules for impossible travel or rare logins are new terms and thresholds, therefore not replicable via Discover to show reduced volume.
=> [Rule Tuning] Ignore "Not Available" in `o365.audit.UserId` for Microsoft 365 Rules

rules/linux/command_and_control_cupsd_foomatic_rip_netcon.toml, rules/linux/execution_cupsd_foomatic_rip_file_creation.toml, rules/linux/execution_cupsd_foomatic_rip_lp_user_execution.toml, rules/linux/execution_cupsd_foomatic_rip_shell_execution.toml, rules/linux/execution_cupsd_foomatic_rip_suspicious_child_execution.toml
Updated references to contain our newest research release.
=> [Tuning] Updated references

rta/linux_command_and_control_telegram_api_request.py
=> react_sync_rta_updates_4096

rta/linux_defense_evasion_process_injection_via_dd.py
=> react_sync_rta_updates_4105

rta/linux_defense_evasion_hex_payload_execution.py
=> react_sync_rta_updates_4102

rta/linux_persistence_suspicious_echo_execution.py
=> react_sync_rta_updates_4099

rta/linux_defense_evasion_base64_xxd_decode_arg_evasion.py
=> react_sync_rta_updates_4098

rules/integrations/okta/initial_access_successful_application_sso_from_unknown_client_device.toml
Added a rule that detects successful single sign-on (SSO) events to Okta applications from an unrecognized or "unknown" client device, as identified by the user-agent string. This activity may be indicative of exploitation of a vulnerability in Okta's Classic Engine, which could allow an attacker to bypass application-specific sign-on policies, such as device or network restrictions. The vulnerability potentially enables unauthorized access to applications using only valid, stolen credentials, without requiring additional authentication factors.
Ref: https://trust.okta.com/security-advisories/okta-classic-application-sign-on-policy-bypass-2024/
During investigation I noticed that registered client apps whom …
=> [New Rule] `Successful Application SSO from Rare Unknown Client Device`

detection_rules/rule.py, hunting/README.md, rules/cross-platform/execution_potential_widespread_malware_infection.toml, rules/integrations/aws/discovery_ec2_multi_region_describe_instances.toml, rules/integrations/aws/discovery_servicequotas_multi_region_service_quota_requests.toml, rules/integrations/aws/impact_aws_s3_bucket_enumeration_or_brute_force.toml, rules/integrations/aws/impact_s3_bucket_object_uploaded_with_ransom_extension.toml, rules/integrations/aws/impact_s3_object_encryption_with_external_key.toml, rules/integrations/aws/initial_access_signin_console_login_no_mfa.toml, rules/integrations/aws/persistence_iam_user_created_access_keys_for_another_user.toml, rules/integrations/aws/privilege_escalation_iam_administratoraccess_policy_attached_to_group.toml, rules/integrations/aws/privilege_escalation_iam_administratoraccess_policy_attached_to_role.toml, rules/integrations/aws/privilege_escalation_iam_administratoraccess_policy_attached_to_user.toml, rules/integrations/aws_bedrock/aws_bedrock_guardrails_multiple_violations_by_single_user.toml, rules/integrations/aws_bedrock/aws_bedrock_guardrails_multiple_violations_in_single_request.toml, rules/integrations/aws_bedrock/aws_bedrock_high_confidence_misconduct_blocks_detected.toml, rules/integrations/aws_bedrock/aws_bedrock_high_resource_consumption_detection.toml, rules/integrations/aws_bedrock/aws_bedrock_multiple_attempts_to_use_denied_models_by_user.toml, rules/integrations/aws_bedrock/aws_bedrock_multiple_validation_exception_errors_by_single_user.toml, rules/integrations/azure/credential_access_entra_signin_brute_force_microsoft_365.toml, rules/integrations/azure/credential_access_entra_signin_brute_force_microsoft_365_repeat_source.toml, rules/integrations/o365/credential_access_microsoft_365_brute_force_user_account_attempt.toml, rules/integrations/okta/credential_access_multiple_device_token_hashes_for_single_okta_session.toml, rules/integrations/okta/credential_access_okta_authentication_for_multiple_users_from_single_source.toml, rules/integrations/okta/credential_access_okta_authentication_for_multiple_users_with_the_same_device_token_hash.toml, rules/integrations/okta/credential_access_okta_multiple_device_token_hashes_for_single_user.toml, rules/integrations/okta/initial_access_okta_user_sessions_started_from_different_geolocations.toml
Adds `keep` ES|QL command to all ES|QL based rules. Add's validation for this as well to enforce it from the ESQLRuleData schema.
Since the validation is in `ESQLRuleData`, running `python -m dev build-release` will load all rules and validate them via their respective data schema.
=> [Rule Tuning] Add KEEP Command to all ES|QL Rules

rules/windows/credential_access_imageload_azureadconnectauthsvc.toml
converted an existing ER diag rule to SIEM rule to also answer a detection request in our community slack channel https://elasticstack.slack.com/archives/C016E72DWDS/p1728897639096869 
added https://medium.com/@breakingmhet/detect-azure-pass-through-authentication-abuse-azure-hybrid-environments-ed4274784252 also to the references.
=> [New] Untrusted DLL Loaded by Azure AD Sync Service

rules/windows/privilege_escalation_gpo_schtask_service_creation.toml
https://elasticstack.slack.com/archives/C016E72DWDS/p1728899561860219
excluding `event.action : "open"`
=> [Tuning] Creation or Modification of a new GPO Scheduled Task or Service

rules/linux/command_and_control_linux_chisel_client_activity.toml, rules/linux/command_and_control_linux_kworker_netcon.toml, rules/linux/command_and_control_suspicious_network_activity_from_unknown_executable.toml, rules/linux/credential_access_potential_linux_local_account_bruteforce.toml, rules/linux/defense_evasion_binary_copied_to_suspicious_directory.toml, rules/linux/defense_evasion_chattr_immutable_file.toml, rules/linux/defense_evasion_dynamic_linker_file_creation.toml, rules/linux/defense_evasion_file_mod_writable_dir.toml, rules/linux/defense_evasion_hidden_file_dir_tmp.toml
=> [Rule Tuning] Q2 Linux DR Tuning - Part 1

rules/linux/defense_evasion_kernel_module_removal.toml, rules/linux/defense_evasion_mount_execution.toml, rules/linux/defense_evasion_root_certificate_installation.toml, rules/linux/defense_evasion_sus_utility_executed_via_tmux_or_screen.toml, rules/linux/discovery_esxi_software_via_find.toml, rules/linux/discovery_esxi_software_via_grep.toml, rules/linux/discovery_kernel_module_enumeration.toml, rules/linux/discovery_pspy_process_monitoring_detected.toml, rules/linux/discovery_sudo_allowed_command_enumeration.toml, rules/linux/discovery_suspicious_which_command_execution.toml
=> [Rule Tuning] Q2 Linux DR Tuning - Part 2

rules/linux/execution_abnormal_process_id_file_created.toml, rules/linux/execution_cupsd_foomatic_rip_lp_user_execution.toml, rules/linux/execution_cupsd_foomatic_rip_shell_execution.toml, rules/linux/execution_cupsd_foomatic_rip_suspicious_child_execution.toml, rules/linux/execution_curl_cve_2023_38545_heap_overflow.toml, rules/linux/execution_file_execution_followed_by_deletion.toml, rules/linux/execution_netcon_from_rwx_mem_region_binary.toml, rules/linux/execution_network_event_post_compilation.toml, rules/linux/execution_remote_code_execution_via_postgresql.toml, rules/linux/execution_shell_openssl_client_or_server.toml, rules/linux/execution_suspicious_executable_running_system_commands.toml
=> [Rule Tuning] Q2 Linux DR Tuning - Part 3

rules/linux/privilege_escalation_dac_permissions.toml, rules/linux/privilege_escalation_load_and_unload_of_kernel_via_kexec.toml, rules/linux/privilege_escalation_potential_suid_sgid_exploitation.toml, rules/linux/privilege_escalation_shadow_file_read.toml, rules/linux/privilege_escalation_suspicious_uid_guid_elevation.toml, rules/linux/privilege_escalation_uid_elevation_from_unknown_executable.toml
=> [Rule Tuning] Q2 Linux DR Tuning - Part 6

rta/linux_defense_evasion_process_masquerading_via_exec.py
=> react_sync_rta_updates_4175

rta/linux_defense_evasion_proxy_execution_via_ld_so.py
=> react_sync_rta_updates_4179

rta/linux_defense_evasion_proxy_execution_via_pidstat.py
=> react_sync_rta_updates_4180

rta/linux_defense_evasion_proxy_execution_via_split.py
=> react_sync_rta_updates_4182

rta/linux_command_and_control_ip_address_arg_from_hidden_executable.py, rta/linux_defense_evasion_proxy_execution_via_sysctl.py
=> react_sync_rta_updates_4183

rta/linux_defense_evasion_shebang_decoded_via_builtin_utility.py
=> react_sync_rta_updates_4185

rta/linux_execution_bind_shell_via_nc_traditional.py
=> react_sync_rta_updates_4186

rta/linux_defense_evasion_proxy_execution_via_sed.py
=> react_sync_rta_updates_4181

rta/linux_execution_bind_shell_via_node.py
=> react_sync_rta_updates_4187

rta/linux_execution_bind_shell_via_socket.py
=> react_sync_rta_updates_4188

rta/linux_execution_gsocket_activity.py
=> react_sync_rta_updates_4189

rta/linux_impact_enable_write_access_to_msr.py
=> react_sync_rta_updates_4192

rta/linux_persistence_webserver_curl_wget_download_ip_args.py
=> react_sync_rta_updates_4207

rta/linux_persistence_webserver_curl_wget_piped_to_interpreter.py
=> react_sync_rta_updates_4208

rta/linux_defense_evasion_process_masquerading_via_exec.py, rta/linux_persistence_webserver_curl_wget_suspicious_redirect.py
=> react_sync_rta_updates_4209

rta/linux_defense_evasion_process_masquerading_via_exec.py, rta/linux_defense_evasion_proxy_execution_via_php.py
=> react_sync_rta_updates_4212

rta/linux_defense_evasion_sysctl_kernel_feature_activity.py
=> react_sync_rta_updates_4224

rta/linux_defense_evasion_lolbin_so_load.py
=> react_sync_rta_updates_4221

rta/linux_command_and_control_curl_wget_hidden_directory_output.py
=> react_sync_rta_updates_4216

rta/linux_command_and_control_cupsd_foomatic_rip_netcon.py
=> react_sync_rta_updates_4215

rules/integrations/aws_bedrock/aws_bedrock_high_confidence_misconduct_blocks_detected.toml
*Issue link(s)*: Identified while testing https://github.com/elastic/integrations/issues/11468
Fileds such as gen_ai.compliance.violation_code ,  gen_ai.policy.confidence can be multivalued where the mapping looks like 
- Use MV_EXPAND on multivalued columns to match the criteria 
- Modified Query  fetching the result
=> Tune Bedrock rule to accept multivalued column

rta/linux_execution_cupsd_foomatic_rip_shell_execution.py
=> react_sync_rta_updates_4226

rta/linux_execution_cupsd_foomatic_rip_suspicious_child_execution.py
=> react_sync_rta_updates_4228

rta/linux_execution_linux_powershell_outbound_network_connection.py
=> react_sync_rta_updates_4229

rta/linux_execution_renice_ulimit.py
=> react_sync_rta_updates_4230

rta/linux_impact_potential_mining_pool_detection.py
=> react_sync_rta_updates_4232

rules/linux/execution_potential_hack_tool_executed.toml
Tuning the following rule to be case insensitive.
=> [Rule Tuning] Potential Linux Hack Tool Launched

rta/linux_command_and_control_cupsd_foomatic_rip_netcon.py, rta/linux_command_and_control_curl_wget_hidden_directory_output.py, rta/linux_defense_evasion_lolbin_so_load.py, rta/linux_defense_evasion_process_masquerading_via_exec.py, rta/linux_defense_evasion_proxy_execution_via_crash.py, rta/linux_defense_evasion_proxy_execution_via_ld_so.py, rta/linux_defense_evasion_proxy_execution_via_php.py, rta/linux_defense_evasion_proxy_execution_via_pidstat.py, rta/linux_defense_evasion_proxy_execution_via_sed.py, rta/linux_defense_evasion_proxy_execution_via_split.py, rta/linux_defense_evasion_proxy_execution_via_sysctl.py, rta/linux_defense_evasion_proxy_execution_via_tcpdump.py, rta/linux_defense_evasion_shebang_decoded_via_builtin_utility.py, rta/linux_defense_evasion_sysctl_kernel_feature_activity.py, rta/linux_execution_bind_shell_via_nc_traditional.py, rta/linux_execution_bind_shell_via_node.py, rta/linux_execution_bind_shell_via_socket.py, rta/linux_execution_cupsd_foomatic_rip_shell_execution.py, rta/linux_execution_cupsd_foomatic_rip_suspicious_child_execution.py, rta/linux_execution_gsocket_activity.py, rta/linux_execution_linux_powershell_outbound_network_connection.py, rta/linux_execution_reverse_or_bind_shell_via_utility.py, rta/linux_impact_enable_write_access_to_msr.py, rta/linux_persistence_webserver_curl_wget_download_ip_args.py, rta/linux_persistence_webserver_curl_wget_piped_to_interpreter.py, rta/linux_persistence_webserver_curl_wget_suspicious_redirect.py
=> react_sync_rta_updates_4250

lib/kibana/kibana/__init__.py, lib/kibana/kibana/connector.py, lib/kibana/pyproject.toml
https://github.com/elastic/detection-rules/issues/4207
When using the Kibana bulk actions API for DaC features with non-default spaces, the API call needs to use the identifier to correctly specify the correct space to push/pull rules from. However, the check to determine whether or not a space exists is done with the name rather than the identifier. 
This PR updates the Kibana space id to be what is checked when determining if the space exists.
See the [Kibana API Docs](https://www.elastic.co/guide/en/kibana/8.15/spaces-api-get-all.html) for an example return of what this code is parsing to see that both `id` and `name` are provided. 
1. Setup a DAC environement including a test rule.
2. Trying exporting rules using the Kibana export-rules CLI command for a Kibana space …
=> [FR] [DAC] Add support for Kibana spaces with names that do not match identifiers

.github/release-drafter.yml, .github/workflows/version-code-and-release.yml, docs/versioning.md
- Testing the workflow, making small tweaks to the release process
- Skipping manual bump of pyproject.toml
=> [FR] Update release-drafter.yml

.github/release-drafter.yml, pyproject.toml
- Testing the version parser prefix.
=> [Testing] Update release-drafter.yml

.github/workflows/version-code-and-release.yml, pyproject.toml
- Need to [fetch](https://github.com/elastic/detection-rules/actions/runs/11728232831/job/32671147526) context
- GitHub action should complete: Testing with this PR
=> [FR] Fetch history for versioning workflow

.github/workflows/version-code-and-release.yml, pyproject.toml
- Resolve incorrect [tag](https://github.com/elastic/detection-rules/actions/runs/11728598627/job/32672390419#step:4:11)
- Testing via CI
=> [FR] Reset package version and push tag via ci

rules/integrations/aws/privilege_escalation_sts_assume_root_from_rare_user_and_member_account.toml
Adds detection coverage for AWS' new `AssumeRoot` API call. An investigation guide has also been added for this rule. 
_Identifies when the STS `AssumeRoot` action is performed by a rare user in AWS. The AssumeRoot action allows users to assume the root member account role, granting elevated but specific permissions based on the task policy specified. Adversaries whom may have compromised user credentials, such as access and secret keys, can use this technique to escalate privileges and gain unauthorized access to AWS resources. This is a [New Terms](https://www.elastic.co/guide/en/security/current/rules-ui-create.html#create-new-terms-rule) rule that identifies
when the STS `AssumeRoot` action is performed by a user …
=> [New Rule] Adding Coverage for `AWS STS AssumeRoot by Rare User and Member Account`

rules/integrations/github/impact_github_repository_deleted.toml
*Issue link(s)*: Part of https://github.com/elastic/detection-rules/issues/4276
- Add missing event.dataset filed for Github rule
- Unit test to Pass 
- Rule was built and json file was imported to check the Rule rendering 
=> Add event dataset for missing rule in Github integration

rules/integrations/aws/persistence_iam_user_created_access_keys_for_another_user.toml
* https://github.com/elastic/kibana/issues/203502#issuecomment-2530715670
Removes trailing comma from `KEEP` command in AWS rule. Identified via https://elastic.slack.com/archives/C02HA9E8221/p1733783804664949
=> [Rule Tuning] Remove Trailing Comma in `AWS IAM User Created Access Keys For Another User`

rules/linux/privilege_escalation_potential_suid_sgid_exploitation.toml, rules/linux/privilege_escalation_sudo_token_via_process_injection.toml
*Issue link(s)*: Identified double bump https://github.com/elastic/detection-rules/pull/4293
- For rules using endpoint fields process.group.id, this filed is made mandatory in 8.16 onwards
- Hence min-stacking the rule to 8.16 
=> Minstack endpoint rules with process.group.id fields

docs/versioning.md, pyproject.toml
*Issue link(s)*: As part of Release https://github.com/elastic/ia-trade-team/issues/513
- Update versions supported. 
- Unit test to pass
=> Update versioning support for 8.17

rules/integrations/azure/credential_access_azure_entra_totp_brute_force_attempts.toml
* https://github.com/elastic/ia-trade-team/issues/519
Adding detection coverage for TOTP brute-force attempts in Microsoft Azure.
To simulate, I wrote a small python script leveraging selenium to mimic user sign-in to Microsoft for a user `authquake` whose conditional authentication method was Microsoft Authenticator, which allows TOTP codes to be attempted. While this does not reflect the method used in the blog by Oasis security, it does produce failed TOTP for a user with that conditional MFA method enabled, just not as fast and uses the auth workflow instead of specific URL endpoints.
ref: https://www.oasis.security/resources/blog/oasis-security-research-team-discovers-microsoft-azure-mfa-bypass …
=> [New Rule] Adding Coverage for `Azure Entra MFA TOTP Brute Force Attempts`

.github/workflows/add-guidelines.yml, .github/workflows/attack-coverage-update.yml, .github/workflows/backport.yml, .github/workflows/branch-status-checks.yml, .github/workflows/community.yml, .github/workflows/kibana-mitre-update.yml, .github/workflows/manual-backport.yml, .github/workflows/pythonpackage.yml, .github/workflows/release-docs.yml, .github/workflows/release-fleet.yml, README.md, detection_rules/devtools.py, pyproject.toml
* https://github.com/elastic/ia-trade-team/issues/438
Changes GitHub secret variables to match the appropriate naming.
=> [Maintenance] Repository Config Update

.github/workflows/pythonpackage.yml
=> [Maintenance] Updated Navigator Gist Token pt 2

.github/workflows/manual-backport.yml, .github/workflows/release-docs.yml
=> [Maintenance] Repository Config Update pt 3

.github/workflows/add-guidelines.yml, .github/workflows/backport.yml, .github/workflows/get-target-branches.yml, .github/workflows/lock-versions.yml, .github/workflows/manual-backport.yml, .github/workflows/release-docs.yml, .github/workflows/release-fleet.yml, pyproject.toml
=> [Maintenance] repository config update pt 4

.github/workflows/backport.yml, .github/workflows/manual-backport.yml
Updated token permissions per scope of backporting workflows. Replaced `GITHUB_TOKEN` with updated token.
=> [Maintenance] repository config update pt 5

.github/workflows/version-code-and-release.yml
Added an ignore filter for TOML files in hunting/ directory.
Example: https://github.com/elastic/detection-rules/pull/4351/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711
=> [Maintenance] Remove hunting TOML files from repo version checks

rules_building_block/defense_evasion_posh_defender_tampering.toml, rules_building_block/discovery_posh_generic.toml, rules_building_block/lateral_movement_posh_winrm_activity.toml
Excludes noisy patterns from PowerShell BBRs.
=> [Rule Tuning] Posh BBRs

rules/windows/defense_evasion_communication_apps_suspicious_child_process.toml, rules_building_block/defense_evasion_outlook_suspicious_child.toml
Breaks the Outlook part of the logic into a new BBR, as it is the only noisy one, "promotes" the old BBR to a normal DR.
=> [Rule Tuning] Suspicious Communication App Child Process

rules/integrations/aws/defense_evasion_sqs_purge_queue.toml, rules/integrations/aws/defense_evastion_sqs_purge_queue.toml
* https://github.com/elastic/ia-trade-team/issues/515
Added detection coverage for AWS SQS queue purging.
SQS queue is a common service used in AWS for various reasons, including the use of storing security monitoring logs where they are retrieved and then ingested (our own integration uses this).
Identifies when an AWS Simple Queue Service (SQS) queue is purged. Adversaries may purge SQS queues to disrupt
operations, delete messages, or impair monitoring and alerting mechanisms. This action can be used to evade detection
and cover tracks by removing evidence of malicious activities.
I chose not to make this a New Terms rule because of the sensitivity of the operation and disruption it could cause. It should always be …
=> [New Rule] Adding Coverage for `AWS SQS Queue Purge`

rules/integrations/aws/lateral_movement_sns_topic_message_publish_by_rare_user.toml
* https://github.com/elastic/ia-trade-team/issues/515
This rule identifies when a message is published to an SNS topic by a user who has rarely or never published messages before. This activity could indicate adversarial actions, such as using SNS topics for phishing campaigns, data exfiltration, or lateral movement within an AWS environment.
This is a [New Terms](https://www.elastic.co/guide/en/security/current/rules-ui-create.html#create-new-terms-rule) rule that only flags when this behavior is observed for the first time on a user in the last 14 days.
* https://github.com/elastic/pwncloud/pull/14
- Have you followed …
=> [New Rule] Adding Coverage for `SNS Topic Message Publish by Rare User`

rules/integrations/fim/persistence_suspicious_file_modifications.toml, rules/linux/persistence_potential_persistence_script_executable_bit_set.toml
Added some paths to Linux persistence rules.
=> [Rule Tuning] Linux Persistence Rules

rules/windows/defense_evasion_amsi_bypass_powershell.toml, rules/windows/defense_evasion_posh_obfuscation.toml
few complementary tuning to add some extra patterns.
=> [Tuning] Powershell Rules

rules/linux/persistence_dbus_service_creation.toml
This rule detects the creation of D-Bus service files on Linux systems. D-Bus is a message bus system that provides a way for applications to talk to one another. D-Bus services are defined in service files that are typically located in default directories. The rule looks for the creation of service files that are not associated with known package managers or system services. Attackers may create malicious D-Bus services to establish persistence or escalate privileges on a system.
0 hits in telemetry last 90d, only TPs in testing stack:
=> [New Rule] D-Bus Service Created

rules/integrations/aws/collection_s3_unauthenticated_bucket_access_by_rare_source.toml, rules/linux/discovery_polkit_version_discovery.toml, rules/linux/execution_executable_stack_execution.toml, rules/linux/execution_unusual_pkexec_execution.toml, rules/linux/persistence_boot_file_copy.toml, rules/linux/persistence_dbus_service_creation.toml, rules/linux/persistence_dbus_unsual_daemon_parent_execution.toml, rules/linux/persistence_dracut_module_creation.toml, rules/linux/persistence_extract_initramfs_via_cpio.toml, rules/linux/persistence_grub_configuration_creation.toml, rules/linux/persistence_grub_makeconfig.toml, rules/linux/persistence_manual_dracut_execution.toml, rules/linux/persistence_network_manager_dispatcher_persistence.toml, rules/linux/persistence_openssl_passwd_hash_generation.toml, rules/linux/persistence_polkit_policy_creation.toml, rules/linux/persistence_systemd_shell_execution.toml, rules/linux/persistence_unpack_initramfs_via_unmkinitramfs.toml, rules/windows/defense_evasion_right_to_left_override.toml
*Issue link(s)*: Follow up to https://github.com/elastic/detection-rules/pull/4358
=> [FR] Add Remaining Guides

rules/linux/credential_access_ssh_backdoor_log.toml
Updating the index pattern list to address issue: https://github.com/elastic/detection-rules/issues/4248.
=> [Rule Tuning] Potential OpenSSH Backdoor Logging Activity

rules/windows/execution_windows_script_from_internet.toml
extended parent list to browsers and compression utilities.
=> [Tuning] Execution of a Downloaded Windows Script

rules/integrations/google_workspace/defense_evasion_google_workspace_new_oauth_login_from_third_party_application.toml, rules/integrations/google_workspace/initial_access_object_copied_to_external_drive_with_app_consent.toml, rules/integrations/okta/initial_access_first_occurrence_user_session_started_via_proxy.toml, rules/integrations/okta/persistence_stolen_credentials_used_to_login_to_okta_account_after_mfa_reset.toml
*Issue link(s)*: Identified while Testing https://github.com/elastic/ia-trade-team/issues/510
- Add newline to Setup information 
- Without this the Rules have badly displayed Setup Headers like below 
- We are not seeing these issues with rules that have proper new lines like [rule_with_space](https://github.com/elastic/detection-rules/blob/main/rules/integrations/google_workspace/collection_google_drive_ownership_transferred_via_google_workspace.toml#L67)
- This also fails schema validation when prebuilt rules can be exported in 9.0.0 versions. 
- Unit test should pass 
=> Fix spacing in Setup information

detection_rules/rule.py, pyproject.toml
*Issue link(s)*: Identified while testing https://github.com/elastic/ia-trade-team/issues/510
- Fix typo "minuets" --> "minutes" in error message rendered to user.
- Ran the sample command to reflect new error message
```console
❯ python -m detection_rules kibana export-rules -r "6cf17149-a8e3-44ec-9ec9-fdc8535547a1" -d /Users/shashankks/elastic_workspace/detection-rules/custom_rules/rules -sv 
Loaded config file: /Users/shashankks/elastic_workspace/detection-rules/.detection-rules-cfg.json
Error loading rule in /Users/shashankks/elastic_workspace/detection-rules/custom_rules/rules/defense_evasi …
```
=> Fix typo in error message

rules/linux/command_and_control_frequent_egress_netcon_from_sus_executable.toml
This rule detects a high number of egress network connections from an unusual executable on a Linux system. This could indicate a command and control (C2) communication attempt, a brute force attack via a malware infection or other malicious activity.
3 TPs last 30d from DOTA3 malware.
This query does not return any hits in telemetry with the added exclusions.
=> [New Rule] High Number of Egress Network Connections from Unusual Executable

rules/linux/defense_evasion_base64_decoding_activity.toml
This rule leverages ES|QL to detect unusual base64 encoding/decoding activity on Linux systems. Attackers may use base64 encoding/decoding to obfuscate data, such as command and control traffic or payloads, to evade detection by host- or network-based security controls. ES|QL rules have limited fields available in its alert documents. Make sure to review the original documents to aid in the investigation of this alert.
This rule will close the gaps based on exclusions in ER. This activity is seen in many malware samples.
=> [New Rule] Unusual Base64 Encoding/Decoding Activity

rules/linux/exfiltration_unusual_file_transfer_utility_launched.toml
This rule leverages ES|QL to detect the execution of unusual file transfer utilities on Linux systems. Attackers may use these utilities to exfiltrate data from a compromised system. ES|QL rules have limited fields available in its alert documents. Make sure to review the original documents to aid in the investigation of this alert.
This behavior is seen in the DOTA3 malware. Through ES|QL this will reduce the noise for benign file transfer utility execution.
=> [New Rule] Unusual File Transfer Utility Launched

rules/_deprecated/initial_access_cross_site_scripting.toml
*Issue link(s)*:  Rule was soaked a BBR with no feedback data to tune, the rule now has compatibility issues with lates integration and stack versions, as seen in [PR](https://github.com/elastic/detection-rules/pull/4502). With no usage there is additional overhead to maintian this rule, hence deprecating this 
- Unit test should pass 
=> Deprecate an APM BBR rule

README.md, pyproject.toml
Related to: https://github.com/elastic/detection-rules/issues/4517
This PR update the primary README  with additional references, specifically to support information, to our `docs-dev/detections-as-code.md`. 
If unit tests pass this PR is g2g. 
=> [FR] [DaC] Update Readme with DaC Support References

hunting/azure/docs/entra_authentication_attempts_behind_rare_user_agents.md, hunting/azure/docs/entra_excessive_non_interactive_sfa_sign_ins_across_users.md, hunting/azure/docs/entra_unusual_client_app_auth_request_on_behalf_of_user.md, hunting/azure/queries/entra_authentication_attempts_behind_rare_user_agents.toml, hunting/azure/queries/entra_excessive_non_interactive_sfa_sign_ins_across_users.toml, hunting/azure/queries/entra_unusual_client_app_auth_request_on_behalf_of_user.toml, hunting/index.md, hunting/index.yml
* https://github.com/elastic/ia-trade-team/issues/566
Adds new hunting queries for anomalies in Entra sign-in activity. This behavior is attributed to a recent botnet targeting M365 environments. The hunting queries focus on non-interactive single-factor authentication, unusual user agents like `FastHTTP`, and unusual client apps used in authentication.
* Please see the meta for additional details on threat modeling, data sources, and emulation.
=> [New Hunt] Adding Hunting Queries for Azure Entra Sign-In Anomalies

.github/workflows/kibana-mitre-update.yml, pyproject.toml
Temporarily disable workflow to change to a different dif calculation.
=> Temporaily Disable Changed FIles Workflow

rules/integrations/o365/initial_access_microsoft_365_abnormal_clientappid.toml
N/A – Minor rule tuning based on Microsoft platform changes
Added the new Outlook for Web (OWA) AppID 9199bf20-a13f-4107-85dc-02114787ef48 to the allowlist in the rule initial_access_microsoft_365_abnormal_clientappid.
Microsoft is migrating OWA to a new authentication model (SPA using MSAL), and the existing AppID is being replaced. This update prevents false positives as the new AppID begins appearing in logs.
Reference: 
https://m365admin.handsontek.net/outlook-outlook-for-web-new-application-id/
=> [Rule Tuning] Added OWA (outlook for web) new AppID

docs/docset.yml
Remove diagnostic hint
*Issue link(s)*: N/A
Related to https://github.com/elastic/detection-rules/pull/4507
Cleaning up the docs builder.
Future PRs should not longer show this warning:
=> [maintenance] Update docset.yml

rules/windows/persistence_suspicious_scheduled_task_runtime.toml
Resolves SDH 565
Excludes a FP pattern observed by the customer.
=> [Rule Tuning] Suspicious Execution via Scheduled Task

.github/ISSUE_TEMPLATE/new_meta.yaml
*Issue link(s)*: https://github.com/elastic/ia-trade-team/issues/558
- Remove the tasklist from ia-trade-team issue template per the guide lines of - https://github.blog/changelog/2025-02-18-github-issues-projects-february-18th-update/ 
- Unit test should pass 
=> Remove Task List reference

detection_rules/etc/non-ecs-schema.json, pyproject.toml, rules/integrations/azure/initial_access_entra_susp_visual_code_signin.toml
https://www.volexity.com/blog/2025/04/22/phishing-for-codes-russian-threat-actors-target-microsoft-365-oauth-workflows/
=> [New] Suspicious Azure Sign-in via Visual Studio Code

hunting/index.md, hunting/index.yml, hunting/macos/docs/command_and_control_suspicious_executable_file_creation_via_python.md, hunting/macos/docs/credential_access_potential_python_stealer.md, hunting/macos/docs/defense_evasion_python_library_load_and_delete.md, hunting/macos/docs/defense_evasion_self_deleted_python_script_accessing_sensitive_files.md, hunting/macos/docs/defense_evasion_self_deleting_python_script.md, hunting/macos/docs/execution_python_script_drop_and_execute.md, hunting/macos/docs/execution_suspicious_executable_file_modification_via_docker.md, hunting/macos/docs/execution_suspicious_file_access_via_docker.md, hunting/macos/docs/execution_suspicious_python_app_execution_via_streamlit.md, hunting/macos/docs/execution_unsigned_or_untrusted_binary_execution_via_python.md, hunting/macos/docs/execution_unsigned_or_untrusted_binary_fork_via_python.md, hunting/macos/docs/execution_unusual_library_load_via_python.md, hunting/macos/queries/command_and_control_suspicious_executable_file_creation_via_python.toml, hunting/macos/queries/credential_access_potential_python_stealer.toml, hunting/macos/queries/defense_evasion_python_library_load_and_delete.toml, hunting/macos/queries/defense_evasion_self_deleted_python_script_accessing_sensitive_files.toml, hunting/macos/queries/defense_evasion_self_deleting_python_script.toml, hunting/macos/queries/execution_python_script_drop_and_execute.toml, hunting/macos/queries/execution_suspicious_executable_file_modification_via_docker.toml, hunting/macos/queries/execution_suspicious_file_access_via_docker.toml, hunting/macos/queries/execution_suspicious_python_app_execution_via_streamlit.toml, hunting/macos/queries/execution_unsigned_or_untrusted_binary_execution_via_python.toml, hunting/macos/queries/execution_unsigned_or_untrusted_binary_fork_via_python.toml, hunting/macos/queries/execution_unusual_library_load_via_python.toml, pyproject.toml
* https://github.com/elastic/ia-trade-team/issues/585?reload=1
Adds hunting queries for DPRK ByBit macOS endpoint attack in Feb 2025.
=> [New Hunt] New Hunting Queries for DPRK ByBit 

pyproject.toml
=> fix: missed version bump

detection_rules/etc/version.lock.json, pyproject.toml
*Issue link(s)*: As part of the release https://github.com/elastic/ia-trade-team/issues/582
- Context of Changes present in https://github.com/elastic/ia-trade-team/issues/582#issuecomment-2830466854
- Unit Test to Pass 
=> Lock versions for releases: 8.14,8.15,8.16,8.17,8.18,9.0

detection_rules/etc/non-ecs-schema.json, pyproject.toml, rules/integrations/azure/initial_access_entra_protection_multi_azure_identity_protection_alerts.toml, rules/integrations/o365/credential_access_antra_id_device_reg_via_oauth_redirection.toml
https://github.com/elastic/ia-trade-team/issues/590
=> [New] Microsoft 365 OAuth Redirect to Device Registration for User 

rules/integrations/azure/defense_evasion_azure_service_principal_addition.toml, rules/integrations/azure/persistence_entra_service_principal_created.toml
* https://github.com/elastic/sdh-protections/issues/573
Excludes service principals added by MSFT entity, rather than user principals or other service principals. Updates some verbiage and tags in the rule as well. Please see SDH for details.
=> [Rule Tuning] Excluding `Microsoft Entra ID Service Principal Addition` Invoked by MSFT Identity

rules/windows/discovery_command_system_account.toml
Exclude top noisy patterns.
https://github.com/elastic/detection-rules/issues/4733
=> [Tuning] Account Discovery Command via SYSTEM Account

rules/integrations/o365/persistence_microsoft_365_global_administrator_role_assign.toml
* https://github.com/elastic/detection-rules/issues/2404
Tunes the `Microsoft 365 Global Administrator Role Assigned`, based on investigation and feedback from related issue.
* Query can be tested in alert telemetry stack or TRADE serverless stack
* Does dramatically reduce noise from global alerts since we exclude system and service principals/accounts.
=> [Rule Tuning] Tuning Microsoft 365 Global Administrator Role Assigned

rules/windows/execution_downloaded_url_file.toml
Remove the explorer.exe exclusion as it will miss files extracted via explorer.exe :
=> [Tuning] Downloaded URL Files

rules/linux/lateral_movement_kubeconfig_file_activity.toml
The kubeconfig file is a critical component in Kubernetes environments, containing configuration details for accessing and managing Kubernetes clusters. Attackers may attempt to get access to, create or modify kubeconfig files to gain unauthorized initial access to Kubernetes clusters or move laterally within the cluster.
=> [New Rule] Kubeconfig File Creation or Modification

detection_rules/etc/non-ecs-schema.json, pyproject.toml, rules/windows/credential_access_kerberos_coerce.toml, rules/windows/credential_access_kerberos_coerce_dns.toml
Adds coverage for Kerberos Coercion techniques used in relay attacks.
=> [New Rules] SPN Spoofing / Coercion Rules

rules/integrations/azure/initial_access_entra_id_unusual_ropc_login_attempt.toml
* https://github.com/elastic/detection-rules/issues/4864
Adds a detection rule for ROPC-based logins by a user principal in Entra ID. This is a New Terms rule to capture this authentication method being an anomaly for the user. ROPC is a legacy auth method that is still valid in some tenants but not recommended by Microsoft. It is often used by adversary tooling for enumeration and password spraying as only credentials need to be supplied during the auth flow.
* Query can be used in the TRADE stack.
=> [New Rule] Unusual ROPC Login Attempt by User Principal

detection_rules/integrations.py, pyproject.toml
*Issue link(s)*: https://github.com/elastic/detection-rules/issues/4884
- Fix variable usage `final_integration_schemas` to identify available versions in schema and skip them 
- saved_integration_schemas changes in PR https://github.com/elastic/detection-rules/pull/3119/files introduced this bug unintentionally and was always redownloading each schema version even though present previously. 
- Details of Time and Processing can be found [here](https://github.com/elastic/detection-rules/issues/4884#issuecomment-3073154775)
- This fix will bring back the original functionality of schema building without overwrite where only new manifests versions are built. 
- Unit Test to Pass 
<details><summary>Build Schema with existing Manifest (Takes 2 seconds as opposed to 17 minutes …
=> Fix variable usage impacting schema build performance

rules/cross-platform/initial_access_azure_o365_with_network_alert.toml
* https://github.com/elastic/detection-rules/issues/4940
Adjusts the datastreams in the ESQL query to tighten the scope. Please see issue for further detail.
=> [Rule Tuning] Microsoft Azure or Mail Sign-in from a Suspicious Source

detection_rules/cli_utils.py, pyproject.toml
Closes #4947 
Closes #4933
Added to the rule prompt logic to add existing mitre attack information from the rule export. 
See the issue for testing purposes. 
<details><summary>Testing Details</summary>
<p>
```bash
python -m detection_rul
es import-rules-to-repo -s /Users/stryker/workspace/Elastic/detection-rules/mikas_folder/rules --required-only /Users/stryker/Downloads/rules_export-16.ndjson 
[+] Building rule for /Users/stryker/workspace/Elastic/detection-rules/mikas_folder/rules/persistence_via_cron.toml
1 results exported
1 rules converted
0 exceptions exported
0 actions connectors …
```
=> [FR] [DAC] Add existing mitre threat information on import

rules/promotions/elastic_security_external_alerts.toml
*Issue link(s)*: 
- Continuation of https://github.com/elastic/detection-rules/pull/4903
Update the external alert to promote the rule override.
=> [Rule Tuning] Elastic Security External Alerts

rules/windows/defense_evasion_network_connection_from_windows_binary.toml
limited the network events to DNS queries and reduced maxspan to 1m for better rule performance.
https://elasticstack.slack.com/archives/C016E72DWDS/p1756714626504359
=> [Tuning] Unusual Network Activity from a Windows System Binary

rules/promotions/crowdstrike_external_alerts.toml
*Issue link(s)*: Reported Internally 
- Keep the tag consistent to "Data Source: Crowdstrike"
- Unit test to pass 
=> Tune a Tag discrepency in rule

rules/integrations/aws/privilege_escalation_iam_customer_managed_policy_attached_to_role.toml, rules/integrations/aws/privilege_escalation_iam_update_assume_role_policy.toml, rules/integrations/azure/credential_access_entra_id_brute_force_activity.toml
*Issue link(s)*: Related to https://github.com/elastic/detection-rules/pull/5079
- Fix updated_date and correct it to today 
- Unit test to pass 
=> Fix updated_date for tunings as part of #5079

pyproject.toml, tests/test_all_rules.py
*Issue link(s)*: Failures seen on [Ruff checks](https://github.com/elastic/detection-rules/actions/runs/17620479399/job/50064691548) on main and protected branches 
- Fix Ruff failures 
- Code checks to pass 
=> Fix Ruff failures

rules/windows/initial_access_execution_from_inetcache.toml, rules/windows/lateral_movement_evasion_rdp_shadowing.toml, rules/windows/lateral_movement_unusual_dns_service_children.toml, rules/windows/persistence_evasion_registry_startup_shell_folder_modified.toml, rules/windows/persistence_priv_escalation_via_accessibility_features.toml
Part of https://github.com/elastic/ia-trade-team/issues/678
Logic adjusts to exclude FPs.
=> [Rule Tuning] Windows High Severity - 4

rules/windows/execution_suspicious_powershell_imgload.toml
=> [Rule Tuning] Suspicious PowerShell Engine ImageLoad

rules/linux/persistence_nodejs_pre_or_post_install_script_execution.toml
This rule detects the execution of Node.js pre or post-install scripts. These scripts are executed by the Node.js package manager (npm) during the installation of packages. Adversaries may abuse this technique to execute arbitrary commands on the system and establish persistence. This activity was observed in the wild as part of the Shai-Hulud worm.
- [Navigating the Shai-Hulud Worm: Elastic's proactive defense against npm supply chain compromise](https://www.elastic.co/blog/shai-hulud-worm-npm-supply-chain-compromise)
=> [New Rule] Node.js Pre or Post-Install Script Execution

rules/linux/privilege_escalation_cve_2025_32463_nsswitch_file_creation.toml, rules/linux/privilege_escalation_cve_2025_32463_sudo_chroot_execution.toml
This PR adds two rules for indicators of a potential CVE-2025-32463 exploitation attempt.
Detects suspicious use of sudo's --chroot / -R option consistent with attempts to exploit CVE-2025-32463 (the "sudo chroot" privilege escalation), where an attacker tricks sudo into using attacker-controlled NSS files or libraries to gain root.
Detects suspicious creation of the nsswitch.conf file, outside of the regular /etc/nsswitch.conf path, consistent with attempts to exploit CVE-2025-32463 (the "sudo chroot" privilege escalation), where an attacker tricks sudo into using attacker-controlled NSS files or libraries to gain root.
=> [New Rules] Potential CVE-2025-32463 Exploitation
