elastic/detection-rules

rules/network/command_and_control_sql_server_port_activity_to_the_internet.toml

Closes #3
I believe this is a typo. See default port for MySQL: https://dev.mysql.com/doc/mysql-port-reference/en/mysql-ports-reference-tables.html#:~:text=Port%203306%20is%20the%20default,such%20as%20mysqldump%20and%20mysqlpump.

Update MySQL port to 3306 not 3336

---

rules/linux/defense_evasion_attempt_to_disable_iptables_or_firewall.toml

[Rule tuning] Fix evasion for disable iptables rule

---

rules/okta/okta_attempt_to_modify_or_delete_application_sign_on_policy.toml

Resolves #8 
An adversary may attempt to modify or delete the sign on policy for an Okta application in order to remove or weaken an organization's security controls. Please see #8 for further details and example events that will trigger this rule.

[New Rule] Attempt to Modify or Delete Okta Application Sign On Policy

---

rules/linux/defense_evasion_attempt_to_disable_iptables_or_firewall.toml

Resolves https://github.com/elastic/detection-rules/issues/7
Update this rule to ensure the correct order of precedence for conditions in the query. See https://github.com/elastic/detection-rules/issues/7 for further details and screenshot of query matching intended events.
https://github.com/elastic/detection-rules/blob/46a400857026c1077eefe7120195a983c7b96136/rules/linux/defense_evasion_attempt_to_disable_iptables_or_firewall.toml#L24

[Rule Tuning] Fix logic bug in rule, Attempt to Disable IPTables or Firewall

---

detection_rules/packaging.py

resolves #31 
Converts the notice.txt file to the expected notice.ts format and stages with it rules when building a package with `build-release`
This is the currently generated file:
```js
/* eslint-disable @kbn/eslint/require-license-header */
/* @notice
* Detection Rules
* Copyright 2020 Elasticsearch B.V.
* 
* ---
* This product bundles rules based on https://github.com/BlueTeamLabs/sentinel-attack
* which is available under a "MIT" license. The files based on this license are:
* 
* - defense_evasion_via_filter_manager.toml
* - discovery_process_discovery_via_tasklist_command.toml
* - persistence_priv_escalation_via_accessibility_features.toml
* - persistence_via_application_shimming.toml
* - defense_evasion_execution_via_trusted_developer_utilities.toml
* 
* MIT License
* 
* …
```

Package notice file with release

---

tests/test_all_rules.py

None
Added a unit test to make sure we don't have duplicate file names. Otherwise, we would have collisions when we flatten the directories and build a package before sending to Kibana.
```
FAILED tests/test_all_rules.py::TestValidRules::test_duplicate_file_names - AssertionError: Found duplicated file names {'credential_access_tcpdump_activity.toml': ['rules/aws/credential_access_tcpdump_activity.toml', 'rules/linux/credential_access_tcpdump_activity.toml']}
```

Add test for duplicate file names

---

detection_rules/main.py
detection_rules/misc.py
detection_rules/packaging.py

resolves #37 
Generates Kibana [index.ts](https://github.com/elastic/kibana/blob/master/x-pack/plugins/security_solution/server/lib/detection_engine/rules/prepackaged_rules/index.ts) file at package generation and saves with in rules directory
<details>
<summary>Expand to see Currently generated index.ts file:</summary>
<br>
```js
/*
* Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
* or more contributor license agreements. Licensed under the Elastic License;
* you may not use this file except in compliance with the Elastic License.
*/
// Auto generated file from either:
// - scripts/regen_prepackage_rules_index.sh
// - detection-rules repo using CLI command build-release
// Do not hand edit. Run script/command to regenerate package information instead
import …
```

Package kibana index file with release rules

---

Makefile
detection_rules/main.py

Closes #36
Depends on #37
Wipes the directory in Kibana away and rebuilds with the latest version of the repository. Assumes you've already built the release, and will pull it from the filesystem. I think it's good to keep these decoupled, makes things one step easier. Exit codes should be enough if we want to automate multiple commands in a row.

Add kibana-push command

---

NOTICE.txt
detection_rules/packaging.py

None
We failed lint tests for https://github.com/elastic/kibana/pull/71332. Now the generated `.ts` files should pass the lint unit tests.

Generate linted .ts in package

---

rules/promotions/elastic_endpoint.toml

This adds a static reference of the Global Endpoint Exception List to the `Elastic Endpoint` rule. This ensures that the `Elastic Endpoint` has the ability to edit/add endpoint exceptions.
Reference:
``` ts
"exceptions_list": [
{
"id": "endpoint_list",
"namespace_type": "agnostic",
"type": "endpoint"
}
],
```
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? Y!
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)? Y!

Add Global Endpoint Exception List to Elastic Endpoint rule

---

requirements.txt

Apparently builds are breaking. Not sure why it can't find pyyaml.
Loosed the requirement in requirements.txt

Loosen yaml requirement

---

detection_rules/main.py
detection_rules/rule.py
detection_rules/schema.py

resolves #63 
This adds support for threshold rules in the schema and CLI. These rules are defined as `type = threshold` and have the additional required fields of `field = string_field` and `value = int_greater_than 0`
Support for the CLI is added as a temporary means, but the prompt will need complete refactoring and can be tracked in #64
```console
python -m detection_rules create-rule test/threshold.toml --required-only
Rule type (machine_learning, saved_query, query, threshold): threshold
author (required)  (multi, comma separated): punt-threater
description (required): test threshold …
```

Add support for threshold rules

---

kql/__init__.py
kql/dsl.py
kql/evaluator.py
kql/kql2eql.py
tests/kuery/test_dsl.py

Closes #80
Added a KQL to query DSL converter. I added a few optimizations so that the query DSL is flattened and doesn't produce overly deep trees.
Nothing is hooked up to the existing APIs. To use it, you need to nest the output underneath a `query: {...}` when building a request. Or put it in a different context when doing aggregations, etc.

Add KQL -> DSL conversion

---

rules/promotions/external_alerts.toml

Updates the External Alerts rule index to match default securitySolution:defaultIndex value
``` toml
index = ["apm-*-transaction*", "auditbeat-*", "endgame-*", "filebeat-*", "logs-*", "packetbeat-*", "winlogbeat-*"]
```
Note: extra spaces are from running `toml-lint`
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? Yes!
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)? Yes!

Update External Alerts rule index to match default securitySolution:defaultIndex value

---

detection_rules/schema.py
rules/aws/credential_access_aws_iam_assume_role_brute_force.toml

Found that this failed on PR because the field is not accepted.
https://github.com/elastic/kibana/pull/72613
Made `threshold.field` required and populate it with an empty string instead of having it missing. This is what the API seems to do from the front end as well if a field is not specified.

[Bug] Set threshold.field to empty string instead of null

---

rules/promotions/elastic_endpoint.toml
rules/promotions/external_alerts.toml

This PR updates the `elastic_endpoint` rule to include the `list_id` for the global endpoint exceptions list as so:
```
"exceptions_list": [
{
"id": "endpoint_list",
"list_id": "endpoint_list",
"namespace_type": "agnostic",
"type": "endpoint"
}
],
```
...and removes `endgame: *` from the `external_alerts` rule `index` field.
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? ✅ 
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)? ✅

Add list_id to exceptions_list and remove endgame:* from external alerts rule

---

detection_rules/eswrap.py
detection_rules/misc.py
detection_rules/schemas/__init__.py
kibana/connector.py

Closes #96 
Now that #84 is done, we can connect all the pieces together for `kibana-upload`.
Now, `kibana-upload` can work for 7.8 and 7.8 stacks. If we were to extend support further back, we just need to update schemas/v77.py accordingly.
There are still some other things to figure out for a bigger picture repository <--> Kibana workflow. But for now, this helps with the ad-hoc upload command.
On error message (hard coded 7.7)
```console
...
File "/Users/rwolf/Development/detection-rules/detection_rules/eswrap.py", line 256, in kibana_upload
payload = downgrade(payload, "7.7.0")
File "/Users/rwolf/Development/detection-rules/detection_rules/schemas/__init__.py", line 40, in downgrade
raise ValueError(f"Unable to downgrade from {CurrentSchema.STACK_VERSION} to {target_version_str}") …
```

Downgrade rule version before uploading to Kibana

---

detection_rules/eswrap.py
kibana/resources.py
requirements.txt
tests/test_schemas.py

Closes #121
dataclasses-json was silently dropping fields, and drifted from the JSON schemas. `index` wasn't included in the RuleResource class definition, the field was silently dropped. I removed the dataclasses-json approach, and just made RuleResource a subclass of dict instead. There is no validation in the schema, and I think that it's okay to make the client validate, since all of that code is there.
Here's the payload after the changes
```python
[{'author': ['Rule export'], 'description': 'The contents of crontab have been modified by a non-root user.', 'tags': ['prod'], 'index': ['filebeat-*'], 'language': 'kuery', 'license': 'Elastic License', 'name': 'Cron - Crontab entry changed', 'risk_score': 15, 'rule_id': '7230e517-3f0f-4652-8c47-c2edd9b25d19', 'severity': 'low', 'type': …
```

Fix kibana-upload and remove cumbersome dataclasses

---

.github/workflows/pythonpackage.yml

None
This adds `build-release` to be run as part of GH actions to ensure packaging mechanisms are also tested

Add build-release to GH actions

---

rules/okta/credential_access_attempts_to_brute_force_okta_user_account.toml

Resolves #73 
Identifies when an Okta user account is locked out 3 times within a 3 hour window. An adversary may attempt a brute force or password spraying attack to obtain unauthorized access to user accounts. The default Okta authentication policy ensures that a user account is locked out after 10 failed authentication attempts.

[New Rule] Attempts to Brute Force an Okta User Account

---

rules/azure/defense_evasion_user_added_as_owner_for_azure_application.toml

Resolves #113 
Identifies when a user is added as an owner for an Azure service principal. The service principal object defines what the application can do in the specific tenant, who can access the application, and what resources the app can access.
A service principal object is created when an application is given permission to access resources in a tenant. An adversary may add a user account as an owner for a service principal and use that account in order to define what an application can do in the Azure AD tenant.

[New Rule] User Added as Owner for Azure Service Principal

---

rules/azure/defense_evasion_mfa_disabled_for_azure_user.toml

Resolves #116 
Identifies when multi-factor authentication (MFA) is disabled for an Azure user account. An adversary may disable MFA for a user account in order to weaken the authentication requirements for the account.

[New Rule] Multi-Factor Authentication Disabled for an Azure User

---

rules/azure/impact_azure_automation_runbook_deleted.toml

Resolves #117 
Identifies when an Azure Automation runbook is deleted. An adversary may delete an Azure Automation runbook in order to disrupt atheir target's automated business operations or to remove a malicious runbook that was used for persistence.

[New Rule] Azure Automation Runbook Deleted

---

rules/azure/collection_update_event_hub_auth_rule.toml

resolves #140 
Identifies when an Event Hub Authorization Rule is created or updated in Azure. An authorization rule is associated with specific rights, and carries a pair of cryptographic keys. When you create an Event Hubs namespace, a policy rule named RootManageSharedAccessKey is created for the namespace. This has manage permissions for the entire namespace and it's recommended that you treat this rule like an administrative root account and don't use it in your application.
-- 1.4.0
- detonate

[New Rule] Azure Event Hub Authorization Rule Created or Updated

---

.gitignore
rules/okta/credential_access_suspicious_okta_user_password_reset_or_unlock_attempts.toml

Resolves #74 
Identifies a high number of Okta user password reset or account unlock attempts. An adversary may attempt to obtain unauthorized access to an account Okta user account using these methods and attempt to blend in with normal activity in their target's environment and evade detection.

[New Rule] High Number of Okta User Password Reset or Unlock Attempts

---

rules/aws/privilege_escalation_root_login_without_mfa.toml

resolves #224 
Updates the severity and risk score for the `AWS Root Login Without MFA` rule.
-- 1.4.0
- detonate

[Rule Tuning] AWS Root Login Without MFA

---

rules/azure/initial_access_external_guest_user_invite.toml

resolves #193 
Identifies an invitation to an external user in Azure Active Directory (AD). Azure AD is extended to include collaboration, allowing you to invite people from outside your organization to be guest users in your cloud account. Unless there is a business need to provide guest access to any user, avoid creating guest users. Guest users could potentially be overlooked indefinitely leading to a potential vulnerability.
-- 1.4.0
- detonate

[New Rule] Azure External Guest User Invitation

---

rules/azure/defense_evasion_network_watcher_deletion.toml

resolves #197 
Identifies the deletion of a Network Watcher in Azure. Network Watchers are used to monitor, diagnose, view metrics, and enable or disable logs for resources in an Azure virtual network. An adversary may delete a Network Watcher in an attempt to evade defenses.
-- 1.4.0
- detonate

[New Rule] Azure Network Watcher Deletion

---

rules/okta/credential_access_attempted_bypass_of_okta_mfa.toml
rules/okta/credential_access_attempts_to_brute_force_okta_user_account.toml
rules/okta/credential_access_okta_brute_force_or_password_spraying.toml
rules/okta/credential_access_suspicious_okta_user_password_reset_or_unlock_attempts.toml
rules/okta/impact_attempt_to_revoke_okta_api_token.toml
rules/okta/impact_possible_okta_dos_attack.toml
rules/okta/initial_access_suspicious_activity_reported_by_okta_user.toml
rules/okta/okta_attempt_to_deactivate_okta_mfa_rule.toml
rules/okta/okta_attempt_to_delete_okta_policy.toml
rules/okta/okta_attempt_to_modify_okta_mfa_rule.toml
rules/okta/okta_attempt_to_modify_okta_network_zone.toml
rules/okta/okta_attempt_to_modify_okta_policy.toml
rules/okta/okta_attempt_to_modify_or_delete_application_sign_on_policy.toml
rules/okta/okta_threat_detected_by_okta_threatinsight.toml
rules/okta/persistence_administrator_privileges_assigned_to_okta_group.toml
rules/okta/persistence_attempt_to_create_okta_api_token.toml
rules/okta/persistence_attempt_to_deactivate_mfa_for_okta_user_account.toml
rules/okta/persistence_attempt_to_deactivate_okta_policy.toml
rules/okta/persistence_attempt_to_reset_mfa_factors_for_okta_user_account.toml

#255 
This PR updates our prebuilt Okta rules to include the Elastic Agent index, `logs-okta*.

[Rule Tuning] Update Okta rules to include Agent index pattern

---

detection_rules/eswrap.py

https://github.com/elastic/detection-rules/issues/345
Bug fix - missing parenthesis cause error if --kibana-url option is provided to the kibana-upload command

[Bug] Fix kibana-url for kibana-upload command

---

rules/windows/defense_evasion_execution_via_trusted_developer_utilities.toml
rules/windows/defense_evasion_via_filter_manager.toml
rules/windows/discovery_process_discovery_via_tasklist_command.toml
rules/windows/discovery_whoami_command_activity.toml
rules/windows/execution_via_compiled_html_file.toml
rules/windows/persistence_priv_escalation_via_accessibility_features.toml
rules/windows/persistence_via_application_shimming.toml

This PR updates all the rules that use `event.code:1` and replaces it with `event.category:process and event.type:(start or process_started)` instead. 
Other than `event.code:1`, I saw no other instances of that field in other rules. 
We should also consider removing a couple noisy rules, like `Whoami Process Activity` and `Process Discovery via Tasklist` and account for them in a more robust EQL discovery sequence and/or convert to a ML job.

[Rule Tuning] Update from event.code to event.category

---

.github/workflows/pythonpackage.yml
CLI.md
Makefile
README.md
detection_rules/__init__.py
detection_rules/devtools.py
detection_rules/eswrap.py
detection_rules/kbwrap.py
detection_rules/main.py
detection_rules/misc.py
detection_rules/rule_loader.py
detection_rules/utils.py
kibana/connector.py

Resolves #279 
Reorganizes commands as follow:
* `dev` - internal commands
* `es` - commands using the Elasticsearch client
* `kibana` - commands using the Kibana client
All other commands remain as top level commands
Client errors are now wrapped under `ClientError` or the helper function `client_error` to esablish consistency with messages and error codes
Global debugging enabled to bypass `ClientError` and let full stacktraces bleed through
Elasticsearch and Kibana clients are now embedded within their respective click groups which does two things:
* separates click options for the clients to the subcommand (group)
* embeds the client in`ctx.obj[**]` for access by any sub-commands to the respective group
Updated some of the argument names to allow for more specificity, specifically …

Re-organize commands under more specific click groups

---

rules/cross-platform/impact_hosts_file_modified.toml
rules/macos/credential_access_kerberosdump_kcc.toml
rules/macos/exfiltration_compress_credentials_keychains.toml
rules/macos/lateral_movement_remote_ssh_login_enabled.toml
rules/network/discovery_post_exploitation_public_ip_reconnaissance.toml
rules/promotions/external_alerts.toml
tests/test_all_rules.py

None
An inconsistency in tag formatting was found during a [rules PR to Kibana](https://github.com/elastic/kibana/pull/79061#discussion_r499857985). This adds two new unit tests for:
```
AssertionError: 594e0cbf-86cc-45aa-9ff7-ff27db27d3ed - AWS CloudTrail Log Created -> Invalid casing for expected tags
Actual tags: Sec Ops, ContinuousMonitoring
Expected tags: SecOps, Continuous Monitoring
```
(a rule with `index = ["winlogbeat-*", "logs-endpoint.events.*"]` and only `Elastic` tag)
```
AssertionError: 4630d948-40d4-4cef-ac69-4002e29bc3db - Adding Hidden File Attribute via Attrib -> Missing tags:
Actual tags: Elastic
Missing all of: Windows
Missing any of: MacOS, Linux
```
This was only based on known index <-> tag relationships based on a survey of the current rule set. We can expand this …

Add unit tests for rule tags

---

detection_rules/rule.py
requirements.txt
rules/windows/defense_evasion_installutil_beacon.toml
rules/windows/defense_evasion_msbuild_beacon_sequence.toml
rules/windows/defense_evasion_mshta_beacon.toml
rules/windows/defense_evasion_msxsl_beacon.toml
rules/windows/defense_evasion_network_connection_from_windows_binary.toml
rules/windows/defense_evasion_reg_beacon.toml
rules/windows/defense_evasion_rundll32_no_arguments.toml
rules/windows/defense_evasion_rundll32_sequence.toml
rules/windows/defense_evasion_suspicious_scrobj_load.toml
rules/windows/defense_evasion_suspicious_wmi_script.toml
rules/windows/execution_ms_office_written_file.toml
rules/windows/execution_pdf_written_file.toml
rules/windows/execution_wpad_exploitation.toml
rules/windows/lateral_movement_cmd_service.toml
rules/windows/persistence_app_compat_shim.toml
rules/windows/privilege_escalation_uac_sdclt.toml

dependent on endgameinc/eql/pull/41
resolves #396
Updates EQL rules to reflect changes in EQL implementation and syntax. Rules were also tuned to adapt to missing fields in respective data sources (or the indexes were removed). EQL searches are strict and will fail if a field does not exist in the mapping

[Rule Tuning] Update EQL rules for 7.10

---

rules/linux/lateral_movement_telnet_network_activity_external.toml
rules/linux/lateral_movement_telnet_network_activity_internal.toml
rules/linux/linux_netcat_network_connection.toml
rules/windows/command_and_control_certutil_network_connection.toml
rules/windows/defense_evasion_installutil_beacon.toml
rules/windows/defense_evasion_misc_lolbin_connecting_to_the_internet.toml
rules/windows/defense_evasion_msxsl_beacon.toml
rules/windows/defense_evasion_network_connection_from_windows_binary.toml
rules/windows/defense_evasion_reg_beacon.toml
rules/windows/defense_evasion_rundll32_no_arguments.toml
rules/windows/defense_evasion_rundll32_sequence.toml
rules/windows/execution_command_prompt_connecting_to_the_internet.toml
rules/windows/execution_html_help_executable_program_connecting_to_the_internet.toml
rules/windows/execution_msbuild_making_network_connections.toml
rules/windows/execution_mshta_making_network_connections.toml
rules/windows/execution_msxsl_network.toml
rules/windows/execution_psexec_lateral_movement_command.toml
rules/windows/execution_register_server_program_connecting_to_the_internet.toml
rules/windows/execution_unusual_network_connection_via_rundll32.toml
rules/windows/execution_unusual_process_network_connection.toml
rules/windows/execution_wpad_exploitation.toml
rules/windows/lateral_movement_cmd_service.toml
rules/windows/lateral_movement_direct_outbound_smb_connection.toml

resolves #419
Modified all rules using the index `logs-endpoint.events.*` (or `winlogbeat-*` which can be compatible with endpoint) that were using `event.type:connection` for network events.
For just about all of these modified rules, the use of `event.type` was used to limit the number of alerts by restricting to only a subset of network events. Even with the `event.type` defined, the rules would still trigger many alerts. The best way to limit this is to use an `eql` sequence off the process `start` event, which would limit it to a single alert.
Also, see the issue for inconsistencies across the two data sources.

Remove connection type from endpoint network rules

---

etc/non-ecs-schema.json
rules/cross-platform/initial_access_zoom_meeting_with_no_passcode.toml

None
Zoom module was added to filebeat in this [PR](https://github.com/elastic/beats/pull/20414/files), which will be released with 7.10. Because the beats module could not be validated at the time the rule was created, this was placed in development. I temporarily added the field to the `non-ecs-schema` for the time being and once beats 7.10 is released, we can refresh the consolidated schema and remove this.

[Rule Tuning] Zoom Meeting with no Passcode to production

---

detection_rules/rule.py
rules/linux/lateral_movement_telnet_network_activity_external.toml
rules/linux/lateral_movement_telnet_network_activity_internal.toml
rules/windows/command_and_control_certutil_network_connection.toml
rules/windows/defense_evasion_misc_lolbin_connecting_to_the_internet.toml
rules/windows/execution_command_prompt_connecting_to_the_internet.toml
rules/windows/execution_html_help_executable_program_connecting_to_the_internet.toml
rules/windows/execution_msbuild_making_network_connections.toml
rules/windows/execution_msxsl_network.toml
rules/windows/execution_register_server_program_connecting_to_the_internet.toml
rules/windows/execution_unusual_network_connection_via_rundll32.toml
rules/windows/lateral_movement_direct_outbound_smb_connection.toml

None
EQL currently does not support comparing `ip` fields using `in`, so all EQL rules checking for multiple IP addresses using the convention `*.ip in ( ... )` must be converted to use `cidrMatch()` (or individual comparisons).

[Rule Tuning] Use cidrMatch for eql rules checking multiple IPs

---

rules/windows/defense_evasion_msbuild_beacon_sequence.toml
rules/windows/defense_evasion_msxsl_beacon.toml
rules/windows/defense_evasion_reg_beacon.toml
rules/windows/defense_evasion_rundll32_sequence.toml
rules/windows/execution_mshta_making_network_connections.toml
rules/windows/execution_msxsl_network.toml
rules/windows/execution_wpad_exploitation.toml
rules/windows/privilege_escalation_uac_sdclt.toml

Upon testing of EQL rules for 7.10, and after the conversion of various KQL rules to EQL, we noticed some rules that we're duplicative. This PR drops those rules to `development`. This will allow us to re-work the syntax or deprecate those rules in the future, without them going into production this release.  
**Duplicative rules:**
`MsBuild Network Connection Sequence`
`Network Connection via Mshta`
`MsXsl Making Network Connections`
`Registration Tool Making Network Connections`
`Unusual Network Connection Sequence via RunDLL32`
Two other rules need additional testing and will also be dropped to dev for 7.10 - 
`Bypass UAC via Sdclt`
`WPAD Service Exploit`
After dropping all these to development, that leaves us with a total of 24 EQL rules for 7.10.
- Have you signed the [contributor …

[Rule Tuning] Remove duplicate rules after EQL conversion

---

rules/google-workspace/persistence_google_workspace_api_access_granted_via_domain_wide_delegation_of_authority.toml

Resolves #467
Detects when a domain-wide delegation of authority is granted to a service account. Domain-wide delegation can be configured to grant third-party and internal applications to access the data of Google Workspace users. An adversary may configure domain-wide delegation to maintain access to their target’s data.

[New Rule] Google Workspace API Access Granted via Domain-Wide Delegation of Authority

---

rules/okta/okta_attempt_to_modify_okta_application.toml

Resolves #492 
Detects attempts to modify an Okta application. An adversary may attempt to modify, deactivate, or delete an Okta application in order to weaken an organization's security controls or disrupt their business operations.

[New Rule] Attempt to Modify an Okta Application

---

rules/okta/okta_attempt_to_deactivate_okta_application.toml

Resolves #493 
Detects attempts to deactivate an Okta application. An adversary may attempt to modify, deactivate, or delete an Okta application in order to weaken an organization's security controls or disrupt their business operations.

[New Rule] Attempt to Deactivate an Okta Application

---

rules/okta/okta_attempt_to_delete_okta_application.toml

Resolves #494 
Detects attempts to delete an Okta application. An adversary may attempt to modify, deactivate, or delete an Okta application in order to weaken an organization's security controls or disrupt their business operations.

[New Rule] Attempt to Delete an Okta Application

---

CLI.md
detection_rules/devtools.py
detection_rules/eswrap.py
detection_rules/kbwrap.py
detection_rules/misc.py
detection_rules/utils.py
kibana/connector.py
requirements.txt
tests/test_utils.py

resolves #484
Adds the following commands:
* `dev test`:
- `event-search` - search elasticsearch with a specified query
- `rule-event-search` - search elasticsearch by specifying a rule
- `rule-survey` - run a survey against all rules specified by a `rule-search` filter and determine search and alert hits
* `kibana`
- `search-alerts` - search alerts with kql
```console
python -m detection_rules dev test rule-survey --hide-zero-counts --hide-errors --date-range now-220d now
Loaded config file: .../.detection-rules-cfg.json
DEBUG MODE ENABLED
Running survey against 325 rules
Saving detailed dump …
```

Add test commands to search and survey rule hits

---

rules/okta/persistence_administrator_role_assigned_to_okta_user.toml

Resolves #397 
Identifies when an administrator role is assigned to an Okta user. An adversary may attempt to assign an administrator role to an Okta user in order to assign additional permissions to a user account and maintain access to their target's environment.

[New Rule] Administrator Role Assigned to Okta User

---

rules/google-workspace/google_workspace_policy_modified.toml

Resolves #469 
Detects when a Google Workspace password policy is modified. An adversary may attempt to modify a password policy in order to weaken an organization’s security controls.

[New Rule] Google Workspace Password Policy Modified

---

rules/google-workspace/mfa_disabled_for_google_workspace_organization.toml

Resolves #470 
Detects when multi-factor authentication (MFA) is disabled for a Google Workspace organization. An adversary may attempt to modify a password policy in order to weaken an organization’s security controls.

[New Rule] MFA Disabled for Google Workspace Organization

---

rules/google-workspace/persistence_google_workspace_admin_role_assigned_to_user.toml

Resolves #506 
Detects when an admin role is assigned to a Google Workspace user. An adversary may assign an admin role to a user in order to elevate the permissions of another user account and persist in their target’s environment.

[New Rule] Google Workspace Admin Role Assigned to a User

---

rules/google-workspace/persistence_google_workspace_custom_admin_role_created.toml

Resolves #507 
Detects when a custom admin role is created in Google Workspace. An adversary may create a custom admin role in order to elevate the permissions of other user accounts and persist in their target’s environment.

[New Rule] Google Workspace Custom Admin Role Created

---

rules/google-workspace/persistence_google_workspace_role_modified.toml

Resolves #510 
Detects when a custom admin role or its permissions are modified. An adversary may modify a custom admin role in order to elevate the permissions of other user accounts and persist in their target’s environment.

[New Rule] Google Workspace Role Modified

---

rules/google-workspace/google_workspace_admin_role_deletion.toml

Resolves #511 
Detects when a custom admin role is deleted. An adversary may delete a custom admin role in order to impact the permissions or capabilities of system administrators.

[New Rule] Google Workspace Admin Role Deletion

---

rules/google-workspace/domain_added_to_google_workspace_trusted_domains.toml

Resolves #513 
Detects when a domain is added to the list of trusted Google Workspace domains. An adversary may add a trusted domain in order to collect and exfiltrate data from their target’s organization with less restrictive security controls.

[New Rule] Domain Added to Google Workspace Trusted Domains

---

rules/google-workspace/google_workspace_mfa_enforcement_disabled.toml

Resolves #514 
Detects when multi-factor authentication (MFA) enforcement is disabled for Google Workspace users. An adversary may disable MFA enforcement in order to weaken an organization’s security controls.

[New Rule] Google Workspace MFA Enforcement Disabled

---

rules/google-workspace/application_added_to_google_workspace_domain.toml

Resolves #512 
Detects when a Google marketplace app is added to the Google Workspace domain. An adversary may add a malicious app to an organization’s Google Workspace domain in order to maintain a presence in their target’s organization and steal data.

[New Rule] Application Added to Google Workspace Domain

---

requirements.txt

Related to https://github.com/endgameinc/eql/issues/43
Updated the EQL dependency so we can use `field : ("wild*card", "...")` syntax for EQL.

Bump EQL dependency to 0.9.6

---

rules/o365/initial_access_o365_exchange_safelinks_disabled.toml

resolves #464 
Identifies when a Safe Link policy is disabled in Office 365. Safe Link policies for Office applications extend phishing protection to documents that contain hyperlinks, even after they have been delivered to a user.

[New Rule] O365 Exchange Safe Link Policy Disabled

---

rules/o365/exfiltration_o365_exchange_transport_rule_creation.toml

resolves #468 
Identifies a transport rule creation in Office 365. Exchange Online mail transport rules should be set to not forward email to domains outside of your organization. An adversary may create transport rules to exfiltrate data.

[New Rule] O365 Exchange Transport Rule Creation

---

rules/o365/initial_access_o365_exchange_anti_phish_policy_deletion.toml

resolves #479 
Identifies the deletion of an anti-phishing policy in Office 365. By default, Office 365 includes built-in features that help protect users from phishing attacks. Anti-phishing polices increase this protection by refining settings to better detect and prevent attacks.

[New Rule] O365 Exchange Anti-Phish Policy Deletion

---

rules/o365/initial_access_o365_exchange_anti_phish_rule_mod.toml

resolves #480 
Identifies the modification of an anti-phishing rule in Office 365. By default, Office 365 includes built-in features that help protect users from phishing attacks. Anti-phishing rules increase this protection by refining settings to better detect and prevent attacks.

[New Rule] O365 Exchange Anti-Phish Rule Modification

---

rules/o365/defense_evasion_o365_exchange_malware_filter_policy_deletion.toml
rules/windows/command_and_control_common_webservices.toml

resolves #503 
Identifies when a malware filter policy has been deleted in Office 365. A malware filter policy is used to alert administrators that an internal user sent a message that contained malware. This may indicate an account or machine compromise, that would need to be investigated. Deletion of a malware filter policy may be done to evade detection.

[New Rule] O365 Exchange Malware Filter Policy Deletion

---

rules/o365/exfiltration_o365_exchange_transport_rule_mod.toml
rules/windows/command_and_control_common_webservices.toml

resolves #505 
Identifies when a transport rule has been disabled or deleted in Office 365. Mail flow rules (also known as transport rules) are used to identify and take action on messages that flow through your organization. An adversary or malicious insider may modify a transport rule to exfiltrate data or evade defenses.

[New Rule] O365 Exchange Transport Rule Modification

---

rules/o365/defense_evasion_o365_exchange_safe_attach_rule_disabled.toml

resolves #525 
Identifies when a Safe Attachment rule is disabled in Office 365. Safe Attachment rules can extend malware protections to include routing all messages and attachments without a known malware signature to a special hypervisor environment. An adversary or malicious insider may disable a Safe Attachment rule to exfiltrate data or evade defenses.

[New Rule] O365 Exchange Safe Attachment Rule Disabled

---

rules/windows/execution_unusual_dns_service_file_writes.toml

resolves #471 
Tune rule to add `event.type` in order to avoid FP's for `access` events (Sysmon 18).

[Rule Tuning] Unusual File Modification by dns.exe

---

detection_rules/kbwrap.py
detection_rules/misc.py
kibana/connector.py

None
Allow `Kibana` connector to auth via an existing cookie. This is especially useful in cases where auth is normally performed via SSO.

Auth to Kibana connector using an existing cookie

---

rules/azure/defense_evasion_azure_application_credential_modification.toml

resolves #714 
Identifies when a new credential is added to an application in Azure. An application may use a certificate or secret string to prove its identity when requesting a token. Multiple certificates and secrets can be added for an application and an adversary may abuse this by creating an additional authentication method to evade defenses or persist in an environment.

[New Rule] Azure Application Credential Modification

---

rules/azure/defense_evasion_azure_service_principal_addition.toml

resolves #715 
Identifies when a new service principal is added in Azure. An application, hosted service, or automated tool that accesses or modify resources need an identity created. This identity is known as a service principal. For security reasons, it's always recommended to use service principals with automated tools rather than allowing them to log in with a user identity.

[New Rule] Azure Service Principal Addition

---

rules/azure/initial_access_azure_active_directory_powershell_signin.toml
rules/azure/initial_access_azure_active_directory_powershell_signon.toml

resolves #713 
Identifies a sign-in using the Azure Active Directory PowerShell module. PowerShell for Azure Active Directory allows for managing settings from the command line, which is intended for users who are members of an admin role.

[New Rule] Azure Active Directory PowerShell Sign-in

---

.github/workflows/pythonpackage.yml

None
I noticed that we build all branches and all PRs. This means that each PR will have two checks. That's unnecessary. Since we already build all branches, I think the PR builds are redundant, so I removed them.

Remove duplicate PR job

---

detection_rules/attack.py
detection_rules/rule.py
detection_rules/schemas/v7_11.py

Related to #52 
Kibana is making (https://github.com/elastic/kibana/pull/85481) threat.technique optional, similar to the decision for threat.technique.subtechnique. This updates the schema to reflect that.

Make threat.technique optional

---

detection_rules/schemas/v7_11.py
tests/test_schemas.py

A user found that some of the latest Sunburst rules weren't working with Kibana upload. The biggest reason is the downgrade process from 7.11 to 7.10. 
We still have an issue where some new EQL functionality won't work properly in the detection engine (e.g. `process.name : ("a", "b", "c")` syntax and `:` with wildcards aren't supported.
The ATT&CK subtechnique process seemed to be working, but I didn't update the downgrade process for optional techniques, which was new in #727.
We'll merge `7.11` into `main` after this is merged.

[Bug] Fix 7.11 -> 7.10 ATT&CK downgrade logic for optional techiques

---

detection_rules/schemas/v7_8.py

From [this community slack thread](https://elasticstack.slack.com/archives/C016E72DWDS/p1611144454021300?thread_ts=1611138771.016300&cid=C016E72DWDS) by @SHolzhauer 
> Not sure what is wrong here.
> Adding the filter works with a script, this does what I need, tnx @ James Spiteri [Elastic Security Solutions Lead]
> I am now running into a TOML/JSON validation issue. I have added the following to the TOML file:
> 
[[rule.filters]]
[rule.filters.query.bool.filter.script.script]
source = "doc['@timestamp'].value.getHour() > 0 && doc['@timestamp'].value.getHour() < 7 || doc['@timestamp'].value.getHour() > 21"
lang = "painless"
> Running the test command or `kibana-upload` it fails with an error:
> 
ERROR tests/test_mappings.py - jsonschema.exceptions.ValidationError: Additional properties are …

Loosen query DSL filter schema validation

---

rules/windows/execution_enumeration_via_wmiprvse.toml

resolves #836 
Identifies native Windows host and network enumeration commands spawned by the Windows Management Instrumentation Provider Service (WMIPrvSE).

[New Rule] Enumeration Command Spawned via WMIPrvSE

---

rules/windows/credential_access_mod_wdigest_security_provider.toml

resolves #838 
Identifies attempts to modify the WDigest security provider in the registry to force the user's password to be stored in clear text in memory. This behavior can be indicative of an adversary attempting to weaken the security configuration of an endpoint. Once the UseLogonCredential value is modified, the adversary may attempt to dump clear text passwords from
memory.

[New Rule] Modification of WDigest Security Provider

---

rules/windows/credential_access_saved_creds_vaultcmd.toml

resolves #840 
Windows Credential Manager allows you to create, view, or delete saved credentials for signing into websites, connected applications, and networks. An adversary may abuse this to list or dump credentials stored in the Credential Manager for saved usernames and passwords. This may also be performed in preparation of lateral movement.

[New Rule] Searching for Saved Credentials via VaultCmd

---

rules/windows/persistence_time_provider_mod.toml

resolves #853 
Windows operating systems are utilizing the time provider architecture in order to obtain accurate time stamps from other network devices or clients in the network. Time providers are implemented in the form of a DLL file which resides in System32 folder. The service W32Time initiates during the startup of Windows and loads w32time.dll. Adversaries may abuse this architecture to establish persistence, specifically by registering and enabling a malicious DLL as a time provider.

[New Rule] Potential Persistence via Time Provider Modification

---

rules/macos/defense_evasion_attempt_del_quarantine_attrib.toml
rules/network/command_and_control_cobalt_strike_default_teamserver_cert.toml
rules/windows/command_and_control_iexplore_via_com.toml
rules/windows/command_and_control_remote_file_copy_scripts.toml
rules/windows/credential_access_kerberoasting_unusual_process.toml
rules/windows/defense_evasion_masquerading_trusted_directory.toml
rules/windows/execution_shared_modules_local_sxs_dll.toml
rules/windows/initial_access_via_explorer_suspicious_child_parent_args.toml
rules/windows/lateral_movement_powershell_remoting_target.toml
rules/windows/lateral_movement_rdp_enabled_registry.toml
rules/windows/persistence_ms_office_addins_file.toml
rules/windows/persistence_ms_outlook_vba_template.toml
rules/windows/persistence_suspicious_scheduled_task_runtime.toml
rules/windows/privilege_escalation_printspooler_registry_copyfiles.toml
rules/windows/privilege_escalation_printspooler_service_suspicious_file.toml
rules/windows/privilege_escalation_printspooler_suspicious_spl_file.toml
rules/windows/privilege_escalation_rogue_windir_environment_var.toml
rules/windows/privilege_escalation_uac_bypass_com_clipup.toml
rules/windows/privilege_escalation_uac_bypass_mock_windir.toml
rules/windows/privilege_escalation_uac_sdclt.toml
rules/windows/privilege_escalation_wpad_exploitation.toml

n/a
Upon review, there are rules in `main` that don't follow our established risk score/severity mappings of - 
`low:21`, 
`medium:47`, 
`high:73`, 
`critical:99`
This PR adjusts the risk score values to align with the severity mapping.

[Rule Tuning] Adjust risk scores to align with severity

---

etc/version.lock.json

N/A
Versions were locked on mergeback but not within the branch
Verified this matched Kibana as expected
```
python -m detection_rules dev kibana-diff -b 7.11
Downloading rules from 7.11 branch in kibana repo using 50 threads ...
{
"diff": [],
"missing_from_kibana": [],
"missing_from_repo": [],
"stats": {
"diff": 0,
"missing_from_kibana": 0,
"missing_from_repo": 0,
"total_gh_prod_rules": 461,
"total_repo_prod_rules": 461
}
}
```

Lock versions for rule changes in v7.11.0

---

rules/macos/execution_curl_spawned_from_installer_package.toml
rules/macos/execution_installer_spawned_network_event.toml

Resolves #957 
This rule identifies when the built-in macOS Installer program is used to install a package that spawns a shell and runs
the cURL command.

[New Rule] Installer Spawning cURL from macOS Package

---

rules/windows/initial_access_suspicious_ms_exchange_files.toml

Resolves #973 
Microsoft Exchange Server’s Unified Messaging service creating non-standard content on disk, which could indicate web shells or other malicious content. CVE-2021-26858

[New Rule] HAFNIUM MS Exchange UM Service Writing - CVE-2021-26858

---

rules/windows/execution_via_xp_cmdshell_mssql_stored_procedure.toml
rules/windows/initial_access_suspicious_ms_exchange_process.toml

Resolves #972 
This rule detects CVE-2021-2685 and detects new processes being spawned by the Exchange UM service where that process has not previously been observed before.

[New Rule] Microsoft Exchange Server’s Unified Messaging Spawning Vulnerability - CVE-2021-26857

---

rules/windows/initial_access_suspicious_ms_exchange_worker_child_process.toml

resolves #984 
Identifies suspicious processes being spawned by the Microsoft Exchange Server worker process (w3wp). This activity may indicate exploitation activity or access to an existing web shell backdoor.

[New Rule] Microsoft Exchange Worker Spawning Suspicious Processes

---

detection_rules/cli_utils.py
detection_rules/main.py
detection_rules/rule.py

No issue, just a minor change. Hoping that it'll help lead to more organized code down the line.
Extracted `Rule.build` as a method into `cli_utils.rule_prompt`.
I'm trying to keep my PR line counts small, so that we can make incremental changes. This is an easy one to do before getting into larger diffs.
```console
$ python -m detection_rules create-rule x.toml --required-only
Rule type (machine_learning, saved_query, query, threshold, eql) (machine_learning, saved_query, query, threshold, eql): query
rule_id [9d92558c-4426-4349-8cfd-3d2f3a532893] ("n/a" to leave blank)  (required): 
description (required): Hello world
name (required): My name is ted
risk_score [21] ("n/a" to leave blank)  (required): 
severity [low] ("n/a" to leave blank)  (required): 
language [kuery] ("n/a" to leave …
```

Move Rule.build to cli_utils.rule_prompt

---

detection_rules/packaging.py

None
Related to https://github.com/elastic/package-spec/pull/142 and https://github.com/elastic/package-storage/pull/843.
Changed the asset type/folder to `security-rule`

Change asset type for integration to security-rule

---

detection_rules/devtools.py
detection_rules/packaging.py
detection_rules/rule_loader.py
detection_rules/schemas/base.py
docs/deprecating.md
etc/deprecated_rules.json
rules/_deprecated/privilege_escalation_setgid_bit_set_via_chmod.toml
tests/test_all_rules.py

resolves #959 
Adds test to ensure rules are properly deprecated. Re-added deprecated rule that was previously removed and updated `deprecated_rules.json`. A readme was also added to provide proper steps to deprecating.
I tried to make this as minimal as possible in order to be the least impactful to #1029, but hope to get this in to prevent any more accidental deletions, such as in #1028

Add tests to ensure rules are properly deprecated

---

detection_rules/packaging.py
detection_rules/rule.py

Unable to save the version lock
I noticed that the most recent changes in #1029 were made after I tested the lock.
I think I never tried re-saving the lock in the new branch. Some of the code was moved.
Now you can save the lock again.
Package hash still looks good.

Fix the version lock update code

---

detection_rules/packaging.py
detection_rules/rule.py
detection_rules/schemas/definitions.py
etc/packages.yml

Found in https://github.com/elastic/kibana/pull/95885 and fixed in https://github.com/elastic/integrations/pull/824
Update the autogenerated integration so that type is the saved object type which is `security-rule`. Linked PRs have more context.

Change the asset .type field

---

detection_rules/devtools.py
etc/version.lock.json
rules/promotions/endgame_adversary_behavior_detected.toml
rules/promotions/endgame_cred_dumping_detected.toml
rules/promotions/endgame_cred_dumping_prevented.toml
rules/promotions/endgame_cred_manipulation_detected.toml
rules/promotions/endgame_cred_manipulation_prevented.toml
rules/promotions/endgame_exploit_detected.toml
rules/promotions/endgame_exploit_prevented.toml
rules/promotions/endgame_malware_detected.toml
rules/promotions/endgame_malware_prevented.toml
rules/promotions/endgame_permission_theft_detected.toml
rules/promotions/endgame_permission_theft_prevented.toml
rules/promotions/endgame_process_injection_detected.toml
rules/promotions/endgame_process_injection_prevented.toml
rules/promotions/endgame_ransomware_detected.toml
rules/promotions/endgame_ransomware_prevented.toml

None
lock versions for 7.12 rules
To reconcile, the promotion rules needed to have a version bump and the `event_override` field added (ref: #1082)
```
python -m detection_rules dev kibana-diff -b 7.12 -t 100
Downloading rules from elastic/kibana 7.12 branch in kibana repo using 100 threads ...
{
"diff": [],
"missing_from_kibana": [],
"missing_from_repo": [],
"stats": {
"diff": 0,
"missing_from_kibana": 0,
"missing_from_repo": 0,
"total_gh_prod_rules": 546,
"total_repo_prod_rules": 546
}
}
```

Lock 7.12 rule versions

---

etc/version.lock.json
rules/promotions/endgame_adversary_behavior_detected.toml
rules/promotions/endgame_cred_dumping_detected.toml
rules/promotions/endgame_cred_dumping_prevented.toml
rules/promotions/endgame_cred_manipulation_detected.toml
rules/promotions/endgame_cred_manipulation_prevented.toml
rules/promotions/endgame_exploit_detected.toml
rules/promotions/endgame_exploit_prevented.toml
rules/promotions/endgame_malware_detected.toml
rules/promotions/endgame_malware_prevented.toml
rules/promotions/endgame_permission_theft_detected.toml
rules/promotions/endgame_permission_theft_prevented.toml
rules/promotions/endgame_process_injection_detected.toml
rules/promotions/endgame_process_injection_prevented.toml
rules/promotions/endgame_ransomware_detected.toml
rules/promotions/endgame_ransomware_prevented.toml

related to #1083 (the promotion rule changes will be _undone_ here)
Endgame promotion rules in Kibana/7.12 are at version 5 and _have_ `timestamp_override` defined (which should not be). These same rules are at version 4 in the detection-rules repo 7.12 branch and kibana/master and `timestamp_override` is _not_ defined. These updates are targeted for 7.12.1
There most likely was an issue with the maze of backports and interlaced updates.
To fix the rules, they need to be reconciled across:
* detection-rules 7.12 & main
* kibana 7.12.1 and master
bump detection-rules/7.12 to v6 -> PR to kibana/master ->  backport to 7.12 + 7.x 
<details>
```
=============================================================================================================================
rule_id …
```

Bump version for endpoint promotion rules for 7.12.1

---

detection_rules/schemas/base.py
detection_rules/schemas/v7_12.py
etc/version.lock.json
rules/aws/credential_access_aws_iam_assume_role_brute_force.toml

related to #1097 
related to #1099 (same change targeting main)
Changes `threshold.field` to disallow empty strings and instead just use an empty array for non-defined values.

Update threshold rule schema to disallow empty field string

---

detection_rules/devtools.py
detection_rules/packaging.py
detection_rules/rule.py
detection_rules/rule_validators.py
detection_rules/schemas/definitions.py
tests/test_all_rules.py
tests/test_mappings.py

Closes #1135 
Moved out query validation to separate classes.
In QueryRule (formerly BaseRuleQuery), it looks up the relevant validator and instantiates it. I also added more base methods that can be overriden for ThreatMatch rules, so we can unblock #1133.

Separate out query validation from the class hierarchy

---

detection_rules/rule.py
detection_rules/schemas/definitions.py

related to #305
This creates the rule type for `threat_match` (Indicator match) rules, which will allow these rules to be added and validated.
This does not include support for adding these rules via the CLI. That will come in a separate PR since the CLI still builds rules exclusively off the old schemas.
<details>
<summary>I tested this with a modified version of the rule from #1133</summary>
```toml
[metadata]
creation_date = "2020/02/18"
maturity = "production"
updated_date = "2021/03/03"
[rule]
author = [ "Elastic",]
description = "This rule is triggered when indicators from the Threat Intel Filebeat module has a match against local file or network observations.\n"
enabled = true
from = "now-600s"
index = [ "auditbeat-*", "filebeat-*", "logs-*",]
interval = "9m"
rule_id = …
```

Add threat_match rule type

---

kql/kql2eql.py
kql/parser.py
tests/kuery/test_parser.py

Unblocks https://github.com/elastic/detection-rules/pull/1133
Add support for wildcards in KQL fields.
For now, I explicitly fail if a wildcard field matches fields with multiple types.
This is faster to implement and more clear how it should behave. We can always come back later and add more support if needed.

Add wildcard field support to KQL

---

detection_rules/rule.py

resolves #1161
Machine learning rule job IDs can now be a single str or list of strings

Allow ML rules to accept a single or array of job IDs

---

.github/workflows/backport.yml

Part of #1171 
Added a new job that will automatically backport commits to the branches in our matrix if a `backport: auto` label is detected.
Today, this means 7.13.
I'll add more jobs to follow on for labeling, so that `backport: auto` is automatically set, and if `backport: skip` is set then it will automatically be removed.
More to come!
Example from my fork (https://github.com/rw-access/detection-rules/pull/13)

Add job for 'backport: auto' labeled PRs

---

.github/workflows/backport.yml

Related to #1171
Fix token issues in #1185.
Defaultt $GITHUB_TOKEN isn't always sufficient to push the backport commit, switching the account.
We don't share secrets with forks and because this job is `pull_request_target`, it will only run on the source repo.
Creating the PR from a fork to confirm.
More info on Github's blog
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

Use @protectionsmachine to push backports

---

.github/workflows/backport.yml

Continuing down the rabbit hole of #1186.
It appears that $GITHUB_TOKEN is set during the checkout action and interferes with the push action. Now the right token is used for everything.
Also, slack was removed because it's too loud.
See https://github.com/ad-m/github-push-action/issues/44#issuecomment-590010727

Disable persist-credentials from checkout job

---

detection_rules/main.py

Toml-lint wasn't working correctly. This small change updates `main.py` and fixes it. 
```bash
Error loading rule in C
Traceback (most recent call last):
File "c:\users\bmurphy\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "c:\users\bmurphy\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\dev\Elastic repos\fork-detection-rules\detection-rules\detection_rules\__main__.py", line 34, in <module>
main()
File "C:\dev\Elastic repos\fork-detection-rules\detection-rules\detection_rules\__main__.py", line 31, in main
root(prog_name="detection_rules")
File "C:\dev\Elastic repos\fork-detection-rules\detection-rules\rulez\lib\site-packages\click\core.py", …
```

[Bug] Update main.py to fix toml-lint

---

.github/workflows/backport.yml

Part of #1171
Works like this on a PR to main:
* If no backport labels are specified, it gets set to `backport: auto`
* If any other backport labels are specified, then `backport: auto` is removed
So if you have two conflicting `backport: auto` and `backport: label` labels, it'll remove the `backport: auto` one.

[CI] Apply `backport: auto` label on PRs to `main` by default

---

detection_rules/devtools.py
detection_rules/misc.py
requirements-dev.txt

Dependency for #1206
Add a `kibana-pr` command to automatically create a Kibana PR.
See it in action:
```console
$  python -m detection_rules dev kibana-pr --assign rw-access --label v7.13.1 --label v7.14.0 --label v8.0.0 --label auto-backport --label release_note:skip --draft
```
Created the pull request: https://github.com/elastic/kibana/pull/100160

Add a command to create a Kibana PR

---

detection_rules/main.py
detection_rules/rule.py
detection_rules/rule_formatter.py

None
Fix bug in `create-rule`:
```
File "C:\dev\Elastic repos\fork-detection-rules\detection-rules\detection_rules\main.py", line 55, in create_rule
rule_loader.reset()
AttributeError: module 'detection_rules.rule_loader' has no attribute 'reset'
```
This also updates `toml-lint` to preserve formatting for all queries

Fix create-rule bug

---

etc/deprecated_rules.json
etc/version.lock.json

None
I checked out `v7.13.0`, and updated the version lock.
Then brought that lock into `main`. It'll get backported onto 7.13.
If you run `python -m detection_rules dev build-release -u`, you'll get this output. It appears correct to match the changes in `main` and `7.13`:
<details>
<summary>Pending changes to the version lock</summary>
```diff
diff --git a/etc/version.lock.json b/etc/version.lock.json
index 987a066c..d0e1d6e7 100644
--- a/etc/version.lock.json
+++ b/etc/version.lock.json
@@ -1424,6 +1424,11 @@
"sha256": "d97ec49f15814bfde2f3f6b0603a9cf03bc171cffb3a6004202db2c71153461c",
"version": 8
},
+  "8a1d4831-3ce6-4859-9891-28931fa6101d": {
+    "rule_name": "Suspicious Execution from a Mounted Device",
+    "sha256": "e88541a1a011cfb788e031595a6452d932dfb34adde8fb0adb6a87f91abf9c1 …
```

Lock the versions from 7.13.0

---

NOTICE.txt
detection_rules/packaging.py
detection_rules/schemas/registry_package.py
etc/packages.yml
etc/security-logo-color-64px.svg

Partial dependency of https://github.com/elastic/detection-rules/issues/1206
Noticed some drift since https://github.com/elastic/integrations/tree/master/packages/security_detection_engine. Also since 7.13 has been released, we need to get a 0.13.0 package out to replace the temporary 0.0.2 package.

[Fleet] Update template and packaging code for fleet packages

---

rules/ml/ml_high_count_network_denies.toml
rules/ml/ml_high_count_network_events.toml
rules/ml/ml_rare_destination_country.toml
rules/ml/ml_spike_in_traffic_to_a_country.toml
tests/test_all_rules.py

None
@ajosh0504 noticed in #1283 that some rules were not using the v2 license of the Elastic License, so this corrects it and adds a test.
So long as all of these rules existed in 7.13, this is ok to backport

Fix rules which were not using v2 license

---

detection_rules/rule.py

Closes #1305
Added an optional `extended` dictionary under metadata.
This can be done by creating a new table called `[metadata.extended]` in TOML.

Extend metadata with `[metadata.extended]` section

---

.github/workflows/pythonpackage.yml

Closes #1204
Archiving artifacts to GitHub is really slow for some reason. One making commits on a PR, we shouldn't have to wait for these to build. It also creates new artifacts for every commit, which is unnecessary.
Now, we only build artifacts on `push` events to any of our target branches: `7.x`, `8.x` and `main`.
Here's me running it on a `push` event to `main` on my fork:
and here's it running on a temporary PR:

[CI] Only upload  build artifacts for `push` events

---

rules/ml/ml_auth_rare_hour_for_a_user_to_logon.toml
rules/ml/ml_auth_rare_source_ip_for_a_user.toml
rules/ml/ml_auth_rare_user_logon.toml
rules/ml/ml_auth_spike_in_failed_logon_events.toml
rules/ml/ml_auth_spike_in_logon_events.toml
rules/ml/ml_auth_spike_in_logon_events_from_a_source_ip.toml

Follow on for PR https://github.com/elastic/detection-rules/pull/1173 and #1317
Set the `min_stack_version` for >= 7.14 rules that haven't been backported yet.
Since the `backport: auto` job isn't yet updated for those PRs, this is manually labeled `backport: skip`

Add min_stack_version to 7.14+ only rules

---

rules/aws/exfiltration_ec2_vm_export_failure.toml
tests/test_all_rules.py

None
Make all rules which require a `Config` in their `note` field match the expected format

Make "config" in note field consistent

---

etc/version.lock.json

None
Switched to the 7.13 branch, locked the versions, then copied the file into `main`.
The lock will be backported via `backport: auto`.

Lock versions for Fleet package 0.13.2

---

.github/workflows/backport.yml
detection_rules/devtools.py
detection_rules/rule_loader.py

Part of #1171
Related to PR #1173, but can be merged independently. 
I added a command that can look at the staging area of Git and move out any changes to rules with incompatible versions.
Here's how I've been testing it. I made a few changes locally that are staged:
```console
$ git status
On branch cli/unstage-incompatible-rules
Your branch is up to date with 'rw-access/cli/unstage-incompatible-rules'.
Changes to be committed:
(use "git restore --staged <file>..." to unstage)
modified:   rules/macos/credential_access_access_to_browser_credentials_procargs.toml
modified:   rules/network/command_and_control_fin7_c2_behavior.toml
renamed:    rules/network/command_and_control_halfbaked_beacon.toml -> rules/network/command_and_control_halfbaked_beacon_renamed.toml
modified: …
```

Add command to unstage incompatible rules from git

---

.github/workflows/backport.yml
.github/workflows/release-kibana.yml
detection_rules/devtools.py

- First half of #1206
Creates a PR to Kibana from a source branch in this repository.
The version labels still aren't very smart. But since this is an on-demand job, each branch actually holds its own definition. Once this PR is backported to the 7.13 branch, we can edit that branch directly to change its defaults, such as the target branch of Kibana and the release labels.
Here's an example PR generated from the 7.13 branch, targeting 7.13.3:
- https://github.com/elastic/kibana/pull/105128
The information says `7.14` in that branch because my 7.13 branch in the fork is actually this `ci/kibana-deploy-job`. I can change that if we want to be more confident that it's working right.

[CI/CD] Create on-demand job to release from Kibana

---

.github/workflows/backport.yml

- Next step (and almost last) for #1171 
Updated the GitHub actions job to use the recent command #1317 to remove incompatible rules when targeting a branch. As a matrix job, there's a separate one will run for each target branch, but we don't have to worry about testing that.
I think we need to think through `etc/version.lock.json`, but can follow up with that in a separate PR. We'll also have to decide that if a rule went through a breaking change, we mark it as immutable in the old branch so that we can't release new versions of it.
The squashed merge commit in main
The selectively cherry-picked commit in 7.13
Squashed merge commit in main
Cherry picked in 7.13

[CI] Update backport job to filter out incompatible rules

---

rules/apm/apm_403_response_to_a_post.toml
rules/apm/apm_405_response_method_not_allowed.toml
rules/apm/apm_null_user_agent.toml
rules/apm/apm_sqlmap_user_agent.toml
rules/promotions/external_alerts.toml
tests/test_all_rules.py

https://github.com/elastic/kibana/pull/105334
https://github.com/elastic/kibana/issues/94702
https://github.com/elastic/kibana/pull/102682
This addresses feedback given in the related Kibana pull request (https://github.com/elastic/kibana/pull/105334) which fixes support for APM data streams in the security solution.

[APM] Adds APM data stream 'traces-apm*' to apm rules (#105334)

---

rules/windows/defense_evasion_file_creation_mult_extension.toml

Part of #1023
Convert the multiple extensions rule to use `regex~`.
This might help performance and generate less expensive Lucene automata. It's possible that if the field is a wildcard field (unlikely) that search performance is worse, but that depends on how regex vs wildcard searches are implemented.

[Rule Tuning] Convert unusual extension rule to regex

---

detection_rules/rule.py

Fix #1305
Dataclass type definition fail. Fixed now and confirmed locally.

Fix metadata.extended

---

etc/version.lock.json

None, just updating the lock for the next release
Here's what I did:
```console
$ python -m detection_rules dev build-release -u
[+] Building package 7.13
- 36 rules excluded from package
Rule changes detected!
Updated version.lock.json file
- 41 changed rules
- 4 new rules
- 0 newly deprecated rules
Package saved to: releases/7.13
- sha256: 8225832f4baced3f8d8611c3b6b04f94c9ffc1652479eb0cea9423119758a4f8
- 558 rules included
$ git checkout 7.14
M	etc/version.lock.json
Switched to branch '7.14'
Your branch is up to date with 'origin/7.14'.
$ python -m detection_rules dev build-release -u
[+] Building package 7.14
- 36 rules excluded from package
Rule changes detected!
Updated version.lock.json file
- 0 changed rules
- 10 new rules
- 0 newly deprecated rules
Package saved to: releases/7.14 …
```

Update the version lock for 7.14.0 and 0.13.3

---

tests/test_all_rules.py

There was a failed 7.13 backport for #1383 because the lock file had a superset of rules.
Disabled a test so the lock file can reference rules that don't exist.
Since we're revisiting the lock file soon, this won't be the long term solution.

Disable missing rule check for the version lock

---

.github/workflows/release-fleet.yml

Fix missing command from #1340
Was accidentally removed in commit https://github.com/elastic/detection-rules/pull/1340/commits/d1350678b76b883a4fad14851490b0b358c6dd03
Fleet jobs weren't publishing because we never cloned detection-rules.
This wasn't tested, but that's nontrivial for GitHub workflows. Should be a straightforward fix 🤞

[CI] Add missing clone for Fleet on-demand job

---

detection_rules/devtools.py
detection_rules/rule_loader.py
detection_rules/utils.py

Possibly a dependency for #1171 
In brainstorming some ways to solve the cross-branch version locking, I realized this method could be helpful. It's not very fast (~20s-30s for a branch) but for some reason multiprocessing doesn't seem to speed it up either.
Might be useful for some other things, so I'll break it off here. Also I fixed some backwards flags for `show_output` while at it.

Add RuleCollection.load_git_branch

---

detection_rules/rule.py

None
Found bug in `ThreatMapping.flatten` method which `updated` items to set rather than `add`ing

[Bug] Flatten method improperly added subtechniques

---

.github/workflows/community.yml

None
Removed event types that would trigger an improper community label (such as labels added by a bot, causing the community tag to not apply)

Remove event triggers from community workflow

---

detection_rules/devtools.py

Dependency for PR #1418 
Make `etc/packages.yml` exempt from the backport.
Tested by making a change to the file, then running
```console
$ python -m detection_rules dev unstage-incompatible-rules --dry-run -t 7.15
Restoring 1 changes from the staging area...
git restore --staged etc/packages.yml
```
Running it without `--dry-run`:
```console
$ python -m detection_rules dev unstage-incompatible-rules -t 7.15          
█▄▄▀ █▄▄  █  █▄▄ █▄▄  █  ▄█▄ █▄█ █ ▀▄█      █ …
```

Skip etc/packages.yml from backport: auto

---

detection_rules/mixins.py
detection_rules/rule.py
etc/api_schemas/master/master.base.json
etc/api_schemas/master/master.eql.json
etc/api_schemas/master/master.machine_learning.json
etc/api_schemas/master/master.query.json
etc/api_schemas/master/master.threat_match.json
etc/api_schemas/master/master.threshold.json

Identified in https://github.com/elastic/detection-rules/pull/1073#discussion_r689026441
Marshmallow dataclass interprets `typing.Any` as `fields.Raw` but `marshmallow_jsonschema` encodes that as a string.
Now we check pre-encoding if it looks like a string and if it does, we encode it properly.
I didn't backport any old schemas, just fixed Python and the `master` schema.

Fix encoding of 'Any' type in jsonschema

---

rules/integrations/azure/initial_access_azure_active_directory_high_risk_signin.toml

There can be a risk_level_during_signin:low but have a risk_level_aggregated:high which is also just as concerning and must be alerted on.
An example is a password spray attack and have a successful login. Which makes me consider a new rule for interesting risk event types
azure.signinlogs.properties.riskEventTypes_v2: unfamiliarFeatures, passwordSpray
This PR is to add additional detection logic to catch other high risk user activity. The current rule does not account for aggregated risk activity such as a password spray attack where the sign in risk is low but the aggregated risk is high.
- Have you followed the [contributor …

[Rule tuning] Azure Active Directory High Risk Sign-in

---

detection_rules/rule.py

resolves #1141 
`RuleTOMLContents.to_dict` method dumps data and metadata directly from those objects in order to serialize with the right schema and avoid ambiguous schema generation from a union field (RuleDataType).
See issue for details

[Bug] RuleTOMLContents.to_dict serialize with proper schema

---

.github/workflows/community.yml

None
Use getMembershipForUser to determine the proper org membership status

[Bug] Community label: use getMembershipForUser

---

.gitignore
detection_rules/misc.py

None
This change will allow the `.detection-rules-cfg` file to be json, toml, or yaml.

Allow CLI config to be multiple formats

---

kql/__init__.py
kql/parser.py
tests/kuery/test_parser.py

None
related to problem identified in #1486 
The parser was not properly converting date field values. This will allow date fields to be used within a query now such as `@timestamp >= "now-30d"`.

[KQL] Add support for date fields in parser

---

rules/cross-platform/threat_intel_module_match.toml

There was the idea to add `@timestamp >= "now-30d"` for all Indicator match rules when we looking for indicators. It should help with the performance of the Indicator match rule.
There are problems with tests because they failed after adding `@timestamp` into the query. It say the `@timestamp` value, not a date.
```
kql.errors.KqlParseError: Error at line:1,column:15
Value doesn't match @timestamp's type: date
@timestamp >= "now-30d" and event.module:threatintel and
```
The problem is located in file - `kql/parser.py` -> `get_literal_type` method
```python
def get_literal_type(literal_value):
if isinstance(literal_value, bool):
return "boolean"
elif isinstance(literal_value, float):
return "float"
elif isinstance(literal_value, int):
return "long"
elif eql.utils.is_string(literal_value): …
```

[Rule Tuning] Add default timestamp condition for threat_query

---

rules/windows/defense_evasion_clearing_windows_security_logs.toml

None
Since elastic agent v7.11, Windows event logs are now collected via the system integration, so this adds the necessary index.

[Rule Tuning] Add system index to Windows Event Logs Cleared

---

rules/windows/impact_volume_shadow_copy_deletion_or_resized_via_vssadmin.toml

Closes #1523
This rule adds volume shadow copy resizing as a technique to hinder ransomware recovery.

[Rule Tuning] Volume Shadow Copy Deletion or Resized via VssAdmin

---

rules/windows/command_and_control_remote_file_copy_scripts.toml
rules/windows/credential_access_kerberoasting_unusual_process.toml
rules/windows/defense_evasion_installutil_beacon.toml
rules/windows/defense_evasion_masquerading_werfault.toml
rules/windows/defense_evasion_msxsl_beacon.toml
rules/windows/lateral_movement_dcom_hta.toml
rules/windows/lateral_movement_dcom_mmc20.toml
rules/windows/lateral_movement_dcom_shellwindow_shellbrowserwindow.toml
rules/windows/lateral_movement_executable_tool_transfer_smb.toml
rules/windows/lateral_movement_incoming_winrm_shell_execution.toml
rules/windows/lateral_movement_incoming_wmi.toml
rules/windows/lateral_movement_powershell_remoting_target.toml
rules/windows/lateral_movement_rdp_sharprdp_target.toml
rules/windows/lateral_movement_remote_services.toml
rules/windows/lateral_movement_scheduled_task_target.toml
rules/windows/privilege_escalation_wpad_exploitation.toml

Starting from 7.16.0, Endpoint will log network.direction with the ingress/egress value, not incoming/outgoing.
This updates the rules that make use of this field to make them compatible with both versions

[Rule Tuning] Update network.direction

---

detection_rules/rule.py
rules/cross-platform/defense_evasion_agent_spoofing_mismatched_id.toml
rules/cross-platform/defense_evasion_agent_spoofing_multiple_hosts.toml
rules/integrations/cyberarkpas/privilege_escalation_cyberarkpas_error_audit_event_promotion.toml
rules/integrations/cyberarkpas/privilege_escalation_cyberarkpas_recommended_events_to_monitor_promotion.toml
rules/linux/defense_evasion_hidden_file_dir_tmp.toml
rules/ml/ml_auth_rare_hour_for_a_user_to_logon.toml
rules/ml/ml_auth_rare_source_ip_for_a_user.toml
rules/ml/ml_auth_rare_user_logon.toml
rules/ml/ml_auth_spike_in_failed_logon_events.toml
rules/ml/ml_auth_spike_in_logon_events.toml
rules/ml/ml_auth_spike_in_logon_events_from_a_source_ip.toml
rules/windows/credential_access_cmdline_dump_tool.toml
rules/windows/defense_evasion_file_creation_mult_extension.toml
rules/windows/execution_suspicious_powershell_imgload.toml
rules/windows/persistence_evasion_registry_ifeo_injection.toml
tests/test_all_rules.py

None
Adds `min_stack_comments` to the metadata schema and adds unit tests which require this field whenever `min_stack_version` is defined.
I also added comments to the existing 15 rules with a min stack version defined.
<details>
<summary>Example error</summary><br>
```
AssertionError: The following (2) rules have a `min_stack_version` defined but missing comments:
b9666521-4742-49ce-9ddc-b8e84c35acae - Creation of Hidden Files and Directories -> missing `extended.min_stack_comments`. min_stack_version: 7.12.0
745b0119-0560-43ba-860a-7235dd8cee8d - Unusual Hour for a User to Logon -> missing `extended.min_stack_comments`. min_stack_version: 7.14.0
```
</details>

Add min_stack_comments to metadata schema

---

detection_rules/cli_utils.py
detection_rules/main.py

resolves #1594 
This will prevent `index` from being stripped when running the `import-rules` command

Preserve index on import-rules command

---

etc/version.lock.json

None
related to #1613 
Bumps the min_stack_version within the version.lock for 2 specific rules which were targeted for 7.15+
Should merge _after_ #1613

Bump min_stack_version in version.lock for specific rules

---

detection_rules/version_lock.py

None
Issue found when locking versions. The function was not being properly called, leading to `null` values

[bug] Current stack version in deprecation lock missing parens

---

rules/windows/defense_evasion_whitespace_padding_in_command_line.toml

As the first of a two-part fix to #1641, we will limit the index that this rule runs on versions prior to 7.16 to logs-endpoint.events

[Rule Tuning] Whitespace Padding in Process Command Line - Limit Indexes

---

rules/network/command_and_control_download_rar_powershell_from_internet.toml

Resolves #1471 
Switch the query language from Lucene to KQL to solve "Can only use regexp queries on keyword and text fields - not on [destination.ip] which is of type [ip]" bug

[Rule Tuning] Switch "Roshal Archive (RAR) or PowerShell File Downloaded from the Internet" to use KQL

---

rules/windows/defense_evasion_whitespace_padding_in_command_line.toml

Resolves #1641 
Add the `min_stack_version` to the rule in order to add back indexes that have wildcard fields in 7.16+ stacks, which are not affected by https://github.com/elastic/elasticsearch/issues/78391

[Rule Tuning] Whitespace Padding in Process Command Line - Re-add index and add min_stack_version

---

etc/version.lock.json
rules/cross-platform/execution_suspicious_jar_child_process.toml

Expand rule coverage by removing the process.args containing a jar file requirement which may help detect also exploitation attempt via command injection vulnerabilities on server apps running JAVA (e.g. JDBC-Attack).

[Rule Tuning] Suspicious JAR Child Process

---

rules/promotions/endgame_adversary_behavior_detected.toml
rules/promotions/endgame_cred_dumping_detected.toml
rules/promotions/endgame_cred_dumping_prevented.toml
rules/promotions/endgame_cred_manipulation_detected.toml
rules/promotions/endgame_cred_manipulation_prevented.toml
rules/promotions/endgame_exploit_detected.toml
rules/promotions/endgame_exploit_prevented.toml
rules/promotions/endgame_malware_detected.toml
rules/promotions/endgame_malware_prevented.toml
rules/promotions/endgame_permission_theft_detected.toml
rules/promotions/endgame_permission_theft_prevented.toml
rules/promotions/endgame_process_injection_detected.toml
rules/promotions/endgame_process_injection_prevented.toml
rules/promotions/endgame_ransomware_detected.toml
rules/promotions/endgame_ransomware_prevented.toml

sdh-security-team # 264
Update/Add the max_signals field on Endgame Promotion rules to 10000, so the circuit break do not affect the alerts coming from Endgame.

[Rule Tuning] Bump max_signals on Endgame Promotion Rules

---

rules/integrations/o365/credential_access_user_excessive_sso_logon_errors.toml

The original rule had the event.category as "web" the correct value is "authentication".

[Rule Tuning] O365 Excessive Single Sign-On Logon Errors

---

detection_rules/rule.py
detection_rules/schemas/definitions.py

resolves #1668 
Adds a pattern for `Rule.name`.
This will prevent leading and trailing whitespace (among other undesirables for rule names)

Add pattern for "name" in rule schema

---

rules/_deprecated/threat_intel_filebeat7x.toml

resolves #1697 
This deprecates this rule, which is compatible with 7.x only.
This should only deprecate as of 8.0 and should not be backported beyond that

[Deprecate Rule] Threat Intel Filebeat Module (v7.x) Indicator Match

---

.github/workflows/backport.yml
etc/packages.yml

None
backports fail due to yaml parsing from the matrix for `8.0` being converted to `8`

fix bug in yaml parsing for github workflows

---

rules/linux/execution_python_tty_shell.toml

related to #1730 
Rolls back changes to rule due to a bug (8.0) where existing rules change rule `type`. We can explore adding these changes back in after a fix is implemented.
If the change is needed urgently before that, we can deprecate this rule and create a new one with the changes

Revert "[Rule Tuning] Interactive Terminal Spawned via Python - Python3 and bypasses fix"

---

rules/integrations/o365/persistence_exchange_suspicious_mailbox_right_delegation.toml

Exclude the "NT AUTHORITY\SYSTEM (Microsoft.Exchange.Servicehost)" user.id. The rule is triggered by a legitimate task executed by this account, that is related to eDiscovery.
More information can be found here: https://community.spiceworks.com/topic/2233033-high-severity-alert-nt-authority-system

[Rule Tuning] O365 Exchange Suspicious Mailbox Right Delegation

---

detection_rules/rule.py
detection_rules/rule_loader.py

Fixes bug found in #1743 
```
f"Rule ID {rule.id} for {rule.name} collides with rule {id_map.get(rule.id).get('name')}"
AttributeError: 'TOMLRule' object has no attribute 'get'
```

[Bug] Fix AttributeError in RuleCollection dupe check

---

etc/non-ecs-schema.json
rules/windows/persistence_ad_adminsdholder.toml

Resolves #1744 
Detects modifications in the AdminSDHolder object. Attackers can abuse the SDProp process to implement a persistent
backdoor in the Active Directory. SDProp compares the permissions on protected objects with those defined on the
AdminSDHolder object. If the permissions on any of the protected accounts and groups do not match, the permissions on
the protected accounts and groups are reset to match those of the domain's AdminSDHolder object, regaining their
Administrative Privileges.

[New Rule] AdminSDHolder Backdoor

---

rules/windows/defense_evasion_disable_posh_scriptblocklogging.toml

Resolves #1748 
Identifies the disable of PowerShell Script Block Logging. Attackers can disable the logging of PowerShell Scripts to
conceal their activities in the host.
The rule works for both sysmon and Elastic Endpoint Security

[New Rule] PowerShell Script Block Logging Disabled

---

rules/windows/credential_access_shadow_credentials.toml

Resolves #1728 
Identify the modification of the msDS-KeyCredentialLink attribute in a Active Directory Computer or User Object.
Attackers can abuse contol over the object and create a key pair, append to raw public key in the attribute, and obtain
persistent and stealthy access to the target object (can be a user or a computer).

[New Rule] Potential Shadow Credentials added to AD Object

---

rules/windows/discovery_net_command_system_account.toml

Related to https://github.com/elastic/sdh-security-team/issues/300
Changes the rule logic to use `winlog.event_data.IntegrityLevel` and `process.Ext.token.integrity_level_name` instead of `user.id`, as the field is always populated with `S-1-5-18`, even on regular user processes with Low/Medium/High integrity.

[Rule Tuning] Net command via SYSTEM account

---

rules/windows/command_and_control_port_forwarding_added_registry.toml
rules/windows/defense_evasion_defender_disabled_via_registry.toml
rules/windows/defense_evasion_hide_encoded_executable_registry.toml
rules/windows/defense_evasion_microsoft_defender_tampering.toml
rules/windows/defense_evasion_scheduledjobs_at_protocol_enabled.toml
rules/windows/defense_evasion_sip_provider_mod.toml
rules/windows/defense_evasion_solarwinds_backdoor_service_disabled_via_registry.toml
rules/windows/lateral_movement_defense_evasion_lanman_nullsessionpipe_modification.toml
rules/windows/lateral_movement_rdp_enabled_registry.toml
rules/windows/lateral_movement_rdp_sharprdp_target.toml
rules/windows/persistence_appcertdlls_registry.toml
rules/windows/persistence_evasion_registry_ifeo_injection.toml
rules/windows/persistence_evasion_registry_startup_shell_folder_modified.toml
rules/windows/persistence_registry_uncommon.toml
rules/windows/persistence_run_key_and_startup_broad.toml
rules/windows/persistence_services_registry.toml
rules/windows/persistence_suspicious_com_hijack_registry.toml
rules/windows/persistence_suspicious_service_created_registry.toml
rules/windows/persistence_time_provider_mod.toml
rules/windows/persistence_via_hidden_run_key_valuename.toml
rules/windows/persistence_via_lsa_security_support_provider_registry.toml
rules/windows/persistence_via_wmi_stdregprov_run_services.toml
rules/windows/privilege_escalation_disable_uac_registry.toml
rules/windows/privilege_escalation_port_monitor_print_pocessor_abuse.toml
rules/windows/privilege_escalation_printspooler_malicious_registry_modification.toml
rules/windows/privilege_escalation_printspooler_registry_copyfiles.toml
rules/windows/privilege_escalation_rogue_windir_environment_var.toml

Resolves #1766
Resolves #1761 
Changes:
* Drops support for sysmon in registry-based rules that look for values other than QWORD & DWORD (Integration Issue, will update once the issue is open)
* Add HKU version of HKEY_USER keys in supported rules
* Fix minor syntax errors and lack of wildcards to be compatible with both sysmon and endpoint

[Rule Tuning] Sysmon Registry-based Rules Review & Fixes

---

rules/windows/execution_register_server_program_connecting_to_the_internet.toml
rules/windows/persistence_local_scheduled_task_creation.toml
rules/windows/privilege_escalation_installertakeover.toml
rules/windows/privilege_escalation_unusual_printspooler_childprocess.toml

Related to #1770 
Replace the usage of user.id (checking if the process is run by SYSTEM) for integrity level fields (process.Ext.token.integrity_level_name & winlog.event_data.IntegrityLevel)

[Rule Tuning] Sysmon Compatibility - Replace user.id for Integrity fields

---

rules/windows/command_and_control_iexplore_via_com.toml

Related to #1770 
Modifies the sequence to use user.name instead of user.id to not cause FPs.

[Rule Tuning] Potential Command and Control via Internet Explorer

---

rules/integrations/azure/persistence_azure_conditional_access_policy_modified.toml

Updates the query to use a more specific `event.action`, so we don't get FPs coming from policy updates in other azure resources

[Rule Tuning] Azure Conditional Access Policy Modified

---

rules/windows/collection_posh_audio_capture.toml
rules/windows/collection_posh_keylogger.toml
rules/windows/collection_posh_screen_grabber.toml
rules/windows/defense_evasion_posh_compressed.toml
rules/windows/execution_posh_psreflect.toml

Update PowerShell queries to avoid partial matches (which are causing FPs) due to field type change (wildcard)

[Rule Tuning] Update PowerShell script_block queries to avoid partial matches

---

.github/workflows/pythonpackage.yml
Makefile
detection_rules/devtools.py
detection_rules/packaging.py

None
The builds are taking longer after merging #1787 due to the extra time spent archiving all of the navigator files. This updates it to only generate those files on pushes to main.

[Github Workflows] Only generate navigator files on push to main

---

rules/linux/defense_evasion_expect_binary.toml

https://github.com/elastic/detection-rules/issues/1816
expect, a common IOC, the Unix binary can be abused to breakout out of restricted shells or environments by spawning an interactive system shell. This activity is not standard use with this binary for a user or system administrator. It indicates a potentially malicious actor attempting to improve the capabilities or stability of their access.

expect shell evasion threat

---

rules/linux/defense_evasion_mysql_binary.toml

https://github.com/elastic/detection-rules/issues/1818
MySQL, an IOC, the Unix binary can be abused to breakout out of restricted shells or environments by spawning an interactive system shell. This activity is not standard use with this binary for a user or system administrator. It indicates a potentially malicious actor attempting to improve the capabilities or stability of their access.

mysql shell evasion threat

---

rules/linux/defense_evasion_gcc_binary.toml

https://github.com/elastic/detection-rules/issues/1821
gcc, an IOC, the Unix binary can be abused to breakout out of restricted shells or environments by spawning an interactive system shell. This activity is not standard use with this binary for a user or system administrator. It indicates a potentially malicious actor attempting to improve the capabilities or stability of their access.

gcc shell evasion threat

---

rules/windows/defense_evasion_posh_process_injection.toml

Adds GetDelegateForFunctionPointer function to second part of the query, making this detection efficient to detect some kinds of powershell loaders, examples:
* https://www.virustotal.com/gui/file/df38ec7ba3b397d66296fabd731e1f594df5afbdeda166fa6f499c0ae221ebb9
* https://www.virustotal.com/gui/file/2821056c9092ad3f2b4f273449353773204b7f2f23e0e6b39c2d20884eba8533

[Rule Tuning] Potential Process Injection via PowerShell

---

rules/_deprecated/privilege_escalation_printspooler_malicious_driver_file_changes.toml
rules/_deprecated/privilege_escalation_printspooler_malicious_registry_modification.toml

This PR deprecates two rules related to PrintNightmare, which are not effective anymore because they look for certain DLL names, which is a variable that the attacker controls.
After discussing with Samir possible tunings, we concluded that adding other DLL names to these rules will not make them stronger.
Rules Deprecated:
- Potential PrintNightmare File Modification
- Potential PrintNightmare Exploit Registry Modification

[Rule Deprecation] Deprecate PrintNightmare Rules

---

detection_rules/rule_validators.py
kql/kql2eql.py
rules/linux/execution_crash_binary.toml
tests/kuery/test_kql2eql.py
tests/test_schemas.py

Resolves #1554 
Adds test cases to ensure `text` fields fail on eql schema validation and conversion from kql to eql.

1554 update eql schemas to fail validation on text fields

---

rules/linux/execution_vi_binary.toml

https://github.com/elastic/detection-rules/issues/1864
An existing threat identification already exists for vi binary. This issue adds the identification for vim.

vim shell evasion threat

---

rules/linux/execution_flock_binary.toml

#1862 
flock an IOC, the Unix binary can be abused to breakout out of restricted shells or environments by spawning an interactive system shell. This activity is not standard use with this binary for a user or system administrator. It indicates a potentially malicious actor attempting to improve the capabilities or stability of their access.

flock shell evasion threat

---

detection_rules/version_lock.py

None
Noticed this didn't cause an expected failure when reviewing another [PR](https://github.com/elastic/detection-rules/pull/1878/files#r834809710), and found a small bug where the wrong lock was referenced

[Bug] Fix bug in version_lock.py

---

etc/version.lock.json

None
related to #1855
In #1855 the rule type was added to all entries in the version.lock file, however, deprecated rules were overlooked. This is causing failures in backports to older branches.
This adds the type to those rules

[Bug] Add type to deprecated rules in version.lock

---

rules/macos/discovery_users_domain_built_in_commands.toml

Jamf Connect uses ldapsearch to synchronize user passwords. This rule generates tons of false positives when Jamf Connect is deployed.

Add Jamf Connect exception for macOS users enumeration rule

---

rules/linux/execution_apt_binary.toml
rules/linux/execution_awk_binary_shell.toml
rules/linux/execution_busybox_binary.toml
rules/linux/execution_c89_c99_binary.toml
rules/linux/execution_cpulimit_binary.toml
rules/linux/execution_crash_binary.toml
rules/linux/execution_expect_binary.toml
rules/linux/execution_find_binary.toml
rules/linux/execution_gcc_binary.toml
rules/linux/execution_mysql_binary.toml
rules/linux/execution_nice_binary.toml
rules/linux/execution_perl_tty_shell.toml
rules/linux/execution_python_tty_shell.toml
rules/linux/execution_ssh_binary.toml
rules/linux/execution_vi_binary.toml

Tuning these shell evasion rules to increase accuracy and performance by taking multi match selections from ":" to "in", taking single match selection from ":" to "==" and by removing sequencing where possible and using entity_id to sequence where necessary. Each of these rules has been tested and validated to ensure they work as expected.

Linux Shell Evasion Rule Tuning

---

detection_rules/schemas/definitions.py

Solves #1904 
Defined timeline template dictionary needs updated to include comprehensive templates.
[template_details.txt](https://github.com/elastic/detection-rules/files/8391593/template_details.txt)

[Bug] Updating defined timeline templates in definitions.py 

---

rules/windows/discovery_net_command_system_account.toml
rules/windows/execution_register_server_program_connecting_to_the_internet.toml
rules/windows/persistence_local_scheduled_task_creation.toml
rules/windows/privilege_escalation_installertakeover.toml
rules/windows/privilege_escalation_unusual_printspooler_childprocess.toml

Related to https://github.com/elastic/sdh-security-team/issues/339
Adds EQL Optional field syntax to rules that use specific fields across different data sources, which was causing schema errors.

[Rule Tuning] Add EQL optional field syntax

---

rules/integrations/aws/impact_rds_instance_cluster_deletion.toml

Related to https://github.com/elastic/detection-rules/issues/1873 
I've added to this rule to improve our coverage. Currently we detect the creation and stopping of both AWS RDS clusters and instances. But we only detect for the deletion of clusters, not instances. This adds the deletion of RDS instances to the detection.

[Rule Tuning] AWS RDS Instance/Cluster Deletion

---

rules/windows/discovery_net_command_system_account.toml

https://github.com/elastic/sdh-security-team/issues/343
Renames and tunes the logic of the "Net command via SYSTEM account" rule to avoid FPs.

[Rule Tuning] Account Discovery Command via SYSTEM Account

---

detection_rules/misc.py

related to #1911 
With the update to elasticsearch module, the `use_ssl` parameter was removed. [REF](https://github.com/elastic/elasticsearch-py/blob/d013e8863667341792c2187cb1b7c677b1fd7862/elasticsearch/_sync/client/utils.py#L187)

Remove deprecated elasticsearch parameter

---

rules/cross-platform/impact_hosts_file_modified.toml
rules/windows/credential_access_lsass_memdump_file_created.toml
rules/windows/defense_evasion_adding_the_hidden_file_attribute_with_via_attribexe.toml
rules/windows/defense_evasion_execution_lolbas_wuauclt.toml
rules/windows/defense_evasion_suspicious_certutil_commands.toml
rules/windows/execution_command_shell_started_by_svchost.toml

Resolves #1924 
Add config note for expanding timestamp overrides to backport 7.13-8.0.

[Rule Tuning] Add timestamp_override config note to 8.1 rules

---

rules/windows/credential_access_disable_kerberos_preauth.toml
rules/windows/credential_access_seenabledelegationprivilege_assigned_to_user.toml
rules/windows/credential_access_shadow_credentials.toml
rules/windows/defense_evasion_clearing_windows_security_logs.toml
rules/windows/discovery_privileged_localgroup_membership.toml
rules/windows/persistence_ad_adminsdholder.toml
rules/windows/persistence_msds_alloweddelegateto_krbtgt.toml
rules/windows/persistence_remote_password_reset.toml
rules/windows/persistence_user_account_added_to_privileged_group_ad.toml
rules/windows/persistence_user_account_creation_event_logs.toml
rules/windows/privilege_escalation_samaccountname_spoofing_attack.toml

Remove the `logs-windows.*` index from rules that uses security, application or system logs.
> Note that for 7.11, security, application and system logs have been moved to the system package.
https://github.com/elastic/integrations/tree/main/packages/windows

[Rule Tuning] Remove `logs-windows.*` index

---

detection_rules/etc/version.lock.json

part of #1949 
Building a rules package from any branch other than main creates a bug for any forked rules. This is because it senses forward changes (which are already accounted for in the `versions.lock`) as _new_ changes, and adds an unnecessary bump.
This change reconciles changes made to the integrations OOB release package (elastic/integrations/pull/3238).

Manually reconciled versions from forked rule package generation bug

---

detection_rules/devtools.py
detection_rules/etc/version.lock.json
detection_rules/mixins.py
tests/test_gh_workflows.py
tests/test_version_locking.py

related to #2001 
In #2001, we trimmed the backport matrix up from 7.13 to 7.16. This included the code to manage version lock changes. This created a situation where rules with previous entries which previously existed that were lower than the _new_ min version (now `7.16`) would fail this [assertion](https://github.com/elastic/detection-rules/blob/35b1a69ff5ad7755e210c644a4b910e04ce31f14/detection_rules/version_lock.py#L267-L271) in the lock code.
This changes a few things:
* adds a test to validate that no previous entries exist, which are lower than the min version supported
* adds a command to conveniently trim and collapse old versions
* trims and collapse the version lock (all occurences <= 7.16 were single entry 7.13, which resulted in bumps only)

Collapse unsupported previous version entries

---

rules/windows/discovery_whoami_command_activity.toml

https://github.com/elastic/sdh-security-team/issues/398
Including the `logs-system.*` index pattern to the rule, as the process creation logs are enough to trigger it

[Rule Tuning] Whoami Process Activity - Support Event 4688

---

rules/windows/persistence_sdprop_exclusion_dsheuristics.toml

https://github.com/elastic/sdh-security-team/issues/395
Adds a filter to look for modifications *only* in the dSHeuristics ad object, instead of any, which is causing FPs.

[Rule Tuning] AdminSDHolder SDProp Exclusion Added

---

detection_rules/etc/version.lock.json
detection_rules/main.py
detection_rules/misc.py
detection_rules/packaging.py
detection_rules/rule.py
detection_rules/schemas/__init__.py
detection_rules/schemas/definitions.py
detection_rules/version_lock.py
tests/test_schemas.py
tests/test_version_locking.py

resolves #1949 
related to #2018
Resolves bug in `Rule` version code.
Support for rules with breaking changes ("forked" or diverged rules) was added in #1434. However, on line
https://github.com/rw-access/detection-rules/blob/5f241de792ba432f4d42905c1a1ba388840be559/detection_rules/rule.py#L411 
and 
https://github.com/rw-access/detection-rules/blob/5f241de792ba432f4d42905c1a1ba388840be559/detection_rules/rule.py#L421
calls to `get_locked_version` pass the `self.metadata.min_stack_version`, which in cases where this is implicitly passed (essentially the "floor" or minimum possible version) the value is `None`. This results in [get_locked_versions](https://github.com/rw-access/detection-rules/blob/5f241de792ba432f4d42905c1a1ba388840be559/detection_rules/version_lock.py#L28-L34) skipping …

[Bug] resolves bug in Rule version methods

---

detection_rules/mixins.py
detection_rules/rule.py
detection_rules/schemas/__init__.py
detection_rules/schemas/stack_compat.py
tests/test_all_rules.py

resolves #2048 
part of #2049
This adds support for rule schema fields with minimum and maximum compatibility with Kibana versions. This also adds a test to ensure that a rule which will backport to older versions does not get backported to branches prior to when the field became valid.
This also added the following new restricted fields to the schema:
- `setup`
- `related_integrations`
- `required_fields`
A field can now add: 
`required_fields: Optional[List[str]] = field(metadata=dict(metadata=dict(min_compat="8.3")))`
`old_field: Optional[List[str]] = field(metadata=dict(metadata=dict(max_compat="8.2")))`
`old_field: Optional[List[str]] = field(metadata=dict(metadata=dict(max_compat="8.2", min_compat="7.14")))`

Add support for restricted fields

---

rules/windows/discovery_privileged_localgroup_membership.toml

Resolves #2024 
Adds `WaAppAgent.exe` as an exception.
Description from [Msdocs](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/windows-azure-guest-agent):
> RD Agent Service: This service is responsible for the Installation of Guest Agent. Transparent Installer is also a component of Rd Agent that helps to upgrade other components and services of Guest Agent. RD Agent is also responsible for sending heartbeats from Guest VM to Host Agent on the physical server.

[Rule Tuning] Enumeration of Privileged Local Groups Membership

---

docs/experimental-machine-learning/user-risk-score.md

Addresses the following doc bugs reported by QA source team for the user risk score readme file: 
- https://github.com/elastic/security-docs/issues/2169
- https://github.com/elastic/security-docs/issues/2167

[DOCS] Updating user risk score readme

---

detection_rules/rule.py
detection_rules/rule_validators.py

Resolves #2056 
- Add `unique_fields` in the post build
- Adds the new rule field `required_fields` to the rule post build.
- Sets the value to None as a default.

Add new `required_fields` as a build-time restricted field

---

rules/cross-platform/execution_revershell_via_shell_cmd.toml

* https://github.com/elastic/detection-rules/issues/2076
@aarju suggested we take a look at this rule for additional tuning as it is generating a number of false-positives within their environment due to scripts accessing container systems.
We have discovered a large amount of false-positives from endpoint behavior rules and will be investigating detection rule telemetry as well. We have ~1,002 detections within the last 90 days. Removing `/dev/tcp/127.0.0.1` and `/dev/udp/127.0.0.1` removes ~97% of false-positives for this activity.

[Rule Tuning] Potential Reverse Shell Activity via Terminal

---

rules/linux/persistence_insmod_kernel_module_load.toml

https://github.com/elastic/detection-rules/issues/2080
This rule will detect the use of the insmod binary to load a Linux kernel object file. Threat actors can use this binary, given they have root privileges, to load a rootkit on a system providing them with complete control and the ability to hide from security products.

[New Rule] Insmod kernel module load

---

rules/linux/persistence_dynamic_linker_backup.toml

https://github.com/elastic/detection-rules/issues/2081
This rule will detect the copying of the Linux dynamic loader binary for the purpose of creating a backup copy. This technique was seen recently being utilized by advanced Linux malware prior to patching the dynamic loader in order to inject and preload a malicious shared object file. This activity should never occur and if it does then it should be considered suspicious or possibly malicious.

[New Rule] Dynamic Linker Copy

---

rules/integrations/gcp/defense_evasion_gcp_firewall_rule_created.toml
rules/integrations/gcp/defense_evasion_gcp_firewall_rule_deleted.toml
rules/integrations/gcp/defense_evasion_gcp_firewall_rule_modified.toml

* https://github.com/elastic/detection-rules/issues/2106
GCP Firewall rules are only for VPC and do not include App Engine. `event.action` values specifying firewall rule activity should be included.
*Checklist*
- Adjust dates
- Adjust verbiage that is VPC only to include App Engine as well
- Update references
- Adjust query to include App Engine values for `event.action` as well as replace any `v*` reference to `*`.
Rule Created
Rule Updated
Rule Deleted

[Rule Tuning] GCP Firewall Rules Should Include App Engine

---

rules/linux/defense_evasion_hidden_file_dir_tmp.toml
rules/linux/defense_evasion_hidden_shared_object.toml

https://github.com/elastic/detection-rules/issues/2085
This rule will detect the creation of a hidden shared object file. Threat actors will commonly drop and hide malicious shared object files which they can then load into an existing and benign system binary in order to hijack system calls and remain hidden.

[New Rule] Hidden so file

---

rules/linux/defense_evasion_chattr_immutable_file.toml

https://github.com/elastic/detection-rules/issues/2090
Detects a file being made immutable using the chattr binary. Making a file immutable means it cannot be deleted or renamed, no link can be created to this file, most of the file's metadata can not be modified, and the file can not be opened in write mode. Threat actors will commonly utilize this to prevent tampering or modification of their malicious files or any system files they have modified for purposes of persistence (e.g .ssh, /etc/passwd, etc.).

[New Rule] File made Immutable by Chattr

---

rules/_deprecated/defense_evasion_attempt_to_disable_iptables_or_firewall.toml
rules/_deprecated/execution_linux_process_started_in_temp_directory.toml
rules/_deprecated/initial_access_login_failures.toml
rules/_deprecated/initial_access_login_location.toml
rules/_deprecated/initial_access_login_sessions.toml
rules/_deprecated/initial_access_login_time.toml

#2162 
As part of the Linux Detection Rule Review, the above rules have been identified for deprecation. The detailed reason for deprecation can be found in the review sheet [Linux Detection Rules Review](https://docs.google.com/spreadsheets/d/1oA7vlsqTzm6pg6A6LPNhx6uzV-ClFlD3hP9qSVwu0O4/edit?usp=sharing)
Meta Issue: https://github.com/elastic/security-team/issues/4094

Rule(s) deprecation as part of Linux Detection Rule Review

---

rules/macos/execution_installer_package_spawned_network_event.toml

https://github.com/elastic/detection-rules/issues/2189
This rule logic is flawed. I spent yesterday afternoon executing every installer package payload [Mystikal](https://github.com/D00MFist/Mystikal) has to offer along with various other malicious [packages](https://redcanary.com/blog/clipping-silver-sparrows-wings/) and this rule did not fire once. The problem with the rule is in the way the process tree spawns with installer packages preventing sequencing on process.entity_id as the child processes spawned from installer or package_script_service are not linked directly by process id and therefore cannot be connected together via the process.entity_id. This will prevent the rule from ever firing.

[Rule Tuning] MacOS Installer Package Net Event

---

rules/linux/impact_process_kill_threshold.toml

#endpoint-rules/issues/1242
Rule(s) to identify potential mining activities. The individual rule can highlight suspicious activities leading to potential mining. The rule individually also governs the basic Linux defense controls tampering. 
Detonate Scripts mentioned in the Issue are used to test the rules

Rule(s) to identify potential mining activities

---

rules/windows/credential_access_remote_sam_secretsdump.toml

Excluding some noisy FPs by file.path (user and machine hives std paths) and event.action (scoped to logged-in)

[Rule Tuning] Potential Remote Credential Access via Registry

---

rules/windows/lateral_movement_remote_services.toml

excluding noisy FPs by process.executable to be compatible with winlog and endpoint.

[Rule Tuning] Remotely Started Services via RPC

---

rules/windows/defense_evasion_suspicious_process_creation_calltrace.toml

Excluding some FPs by process.parent.executable and process.parent.args.

[Rule Tuning] Suspicious Process Creation CallTrace

---

rules/macos/persistence_folder_action_scripts_runtime.toml

Resolves #2173 
- Exclude FPs for fig-iterm-integration.scpt

[Rule Tuning] Persistence via Folder Action Script

---

detection_rules/rule.py

Continuation of https://github.com/elastic/detection-rules/pull/2060
Branch status checks are failing due to a missing indent in related integrations causing the new field to be added to all rule stack versions.
- Only add related integration if it's on the correct stack.

[Bug] related_integration added to all rule versions

---

requirements.txt

https://github.com/elastic/detection-rules/runs/7886816704?check_suite_focus=true
A recent minor update in `typing-inspect==0.7.1` causes dataclass conversions to fail due to typing. This locks in the version to 0.7.1

[Bug] Set typing-inspect requirement to 0.7.1

---

detection_rules/eswrap.py

Resolves #2292 
- Checks the list of events for matches instead of only checking the root object.
Should complete with no errors. See the original issue for the error that existed.
```bash
(detection_dev) ➜  detection-rules git:(2292-bug-keyerror-on-rule-survey-hits) ✗ python -m detection_rules dev test rule-survey -d now-10s now
Loaded config file: /Users/stryker/workspace/Elastic/detection-rules/.detection-rules-cfg.json
Running survey against 684 rules
Saving detailed dump to: /Users/stryker/workspace/Elastic/detection-rules/surveys/20220912T154106L.json
(detection_dev) ➜  detection-rules …
```

[Bug] Keyerror on rule-survey hits

---

detection_rules/version_lock.py

* https://github.com/elastic/detection-rules/pull/2272
Adjusted route C to update the dictionary for the `lock_from_file` variable as `max_allowable_version` was overwritten and therefore did not exist in the output.
Testing:
1. Check out 8.2
2. Update `command_and_control_telnet_port_activity.toml` in rule contents
3. Run `python -m detection_rules dev build-release --update-version-lock`
4. Check diff for `version.lock.json` file and notice `max_allowable_version` is missing
Bug Screenshot:
Solution Screenshot:

[Bug] Adding Adjustment to Route C of manage_versions.py

---

rules/integrations/kubernetes/discovery_denied_service_account_request.toml
rules/integrations/kubernetes/initial_access_anonymous_request_authorized.toml
rules/integrations/kubernetes/privilege_escalation_suspicious_assignment_of_controller_service_account.toml

https://github.com/elastic/detection-rules/issues/2309 
- https://github.com/elastic/detection-rules/blob/main/rules/integrations/kubernetes/discovery_denied_service_account_request.toml 
- https://github.com/elastic/detection-rules/blob/main/rules/integrations/kubernetes/initial_access_anonymous_request_authorized.toml 
- https://github.com/elastic/detection-rules/blob/main/rules/integrations/kubernetes/privilege_escalation_suspicious_assignment_of_controller_service_account.toml
min_stack change to 8.4 with new required fields added to Kubernetes Integration

[Rule Tuning] Kubernetes - update min_stack for new rules

---

.github/workflows/backport.yml

#2310
#1991
When PRs are started in `draft`, then converted to `ready for review`, the `backport: auto` label is not added to drafts and has to be manually added after.  Even worst, GitHub doesn't reflect PR state changes between draft, so you can not go back and look at an issue to tell that it was started as a Draft PR.
This PR adds the `ready_for_review` [activity type](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) which will add the `backport: auto`.

[Bug] Add ready_for_review to backport activity types

---

detection_rules/etc/non-ecs-schema.json
rules/integrations/kubernetes/discovery_suspicious_self_subject_review.toml
rules/integrations/kubernetes/execution_user_exec_to_pod.toml
rules/integrations/kubernetes/initial_access_anonymous_request_authorized.toml
rules/integrations/kubernetes/persistence_exposed_service_created_with_type_nodeport.toml
rules/integrations/kubernetes/privilege_escalation_pod_created_with_hostipc.toml
rules/integrations/kubernetes/privilege_escalation_pod_created_with_hostnetwork.toml
rules/integrations/kubernetes/privilege_escalation_pod_created_with_hostpid.toml
rules/integrations/kubernetes/privilege_escalation_pod_created_with_sensitive_hostpath_volume.toml
rules/integrations/kubernetes/privilege_escalation_privileged_pod_created.toml
rules/integrations/kubernetes/privilege_escalation_suspicious_assignment_of_controller_service_account.toml

K8s Rule Changes
https://github.com/elastic/detection-rules/issues/2336
Several Rule Tuning Opportunities across all K8s Rules. Primarily using new fields to filter for "allowed" activity and to exclude the elastic-agent container image which must run with privileged configurations.
Rule | Changes | 
:---: | :---: | 
https://github.com/elastic/detection-rules/blob/main/rules/integrations/kubernetes/discovery_denied_service_account_request.toml | n/a |
https://github.com/elastic/detection-rules/blob/main/rules/integrations/kubernetes/discovery_suspicious_self_subject_review.toml | min_stack : 8.4 for K8s Integration Fields, Update Date, Query adds : event.dataset + decision : allowed | 
https://github.com/elastic/detection-rules/blob/main/rules/integrations/kubernetes/execution_user_exec_to …

Kubernetes Rule Tunings for "allowed" activity

---

rules/windows/defense_evasion_potential_processherpaderping.toml

The [Potential Process Herpaderping Attempt](https://github.com/elastic/detection-rules/blob/main/rules/windows/defense_evasion_potential_processherpaderping.toml) Windows rule needs tuned to exclude false-positives generated from the Elastic Agent and Trend Micro agent during updates.
The following paths have been added to `not process.parent.executable`:
- `?:\\Program Files\\Elastic\\Agent\\data\\*.exe`
- `?:\\Program Files (x86)\\Trend Micro\\*.exe`

[Rule Tuning] Exclude Elastic Agent from "Potential Process Herpaderping Attempt"

---

rules/integrations/kubernetes/privilege_escalation_pod_created_with_hostipc.toml
rules/integrations/kubernetes/privilege_escalation_pod_created_with_hostnetwork.toml
rules/integrations/kubernetes/privilege_escalation_pod_created_with_hostpid.toml
rules/integrations/kubernetes/privilege_escalation_pod_created_with_sensitive_hostpath_volume.toml
rules/integrations/kubernetes/privilege_escalation_privileged_pod_created.toml

https://github.com/elastic/detection-rules/issues/2338
This adds the following attacker threat and technique to each of these 5 rules.
``` 
[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1610"
name = "Deploy Container"
reference = "https://attack.mitre.org/techniques/T1610/"
[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
```

 [Rule Tuning] Kubernetes Rules- Add MITRE technique "Deploy Container"

---

detection_rules/main.py

Resolves #2376 
Converts the config to a `pathlib.Path` obj as the default `click.Path` obj defaults to a `str` per the [docs](https://click.palletsprojects.com/en/8.1.x/api/?highlight=click%20path#click.Path)

[Bug] Convert config to pathlib.Path

---

rules/linux/execution_reverse_shell_via_named_pipe.toml

* https://github.com/elastic/detection-rules/pull/2395
Identifies a reverse shell via the abuse of named pipes on Linux with the help of OpenSSL or Netcat. First in, first out
(FIFO) files are special files for reading and writing to by Linux processes. For this to work, a named pipe is created
and passed to a Linux shell where the use of a network connection tool such as Netcat or OpenSSL has been established.
The stdout and stderr are captured in the named pipe from the network connection and passed back to the shell for
execution.
EQL Search Results:
Reverse Shell Established:

[New Rule] Reverse Shell Created via Named Pipe

---

rules/windows/privilege_escalation_suspicious_dnshostname_update.toml

tuning of https://github.com/elastic/detection-rules/blob/main/rules/windows/privilege_escalation_suspicious_dnshostname_update.toml to exclude the main FP pattern (100% of FPs) where the new DnsHostName is equal to the computer account name (for TPs the Dns Hostname should be equal to a Domain Controller computer name).

[Rule Tuning] Remote Computer Account DnsHostName Update

---

rules/cross-platform/guided_onborading_sample_rule.toml

CC: @approksiu 
https://github.com/elastic/kibana/pull/146062
Changed name to "My First Rule"

[Guided Onboarding] Name Change for guided_onboarding_sample_rule.toml

---

rules/windows/persistence_driver_newterm_imphash.toml

`New Term` rule to detect when a new driver is loaded based on the unique ` ["dll.pe.original_file_name", "dll.code_signature.subject_name"]` for the last 30 days. 
https://www.elastic.co/kr/security-labs/stopping-vulnerable-driver-attacks

[New Rule] First Time Seen Driver Loaded

---

rules/windows/privilege_escalation_persistence_phantom_dll.toml

Updating Missing DLL list with few more ones (`"oci.dll", "TPPCOIPW32.dll", "tpgenlic.dll", "thinmon.dll", "fxsst.dll", "msTracer.dll"`)

[Rule Tuning] Suspicious DLL Loaded for Persistence or Privilege Escalation

---

rules/integrations/google_workspace/collection_google_drive_ownership_transferred_via_google_workspace.toml
rules/integrations/google_workspace/collection_google_workspace_custom_gmail_route_created_or_modified.toml
rules/integrations/google_workspace/defense_evasion_application_removed_from_blocklist_in_google_workspace.toml
rules/integrations/google_workspace/defense_evasion_domain_added_to_google_workspace_trusted_domains.toml
rules/integrations/google_workspace/defense_evasion_google_workspace_bitlocker_setting_disabled.toml
rules/integrations/google_workspace/defense_evasion_google_workspace_restrictions_for_google_marketplace_changed_to_allow_any_app.toml
rules/integrations/google_workspace/impact_google_workspace_admin_role_deletion.toml
rules/integrations/google_workspace/impact_google_workspace_mfa_enforcement_disabled.toml
rules/integrations/google_workspace/persistence_application_added_to_google_workspace_domain.toml
rules/integrations/google_workspace/persistence_google_workspace_2sv_policy_disabled.toml
rules/integrations/google_workspace/persistence_google_workspace_admin_role_assigned_to_user.toml
rules/integrations/google_workspace/persistence_google_workspace_api_access_granted_via_domain_wide_delegation_of_authority.toml
rules/integrations/google_workspace/persistence_google_workspace_custom_admin_role_created.toml
rules/integrations/google_workspace/persistence_google_workspace_policy_modified.toml
rules/integrations/google_workspace/persistence_google_workspace_role_modified.toml
rules/integrations/google_workspace/persistence_google_workspace_user_group_access_modified_to_allow_external_access.toml
rules/integrations/google_workspace/persistence_google_workspace_user_organizational_unit_changed.toml
rules/integrations/google_workspace/persistence_mfa_disabled_for_google_workspace_organization.toml

https://github.com/elastic/detection-rules/pull/2464
https://github.com/elastic/integrations/pull/3430
While updating and locking rule versions for the v8.3.4 and v8.4.2 release, we noticed that Google Workspace rule versions were double bumped. [Analysis](https://github.com/elastic/detection-rules/pull/2464/files#r1068332494) revealed this to be a result of build-time fields, specifically `related_integrations`. At the Detection Rules 8.3 branch, the build-time `version` value for `related_integrations` is 1.2.0, whereas for the 8.4 branch the value is 2.0.0 and thus the versions double bumped.
We have had a discussion with @spong about potentially adjusting this build-time value being determined via Fleet instead as we would supply the package and integration. While this is a long-term …

[Rule Tuning] Bumping min-stack version for Google Workspace to 8.4

---

rules/windows/credential_access_posh_invoke_ninjacopy.toml

Detects PowerShell scripts that contain the default exported functions used on Invoke-NinjaCopy. Attackers can use
Invoke-NinjaCopy to read SYSTEM files that are normally locked, such as the NTDS.dit file or registry hives.

[New Rule] PowerShell Invoke-NinjaCopy script

---

rules/windows/collection_posh_mailbox.toml

Detects PowerShell scripts that can be used to collect data from mailboxes. Adversaries may target user email to collect sensitive information.

[New Rule] PowerShell Mailbox Collection Script

---

rules/windows/collection_posh_clipboard_capture.toml

Detects PowerShell scripts that can get the contents of the clipboard, which attackers can abuse to retrieve sensitive
information like credentials, messages, etc.

[New Rule] PowerShell Suspicious Script with Clipboard Retrieval Capabilities

---

rules/windows/defense_evasion_timestomp_sysmon.toml

`user.id` is always set to `S-1-5-18` and not suitable for filtering.

[New Rule] T1070.006 - Timestomp

---

rules/windows/discovery_system_service_discovery.toml

Detects the usage of commonly used system service discovery techniques, which attackers may use during the reconnaissance phase after compromising a system in order to gain a better understanding of the environment and/or escalate privileges.

[New Rule] System Service Discovery through built-in Windows Utilities

---

rules/windows/credential_access_shadow_credentials.toml

Excludes the default azure connect AD synchronization account, which reduces the noise by ~45%

[Rule Tuning] Potential Shadow Credentials added to AD Object

---

rules/windows/discovery_admin_recon.toml
rules/windows/discovery_privileged_localgroup_membership.toml

Tuned 2 rules:
- relax the conditions by using wildcard ```*admin*```
- added missing techniques
(relaxed condition captures "administrator" and "Administrator" args)
(working query: no test data)

[Rule Tuning] T1069 and T1087 - admin wildcard and missing techniques

---

rules/windows/credential_access_dcsync_replication_rights.toml

- Adds the service account used by default by the Cisco Umbrella AD Connector, which accounts for ~16% of the alerts, as a exception.
- Adds information on the false positive analysis section of the investigation guides, as most of the FPs come from custom-named Azure AD accounts.

[Rule Tuning] Potential Credential Access via DCSync

---

rules/windows/execution_posh_hacktool_functions.toml

Detects known PowerShell offensive tooling functions names in PowerShell scripts. Attackers commonly use out-of-the-box offensive tools without modifying the code. This rule aim is to take advantage of that.

[New Rule] Potential PowerShell HackTool Script by Function Names

---

rules/windows/discovery_enumerating_domain_trusts_via_dsquery.toml

T1482 Domain Trust Discovery
New rule to capture domain trust discovery with dsquery.

[New Rule] Enumerating Domain Trusts via Dsquery.exe

---

rules/windows/defense_evasion_network_connection_from_windows_binary.toml

Exclude common OCSP (Online Certificate Status Protocol) sites contacted by MSIEXEC and *.local domains, ~12% alert count reduction

[Rule Tuning] Unusual Network Activity from a Windows System Binary

---

detection_rules/integrations.py

None
Backport checks failed after merging in #2470
- Prior to 8.3 where we min_stacked the rules, some of the rules did not include a min_stack. 
- Additionally some of the rules min_stack version only contained the major.minor vs full semantic versioning. 
This additional logic now defaults the min_stack version to the package version to address rules without a min_stack within the toml file.

Resolve backport checks on 2470 by checking Version min_stack

---

detection_rules/etc/non-ecs-schema.json
detection_rules/integrations.py

Backport checks failed after merging in https://github.com/elastic/detection-rules/pull/2470
- Some rules used fields from integrations that have been renamed/no longer exist. This modification updates the non-ecs-schema-file to catch the edge case simply to support older rule versions.
- To support older rule branches that cross major releases, we also have to support those edge cases.

Check integrations cross major versions for older release support

---

rules/windows/defense_evasion_unusual_ads_file_creation.toml

The current Powershell command includes -file which is not a valid parameter for this module. The "-file" must be removed to be effective. Also, I changed the sample ADSname to something a little more obvious to the end user that it is a value that they need to change.
If a user runs the following sample command, they will get an error:
```
PS C:\Program Files\Test> Get-Content -file .\SpecialFile.ps1 -stream PatchVersion
Get-Content: Could not open the alternate data stream 'PatchVersion' of the file 'C:\Program Files\Test\SpecialFile.ps1'.
```
Instead, they should run:
```
PS C:\Program Files\Test> Get-Content .\SpecialFile.ps1 -stream PatchVersion
2.4
```

[Investigation Guide] Update defense_evasion_unusual_ads_file_creation.toml

---

detection_rules/rule.py
detection_rules/version_lock.py

* https://github.com/elastic/detection-rules/pull/2503
This PR contains a bug fix related to #2503 where version lock file references were being pulled incorrectly and thus version collisions were occurring as the result of the latest version referenced by default.
Adjust `rule.get_supported_version` return to be a string of `major.minor` rather than a full semantic version string.
Code was modified on the 7.16 branch after the bug was resolved and then unit tests were ran again, which then all passed. The code changes were then exported to a git diff file and then checked out of each branch that the unit tests failed to then test the unit testing in each branch.

[Bug] Patch fix for #2503

---

detection_rules/rule.py
tests/test_all_rules.py

* https://github.com/elastic/detection-rules/pull/2503
Added `optional_minor_and_patch` flag to `TestRuleTiming` unit test for valid full semantic version parsing prior to comparison logic. Flag was also added to `check_restricted_fields_compatibility` because `major.minor` was being passed in and failed semantic version parsing.
After addressing bugs, the a git diff file was created and then applied at every branch from 7.16-8.6 to ensure that unit testing passes for each branch.

[Bug] Patch fix for 2503 update addressing separate bugs

---

rules/ml/credential_access_ml_auth_spike_in_logon_events_from_a_source_ip.toml
rules/ml/initial_access_ml_auth_rare_user_logon.toml
rules/ml/initial_access_ml_windows_anomalous_user_name.toml

https://github.com/elastic/detection-rules/issues/2529
[Rare User Logon](https://github.com/elastic/detection-rules/blob/fb2b4529c508694a8e65febf1ca721628ee80085/rules/ml/initial_access_ml_auth_rare_user_logon.toml#L28) - add sub-techniques
[Unusual Windows Username](https://github.com/elastic/detection-rules/blob/fb2b4529c508694a8e65febf1ca721628ee80085/rules/ml/initial_access_ml_windows_anomalous_user_name.toml#L31) - add sub-techniques
[Spike in Successful Logon Events from a Source IP](https://github.com/elastic/detection-rules/blob/fb2b4529c508694a8e65febf1ca721628ee80085/rules/ml/credential_access_ml_auth_spike_in_logon_events_from_a_source_ip.toml#L25) - add technique and sub-techniques
The Mitre Eval Score Analysis - 2022 [ …

[Rule Tuning] Rule Tunings to add T1078 technique and subtechniques

---

detection_rules/devtools.py
detection_rules/rule.py
tests/test_version_locking.py

* https://github.com/elastic/detection-rules/pull/2535
Based on #2535 comments, we had triple bumps when forked rule versions were being compared to the current version in the `rule.BaseRuleContents.is_dirty` method. Since `rstrip(".0")` was being used on string versions, `8.0.0` became `8` and thus could not properly access the correct nested JSON object in the version-lock dictionary as the key was `8.0`.
Use `f"{version.major}.{version.minor}"` instead of `rstrip` to ensure the correct key is being used for the version lock file in `rule.BaseRuleContents.is_dirty`.
The changes have been tested on the 7.16->8.7 branch to ensure unit tests pass and the version lock triple bumps do not occur.

[Bug] Removed Strip Calls in Favor of F-Strings with Major and Minor Versions

---

rules/linux/privilege_escalation_shadow_file_read.toml

After excluding the true positives such as grep, egrep, sed, awk and cat, several false positives remained. This tuning request excludes the following three false positives:
- chown root:shadow --> which is benign behavior, as these permissions are default for the /etc/shadow file
- chmod 640 --> which is benign behavior, as these permissions are default for the /etc/shadow file
- process.executable restorecon --> which is used by SELinux to restore files to their proper permission state.
The query was tested in my test environment, and runs correctly. 
After excluding these false positives from the rule, the total number of hits will be reduced from 2856 to 2712. 
This is still a large number, however these alerts are true positives.

[Rule Tuning] Potential Shadow File Read via CLI

---

rules/linux/defense_evasion_attempt_to_disable_iptables_or_firewall.toml

#2590 
The rule was in endpoint and is being moved to detection mode as part of elastic/endpoint-rules/issues/1817
No additional testing is required. Tested as part of elastic/endpoint-rules/pull/1297

New Rule to identify iptables or firewall disabling.

---

rules/linux/credential_access_credential_dumping.toml

#2603 
This detection identifies the use of the Linux utility 'unshadow' being executed with the right set of parameters.
This technique could be used by malicious actors to retrieve the contents of the '/etc/shadow' and '/etc/password' files.
Using these files the malicious threat actors can prepare themselves for password-cracking utilities.

New Rule to identify potential linux credential dumping

---

rules/windows/defense_evasion_amsi_bypass_powershell.toml

Resolves https://github.com/elastic/sdh-protections/issues/389
Tune the rule to not have FPs due to partial match.
Due to the nature of the `powershell.file.script_block_text` field (Some context can be found [here](https://github.com/elastic/integrations/pull/1931)), we need to double quote any field value that contains non-alphanumerical chars, because KQL will use them as delimiters and treat the text as separated keywords instead of a full text. For example:

[Rule Tuning] Potential Antimalware Scan Interface Bypass via PowerShell

---

tests/test_all_rules.py

related to #2286
Since all rules are min_stacked to 8.3, rule updates did not backport prior to that, but the unit test did. This change skips the test for <8.3 branches

[Test] Restrict host.os.type unit test to 8.3+

---

tests/base.py

resolves #1869 
resolves #2623 
This PR caches the rule loader default rules for unit tests. It also skips rule based-test when the rule loader fails.
To test, change any rule `author` to `authorz` and run unit tests
Duration before:
```
passing: make test  165.21s user 11.06s system 96% cpu 3:03.31 total
failing: make test  478.26s user 14.04s system 97% cpu 8:23.70 total
```
Duration after:
```
passing: make test  96.66s user 6.64s system 96% cpu 1:47.22 total
failing: make test  49.61s user 5.81s system 93% cpu 59.209 total
```
Each unittest class in `test_all_rules` loads the `BaseRuleTest.setUp` method when setting up unit tests. This meant that the rule loader was run multiple times. It now caches that load to limit it to a single load.
Now, if the loader fails, it will skip all …

Speed up unit tests

---

rules/windows/privilege_escalation_via_token_theft.toml

* https://github.com/elastic/detection-rules/issues/2620
* https://github.com/elastic/detection-rules/issues/2578
A couple community issues were created regarding potential False-Positive (FP) alerts for Process Created with an Elevated Token. Specifically, a Windows update executable, `TiWorker.exe` where child processes were for `iissetup.exe` and `ngen.exe`. 
This PR adds these as an exception, focusing on the parent and child executables, as well as some other FP alerts we observed from global telemetry.
Screenshots:

[Rule Tuning] Process Created with an Elevated Token (TiWorker.exe)

---

tests/base.py

related to #2626 
Rolls back to initial commit in #2626. Uses global constants to hold flags rather than using class variables. This is necessary because of how `SetUpClass` is called and because each new `TestCase` reloads the base class

[Tweak] Use global constants to speed up tests

---

rules/windows/defense_evasion_untrusted_driver_loaded.toml

Changes the event.category to `driver`, in order to make the rule work with the stack EQL.

[Rule Tuning] Untrusted Driver Loaded

---

detection_rules/navigator.py

https://github.com/elastic/ia-trade-team/issues/108
Updating Layer `4.3` -> `4.4` for updating the MIRE ATT@CK Navigator. 
For testing see: https://github.com/elastic/ia-trade-team/issues/108#issuecomment-1490480452
And for troubleshooting testing see: https://github.com/elastic/ia-trade-team/issues/108#issuecomment-1490546545

Update layer version to 4.4

---

rta/__init__.py

Enhancing the rta test print option to include the rule id and rule name the test triggers.  This make it easier to find the rule in Kibana to enable it.
I also increased the longest test name size by three to account for the `.py` file extension. 
```
% python -m rta -l -o linux
Printing available tests
name                              | platforms             | rule id                              | rule name
=================================================================================================================================
empire_stager.py                  | macos, linux          | b7974ff6-82ff-4743-9e07-1c6901b1f0ea | Empire Stager Execution
eggshell_backdoor.py              | macos, linux          | feed7842-34a6-4764-b858-6e5ac01a5ab7 | EggShell Backdoor Execution
| …
```

Add Rule Id and Rule Name to the RTA Test List Function

---

tests/test_all_rules.py

* https://github.com/elastic/detection-rules/pull/2682
Kubernetes rules in 8.3 did not have `event.dataset` in them as the integration did not have that field available. They were min-stacked to 8.4 where these were then added. As a result the `TOMLRuleContents.get_packaged_integrations` call returns None, indicating that Kubernetes is not in the manifest file on the 8.3 branch.
To resolve this, we emulate the `TOMLRuleContents.get_packaged_integrations` logic by checking if `event.dataset` is in the rule being tested. If it is, then it should be parsable and a `package:integration` returned.
Change implemented and tested on the 8.3 branch.

[Bug] Fixes Unit Test `test_integration_tag` in Older Branches 

---

rules/windows/persistence_service_windows_service_winlog.toml

Remove the following patterns to avoid FPs with legitimate software and system processes:
Reduce alerts in the last 90d by ~90%
Noisy ones:
*  `\\ProgramData\\`
*  `*.sys*` -> Any driver, including Elastic ones
*  `*svchost*` -> Noisiest, ~70% of the alerts
Some I think we should remove to avoid FPs on legitimate software:
*  `\\Intel\\`
*  `:\\HP\\`

[Rule Tuning] Suspicious service was installed in the system

---

rules/windows/execution_posh_hacktool_functions.toml

Fixes a query error caused by a missing space

[Rule Tuning] Potential PowerShell HackTool Script by Function Names

---

rules/integrations/google_workspace/collection_google_drive_ownership_transferred_via_google_workspace.toml
rules/integrations/google_workspace/collection_google_workspace_custom_gmail_route_created_or_modified.toml
rules/integrations/google_workspace/defense_evasion_application_removed_from_blocklist_in_google_workspace.toml
rules/integrations/google_workspace/defense_evasion_domain_added_to_google_workspace_trusted_domains.toml
rules/integrations/google_workspace/defense_evasion_google_workspace_bitlocker_setting_disabled.toml
rules/integrations/google_workspace/defense_evasion_google_workspace_new_oauth_login_from_third_party_application.toml
rules/integrations/google_workspace/defense_evasion_google_workspace_restrictions_for_google_marketplace_changed_to_allow_any_app.toml
rules/integrations/google_workspace/impact_google_workspace_admin_role_deletion.toml
rules/integrations/google_workspace/impact_google_workspace_mfa_enforcement_disabled.toml
rules/integrations/google_workspace/initial_access_external_user_added_to_google_workspace_group.toml
rules/integrations/google_workspace/initial_access_google_workspace_suspended_user_renewed.toml
rules/integrations/google_workspace/persistence_application_added_to_google_workspace_domain.toml
rules/integrations/google_workspace/persistence_google_workspace_2sv_policy_disabled.toml
rules/integrations/google_workspace/persistence_google_workspace_admin_role_assigned_to_user.toml
rules/integrations/google_workspace/persistence_google_workspace_api_access_granted_via_domain_wide_delegation_of_authority.toml
rules/integrations/google_workspace/persistence_google_workspace_custom_admin_role_created.toml
rules/integrations/google_workspace/persistence_google_workspace_policy_modified.toml
rules/integrations/google_workspace/persistence_google_workspace_role_modified.toml
rules/integrations/google_workspace/persistence_google_workspace_user_organizational_unit_changed.toml
rules/integrations/google_workspace/persistence_mfa_disabled_for_google_workspace_organization.toml

This PR updates min stack comments for Google Workspace rules that are min-stacked at 8.4.0. These are just rule metadata changes.

[Rule Tuning] Update min-stack comments for Google Workspace Rules

---

detection_rules/rule.py
tests/test_transform_fields.py

resolves #2740 
This bug actually led to the discovery of 2 additional bugs
- A: `TOMLRuleContents.to_dict` was not called from `TOMLRuleContents.to_api_format`, bypassing the transform logic (original bug)
- B: `test_transform_fields` tests were calling the `TOMLRuleContents.to_dict` rather than `TOMLRuleContents.to_api_format` method, bypassing the emulated check on actual rule generation
- C: for the substitution rendering, there was the potential for pattern poisoning where any word within the investigation guide starting with `$` would render as a pattern and raise a key error for missing values. 
- A: resolved by making the call
- B: resolved by fixing the test
- C: resolved by using `safe_substitute` to ignore non-explicit patterns
- `make test` and view `test_transform_fields`
- …

[Bug] Render transform logic on rule build

---

.github/workflows/release-docs.yml
detection_rules/devtools.py
detection_rules/docs.py

#2743 
Adds a release-docs workflow that automates pushing docs to the security-docs repo. 
- Run the release-docs workflow (which should create a [PR](https://github.com/elastic/security-docs/pull/3194))
- Run `python -m detection_rules dev build-integration-docs 8.3.3 --pre integration-v8.3.2 --post integration-v8.3.3 -d /Users/stryker/workspace/ElasticGitHub/security-docs/docs/detections/prebuilt-rules/downloadable-packages --force` and make sure docs are updated as expected in the security-docs repo per the instructions [here](https://github.com/elastic/ia-trade-team/wiki/Detection-Rules-Releasing-v2)
- Adds index.asciidoc:index_include in docs/index.asciidoc
- Adds table_entry to docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
- Adds table_include …

[FR] Add release-docs workflow and automation

---

detection_rules/docs.py

* https://github.com/elastic/ia-trade-team/issues/122
The following code snippet had a misspelling, thus causing an error with the `8.7` OOB package release.
```python
deprecated_rule_ids = list(set(deprecated_rule_ids))
for rule_id in deprecated_rule_ids:
rule_changes['deprecated'].append(self.new_package.deprecate_rules.id_map[rule_id])
```
Fix is: `self.new_package.deprecated_rules.id_map[rule_id]`
Failed GitHub Actions reference: https://github.com/elastic/detection-rules/actions/runs/5015866807/jobs/8992007360

[Bug] Fix misspelled variable call for `deprecated_rules` in doc generation

---

rules/integrations/azure/credential_access_azure_full_network_packet_capture_detected.toml

Fixed an issue pointed out [here](https://github.com/elastic/geneve/issues/168) of using double quotes when working with KQL wildcards, which turns the string into a literal and therefore does no longer capture the wished-for behavior.
This PR fixes this unwanted behavior.

[Tuning] Azure Network Packet Capture Detected

---

README.md
pyproject.toml

Resolves #2884
Adds "pywin32" for windows builds.
Should be able to run `python -m detection_rules --help` after installing via `pip3 install ".[dev]"` with no errors.

[Bug] Add pywin32 to windows install

---

detection_rules/schemas/definitions.py
rules/windows/collection_posh_clipboard_capture.toml
rules/windows/collection_posh_keylogger.toml
rules/windows/collection_posh_mailbox.toml
rules/windows/defense_evasion_amsi_bypass_powershell.toml
rules/windows/defense_evasion_posh_encryption.toml
tests/test_all_rules.py

The query optimization PR (https://github.com/elastic/detection-rules/pull/2823) removed the quotes from some of the powershell KQL queries' keywords, introducing partial matches (FPs). Here is a summary of what this means from #2614
> Tune the rule to not have FPs due to partial match.
>
>Due to the nature of the `powershell.file.script_block_text` field (Some context can be found [here](https://github.com/elastic/integrations/pull/1931)), we need to double quote any field value that contains non-alphanumerical chars, because KQL will use them as delimiters and treat the text as separated keywords instead of a full text. For example:
>
> ![image](https://user-images.githubusercontent.com/26856693/222544527-54dce0ec-667f-4c49-a7a0-3b60a754eb4b.png)

[Rule Tuning] [BUG] Revert PowerShell Query modifications from #2823

---

detection_rules/etc/non-ecs-schema.json
rules/linux/credential_access_potential_successful_linux_ftp_bruteforce.toml
rules/linux/credential_access_potential_successful_linux_rdp_bruteforce.toml

This PR proposes the addition of two new `auditd_manager` rules to detect a successful brute force attack on FTP/RDP services in Linux. This behavior is not logged by default such as for example ssh login attempts are. The PR proposes the following two new rules:
1. Potential Successful Linux RDP Brute Force Attack Detected
2. Potential Successful Linux FTP Brute Force Attack Detected
As there was no `auditd manager` setup guide available yet, I wrote a new one. Please comment on how to improve this set up guide, and I will add the improvements to all upcoming auditd manager related rules.
An RDP (Remote Desktop Protocol) brute force attack involves an attacker repeatedly attempting various username and password combinations to gain unauthorized access to a remote computer via RDP, and if …

[New Rules] ftp/rdp bruteforce

---

detection_rules/rule.py
detection_rules/rule_validators.py

* https://github.com/elastic/detection-rules/issues/2811
This PR adds the following EQL rule type configuration fields:
* `timestamp_field`
* `event_category_override`
* `tiebreaker_field`
These fields are only available in EQL rules as shown in the image below.
To begin, a custom rule was created in the UI and then exported. These three fields are in the base of the rule.
<details>
<summary> Exported Rule </summary>
```
{
"id": "4fcc35d0-1f97-11ee-9323-995da7e2ec1a",
"updated_at": "2023-07-11T03:02:04.098Z",
"updated_by": "4220331459",
"created_at": "2023-07-11T03:02:03.444Z",
"created_by": "4220331459",
"name": "EQL Defined Rule",
"tags": [
"Testing"
],
"interval": "10m",
"enabled": false,
"description": "EQL Defined RUle",
"risk_score": 21,
"severity": "low",
"license": "", …
```

[FR] Add EQL Rule Type Configuration Fields

---

rules/windows/collection_mailbox_export_winlog.toml
rules/windows/collection_posh_audio_capture.toml
rules/windows/collection_posh_clipboard_capture.toml
rules/windows/collection_posh_keylogger.toml
rules/windows/credential_access_posh_invoke_ninjacopy.toml
rules/windows/credential_access_posh_request_ticket.toml
rules/windows/defense_evasion_amsi_bypass_powershell.toml
rules/windows/defense_evasion_posh_assembly_load.toml
rules/windows/defense_evasion_posh_compressed.toml
rules/windows/discovery_posh_suspicious_api_functions.toml
rules/windows/execution_posh_hacktool_functions.toml
rules/windows/privilege_escalation_posh_token_impersonation.toml

Exclude widespread False Positives from PowerShell rules, with an honorable mention to SentinelOne https://github.com/mttaggart/wtfbins/issues/24:
> A legitimate PowerShell script associated with SentinelOne includes encoded PowerShell, AMSI bypass encoding, as well as strings for offensive security commands such as 'Invoke-Mimikatz'. If running another security solution - like Defender - it may flag this SentinelOne legitimate PowerShell activity as malicious.
This also corrects some legitimate activity and removes keywords used in many legitimate modules.

[Rule Tuning] PowerShell Rule Tunings

---

rules/linux/execution_shell_suspicious_parent_child_revshell_linux.toml
rules/linux/execution_shell_via_java_revshell_linux.toml
rules/linux/execution_shell_via_lolbin_interpreter_linux.toml
rules/linux/execution_shell_via_suspicious_binary.toml
rules/linux/execution_shell_via_tcp_cli_utility_linux.toml

Added the following extra check to minimize FPs. Found some FPs of services connecting to databases etc. on 127.0.0.1. This tuning reduces the number of hits from 12,179 back to 17, which are 17 TPs. 
```
and destination.ip != null and destination.ip != "127.0.0.1" and destination.ip != "::1"
```

[Tuning] Reverse Shell Rules

---

rules/linux/persistence_init_d_file_creation.toml
rules/linux/persistence_linux_backdoor_user_creation.toml
rules/linux/persistence_linux_group_creation.toml
rules/linux/persistence_linux_shell_activity_via_web_server.toml
rules/linux/persistence_linux_user_account_creation.toml
rules/linux/persistence_linux_user_added_to_privileged_group.toml
rules/linux/persistence_message_of_the_day_creation.toml
rules/linux/persistence_message_of_the_day_execution.toml
rules/linux/persistence_rc_script_creation.toml
rules/linux/persistence_systemd_scheduled_timer_created.toml

Added the following note:
`> This investigation guide uses [placeholder fields](https://www.elastic.co/guide/en/security/current/osquery-placeholder-fields.html) to dynamically pass alert data into Osquery queries. Placeholder fields were introduced in Elastic Stack version 8.7.0. If you're using Elastic Stack version 8.6.0 or earlier, you'll need to manually adjust this investigation guide's queries to ensure they properly run.`
To the following IGs:
- Potential Persistence Through init.d Detected
- Potential Linux Backdoor User Account Creation
- Linux Group Creation
- Potential Remote Code Execution via Web Server
- Linux User Account Creation
- Linux User Added to Privileged Group
- Potential Persistence Through MOTD File Creation Detected
- Suspicious Process Spawned from MOTD …

[Security Content] Added Compatibility note to all IGs

---

rules/linux/defense_evasion_file_mod_writable_dir.toml

#2911 
- The Rule was analyzed for False positives in the latest version of rule "103"
- The rule originally was in kquery without no quotes around the file path, which tends to generate false positives from our previous experience
- The rule is tuned to be in EQL with quotes around file paths.
- Additionally, safe parent processes are added as an exclusion to further reduce false positives
- parent.process.name exclusion is added as an "in" in EQL to support the addition of any new safe parent process to reduce false positives. 

Rule Tuning File Permission Modification in Writable Directory

---

rules_building_block/persistence_suspicious_file_opened_through_editor.toml

This rule monitors for the potential edit of a suspicious file. In Linux, when editing a file through an editor, a temporary .swp file is created. By monitoring for the creation of this .swp file, we can detect potential file edits of suspicious files. The execution of this rule is not a clear sign of the file being edited, as just opening the file through an editor will trigger this event. Attackers may alter any of the files added in this rule to establish persistence, escalate privileges or perform reconnaisance on the system. 
The interesting part about this rule is that we aren't really capable of capturing file edit events on Linux, and this bypasses this limitation when files are being edited through an editor. By monitoring for the creation of a .swp file, we are basically …

[New BBR] Potential Suspicious File Edit

---

rules/cross-platform/threat_intel_indicator_match_hash.toml
rules/cross-platform/threat_intel_indicator_match_url.toml

Resolves #2954 
* Threat Intel URL Indicator Match:
* Drops the `domain` fields on this rule, as it is more noisy than expected, as a lot of commonly used web services are included in threat intel fields. Such as Github, dropbox, discord, google drive, etc.
* Threat Intel Hash Indicator Match
* Drops the support to `dll.pe.imphash`, as integrations such as abusech contain events with this field empty, which can match the target field in specific conditions in which it is not populated by Elastic Endpoint, generating thousands of unintended matches:
I've looked at using QueryDSL as a filter in the Indicator index query but excluding indicators that don't populate certain fields will cause the other fields which contain the information to be excluded, causing FNs.
As this matches a specific …

[Rule Tuning] Tune Threat Indicator Match Rules

---

rules/linux/credential_access_potential_linux_local_account_bruteforce.toml

Identifies multiple consecutive login attempts executed by one process targeting a local linux user account within a short time interval. Adversaries might brute force login attempts across different users with a default wordlist or a set of customly crafted passwords in an attempt to gain access to these accounts.
This behavior is common across different local account brute force scripts e.g. https://github.com/carlospolop/su-bruteforce or manual attempts of brute forcing a useraccount. As new process.entity_id's and process.parent.entity_id's are generated per authentication attempt, the only feasible way of detecting this is through the process.parent.executable. As the timespan is set to 1 second, this shouldn't be a big performance hit.
Red sector shows 0 hits for this query in the …

[New Rule] Linux Local Account Brute Force

---

rules/linux/privilege_escalation_writable_docker_socket.toml

This rule monitors for the usage of Docker runtime sockets to escalate privileges on Linux systems. Docker sockets by default are only be writable by the root user and docker group. Attackers that have permissions to write to these sockets may be able to create and run a container that allows them to escalate privileges and gain further access onto the host file system.
0 hits last 365 days in red sector, nor in my docker test clusters. Added `and not user.Ext.real.id : "0" and not group.Ext.real.id : "0"` to minimize FPs. 
```
process where host.os.type == "linux" and event.type == "start" and event.action == "exec" and 
(
(process.name == "docker" and process.args : "run" and process.args : "-it"  and 
process.args : ("unix://*/docker.sock", "unix://*/dockershim.sock")) or …
```

[New Rule] PE through Writable Docker Socket

---

CONTRIBUTING.md
detection_rules/docs.py

Related to #2867
- Generates a duplicate of the [prebuilt rule reference](https://www.elastic.co/guide/en/security/8.9/prebuilt-rules.html) page  without version history
- Small tweaks to our build to point users to `update-prebuilt-rules` moving forward instead of `download-prebuilt-rules`

[FR] Generate Prebuilt Rules Reference Page

---

detection_rules/packaging.py
detection_rules/rule_loader.py
rules_building_block/command_and_control_non_standard_http_port.toml
rules_building_block/discovery_posh_generic.toml
rules_building_block/discovery_windows_system_information_discovery.toml
tests/test_all_rules.py

#2949 
Adds support for BBR rules to be included in:
- version lock updates
- default rule loader 
Run `python -m detection_rules dev build-release --update-version-lock` to verify that the version lock file is updated (included bbr rules)
<details><summary>Sample Update</summary>
<p>
BBR Rule added to the version lock file.
</p>
</details>

[FR] Add support for BBR rules to the rule loader

---

rules/linux/execution_shell_suspicious_parent_child_revshell_linux.toml
rules/linux/execution_shell_via_lolbin_interpreter_linux.toml
rules/linux/execution_shell_via_suspicious_binary.toml
rules/linux/execution_shell_via_tcp_cli_utility_linux.toml

While testing for socat tunneling, I noticed I didn't detect a bind shell with my reverse shell rules. I went to check why, and noticed the rules only checked for "connection_attempted", which indeed is the most common event.action, however it missed several occurences in which event.action == "connection_accepted". This PR fixes this.

[Rule Tuning] added additional event action

---

rules/windows/persistence_run_key_and_startup_broad.toml
rules_building_block/defense_evasion_masquerading_communication_apps.toml

- Expand the rules to cover Outlook and Thunderbird
- Tunings on legitimate signatures for some of the executables
- Resolves #2993

[Rule Tuning] Potential Masquerading as Communication Apps

---

kibana/connector.py
rules/cross-platform/threat_intel_indicator_match_hash.toml

- Closes #3030 
This rule currently watches for matches on "imphash" hashes. Unfortunately this may only mean a file was created in a similar manner to a malware sample, but it does not mean the file is inherently malicious. While an imphash may assist with forensics, this is unfortunately causing false positives to the point of the rule exceeding "the maximum alert limit for the rule execution". I am proposing the removal of "imphash" matches due to the infeasibility of investigating and whitelisting hashes based on imphash matches.

[Rule Tuning] Threat Intel Hash Indicator Match

---

rules_building_block/discovery_suspicious_which_command_execution.toml

This rule monitors for the usage of the which command with an unusual amount of process arguments. Attackers may leverage the which command to enumerate the system for useful installed utilities that may be used after compromising a system to escalate privileges or move latteraly across the network. 
**This rule (without the additional tuning options) shows 0 hits in telemetry, and 0 FPs in my own stacks.**
```
process where host.os.type == "linux" and event.action == "exec" and event.type == "start" and 
process.name == "which" and process.args_count >= 10
/* potential tuning if rule would turn out to be noisy
and process.args in ("nmap", "nc", "ncat", "netcat", nc.traditional", "gcc", "g++", "socat") and 
process.parent.name in ("bash", "dash", "ash", "sh", "tcsh", "csh", "zsh", "ksh", …
```

[New BBR] Suspicious which Enumeration

---

rules/linux/discovery_sudo_allowed_command_enumeration.toml
rules/linux/execution_abnormal_process_id_file_created.toml
rules/linux/privilege_escalation_sda_disk_mount_non_root.toml

Just 2 small tunings to reduce FPs on these rules back to 0.
**edit**
I added one more tuning to address issue [#3041](https://github.com/elastic/detection-rules/issues/3041). This will reduce FPs and trigger on TPs:

[Rule Tuning] 3 tunings to reduce FPs

---

rules/linux/credential_access_gdb_init_memory_dump.toml
rules_building_block/credential_access_gdb_memory_dump.toml

This PR proposes the addition of two new GDB secret dumping rules:
1. Linux init (PID 1) Secret Dump via GDB
2. Linux Secret Dumping via GDB - BBR
This rule monitors for the potential memory dump of the init process (PID 1) through gdb. Attackers may leverage memory dumping techniques to attempt secret extraction from privileged processes. Tools that display this behavior include "truffleproc" and "bash-memory-dump". This behavior should not happen by default, and should be investigated thoroughly.
**0 FPs in telemetry, also 0 FPs in my own stacks. Many FPs of security testing.**
```
process where host.os.type == "linux" and event.action == "exec" and event.type == "start" and 
process.name == "gdb" and process.args == "--pid" and process.args == "1"
```
This rule monitors for potential …

[New Rules] GDB Secret Dumping

---

rules/linux/discovery_unusual_user_enumeration_via_id.toml

This rule monitors for a sequence of 20 "id" command executions within 1 second by the same parent process. This behavior is unusual, and may be indicative of the execution of an enumeration script such as LinPEAS or LinEnum. These scripts leverage the "id" command to enumerate the privileges of all users present on the system.
```
sequence by host.id, process.parent.entity_id with maxspan=1s
[process where host.os.type == "linux" and event.action == "exec" and event.type == "start" and 
process.name == "id" and process.args_count == 2] with runs=20
```

[New Rule] Unusual User Privilege Enumeration via id

---

rules/windows/execution_command_shell_started_by_unusual_process.toml

When dllhost.exe is called with the "/Processid:{CA8C87C1-929D-45BA-94DB-EF8E6CB346AD}" argument it is creating an "OOBE Elevated Object Server"  as per https://strontic.github.io/xcyclopedia/library/clsid_ca8c87c1-929d-45ba-94db-ef8e6cb346ad.html
Out of the box experience is part of the Windows autopilot and therefore should be legitimate behaviour.

Tunes Unusual Parent Process for cmd.exe rule to exclude oobe activity

---

rules/integrations/lmd/lateral_movement_malicious_remote_file_creation.toml
rules/integrations/lmd/lateral_movement_ml_high_mean_rdp_process_args.toml
rules/integrations/lmd/lateral_movement_ml_high_mean_rdp_session_duration.toml
rules/integrations/lmd/lateral_movement_ml_high_remote_file_size.toml
rules/integrations/lmd/lateral_movement_ml_high_variance_rdp_session_duration.toml
rules/integrations/lmd/lateral_movement_ml_rare_remote_file_directory.toml
rules/integrations/lmd/lateral_movement_ml_rare_remote_file_extension.toml
rules/integrations/lmd/lateral_movement_ml_spike_in_connections_from_a_source_ip.toml
rules/integrations/lmd/lateral_movement_ml_spike_in_connections_to_a_destination_ip.toml
rules/integrations/lmd/lateral_movement_ml_spike_in_rdp_processes.toml
rules/integrations/lmd/lateral_movement_ml_spike_in_remote_file_transfers.toml
rules/integrations/lmd/lateral_movement_ml_unusual_time_for_an_rdp_session.toml
rules/integrations/lmd/lateral_movement_remote_file_creation_in_sensitive_directory.toml

* https://github.com/elastic/ia-trade-team/issues/174
Integration was made `ga` for 8.5+. As a result, when we originally merged the PR to add the rules in https://github.com/elastic/detection-rules/pull/3119, they were min-stacked to 8.3.0. Thus, they broke some unit testing in 8.3 and 8.5 branches that checks that these rules are compatible with these stack versions. @ajosh0504 this was an oversight on my end. For the next set of rules and packages, we just need to check the min-stack for each rule according to package availability.
Solution:
1. Go to 8.3 and 8.4 branch, remove rules and push to branches
2. This PR to update min-stack and let backporting happen

[Rule Tuning] Update `LMD` Rules Min-Stack to `8.5`

---

rules/windows/persistence_sysmon_wmi_event_subscription.toml

* https://github.com/elastic/detection-rules/pull/3151
This PR adjusts the minimum stack version of this rule. This is due to backporting and version control, where the build time field `required_fields` has a field `winlog.event_data.Operation` where the type is `unknown` up until 8.8. After 8.8, the field type is `keyword`. As a result, the SHA256 of the rule changes between branches and when version lock occurs, causes the double bump mentioned [here](https://github.com/elastic/detection-rules/pull/3151/files#r1344412618). This occurs when the integration (here it is the Windows integration) changes OOB and causes changes downstream to build time fields.
As a result, we need to fork the rule to separate it from 8.3-8.7 and 8.8+. This will make 8.3-8.7 version 5 with a buffer to 103, …

[Rule Tuning] Fork `Suspicious WMI Event Subscription Created` for Version Control

---

rules/linux/privilege_escalation_looney_tunables_cve_2023_4911.toml

This rule detects potential privilege escalation attempts through Looney Tunables (CVE-2023-4911). Looney Tunables is a buffer overflow vulnerability in GNU C Library's dynamic loader's processing of the GLIBC_TUNABLES environment variable.
```
sequence by host.id, process.parent.entity_id with maxspan=5s
[process where host.os.type == "linux" and event.type == "start" and event.action == "exec" and process.name == "su" 
and process.env_vars : "GLIBC_TUNABLES=glibc.malloc.mxfast*"] with runs=5
```

[New Rule] PE via CVE-2023-4911 (Looney Tunables)

---

detection_rules/main.py
detection_rules/schemas/definitions.py
rules_building_block/collection_common_compressed_archived_file.toml

Creates a new BBR to detect compressed and archived files based on file header. All existing compressions detections are based on process names and subsets of activity.
This also includes a new command to generate the threat map entry `build-threat-map-entry`.

[New Rule] File Compressed or Archived into Common Format

---

rules/network/command_and_control_cobalt_strike_beacon.toml
rules/network/command_and_control_fin7_c2_behavior.toml
rules/network/command_and_control_halfbaked_beacon.toml
rules/network/initial_access_unsecure_elasticsearch_node.toml

Resolves #3187 
Adjust Lucene queries to use Uppercase operators in order to avoid non-intentional matches.

[Rule Tuning] Adjust Lucene queries to use Uppercase operators

---

rules/windows/privilege_escalation_installertakeover.toml

Related to https://github.com/elastic/sdh-protections/issues/449
Excludes some FPs where the elevation_service.exe process doesn't contain any value on `process.pe.original_file_name`, drops sysmon support in favor of process signature checking

[Rule Tuning] Potential Privilege Escalation via InstallerFileTakeOver

---

tests/test_all_rules.py

Resolves https://github.com/elastic/detection-rules/issues/3137
This PR adjusts the risk severity settings to allow specific ranges for low, medium, high and critical severity as [documented](https://www.elastic.co/guide/en/security/current/rules-ui-create.html#rule-ui-basic-params). When community members are creating custom rules, unit tests fail for what is acceptable upstream. For more information, please see issue.

[FR] Adjust Risk Severity Unit Test to Match UI

---

rules/linux/defense_evasion_clear_kernel_ring_buffer.toml

Monitors for the deletion of the kernel ring buffer events through dmesg. Attackers may clear kernel ring buffer events to evade detection after installing a Linux kernel module (LKM).
This behavior was observed in [BDS LKM ROOTKIT](https://github.com/bluedragonsecurity/bds_lkm#bds-lkm-rootkit). More information and progress on root kit rule dev is documented in https://github.com/elastic/detection-rules/issues/3210.
```
process where host.os.type == "linux" and event.action == "exec" and event.type == "start" and
process.name == "dmesg" and process.args : "-c"
```
Root kit executing these commands upon and after installation:

[New Rule] Attempt to Clear Kernel Ring Buffer

---

detection_rules/rule.py
pyproject.toml

Directly Resolves: https://github.com/elastic/detection-rules/issues/3130
Tangentially Resolves: https://github.com/elastic/detection-rules/issues/3255
This PR fixes an issue where exporting rules would fail due to invalid values being based to the TomlRuleContents schema when a rule had a transform section. This occurred as the transform was not properly cast to a dictionary before being attempting to load it with the rest of the rule contents via `TOMLRuleContents.from_dict()`. This fix was to convert it to a dictionary directly via `.to_dict()` before passing it following a similar pattern to what is used in [devtools.py](https://github.com/elastic/detection-rules/blob/f53f46efd54ac50d776330a0191f6c93cbd39c8e/detection_rules/devtools.py#L1471).
Additionally, this PR includes an update …

[Bug] Fix typo in downgrade_contents_from_rule

---

rules/integrations/okta/initial_access_okta_user_sessions_started_from_different_geolocations.toml

* https://github.com/elastic/ia-trade-team/issues/106
This pull request adds detection logic for Okta user sessions started by a user from different geolocations. This query also negates `okta.security_context.is_proxy:true` to eliminate false-positives where a user may be using a VPN or proxy. This is a threshold rule that groups the events by `okta.actor.id` and adds cardinality by `client.geo.country_name`.

[New Rule] Adding Detection Logic for Okta User Sessions Started from Different Geolocations

---

detection_rules/integrations.py
detection_rules/rule.py
detection_rules/rule_validators.py
detection_rules/schemas/definitions.py

https://github.com/elastic/detection-rules/issues/3275
- Adds support for the ES|QL Rule type based on the [kibana implementation](https://github.com/elastic/kibana/blob/3a18916b31d27d2ffeb7df682e69224a273b39b4/x-pack/plugins/security_solution/server/lib/detection_engine/rule_schema/model/rule_schemas.ts#L160-L168)
- Adds base stub classes to validate esql rules
1. Unit tests should pass with the sample esql rule locally.
2. Manual testing with CLI commands. 
<details><summary>Sample Rule</summary>
<p>
Use the following rule, and run view-rule command to ensure the esql rule loads successfully, skipping validation.
```toml
[metadata]
creation_date = "2023/02/27"
integration = ["endpoint"]
maturity = "production"
min_stack_comments = "New fields added: required_fields, …
```

FR] Add Core Support for ES|QL Rule Type

---

rules/integrations/okta/credential_access_multiple_auth_events_from_single_device_behind_proxy.toml
rules/integrations/okta/initial_access_multiple_active_users_from_single_device.toml

A user has given feedback that the detection logic for this rule is too broad. Rule tuning and an investigation guide has been added to reduce potential false-positive rate.
- Before: Alert for >= 2 users with the same sourcing device token hash for any system or user events
- After: Alert for >= 3 users with the same sourcing device token hash for only user authentication events where the device is behind a proxy.
This should align more with credential stuffing and password spraying attempts. Additionally, MITRE ATT&CK mappings have been updated to more accurately reflect these techniques.

[Rule Tuning] Multiple Users with the Same Okta Device Token Hash

---

rules/linux/persistence_chkconfig_service_add.toml
rules/linux/persistence_cron_job_creation.toml
rules/linux/persistence_etc_file_creation.toml
rules/linux/persistence_systemd_service_creation.toml

This rule adds Investigation Guides for 4 persistence related Linux rules. Due to PTO I will split this task up in 2 PRs. The next PR will add 6 more.

[Security Content] Add Investigation Guides to Linux Persistence Rules - 1

---

rules/integrations/okta/initial_access_okta_fastpass_phishing.toml

This pull request adjusts min-stack for the `Okta FastPass Phishing Detection` rule. This min-stack was set to `8.3.0` which caused the dynamically generated `related_integrations` field to refer an older version below `2.0.0`. The Okta integration had a breaking change at `2.0.0` which is why all Okta rules are min-stacked to `8.10.0` where `^2.0.0` version is compatible.
This was found during the release for `8.11.5` regarding the version locking PR:
* https://github.com/elastic/detection-rules/pull/3317

[Rule Tuning] Adjust Min-Stack for `Okta FastPass Phishing Detection` Rule

---

rules/windows/persistence_remote_password_reset.toml

https://github.com/elastic/detection-rules/issues/3332
- reduced maxspan from 5m to 1m (automated pwd reset)
- excluded most observed noisy winlog.event_data.TargetUserName patterns (IAM/AD service account dedicated for mass pwd reset)
- added a note for performance impact

[Rule Tuning] Account Password Reset Remotely

---

rules/windows/credential_access_bruteforce_multiple_logon_failure_followed_by_success.toml

https://github.com/elastic/ia-trade-team/issues/232
99% of noise is coming from Anonymous logon ("S-1-0-0"), not always populated in user.name thus the addition of `not user.id : "S-1-0-0"`

[Tuning] Multiple Logon Failure Followed by Logon Success

---

rules/windows/lateral_movement_direct_outbound_smb_connection.toml

Related to https://github.com/elastic/ia-trade-team/issues/232
The goal of this PR is to optimize the query for performance, as it has been identified as an overly expensive execution. To do so, I targeted a few things:
* added a `maxspan`
* added a short circuit using `until`
* modified some of the exclusions
The primary thing we need to do is to attempt to restrict the first subquery down even more, because right now it is too wide open, essentially matching on _all_ non `pid 4` processes and holding on to state. We should look to restrict it based on executable location or user.id. I know this may present opportunity for FN, however, for performance reasons, I think it is worth the tradeoff.
Without a `maxspan`, this is unbounded for the entire rule run. While this was only 9m, …

[Rule Tuning] Optimize query for Direct Outbound SMB Connection

---

detection_rules/etc/non-ecs-schema.json
rules/windows/lateral_movement_remote_task_creation_winlog.toml

Related to https://github.com/elastic/ia-trade-team/issues/232
using `winlog.event_data.RpcCallClientLocality : 0` we can infer that the task was created via remote RPC calls. This will limit rule scope to Win10/19 +

[Tuning] Remote Scheduled Task Creation

---

detection_rules/main.py
detection_rules/rule.py

* https://github.com/elastic/detection-rules/issues/3363
This pull request adds `--add-metadata` argument to the `export-rules` CLI command. This addition is required for rules-as-data initiative in the issue referenced above. It also enables users to include metadata in rule JSON objects if desired. 
For this to work, `to_api_format()` had to be adjusted to add an option for including the metadata, similar to version. By default this is `False` as `to_api_format()` is commonly used for other commands, including building release packages. This way, the capability is exposed but does not alter the normal flow of rule loading and conversion.
**Run export-rules on all rules**
```
python -m detection_rules export-rules --directory rules/ --include-metadata
```
**Test single rule**
```
python …
```

[FR] Add `--include-metadata` argument to `export-rules` command

---

rules/integrations/cloud_defend/privilege_escalation_debugfs_launched_inside_a_privileged_container.toml
rules/integrations/cloud_defend/privilege_escalation_mount_launched_inside_a_privileged_container.toml

Tuning to update the min_stack version for 2 rules using a field introduced to ecs in 8.10.0 : `container.security_context.privileged`

[Tuning] Update min_stack for container rules new ecs field 

---

detection_rules/utils.py

https://github.com/elastic/ia-trade-team/issues/245
This PR updates the event sorting to use datetime objects instead of direct numeric comparison. Python 3 supports direct comparison and sorting of datetime objects. 
Run the `collect-events` command with an RTA against an Elastic stack with a host with the Elastic agent running.
Example command: 
```shell
python -m detection_rules es --cloud-id <CLOUD_ID> collect-events --rta-name <RTA_NAME> <HOST_ID>
```
When doing this make sure to execute the RTA on the host as well in order to generate some events to capture. 
<details><summary>Example Output</summary>
<p>
On development machine
```shell
> python -m detection_rules es --cloud-id <CLOUD_ID> collect-events --rta-name adobe_hijack <HOST_ID>
█▀▀▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄   ▄ …
```

[FR] Update _event_sort to use datetime instead of time

---

rules/linux/defense_evasion_chattr_immutable_file.toml
rules/linux/persistence_etc_file_creation.toml

Found while Testing rules for https://github.com/elastic/endpoint-rules/issues/3228
- Two of the Linux Rules user users.name == "root" as a query criteria in them
- File made Immutable by Chattr
- Suspicious File Creation in /etc for Persistence
- While testing for some behaviours in issue mentioned I found not all instances user.name is enumerated as "root" on one of the test systems it is enumerated as  "r00t". This would mean the query would not identify such edge cases.
- Hence I have changed the query to use user.id=="0" instead which provides correct results for both the queries
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTR …

Linux Rule Tuning

---

rules/windows/persistence_suspicious_com_hijack_registry.toml
rules/windows/persistence_time_provider_mod.toml
rules/windows/persistence_webshell_detection.toml
rules/windows/privilege_escalation_expired_driver_loaded.toml
rules/windows/privilege_escalation_printspooler_service_suspicious_file.toml

Part of #3186 
* Component Object Model Hijacking
* Potential Persistence via Time Provider Modification
* Web Shell Detection: Script Process Child of Common Web Processes
* Expired or Revoked Driver Loaded
* Suspicious PrintSpooler Service Executable File Creation

[Rule Tuning] Windows DR Tuning - 14

---

rules/linux/persistence_kernel_driver_load_by_non_root.toml

Detects the loading of a Linux kernel module by a non-root user through system calls. Threat actors may leverage Linux kernel modules to load a rootkit on a system providing them with complete control and the ability to hide from security products. As other rules monitor for the addition of Linux kernel modules through system utilities or .ko files, this rule covers the gap that evasive rootkits leverage by monitoring for kernel module additions on the lowest level through auditd_manager.
This behavior is possible when a binary is assigned the `cap_sys_module` capability.
```
driver where host.os.type == "linux" and event.dataset == "auditd_manager.auditd" and 
event.action == "loaded-kernel-module" and auditd.data.syscall in ("init_module", "finit_module") and user.id != "0"
```

[New Rule] Kernel Driver Load by non-root User

---

rules/linux/privilege_escalation_netcon_via_sudo_binary.toml

Detects network connections initiated by the "sudo" binary. This behavior is uncommon and may occur in instances where reverse shell shellcode is injected into a process run with elevated permissions via "sudo". Attackers may attempt to inject shellcode into processes running as root, to escalate privileges. 
1 hit in telemetry last 365 days, seems to be suspicious behavior. 1 hit 365 days in my stack, related to process injection testing. 
```
network where host.os.type == "linux" and event.action == "connection_attempted" and event.type == "start" and
process.name == "sudo"
```

[New Rule] Network Connection via Sudo Binary

---

rules/windows/discovery_privileged_localgroup_membership.toml
rules/windows/discovery_whoami_command_activity.toml
rules/windows/execution_apt_solarwinds_backdoor_unusual_child_processes.toml
rules/windows/execution_command_prompt_connecting_to_the_internet.toml
rules/windows/execution_html_help_executable_program_connecting_to_the_internet.toml

Part of #3186 
* Enumeration of Privileged Local Groups Membership
* Whoami Process Activity
* Suspicious SolarWinds Child Process
* Command Prompt Network Connection
* Network Connection via Compiled HTML File

[Rule Tuning] Windows DR Tuning - 10

---

rules/windows/lateral_movement_suspicious_rdp_client_imageload.toml
rules/windows/persistence_appinitdlls_registry.toml
rules/windows/persistence_local_scheduled_job_creation.toml
rules/windows/persistence_scheduled_task_creation_winlog.toml
rules/windows/persistence_services_registry.toml

Part of #3186 
* Suspicious RDP ActiveX Client Loaded
* Registry Persistence via AppInit DLL
* Persistence via Scheduled Job Creation
* A scheduled task was created
* Unusual Persistence via Services Registry

[Rule Tuning] Windows DR Tuning - 13

---

detection_rules/rule_validators.py

#3371 
This PR modifies the way we validate integration rules by refactoring the validate_integrations method in the eql and kql validator classes. The major change was to ensure the validation catches different combinations of rules and edge cases:
1. The base case where rules have fields that belong to a package-integration schema
2. Case where a field is in a schema of a package with no integration (integration=None)
3. Case where a field is in a package-integration schema but not in any other package-integration combination possible with the rule (e.g. a rule that has OR between different datasets)
4. Case where a field is in a later schema of a package-integration combination, but the rule is minstacked lower to a non-supported combination
5. Case where parsing kql errors lines …

[FR] Update Validate Integrations to Check Fields Across All Schema Variations

---

tests/test_all_rules.py

* https://github.com/elastic/detection-rules/issues/3394
This PR fixes the `TestRuleTiming.test_event_override` unit test by doing the following:
- Removes `rule_integrations` variable as it is not used in the logic to determine if the `timestamp_override` field is necessary
- Removes `rule_query` since we are using `is_sequence()` method to determine if the EQL query uses sequences
- Changes `"sequence" in rule_query` to `rule.contents.data.is_sequence`
Note: While `is_sequence` is a method of `EQLRuleData`, it exists as an attribute of this object because `QueryRuleData` is inherited into these dataclass. We only run the rest of this unit test if the `rule.contents.data` is `QueryRuleData`.

[Bug] Cleanup test_event_override unit test

---

rules/windows/defense_evasion_wsl_filesystem.toml

Drops endgame support, the query uses `process.entity_id`, which is not populated by Endgame.

[Rule Tuning] Host Files System Changes via Windows Subsystem for Linux

---

rules/windows/lateral_movement_direct_outbound_smb_connection.toml

* Drops Sysmon support as we are using process code signature fields.
* Limits the query to unsigned or MS-signed executables.

[Rule Tuning] Direct Outbound SMB Connection

---

rules/windows/credential_access_dcsync_newterm_subjectuser.toml
rules/windows/credential_access_dcsync_replication_rights.toml

add new event action for 4662 `object-operation-performed`. https://elasticstack.slack.com/archives/C018PDGK6JU/p1706360190882899

[Tuning] DCSync Rules - 4662 event.action

---

rules/cross-platform/command_and_control_google_drive_malicious_file_download.toml

rule is generating lot of FPs, use of sequence is unecessary, since the main suspicious part is the process arguments pointing to google drive and the download and AV exclusion url flags. In addition the expected process to handle phishing URLs are browser processes (excluded in previous logic) which will cause to miss the scenario referenced in the referecnes url https://github.com/elastic/detection-rules/blob/main/rules/cross-platform/command_and_control_google_drive_malicious_file_download.toml#L25

[Tuning] Suspicious File Downloaded from Google Drive

---

rules/windows/lateral_movement_remote_task_creation_winlog.toml

https://github.com/elastic/detection-rules/issues/3417 
added `winlog.event_data.ClientProcessId:"0"` to resolve FPs related to default value of 0 for `winlog.event_data.RpcCallClientLocality : "0"`

[Tuning] Remote Scheduled Task Creation via RPC

---

rules/linux/persistence_systemd_netcon.toml

Detects suspicious network events executed by systemd, potentially indicating persistence through a systemd backdoor. Systemd is a system and service manager for Linux operating systems, used to initialize and manage system processes. Attackers can backdoor systemd for persistence by creating or modifying systemd unit files to execute malicious scripts or commands, or by replacing legitimate systemd binaries with compromised ones, ensuring that their malicious code is automatically executed at system startup or during certain system events.
0 FPs in telemetry / my own stack.
```
sequence by host.id with maxspan=5s
[process where host.os.type == "linux" and event.action == "exec" and event.type == "start" and
process.parent.name == "systemd" and process.name in (
"python*", "php*", "perl", …
```

[New Rule] Suspicious Network Connection via systemd

---

rules/linux/defense_evasion_kthreadd_masquerading.toml

Monitors for kernel processes with associated process executable fields that are not empty. Unix kernel processes such  as kthreadd and kworker typically do not have process.executable fields associated to them. Attackers may attempt to hide their malicious programs by masquerading as legitimate kernel processes.

[New Rule] Executable Masquerading as Kernel Process

---

.github/workflows/release-fleet.yml
detection_rules/devtools.py

* https://github.com/elastic/detection-rules/issues/3374
This pull request fixes the Detection Rules release workflow and related CLI commands used. Below is a list of issues that were addressed and have more detailed information in the related issue.
- Automatic Locked Version Workflow Commit Hash Identification
- Incorrect use of branch version for determining previous release packages from EPR
- Add historical rules not default since the dropped support for 8.7 and previous 
- Integrations PR labeling and description updates
```[tasklist]
```
Testing will be a big part of these updates. The importance of testing it to ensure these important steps work as intended:
- Locked Versions workflow commit is properly obtained and used after checking out protected branches
- When …

[Bug] Update Prebuilt Detection Rules Release Process

---

PHILOSOPHY.md

None
Adopt the [Zen of Security Rules](https://zenofsecurity.io/rules) into the philosophy

Add the Zen of Security Rules to philosophy

---

detection_rules/rule.py
detection_rules/schemas/definitions.py
tests/test_all_rules.py

Resolves #3393
Adds support for alert supression with threshold rules. The changes predominately mirror logic added in [171423](https://github.com/elastic/kibana/pull/171423) with some tweaks to better align:
- Broke out `AlertSuppressionDuration` to be reused across rule multiple schema data classes (similar to implementation upstream).
- Added a dedicated definition for `AlertSuppressionGroupBy` to enforce limitations, and removed `test_group_length` duplicative unit test
- Updates the unit test to check minstack (8.12) for the feature
1. Try importing rules exported from Kibana `python -m detection_rules import-rules`. Note: the default importer skips optional fields like alert suppression, so you'll have to make adjustments for this.
Three combinations in the …

[FR] Add support for Threshold Alert Suppression

---

rules/linux/credential_access_potential_linux_local_account_bruteforce.toml
rules/linux/credential_access_proc_credential_dumping.toml
rules/linux/defense_evasion_base16_or_base32_encoding_or_decoding_activity.toml
rules/linux/defense_evasion_binary_copied_to_suspicious_directory.toml
rules/linux/defense_evasion_clear_kernel_ring_buffer.toml

Part 2 of the Linux DR tuning. Besides regular rule tuning, this PR added compatibility with additional data sources where possible, added correct tags/indices, fixed formatting, and checked for potential rule performance increases.

[Tuning] Linux DR Tuning - Part 2

---

rules/linux/defense_evasion_attempt_to_disable_iptables_or_firewall.toml
rules/linux/defense_evasion_disable_apparmor_attempt.toml
rules/linux/defense_evasion_disable_selinux_attempt.toml
rules/linux/defense_evasion_esxi_suspicious_timestomp_touch.toml
rules/linux/defense_evasion_file_deletion_via_shred.toml

Part 3 of the Linux DR tuning. Besides regular rule tuning, this PR added compatibility with additional data sources where possible, added correct tags/indices, fixed formatting, and checked for potential rule performance increases.

[Tuning] Linux DR Tuning - Part 3

---

rules/linux/credential_access_potential_successful_linux_ftp_bruteforce.toml
rules/linux/credential_access_potential_successful_linux_rdp_bruteforce.toml
rules/linux/discovery_pspy_process_monitoring_detected.toml
rules/linux/execution_shell_via_meterpreter_linux.toml
rules/linux/execution_shell_via_udp_cli_utility_linux.toml
rules/linux/persistence_kernel_driver_load_by_non_root.toml
rules/linux/privilege_escalation_suspicious_chown_fowner_elevation.toml
rules/linux/privilege_escalation_suspicious_passwd_file_write.toml
rules_building_block/discovery_kernel_module_enumeration_via_proc.toml
rules_building_block/discovery_linux_modprobe_enumeration.toml
rules_building_block/discovery_linux_sysctl_enumeration.toml
rules_building_block/discovery_suspicious_proc_enumeration.toml
rules_building_block/persistence_kernel_driver_load.toml

This PR removes the event.dataset == "auditd_manager.auditd" entries from the Auditd Manager rules. Additionally, it adds the "Data Source: Auditd Manager" tag to the tag list. The reasoning behind this is documented in https://github.com/elastic/detection-rules/pull/3430.

[Tuning] Event.dataset removal & Tag Addition

---

rules/integrations/aws/persistence_route_table_created.toml
rules/integrations/aws/persistence_route_table_modified_or_deleted.toml

Closes #3498 
Closes #3499 
The rules _AWS Route Table Created_ and _AWS Route Table Modified or Deleted_ are using the wrong `event.provider`, this PR correct the `event.provider` from `cloudtrail.amazonaws.com` to `ec2.amazonaws.com`

[ Rule Tuning ] Correct the provider for AWS Route Table Created and AWS Route Table Modified or Deleted

---

rules/network/command_and_control_port_26_activity.toml

N/A
Tunes the rule to remove the branch of the query where event.dataset matched two different datasets.
See [slack convo](https://elastic.slack.com/archives/C02USDK55AQ/p1710780645002749).

[Rule Tuning] SMTP on Port 26/TCP

---

detection_rules/eswrap.py

https://github.com/elastic/detection-rules/issues/3530
This PR updates the sort parameter so that the `collect-events` command functions correctly with  the `elasticsearch` 8.12 python library. See issue for more background/context info. 
Run collect events and make sure you can collect data. If data is collected, the test is successful. 
```shell
endpoint-rules on  2356-fr-add-host-family-to-data-path [?] via  v3.8.10 (venv) on  eric.forte took 20s 
❯ python -m endpoint_rules es --cloud-id <cloud_id> collect-events --rta-name bitsadmin_execution <host_id>
███████╗███╗   ██╗██████╗ ██████╗  ██████╗ ██╗███╗   ██╗████████╗
██╔════╝████╗  ██║██╔══██╗██╔══██╗██╔═══██╗██║████╗  ██║╚══██╔══╝
█████╗  ██╔██╗ ██║██║  ██║██████╔╝██║   ██║██║██╔██╗ ██║   ██║
██╔══╝  ██║╚██╗██║██║  ██║██╔═══╝ ██║ …
```

[Bug] Update Sort Parameter

---

rules/windows/lateral_movement_remote_services.toml

fix typo in rule, the extra quote was getting rendered 
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? yes
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)? yes

fix typo  in lateral_movement_remote_services.toml

---

rules/windows/credential_access_adidns_wildcard.toml

Active Directory Integrated DNS (ADIDNS) is one of the core components of AD DS, leveraging AD's access control and
replication to maintain domain consistency. It stores DNS zones as AD objects, a feature that, while robust, introduces
some security issues, such as wildcard records, mainly because of the default permission to create DNS-named records.
Attackers can create wildcard records to redirect traffic that doesn't explicitly match records contained in the zone,
becoming the Man-in-the-Middle and being able to abuse DNS similarly to LLMNR/NBNS spoofing.
<details>
<summary> Event Data </summary>
```
{
"_index": ".ds-logs-system.security-default-2024.03.13-000023",
"_id": "5nAfe44B1-PCmUgATpBK",
"_version": 1,
"_score": 0,
"_source": {
"input": {
"type": "winlog"
},
"agent": {
"name": …
```

[New Rule] Potential ADIDNS Poisoning via Wildcard Record Creation

---

rules/windows/credential_access_dnsnode_creation.toml

Active Directory Integrated DNS (ADIDNS) is one of the core components of AD DS, leveraging AD's access control and replication to maintain domain consistency. It stores DNS zones as AD objects, a feature that, while robust, introduces some security issues because of the default permission (Any authenticated users) to create DNS-named records. Attackers can perform Dynamic Spoofing attacks, where they monitor LLMNR/NBT-NS requests and create DNS-named records to target systems that are requested from multiple systems. They can also create specific records to target specific services, such as wpad, for spoofing attacks.
<details>
<summary> Event Data </summary>
```
{
"_index": ".ds-logs-system.security-default-2024.03.13-000023",
"_id": "FbmZfI4B1-PCmUgAlUFI",
"_version": 1,
"_score": 0, …
```

[New Rule] Creation of a DNS-Named Record

---

CLI.md
detection_rules/main.py

None, but related to several PRs testing import rules features.
While testing other PRs, I had to manually change this line just to fully test fields that are not required. 
- This exposes a required-only option to the import-rules CLI so that the default isn't set to not import required fields. 
- Updates the CLI.md
- ⚠️ NOTE: This is a breaking change which will prompt users for fields if the `--required-only` flag is not supplied.
- If the CI passes, this should be g2g
- Test the import command with the new field:
<details><summary>Import-Rules CLI</summary>
<p>
```bash
(detection-rules-build) ➜  detection-rules git:(update_import_rules) ✗ python -m detection_rules import-rules /Users/stryker/Downloads/rules_export\(2\).ndjson
Loaded config file: …
```

[FR] Add required-fields option to import-rules

---

detection_rules/devtools.py
detection_rules/etc/packages.yml

#3527
- Use the supported format of GitHub PR for 3.12 
- Per the 3.12 [docs](https://pygithub.readthedocs.io/en/stable/github_objects/Repository.html#github.Repository.Repository.create_pull) the expected format would be
```
pr = repo.create_pull(
base=base_branch,
head=branch_name,
title=message,
body=body,
maintainer_can_modify=True,
draft=draft
)
```

Fix create PR in release workflow

---

detection_rules/rule.py

Resolves https://github.com/elastic/detection-rules/issues/3135
Resolves https://github.com/elastic/detection-rules/issues/3224
- Add's support for the new field `investigation_fields` completed in 8.11 with min_compat set to 8.11
- Original feature was added [here](https://github.com/elastic/kibana/pull/163235) in 8.10 but updated later [here](https://github.com/elastic/kibana/pull/164133) in 8.11
- Added @yctercero who implemented the feature upstream for review
- Didn't add any downgrade functionality since we didn't implement the breaking change included in 8.10
- Note: I did not add validation on the field values. I suspect this will be expensive to do in the data class validation. We could potentially add a unit test that loads all the schemas, but we may run into the same issue …

[FR] Add support for investigation_fields

---

rules/integrations/o365/collection_microsoft_365_new_inbox_rule.toml
rules/integrations/o365/credential_access_microsoft_365_brute_force_user_account_attempt.toml
rules/integrations/o365/credential_access_microsoft_365_potential_password_spraying_attack.toml
rules/integrations/o365/credential_access_user_excessive_sso_logon_errors.toml
rules/integrations/o365/defense_evasion_microsoft_365_exchange_dlp_policy_removed.toml
rules/integrations/o365/defense_evasion_microsoft_365_exchange_malware_filter_policy_deletion.toml
rules/integrations/o365/defense_evasion_microsoft_365_exchange_malware_filter_rule_mod.toml
rules/integrations/o365/defense_evasion_microsoft_365_exchange_safe_attach_rule_disabled.toml
rules/integrations/o365/defense_evasion_microsoft_365_mailboxauditbypassassociation.toml
rules/integrations/o365/exfiltration_microsoft_365_exchange_transport_rule_creation.toml
rules/integrations/o365/exfiltration_microsoft_365_exchange_transport_rule_mod.toml
rules/integrations/o365/impact_microsoft_365_potential_ransomware_activity.toml
rules/integrations/o365/impact_microsoft_365_unusual_volume_of_file_deletion.toml
rules/integrations/o365/initial_access_microsoft_365_abnormal_clientappid.toml
rules/integrations/o365/initial_access_microsoft_365_exchange_anti_phish_policy_deletion.toml
rules/integrations/o365/initial_access_microsoft_365_exchange_anti_phish_rule_mod.toml
rules/integrations/o365/initial_access_microsoft_365_exchange_safelinks_disabled.toml
rules/integrations/o365/initial_access_microsoft_365_user_restricted_from_sending_email.toml
rules/integrations/o365/initial_access_o365_user_reported_phish_malware.toml
rules/integrations/o365/lateral_movement_malware_uploaded_onedrive.toml
rules/integrations/o365/lateral_movement_malware_uploaded_sharepoint.toml
rules/integrations/o365/persistence_exchange_suspicious_mailbox_right_delegation.toml
rules/integrations/o365/persistence_microsoft_365_exchange_dkim_signing_config_disabled.toml
rules/integrations/o365/persistence_microsoft_365_exchange_management_role_assignment.toml
rules/integrations/o365/persistence_microsoft_365_global_administrator_role_assign.toml
rules/integrations/o365/persistence_microsoft_365_teams_custom_app_interaction_allowed.toml
rules/integrations/o365/persistence_microsoft_365_teams_external_access_enabled.toml
rules/integrations/o365/persistence_microsoft_365_teams_guest_access_enabled.toml
rules/integrations/o365/privilege_escalation_new_or_modified_federation_domain.toml

Double version bumop found in lock versions https://github.com/elastic/detection-rules/pull/3564
- Fix the minstack version for breaking changes in o365 integration.
- Identified new minstack as 8.8.0 

Fix minstack version for 0365 prod rules

---

rules/linux/credential_access_potential_linux_ssh_bruteforce_external.toml
rules/linux/credential_access_potential_linux_ssh_bruteforce_internal.toml
rules/linux/credential_access_potential_successful_linux_ssh_bruteforce.toml
rules/linux/persistence_linux_group_creation.toml
rules/linux/persistence_linux_user_account_creation.toml

- #3559 
Add the filebeat-* index pattern to the rules that use the `system.auth` dataset. These rules already contain a "Filebeat setup" section, which is useless if the `filebeat-*` index is not considered during searches. 
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? ✅ 
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)? ✅

Add filebeat-* index pattern to rules based on system.auth dataset

---

detection_rules/rule_formatter.py

Resolves #2418
- Adds a new method `preserve_formatting_for_fields` that can traverse nested dictionaries and mark as a `NonformattedField` so that newlines and whitespaces are preserved. The method is meant to be abstracted enough to support preserving any field by passing in as a dotted notation.
- Preserves the `action.params.message` field.
- Run the importer with the sample file: `python -m detection_rules import-rules /Users/stryker/Downloads/rules_export_mail.ndjson` [rules_export_mail.ndjson.txt](https://github.com/elastic/detection-rules/files/14839897/rules_export_mail.ndjson.txt). The `message` field should preserve newlines in the action.

[Bug] Add explicit format preserver

---

detection_rules/rule.py
detection_rules/rule_validators.py
detection_rules/utils.py
tests/test_all_rules.py

https://github.com/elastic/detection-rules/issues/3573
We would like this uppercase conversion feature to be available for customers but internally we do not want it to be enabled by default. 
See https://github.com/elastic/detection-rules/pull/3568 for more context. There should be 6 instances where we use kql.parse for creating/importing/testing/validation that we wish to revert. The only remaining case we want to keep is the unit test to make sure conversion functions as expected. 
1. Modify an existing `kuery` rule to use uppercase keywords.
E.g. modify the query for `rules/integrations/gcp/defense_evasion_gcp_firewall_rule_created.toml` to:
```toml
query = '''
event.dataset:gcp.audit AND event.action:(*.compute.firewalls.insert OR google.appengine.*.Firewall.Create*Rule)
'''
```
2. …

[FR] Switch Default Behavior to not allow uppercase KQL Keywords 

---

lib/kql/pyproject.toml

https://github.com/elastic/detection-rules/pull/3574
This PR bumps the KQL version due to recent updates to the KQL library (other PR should have had this bump in it).

[FR] Bump KQL Lib Version

---

lib/kql/kql/__init__.py

https://github.com/elastic/detection-rules/pull/3574
https://github.com/elastic/detection-rules/pull/3575
This PR bumps the KQL version due to recent updates to the KQL library (other PRs should have had this bump in it).

[FR] Bump KQL Version in Init

---

rules/windows/defense_evasion_sccm_scnotification_dll.toml

Related to https://github.com/elastic/ia-trade-team/issues/325
This detection rule identifies when 'SCNotification.exe' loads an untrusted DLL, which is a potential indicator of an
attacker attempt to hijack/impersonate a Windows user session.

[New Rule] Potential Windows Session Hijacking via CcmExec

---

rules/windows/persistence_remote_password_reset.toml

* https://github.com/elastic/ia-trade-team/issues/330
This PR reverts the `Account Password Reset Remotely` rule to the version merged correctly in [7a4f1224dc8c0146b28f21ee87b88d8b685fb0e8](https://github.com/elastic/detection-rules/commit/7a4f1224dc8c0146b28f21ee87b88d8b685fb0e8).
This is the last correct version of the rule that was merged in from #3335 for tuning.
From this branch, I ran `view-rule` which showed version 114, then checked out 8.3 and ran the same command to receive the same version, 114. Originally, these versions were split.

[Rule Tuning] Reverting `Account Password Reset Remotely` To Previous Version

---

rules/windows/persistence_remote_password_reset.toml

* https://github.com/elastic/ia-trade-team/issues/330
This PR updated the performance note for this rule. This change should backport to 8.3 and thus return the rule to a specific state across all branches, while resolving the version lock issue mentioned in the issue above.

[Rule Tuning] Update Performance Note in `Account Password Reset Remotely` and Backport to 8.3

---

rules/integrations/azure/initial_access_consent_grant_attack_via_azure_registered_application.toml

Identified during https://github.com/elastic/ia-trade-team/issues/330
- Similar to https://github.com/elastic/detection-rules/pull/3565
- Microsoft 365 integration has breaking change in 8.80 and one of azure rules uses that integration.
- This change address the minstack version fix to avoid double bump. 
Until Versions 8.3-->8.7 for the rule "rules/integrations/azure/initial_access_consent_grant_attack_via_azure_registered_application.toml"
```
"related_integrations": [
{
"integration": "activitylogs",
"package": "azure",
"version": "^1.0.0"
},
{
"package": "azure",
"version": "^1.0.0"
},
{
"package": "o365",
"version": "^1.3.0"
}
],
```
From versions 8.8-->8.13  for the rule "rules/integrations/azure/initial_access_consent_grant_attack_via_azure_registered_application.toml"
``` …
```

Fix minstack version for 0365 in azure integration rules

---

detection_rules/rule.py
rules/integrations/aws/impact_aws_s3_bucket_enumeration_or_brute_force.toml

It was recently [shared](https://medium.com/@maciej.pocwierz/how-an-empty-s3-bucket-can-make-your-aws-bill-explode-934a383cb8b1) that S3 buckets are vulnerable to exhaustive `PUT` requests for the sake of causing financial impact to an organization, only needing to know the bucket name. (AWS did [respond](https://x.com/jeffbarr/status/1785386554372042890) quickly that they were addressing the billing of such operations).
What makes this slightly more impactful is the fact that bucket names themselves are trivially discoverable via enumeration, allowing for randomized or targeted brute forcing in a simple manner.
AWS S3 buckets can be be brute forced to cause financial impact against the resource owner. What makes this even riskier is that even private, locked down buckets can still …

[New Rule] AWS S3 Bucket Enumeration or Brute Force

---

detection_rules/navigator.py

Main are currently failing due to an ESQL rule being merged (which does not have `index`). This resolves that bug

[Bug] Fix missing indexes on navigator build

---

detection_rules/rule_formatter.py

https://github.com/elastic/detection-rules/issues/3667
This updates the rule formatter to handle backslashes correctly.
Prior to this fix running the `python -m detection_rules dev attack update-rules` command would cause the following breaking change in `rules/windows/privilege_escalation_group_policy_iniscript.toml` to the note section.
Breaking Change:
```
The scripts are stored in the following paths:
- `<GPOPath>\Machine\Scripts\`
- `<GPOPath>\User\Scripts\`
```
Running the command with the current update results in:
```
The scripts are stored in the following paths:
- `<GPOPath>\\Machine\\Scripts\\`
- `<GPOPath>\\User\\Scripts\\`
```
Which is the desired behavior.

[Bug] Update Rule Formatter

---

.github/workflows/backport.yml
.github/workflows/get-target-branches.yml
.github/workflows/lock-versions.yml
.github/workflows/manual-backport.yml
.github/workflows/pythonpackage.yml
.github/workflows/release-docs.yml
.github/workflows/release-fleet.yml
CLI.md
Makefile
README.md
detection_rules/etc/test_cli.bash
pyproject.toml

Related to https://github.com/elastic/detection-rules/pull/3514
Instead of bundling kql/kibana packages separately, add the packages to the code pyproject.toml using the git+ url.
Note: This implies that kql/kibana will pull from `main` git. For local development you will need to uninstall the git version and install locally for testing/dev. 
Updates the test cli script to use the new export command.
- CI should pass
- `make test-cli` and `make test-remote-cli` should pass.
- `make` should work as expected.
<details><summary>Make output</summary>
<p>
```
➜  detection-rules git:(main) ✗ make
python3.12 -m pip install --upgrade pip setuptools
Looking in indexes: https://pypi.org/simple, https://artifactory.elastic.dev/artifactory/api/pypi/pypi-endgame/simple
Requirement already satisfied: …
```

[FR] Bundle KQL & Kibana libs into base dependencies

---

docs/custom-rules.md

https://github.com/elastic/detection-rules/issues/3672
Adds some updates to the custom-rules.md based on some recent updates to the DAC-Feature branch.

[FR] [DAC] Update custom-rules.md with Additional Notes

---

detection_rules/custom_rules.py

N/A 
Adds the building block rule folder as part of the default setup
Run `python -m detection-rules custom-rules setup-config <path>` should generate a config with the `bbr_rules_dir` populated instead of an empty `[]`.

[FR] Update custom rules setup

---

detection_rules/cli_utils.py

https://github.com/elastic/detection-rules/pull/3654
Small PR to add the default functionality of using the Rules config default directories if none are specified. 
Use `python -m detection_rules kibana import-rules --overwrite` to add or update a rule from your config in Kibana.

[FR] [DAC] Use Rules Config Directories If None Specified 

---

detection_rules/custom_rules.py

https://github.com/elastic/detection-rules/issues/3682
This PR changed the behavior of `setup-config` to by bypass the following unit tests (specific to Elastic package release version locking)
```
- tests.test_gh_workflows.TestWorkflows.test_matrix_to_lock_version_defaults
- tests.test_schemas.TestVersionLockSchema.test_version_lock_has_nested_previous
- tests.test_packages.TestRegistryPackage.test_registry_package_config
- tests.test_all_rules.TestValidRules.test_schema_and_dupes
```
It also introduces a flag `-e` to allow one to change this behavior to have these bypasses commented out to enable all unit tests.
To test try making configs without the `-e` flag and with the flag. After this, run `make test` with your non-`-e` config specified through the `CUSTOM_RULES_DIR` environment …

[FR] [DAC] Add Flag to Enable All Prebuilt Tests

---

lib/kibana/kibana/__init__.py
lib/kibana/kibana/connector.py
lib/kibana/pyproject.toml

N/A
When trying to import / export rules to Kibana with spaces, the `space` in the url is lowercased.
If you create a space called `DEV` the url will have `s/dev`. To support this, we need to ensure we're supplying the lowercased version of the space to match the `URL identifier`.
Try to import and export rules with a space name that is capitalized and lowercased URL identifier:
- `python -m detection_rules kibana --space devs import-rules --directory mikas_dir/rules/`
- `python -m detection_rules kibana --space dev export-rules -d mikas_dir/rules/`

[Bug] Support spaces with capital letters

---

detection_rules/devtools.py

This PR adds a `--force` flag to lock versions to allow this command to be run in CI such that users can lock versions without needing to build a package. 
` python -m detection_rules dev update-lock-versions --force` should not have a confirm prompt.

[FR] Add --force flag to update-lock-versions

---

detection_rules/etc/packages.yaml
detection_rules/schemas/registry_package.py

- Related to https://github.com/elastic/integrations/pull/9938
- Add security capability to package manifest to match to the changes https://github.com/elastic/integrations/pull/9938
- This should backport to 8.12 as we use to format version 3.0.0 and this capability is available from 2.10.0 https://github.com/elastic/package-spec/blob/db9a76d9534bca28a227d24543d80c5413c77ed6/spec/changelog.yml#L184
- We don't have to worry on packages 8.11 and below as this change is tightly coupled to RegistryPackageManifestV3 Data class.

Package Manifest changes to add capabilities

---

.github/workflows/backport.yml
pyproject.toml

- Failures https://github.com/elastic/detection-rules/actions/runs/9286062166/job/25551938923
Seems to be an issue with package versions of nodeenv1.9.0 which stopped coupling up setuptools along with. 
We have the following dependency 
- Collecting nodeenv>=0.11.1 (from pre-commit==3.6.2->detection_rules==0.1.0)
- The previous installations nodeenv-1.8.0-py2.py3-none-any.whl.metadata  got in [setuptools](https://github.com/elastic/detection-rules/actions/runs/9275165818/job/25519208988) 
- Collecting setuptools (from nodeenv>=0.11.1->pre-commit==3.6.2->detection_rules==0.1.0)
- Now recent runs are using nodeenv-1.9.0-py2.py3-none-any.whl.metadata (21 kB) which does not bundle this up!
- Fix nodeenv to previous known version 1.8.0

Fix nodeenv version dependancy

---

rules/integrations/o365/credential_access_microsoft_365_brute_force_user_account_attempt.toml

Closes #3694 
The query rule has been updated to exclude a logon error for non-existing users via SSO, an interrupt requiring registration in self-service password reset, and two high volume logon errors related to Conditional Access Policy expiration.
x Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
x Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

[Rule Tuning] Tune exceptions for M365 Brute Force User Attempt

---

rules/integrations/dga/command_and_control_ml_dga_activity_using_sunburst_domain.toml
rules/integrations/dga/command_and_control_ml_dga_high_sum_probability.toml
rules/integrations/dga/command_and_control_ml_dns_request_high_dga_probability.toml
rules/integrations/dga/command_and_control_ml_dns_request_predicted_to_be_a_dga_domain.toml
rules/integrations/problemchild/defense_evasion_ml_suspicious_windows_event.toml
rules/integrations/problemchild/defense_evasion_ml_suspicious_windows_event_high_probability.toml

Related to Security Doc Build [Failures](https://buildkite.com/elastic/docs-build-pr/builds/86313#018fc9b4-90ac-4f7e-a68f-1980f1a9df67)
- There is a [rouge backtick](https://github.com/elastic/detection-rules/pull/3652/files#diff-a4e0110b58dfb4ebe75271a82820d74da69044bc480c0d3307a34a012cc8ca65L69) that is left when the rule tuning went in as part of [PR](https://github.com/elastic/detection-rules/pull/3652) for DGA Rules. 
- This caused the invalid references and we have cleaned this up in the documents.
- This PR corrects those backticks

Remove unwanted backticks

---

rules/integrations/aws/discovery_new_terms_sts_getcalleridentity.toml

+ https://github.com/elastic/ia-trade-team/issues/346 
Identifies the use of `sts:GetCallerIdentity` API function. This is equivalent to `whoami` in linux and provides the caller with the user identity information for the set of credentials being used. A legitimate user would likely not need to make this call as they know who they are, and this is especially suspicious behavior coming from a service like Lambda or an EC2 instance role. `GetCallerIdentity` does not require any permissions as it returns the same information even when explicit deny policies  are in place that deny access to the API. For this reason I've decided not to include `event.outcome: success` as part of the query.
This is a new_terms rule as some operations may need to call the GetCallerIdentity function as part of …

[New Rule] AWS GetCallerIdentity API Called for the First Time

---

rules/cross-platform/defense_evasion_agent_spoofing_mismatched_id.toml

This PR adds `mismatch` to the `event.agent_id_status` field within the query, as newer Elastic agents no longer mark this as `agent_id_mismatch`. 
This is checked with the LS data, and would've flagged the rogue host.

[Rule Tuning] Agent Spoofing

---

rules/windows/persistence_user_account_added_to_privileged_group_ad.toml

Related to #3005 
Expands the rule to detect modifications to these groups on non-English AD envs.

[Rule Tuning] User Added to Privileged Group

---

rules_building_block/discovery_userdata_request_from_ec2_instance.toml

* https://github.com/elastic/sdh-protections/issues/490
Per SDH, `Attempt to Retrieve User Data from AWS EC2 Instance` had an incorrect index mapping for AWS Cloudtrail data. Instead of `logs.aws.cloudtrail-*`, it should have been `logs-aws.cloudtrail-*`. I have verified all of the other AWS rules did not have this issue.

[Rule Tuning] Fixing index in `Attempt to Retrieve User Data from AWS EC2 Instance`

---

rules/windows/collection_email_powershell_exchange_mailbox.toml
rules/windows/command_and_control_port_forwarding_added_registry.toml
rules/windows/command_and_control_rdp_tunnel_plink.toml
rules/windows/command_and_control_screenconnect_childproc.toml
rules/windows/credential_access_domain_backup_dpapi_private_keys.toml
rules/windows/credential_access_kirbi_file.toml
rules/windows/credential_access_mimikatz_memssp_default_logs.toml
rules/windows/defense_evasion_amsi_bypass_dllhijack.toml
rules/windows/defense_evasion_hide_encoded_executable_registry.toml
rules/windows/defense_evasion_masquerading_suspicious_werfault_childproc.toml
rules/windows/defense_evasion_persistence_account_tokenfilterpolicy.toml
rules/windows/defense_evasion_suspicious_zoom_child_process.toml
rules/windows/execution_command_shell_started_by_unusual_process.toml
rules/windows/initial_access_suspicious_ms_outlook_child_process.toml
rules/windows/persistence_adobe_hijack_persistence.toml
rules/windows/persistence_appcertdlls_registry.toml
rules/windows/persistence_local_scheduled_job_creation.toml
rules/windows/persistence_system_shells_via_services.toml
rules/windows/persistence_via_bits_job_notify_command.toml
rules/windows/persistence_webshell_detection.toml

Double Bump in Version Lock https://github.com/elastic/detection-rules/pull/3776
- Follow steps of `How do I Fix double version bumps for related integrations rules` in [FAQ](https://github.com/elastic/ia-trade-team/wiki/Detection-Rules-Releasing-v2#faq)
- Update Min stack version for all affected rules
- SentinelOne integration version changed across versions documented [here](https://github.com/elastic/detection-rules/pull/3777#issuecomment-2160672392)

Update Minstack versions for SentinelOne rules

---

rules/integrations/aws/privilege_escalation_sts_assumerole_usage.toml
rules/threat_intel/threat_intel_rapid7_threat_command.toml

The existing Rapid7 CVEs rule is querying on wrong `threat_index` and `filters`.
1. The `threat_index` value is updated to `logs-ti_rapid7_threat_command_latest.vulnerability` which represents the index for storing vulnerabilities. Previously, the rule was pointing at `logs-ti_rapid7_threat_command_latest.ioc` which represents threat indicators.
2. Fixes the `filters` as they are wrongly applied to `threat_filters` as per https://github.com/elastic/integrations/issues/7360#issuecomment-2138798243.

[Rule Tuning]: Fix threat_index and filters in Rapid7 CVE rule

---

rules/integrations/okta/initial_access_okta_user_sessions_started_from_different_geolocations.toml

* https://github.com/elastic/detection-rules/issues/3438
This pull request tunes the `Okta User Sessions Started from Different Geolocations` after recommendation from the related issue. Note, we have added an investigation guide as well tailored for this activity. In addition, we have converted this to ES|QL.

[Rule Tuning] Okta User Sessions Started from Different Geolocations

---

rules/integrations/okta/credential_access_okta_authentication_for_multiple_users_from_single_source.toml
rules/integrations/okta/credential_access_okta_authentication_for_multiple_users_with_the_same_device_token_hash.toml
rules/integrations/okta/credential_access_okta_credential_stuffing_by_unique_device.toml
rules/integrations/okta/credential_access_okta_multiple_device_token_hashes_for_single_user.toml

This pull request adds new threat detection rules for Okta data that identify potential credential stuffing or password spraying attempt by adversaries. These rules leverage ES|QL to aggregate specific attributes of the authentication requests that should identify anomalies based on high counts.
These rules focus primarily on authentication via Okta's API endpoint `/api/v1/authn` which adversaries often use to test stolen credentials from infostealers or third-party markets. 
- Okta's Device Token Hash (`okta.debug_context.debug_data.dt_hash`) is a cookie used to identify client devices, and once an authenticated session is established, remains persistent for the lifetime of the session. However, if a request is invalid, a new device …

[New Rule] Okta Credential Stuffing and Password Spraying Identification via Source, Device Token and Actor

---

rules/cross-platform/defense_evasion_agent_spoofing_multiple_hosts.toml

This PR adds an exception for events tagged as "forwarded". These events don't contain information about the host running the agent, such as `host.id` or `host.name`. Certain integrations, including entity analytics, ingested EDR (eg M365 Defender) logs, and vulnerability management may populate these fields with details about the host or device in that event. 
An alert is triggered on each run after these events are ingested. Excluding forwarded events will reduce false positives.
Closes #3613 
The rule's query has been tuned to exclude forwarded events.

 [Rule Tuning]  Agent Spoofing - Multiple Hosts Using Same Agent

---

rules/windows/credential_access_lsass_openprocess_api.toml

Re-introduces the code signature check with a different approach + optional field.
Context: https://elastic.slack.com/archives/C02USDK55AQ/p1719415974247789?thread_ts=1719410796.090999&cid=C02USDK55AQ

[Rule Tuning] LSASS Process Access via Windows API

---

rules/integrations/aws/impact_s3_bucket_object_uploaded_with_ransom_extension.toml

Tunes the 'Potential AWS S3 Bucket Ransomware Note Uploaded' rule by removing the extension `.` from the ES|QL WHERE clause. During testing from https://rhinosecuritylabs.com/aws/s3-ransomware-part-1-attack-vector/, Isai noticed that since we do not filter for `.txt`, this rule did not fire, however `ransom` was in the file name. Therefore the changes will allow these very specific encryption strings to be allowed within the file name or extension.
Telemetry was referenced to determine if any additional tuning was necessary, however global alerts for this rule have not been observed yet.

[Rule Tuning] Potential AWS S3 Bucket Ransomware Note Uploaded 

---

detection_rules/config.py
detection_rules/devtools.py
detection_rules/eswrap.py
detection_rules/etc/_config.yaml
detection_rules/rule.py
detection_rules/rule_validators.py
detection_rules/utils.py
docs/custom-rules.md
tests/test_all_rules.py
tests/test_mappings.py

https://github.com/elastic/detection-rules/issues/3624
https://github.com/elastic/detection-rules/pull/3574
This PR updates the default KQL parsing behavior when a custom rule directory is set. Now when the `NORMALIZE_KQL_KEYWORDS` environment variable is set, the normalization flag is set to `True`
Make a custom KQL rule and modify the keyword to be upper case and test with view rule.
<details><summary>Example KQL Rule</summary>
<p>
```
[metadata]
creation_date = "2023/05/22"
maturity = "production"
updated_date = "2024/05/21"
[transform]
[[transform.osquery]]
label = "Osquery - Retrieve DNS Cache"
query = "SELECT * FROM dns_cache"
[[transform.osquery]]
label = "Osquery - Retrieve All Services"
query = "SELECT description, display_name, name, path, pid, service_type, start_type, status, …
```

[FR] [DAC] Update default KQL parsing behavior to normalize keywords for custom rule directories.

---

detection_rules/rule.py

https://github.com/elastic/detection-rules/issues/3843
This PR addresses an issue where MITRE Updated the format in which the URLs were supplied for the MITRE ATT&CK Framework. Originally they were supplied with a trailing `/` and now they are supplied without it. Given that we will want to support rules under both older and newer versions of MITRE ATT&CK, the proposed solution is to add a pre-load check which will modify the reference URLs to match the required schema. 
Create a rule in Kibana and add MITRE ATT&CK information. Prior to this fix, using the DAC export rules command would result in schema errors in any rules with MITRE ATT&CK information. Now the rule should export successfully. 
Example Run:
<details><summary>Details</summary>
<p>
Example Rule:
```toml
[metadata] …
```

[FR] Added Modify URL Preload Function

---

rules/windows/credential_access_adidns_wildcard.toml
rules/windows/credential_access_adidns_wpad_record.toml
rules/windows/credential_access_dnsnode_creation.toml
rules/windows/credential_access_ldap_attributes.toml
rules/windows/credential_access_shadow_credentials.toml
rules/windows/credential_access_spn_attribute_modified.toml
rules/windows/discovery_high_number_ad_properties.toml
rules/windows/persistence_ad_adminsdholder.toml
rules/windows/persistence_sdprop_exclusion_dsheuristics.toml
rules/windows/privilege_escalation_credroaming_ldap.toml

Fix the `event.action` conditions.
This [PR](https://github.com/elastic/integrations/pull/8289) introduced hard coded values to the `event.action` fields for 5136 and 4662 events, which break the conditions we have on our rules.

[Rule Tuning] Fix event.action conditions - AD Rules

---

detection_rules/packaging.py
detection_rules/rule.py
detection_rules/rule_validators.py

https://github.com/elastic/detection-rules/issues/3697
This PR adds a property to `QueryRuleData` that allows you to use either index or data view depending on which one is set. This PR is dependent on a validation update to main that prevents both indexes and data views from being set. 
Please review and merge https://github.com/elastic/detection-rules/pull/3830 first and backport this to DAC-Feature before reviewing this PR. **Update: 3830 is now Merged.**
Note: There are a few remaining `data.index` calls that do not appear to support using this property. For example, in `validate_eql`  this update is not supported as `data.index` is used as an index parameter to the `self.es_client.eql.search` function call which does not support data views. 
Make a package using `make` to make sure …

[FR] [DAC] Add index_or_dataview Property

---

hunting/generate_markdown.py

* https://github.com/elastic/ia-trade-team/issues/280
⚡ A list of hunting queries (see below) had `ñ` characters in the regex when normalizing paths in ES|QL queries. This was added intentionally to match on that character. However, when running `hunting/generate_markdown.py` script, we did not include UTF-8 encoding on the content when loading the TOML file, only when writing to Markdown. As a result @Aegrah [pointed out](https://github.com/elastic/detection-rules/pull/3872#pullrequestreview-2165516644) that the `ñ` changed when writing to the Markdown files from a Windows host.
This is likely because UTF-8 was used on the writing operations and not the loading.
List of hunts affected:
- Low Occurrence of Suspicious Launch Agent or Launch Daemon
- Low Occurrence Rate of …

[Bug] Hunting - Add UTF-8 Encoding for all Read and Write Operations

---

detection_rules/rule.py

We inadvertently [intoduced](https://github.com/elastic/detection-rules/pull/3857/files#diff-4bfef80203b44ad6eb23895355be52bd3437a54c62666495093527c7c9832749R708) a small bug with a typo. This PR fixes the typo.
Running an export originally triggered this error `python -m detection_rules kibana export-rules -d test_rules/ -sv`. See below:
<details><summary>Prior CLI Snippet</summary>
```bash
File "/Users/stryker/workspace/ElasticGitHub/detection-rules/detection_rules/rule.py", line 734, in validate_query
return validator.validate(self, meta)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/stryker/workspace/ElasticGitHub/detection-rules/detection_rules/rule_validators.py", line 132, in validate
validation_checks["stack"] = self.validate_stack_combos(data, meta) …
```

[Bug] Fix typo in dataview variable

---

detection_rules/cli_utils.py
detection_rules/main.py
detection_rules/rule.py
detection_rules/rule_formatter.py

Related to https://github.com/elastic/detection-rules/issues/3542
This PR supports import/export of the `new_terms` rule type w/custom toml formatting. 
In https://github.com/elastic/detection-rules/pull/2360 We added the inital support to new_terms schemas, however this introduced something new to our ruleset where we added custom formating in our toml files that does not 1-1 match the schema exported from Kibana. The custom formatting within the toml rule IMO is more organized in this way. The original intent also was to manually develop rules for prebuilt content and push externally (one-way support).
The problem is that it introduced an issue where it prevented us from importing the rules from ndjson since the schemas do not much (two-way support of import/export).
In …

[FR] Support new_terms schema import/export w/custom format

---

detection_rules/main.py

This PR addresses a few issues in the `import_rules_into_repo` command on the DAC-Feature branch where the rule_prompt would attempt to import exceptions as rule if the `-e` flag was not used and there are exceptions in the .ndjson export. Also, this addresses a case where the exceptions would be parsed unnecessarily even if the `-e` flag was not used. Additionally I added some cleaner error handling for cases where exception parsing is desired but no directory is specified for writing the files.
To test run the following command without a rules config env variable set, and you should have a clean FileNotFound error message. 
<details><summary>Example</summary>
<p>
```shell
detection-rules on  import_rules_into_repo_bug [$!?] is  v0.1.0 via  v3.12.4 …
```

[Bug] [DAC] Import rules into repo loads exceptions without argument

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/add-guidelines.yml

*Issue*: Remove Rule: Promotion in https://github.com/elastic/detection-rules/blob/main/.github/workflows/add-guidelines.yml#L19 since promotions don't exist in detection rules
- Remove Rule:Promotion
- Add schema and hunting lables
- Add relavant labels to test

Remove Rule:Promotion labels and add other relavent labels

---

rules/linux/persistence_user_or_group_creation_or_modification.toml

Added setup guide instructions to this rule, to allow customers to more easily set up the necessary auditd rules.

[Rule Tuning] Updated setup guide

---

rules/linux/persistence_git_hook_execution.toml
rules/linux/persistence_git_hook_netcon.toml

This PR adds two new rules that are deprecated from ER due to the rules not being malicious activity all the time. These rules are better suited for DR.
- Git Hook Egress Network Connection
- Git Hook Command Execution
This rule detects a suspicious egress network connection attempt from a Git hook script. Git hooks are scripts that Git executes before or after events such as: commit, push, and receive. An attacker can abuse these features to execute arbitrary commands on the system, establish persistence or to initialize a network connection to a remote server and exfiltrate data or download additional payloads.
This rule has only TPs in my testing stack, and several hits in telemetry (as it got converted from ER back to DR)
This rule detects the execution of a potentially malicious …

[New Rules] Git Hook execution/netcon

---

rules/integrations/aws/impact_s3_object_versioning_disabled.toml

- https://github.com/elastic/ia-trade-team/issues/346
Identifies when object versioning is suspended for an Amazon S3 bucket. Object versioning allows for multiple versions of an object to exist in the same bucket. This allows for easy recovery of deleted or overwritten objects. When object versioning is suspended for a bucket, it could indicate an adversary's attempt to inhibit system recovery following malicious activity. 
--
In cases of ransomware, this is a step that might happen before an encryption event. Which would make it impossible to recover the copied files without the encryption key. 
```
$ aws s3api put-bucket-versioning --bucket simulation-bucket-02-fn9z8gdleui5oy0h /
--versioning-configuration Status=Suspended
```

[New Rule] AWS S3 Object Versioning Suspended

---

rules/integrations/aws/exfiltration_s3_bucket_replicated_to_external_account.toml

- https://github.com/elastic/ia-trade-team/issues/346
Identifies when the `PutBucketReplication` operation is used to replicate S3 objects to a bucket in another AWS account. Adversaries may use bucket replication to exfiltrate sensitive data to an environment they control.
--
I used EQL to look in the `request_parameters` for inclusion of an `Account` key-value pair which is only included when an S3 bucket is replicated to an external account. I've included screenshots of replication to a bucket in the same account and replication to a bucket in a separate account showing this difference. 
Bucket Replicated in the Same Account
Bucket Replicated to a Seperate Account

[New Rule] AWS S3 Bucket Replicated to Another Account

---

rules/cross-platform/credential_access_forced_authentication_pipes.toml

Part of #3544 
Identifies a potential forced authentication using related SMB named pipes. Attackers may attempt to force targets to authenticate to a host controlled by them to capture hashes or enable relay attacks.
<details>
<summary>Events/Sample Data</summary>
```
{
"_index": ".ds-logs-endpoint.events.network-default-2024.07.12-000025",
"_id": "ZkNd25ABiLqpmBCYBX6u",
"_score": 1,
"_source": {
"agent": {
"id": "ea387e70-7cb8-4978-8df2-e9f44e3ef15d",
"version": "8.12.2"
},
"process": {
"Ext": {
"ancestry": [
"ZWEzODdlNzAtN2NiOC00OTc4LThkZjItZTlmNDRlM2VmMTVkLTM5MTItMTcyMTY0ODQ4Ng==",
"ZWEzODdlNzAtN2NiOC00OTc4LThkZjItZTlmNDRlM2VmMTVkLTM5MDYtMTcyMTY0ODQ4Ng==",
"ZWEzODdlNzAtN2NiOC00OTc4LThkZjItZTlmNDRlM2VmMTVkLTM5MDUtMTcyMTY0ODQ4Ng==", …
```

[New Rule] Active Directory Forced Authentication from Linux Host - SMB Named Pipes

---

rules/linux/privilege_escalation_linux_suspicious_symbolic_link.toml
rules/linux/privilege_escalation_sda_disk_mount_non_root.toml

Related to a community Slack discussion: https://elasticstack.slack.com/archives/C016E72DWDS/p1722357007143239?thread_ts=1722278293.016539&cid=C016E72DWDS. 
These two rules were created with Endgame compatibility but were made incompatible after tunings. The tunings did not remove the Endgame compatibility within the rule.
This PR fixes this.

[Rule Tuning] Removed Endgame from Incompatible Rules

---

rules/windows/credential_access_regback_sam_security_hives.toml

Excludes `taskhost.exe` as it is used in windows server 2012 instead of `taskhostw.exe`

[Rule Tuning] Sensitive Registry Hive Access via RegBack

---

rules/cross-platform/credential_access_dollar_account_relay.toml
rules/windows/credential_access_dollar_account_relay.toml

Part of #3544 
Identifies potential relay attacks against a domain controller (DC) by identifying authentication events using the domain controller computer account coming from other hosts to the DC that owns the account. Attackers may relay the DC hash after capturing it using forced authentication.
<details>
<summary>Events/Sample Data</summary>
```
{
"_index": ".ds-logs-system.security-default-2024.07.02-000028",
"_id": "mI115ZABiLqpmBCYFlys",
"_score": 1,
"_source": {
"agent": {
"name": "kingslanding",
"id": "c725ae87-e846-4602-9a08-2c717a3a504b",
"type": "filebeat",
"ephemeral_id": "dc8646cb-c8d3-48b9-b474-f3615a39f136",
"version": "8.14.2"
},
"process": {
"name": "-",
"pid": 0,
"executable": "-"
},
"winlog": {
"computer_name": "kingslanding.sevenkingdoms.local",
"process": {
"pid": …
```

[New Rule] Potential Relay Attack against a Domain Controller

---

rules/integrations/aws/impact_s3_object_versioning_disabled.toml

Resolves https://github.com/elastic/detection-rules/issues/3950
Adds missing index field.

[Rule Tuning] AWS S3 Object Versioning Suspended

---

rules/linux/persistence_potential_persistence_script_executable_bit_set.toml

RHEL derivatives require execution permissions to be set for `/etc/rc.d/rc.local` when attempting to manually enable and execute `/etc/rc.local`. Added this to the rule, to ensure coverage.

[Tuning] Executable Bit Set for Potential Persistence Script

---

CLI.md
detection_rules/action.py
detection_rules/action_connector.py
detection_rules/config.py
detection_rules/custom_rules.py
detection_rules/etc/_config.yaml
detection_rules/generic_loader.py
detection_rules/kbwrap.py
detection_rules/main.py
detection_rules/rule.py
detection_rules/rule_formatter.py
detection_rules/schemas/__init__.py
docs/custom-rules.md
lib/kibana/kibana/resources.py
lib/kibana/pyproject.toml
rules/integrations/aws/credential_access_iam_compromisedkeyquarantine_policy_attached_to_user.toml
rules/integrations/aws/impact_s3_object_versioning_disabled.toml
rules/linux/defense_evasion_binary_copied_to_suspicious_directory.toml
rules/linux/persistence_potential_persistence_script_executable_bit_set.toml
rules/network/command_and_control_accepted_default_telnet_port_connection.toml
rules/windows/command_and_control_outlook_home_page.toml
rules/windows/credential_access_dollar_account_relay.toml
rules/windows/credential_access_regback_sam_security_hives.toml
rules_building_block/credential_access_iis_apppoolsa_pwd_appcmd.toml

This PR adds support for action connectors in separate toml files. This connector information was previously ignored by our import and export processes and would cause the import/export of rules with action connectors to fail as the connector could 
not be found.  
It is worth noting that actions and action connectors are different. The support we are looking to provide with `actions.py` is the ability to store action information separate from the rule toml. Actions are currently attached to the rule file and are supported that way for editing on an individual level. However, action connectors are a shared resource among actions that some action types use (e.g. webhook) to save information that can broadly applicable to individual actions. For instance in the example …

[DaC] [FR] Ndjson support for action connectors

---

rules/windows/credential_access_mod_wdigest_security_provider.toml
rules/windows/credential_access_persistence_network_logon_provider_modification.toml
rules/windows/defense_evasion_amsienable_key_mod.toml
rules/windows/defense_evasion_code_signing_policy_modification_registry.toml
rules/windows/defense_evasion_create_mod_root_certificate.toml
rules/windows/defense_evasion_defender_disabled_via_registry.toml
rules/windows/defense_evasion_dns_over_https_enabled.toml
rules/windows/defense_evasion_microsoft_defender_tampering.toml
rules/windows/defense_evasion_ms_office_suspicious_regmod.toml
rules/windows/defense_evasion_persistence_account_tokenfilterpolicy.toml
rules/windows/defense_evasion_reg_disable_enableglobalqueryblocklist.toml
rules/windows/defense_evasion_scheduledjobs_at_protocol_enabled.toml
rules/windows/defense_evasion_sip_provider_mod.toml
rules/windows/defense_evasion_solarwinds_backdoor_service_disabled_via_registry.toml
rules/windows/defense_evasion_wsl_registry_modification.toml
rules/windows/lateral_movement_defense_evasion_lanman_nullsessionpipe_modification.toml
rules/windows/lateral_movement_rdp_enabled_registry.toml
rules/windows/lateral_movement_rdp_sharprdp_target.toml
rules/windows/lateral_movement_scheduled_task_target.toml

* Excludes some noisy patterns from rules that use registry events.
* Uses `registry.value` to filter registry keys before expensive wildcards.
* Adds `event.type` to rules that don't use it to avoid matches in other types like access.
* Removes `creation` from `event.type` as there are no events of that type either on my stack or telemetry.

[Rule Tuning] Windows Registry Rules Tuning - 1

---

rules/windows/persistence_app_compat_shim.toml
rules/windows/persistence_appcertdlls_registry.toml
rules/windows/persistence_appinitdlls_registry.toml
rules/windows/persistence_evasion_hidden_local_account_creation.toml
rules/windows/persistence_evasion_registry_ifeo_injection.toml
rules/windows/persistence_evasion_registry_startup_shell_folder_modified.toml
rules/windows/persistence_local_scheduled_task_scripting.toml
rules/windows/persistence_registry_uncommon.toml
rules/windows/persistence_run_key_and_startup_broad.toml
rules/windows/persistence_services_registry.toml
rules/windows/persistence_suspicious_com_hijack_registry.toml
rules/windows/persistence_suspicious_service_created_registry.toml
rules/windows/persistence_time_provider_mod.toml
rules/windows/persistence_via_hidden_run_key_valuename.toml
rules/windows/persistence_via_lsa_security_support_provider_registry.toml
rules/windows/persistence_via_wmi_stdregprov_run_services.toml
rules/windows/privilege_escalation_port_monitor_print_pocessor_abuse.toml
rules/windows/privilege_escalation_rogue_windir_environment_var.toml
rules_building_block/defense_evasion_msiexec_installsource_archive_file.toml

* Excludes some noisy patterns from rules that use registry events.
* Uses `registry.value` to filter registry keys before expensive wildcards.
* Adds `event.type` to rules that don't use it to avoid matches in other types like access.
* Removes `creation` from `event.type` as there are no events of that type either on my stack or telemetry.

[Rule Tuning] Windows Registry Rules Tuning - 2

---

rules/cross-platform/command_and_control_google_drive_malicious_file_download.toml
rules/cross-platform/credential_access_forced_authentication_pipes.toml
rules/windows/credential_access_dollar_account_relay.toml

Resolves https://github.com/elastic/detection-rules/issues/3939
Adds winlogbeat index to some Windows rules.

[Rule Tuning] Fix missing Winlogbeat index

---

rules/linux/defense_evasion_disable_apparmor_attempt.toml

The current rule does not have all ways of disabling app armor integrated. While detonating malware samples, I noticed we were lacking coverage. This tuning PR adds this coverage. 
Hits in detonate:

[Rule Tuning] Potential Disabling of AppArmor

---

rules/linux/defense_evasion_log_files_deleted.toml

Rootkits are seen to remove `/var/log/dmesg`, and this was missing in the current rule. This tuning adds it.

[Rule Tuning] System Log File Deletion

---

rules/linux/defense_evasion_attempt_to_disable_iptables_or_firewall.toml

While detonating malware in Detonate, I noticed we lacked coverage on several techniques to disable the firewall / flush the IPTables. This tuning PR adds additional coverage to the rule.
Detonate hits:

[Rule Tuning] Attempt to Disable IPTables or Firewall

---

tests/test_all_rules.py

*Issue link(s)*: https://github.com/elastic/detection-rules/issues/3965
- Of the two possible solutions proposed in https://github.com/elastic/detection-rules/issues/3965, the PR is raised for unit test creation.
- Primarily because skipping Unit tests in DAC is simpler and documented [here](https://dac-reference.readthedocs.io/en/latest/internals_of_the_detection_rules_repo.html#unit-testing)
- With this for developers working on prebuilt rule set, having an index or a data_view_id is enforced.
- For customers working on their custom rule set, this enforcement can easily be skipped.
- All Unit Tests should Pass
- Local Testing 
> - All rules have the required index
> ```
> Received JSON data in run script
> Running pytest with args: ['-p', 'vscode_pytest', …
```

Add Unit Test test_index_or_data_view_id_present

---

rta/common.py

*Issue link(s)*: Issue reported in community slack
- Fix attribute isse with func.__code__object per 3.11 [Refer](https://discuss.python.org/t/some-attribute-issue-with-python-3-11-func-code-object/33784/2)
- RTA should execute with no attribute errors
```console
(venv) PS C:\Users\shashank_suryanaraya\detection-rules> python -m rta -n winrar_encrypted
[!] Missing dependencies for C:\Users\shashank_suryanaraya\detection-rules\rta\winrar_encrypted.py:main()
- bin\Rar.exe
(venv) PS C:\Users\shashank_suryanaraya\detection-rules>
```

Fix Attribute Issue in RTA common.py

---

detection_rules/cli_utils.py
detection_rules/etc/test_cli.bash
detection_rules/rule.py
tests/test_all_rules.py

*Issue link(s)*: https://github.com/elastic/detection-rules/issues/3640
Adds Alert Suppression support to our schemas for different rule types based on the [Kibana Schemas](https://github.com/elastic/kibana/blob/main/x-pack/plugins/security_solution/common/api/detection_engine/model/rule_schema/rule_schemas.schema.yaml). 
- EQL Non Sequence : [Kibana PR](https://github.com/elastic/kibana/pull/176422) - `8.14.0`
- ML : [Kibana PR](https://github.com/elastic/kibana/pull/181926) - `8.15.0`
- ESQL : [Kibana PR](https://github.com/elastic/kibana/pull/180927) - `8.15.0`
- New Terms : [Kibana PR](https://github.com/elastic/kibana/pull/178294) - `8.14.0`
- Indicator Match : [Kibana PR](https://github.com/elastic/kibana/pull/174241) - `8.13.0`
<details><summary>Make Tests</summary>
<p>
- …

[FR] Add Alert Suppression for Addtional Rule Types

---

detection_rules/devtools.py

*Issue link(s)*: Release Fleet Workflow failures https://github.com/elastic/detection-rules/actions/runs/10475629333/job/29012708561
- @click.pass_context was added to bump_versions as part of DAC [commit](https://github.com/elastic/detection-rules/pull/3889/commits/303a64e388bdd7684ee654a4a48ebd19a9934e3a#diff-e451accac6e3d163c27239dce087f27f707daf31a84a45b12ebd0f0c26dc8c83)
- This is not being used in the function and is causing type errors for variables
- We have removed this context for the function
- Locally Built a patch release on main and worked as expected 
```
❯ python -m detection_rules dev bump-pkg-versions --patch-release  --new-package true   --maturity beta
█  █ █▄▄  █  █▄▄ █    █   █  █ █ █▀▄ █      █▄▄▀ █ …
```

Remove unused @click.pass_context

---

detection_rules/integrations.py
detection_rules/packaging.py

*Issue link(s)*: N/A First observed [here](https://github.com/elastic/detection-rules/pull/4000) 
In this original [commit](https://github.com/elastic/detection-rules/pull/3407/files#diff-f52ba8aa6684236d546d35ef2525ef97bcd8c2443a763574c458bb727cec9039), the historical rule functionality was removed, and broke the file naming schema which appends rule version to the end of the rule_id (`e.g. <rule_id>_<version>.json`).   This PR  re-adds historical rules by default and ensures only the latest historical rules and the latest version are generated for the release package, but ensures they have versions appended. The versions are necessary for kibana's historical rules feature.
1. Run the build without fail.
```bash
python -m detection_rules dev build-release --update-version-lock
Loaded …
```

[Bug] Add historical Rules as Default when Build Package

---

rules/windows/privilege_escalation_exploit_cve_202238028.toml

Adds some filters for `event.type` and `file.name` before the wildcards to improve performance.

[Rule Tuning] Potential privilege escalation via CVE-2022-38028

---

rules/linux/defense_evasion_ssl_certificate_deletion.toml

This rule detects the deletion of SSL certificates on a Linux system. Adversaries may delete SSL certificates to subvert trust controls and negatively impact the system.
This behavior is not inherently malicious, so telemetry shows 70 hits last 90d. I bumped it to low, rather than BBR, because it is a note worthy event.
One TP in detonate stack:

[New Rule] SSL Certificate Deletion

---

rules/linux/defense_evasion_attempt_to_disable_auditd_service.toml

Adversaries may attempt to disable the Auditd service in an attempt to evade detection. Auditd is a Linux service that provides system auditing and logging. Disabling the Auditd service can prevent the system from logging important security events, which can be used to detect malicious activity.
This rule is created as `low` severity, as it can be administrator activity as well.

[New Rule] Attempt to Disable Auditd Service

---

rules_building_block/defense_evasion_acl_modification_via_setfacl.toml

This BBR increases coverage for ACL modifications. This is not a malicious action but is used by malicious scripts (see [ref](https://www.uptycs.com/blog/threat-research-report-team/evasive-techniques-used-by-malicious-linux-shell-scripts)) to modify file attributes. 
This BBR is useful to just get an extra signal for instances where it might be used to evade detection.

[New Rule] Access Control List Modification via setfacl

---

rules/linux/defense_evasion_root_certificate_installation.toml

This rule detects the installation of root certificates on a Linux system. Adversaries may install a root certificate on a compromised system to avoid warnings when connecting to their command and control servers. Root certificates are used in public key cryptography to identify a root certificate authority (CA). When a root certificate is installed, the system or application will trust certificates in the root's chain of trust that have been signed by the root certificate.
3 hits in telemetry, only TPs in testing stack from e.g. a CVE installing a root certificate.

[New Rule] Root Certificate Installation

---

rules/windows/defense_evasion_network_connection_from_windows_binary.toml

as per community [report](https://elasticstack.slack.com/archives/C016E72DWDS/p1725928280816399), some noisy FPs are due to a host querying for it's own DNS record (dns.question.name contains host.name).

[Tuning] Unusual Network Activity from a Windows System Binary

---

detection_rules/etc/test_cli.bash
detection_rules/etc/test_toml.json
detection_rules/rule_formatter.py

*Issue link(s)*: https://github.com/elastic/detection-rules/issues/4033
- Added a code condition to handle  lists of dictionaries in toml linting.
- Also added toml-lint commands to `test_cli.bash` script
- Update the test_toml.json to include transform fields
- Try to run toml-lint on the rule with transform.investigate fields 
`python -m detection_rules toml-lint -f rules/windows/command_and_control_common_webservices.toml`
<details><summary>No Errors Found</summary>
<p>
```console
❯ python -m detection_rules toml-lint -f rules/windows/command_and_control_remote_file_copy_powershell.toml       
Loaded config file: /Users/shashankks/elastic_workspace/detection-rules/.detection-rules-cfg.json
█  █ █▄▄  █  █▄▄ █    █   █  █ …
```

Support toml lint for investigate transforms

---

rules/integrations/aws/discovery_new_terms_sts_getcalleridentity.toml

*Issue link(s)*: https://github.com/elastic/ia-trade-team/issues/458 
Tuning this rule to exclude identity type `AssumedRole` as this is too common a behavior, often automated, and used to verify current identity and role assumptions. Therefore it is not as indicative of suspicious behavior when used by assumed roles. This rule will still trigger for `IAMUser` and `FederatedUser` identity types. In telemetry this change reduces alerts from ~240,000 to 43 in the last 30 days.
<details><summary>Screenshot to show valid query</summary>
<p>
</p>
</details>

[Rule Tuning] AWS STS GetCallerIdentity API Called for the First Time

---

rules/linux/command_and_control_cupsd_foomatic_rip_netcon.toml
rules/linux/execution_cupsd_foomatic_rip_file_creation.toml
rules/linux/execution_cupsd_foomatic_rip_lp_user_execution.toml
rules/linux/execution_cupsd_foomatic_rip_shell_execution.toml
rules/linux/execution_cupsd_foomatic_rip_suspicious_child_execution.toml

A set of vulnerabilities in the CUPS printing system (CVE-2024-47176, CVE-2024-47076, CVE-2024-47175, and CVE-2024-47177) allows remote unauthenticated attackers to achieve remote code execution (RCE) by sending UDP packets to port 631 or through local network-based attacks, such as spoofing mDNS or DNS-SD advertisements. These flaws affect components like cups-browsed, libcupsfilters, libppd, and foomatic-rip, enabling attackers to replace or install malicious printer configurations, which could lead to arbitrary command execution when a print job is started. The detection rules aim to identify suspicious IPP requests and command execution attempts to mitigate the risk of exploitation from these vulnerabilities.
This PR adds 5 new detection rules, all focusing on different behaviors that …

[New Rules] CVE-2024-x.x.x.x.x (CUPS/Foomatic-RIP RCE)

---

rules/windows/defense_evasion_posh_assembly_load.toml

Excluding common Microsoft native assemblies (`Microsoft.*.dll`, `System.*.dll`) often loaded via `::Load` function.

[Tuning] Suspicious .NET Reflection via PowerShell

---

rules/integrations/aws/discovery_servicequotas_multi_region_service_quota_requests.toml

* https://elastic.slack.com/archives/C011H2BCRRN/p1727868765806559
Fixed typo in query where `=` was used instead of `==` operator in ES|QL as pointed out by @aarju.

[Rule Tuning] Fixing Incorrect ES|QL Operator Use - AWS Service Quotas Multi-Region `GetServiceQuota` Request

---

hunting/README.md
hunting/aws/queries/iam_assume_role_creation_with_attached_policy.toml
hunting/aws/queries/lambda_add_permissions_for_write_actions_to_function.toml
hunting/aws/queries/signin_single_factor_console_login_via_federated_session.toml
hunting/aws/queries/ssm_sendcommand_api_used_by_ec2_instance.toml
hunting/aws/queries/sts_suspicious_federated_temporary_credential_request.toml
hunting/definitions.py
hunting/okta/queries/defense_evasion_failed_oauth_access_token_retrieval_via_public_client_app.toml

* https://github.com/elastic/detection-rules/pull/4146
* Updated all queries that did not have `keep` or `stats` in them to include at least `keep`
* Added `validate_esql_query` method to `Hunt` dataclass that is called only in a query starts with `from` (assuming all ES|QL queries for hunting will use `FROM` source commands only
Run: `pytest tests/test_hunt_data.py` from this branch to check for success. Then make adjustments to any hunt queries that are ES|QL and remove the Keep or Stats functions.

[Hunt Tuning] Enforce `STATS` or `KEEP` functions in ES|QL hunting queries

---

Makefile
pyproject.toml

*Issue link(s)*: https://github.com/elastic/detection-rules/issues/4083
- Add setuptools==75.2.0 as project dependency
The alternatives to the above solution which requires in depth planning and execution are as below
- Refactor the overall data modelling to pydantic. 
- Refactor the code dependant on the deprecated package and move it into a separate repository
- Fork the `marshmallow-jsonschema` as a internal private repository and apply patches that would resolve the pkg_resources dependency.
- Also the package upstream has a fix opened in [PR](https://github.com/fuhrysteve/marshmallow-jsonschema/pull/183), which would also fix our issue , but it is stale from. April 2.
While there is a refactor meta for detection rules already tracking such larger improvements …

Add setuptools as project dependency

---

rta/linux_execution_reverse_or_bind_shell_via_utility.py

react_sync_rta_updates_4190

---

rules/linux/persistence_linux_user_added_to_privileged_group.toml

This rule had a rule logic issue, commented on in https://elasticstack.slack.com/archives/C016E72DWDS/p1729767155322309.
This tuning fixes this.

[Rule Tuning] Linux User Added to Privileged Group

---

rules/integrations/aws/privilege_escalation_sts_role_chaining.toml

*Issue link(s)*: https://github.com/elastic/ia-trade-team/issues/458
Identifies role chaining activity. Role chaining is when you use one assumed role to assume a second role through the AWS CLI or API. While this a recognized functionality in AWS, role chaining can be abused for privilege escalation if the subsequent assumed role provides additional privileges. Role chaining can also be used as a persistence mechanism as each AssumeRole action results in a refreshed session token with a 1 hour maximum duration. This rule looks for role chaining activity happening within a single account, to eliminate false positives produced by common cross-account behavior.
- I have a terraform script to create the necessary role resources and a python script to emulate the role-chaining behavior. I can …

[New Rule] AWS STS Role Chaining

---

.github/workflows/version-code-and-release.yml
pyproject.toml

- We need to make sure the drafts are updated based on the context on the PR so that the labels influence the tagging.
- Simplified the workflow to update the draft when the PR merges

[FR] DRAFT Release Workflow on PR Merge

---

.github/workflows/version-code-and-release.yml
docs/versioning.md
pyproject.toml
rules/windows/credential_access_suspicious_lsass_access_generic.toml

- Now tags independently on all code changes (instead of waiting on the release workflow), to preserve proper versions. This prevents issues where our code base and tags can get out of sync.
- Updates versioning docs

[FR] Update the release versioning process and workflow

---

detection_rules/devtools.py
pyproject.toml

*Issue link(s)*: PR(s) are being raised for newline with no actual changes 
Example - https://github.com/elastic/detection-rules/pull/4211
- Remove the additional new line, so PR is created only when content has changed
- Remove spaces from the header content so we wont have issues like in PR https://github.com/elastic/detection-rules/pull/4264/
- Unit Test should pass 
- We have Ran a workflow from the private branch https://github.com/elastic/detection-rules/actions/runs/11742727980/job/32714051302?pr=4263
- Only Updates are seen as in this PR with no header content changes https://github.com/elastic/detection-rules/pull/4265/files
- Have you followed the [contributor …

Fix extra new line in ATT&CK-coverage.md

---

rules/linux/defense_evasion_kernel_module_removal.toml

This rule had a bad update_date.

[Rule Tuning] Kernel Module Removal

---

detection_rules/devtools.py
pyproject.toml

*Issue link(s)*: https://github.com/elastic/detection-rules/issues/4150 Smart Limits is being available in 8.17.0 and above kibana version and we can now include all historical versions for our rule packages 
-  Smart Limits is being available in 8.17.0 and above kibana version and we can now include all historical versions for our rule packages 
- We will continue to limit the historical rule versions to latest and latest-1 for packages 8.16.0 and below
- We had considered the idea of introducing a flag for the build function which would require us to change all our workflows of build for supported versions. 
- This will introduce a constant version for comparison but have left comments for usage 
Please note this is a required PR for the next week release
- Building 8.17.0 Package
```
❯ …
```

Add all historical versions for v8.17.0 and above packages

---

rules/integrations/azure/initial_access_consent_grant_attack_via_azure_registered_application.toml

https://github.com/elastic/sdh-protections/issues/538 
o365 integration had a field pipeline change that renamed the `o365.audit.Operation` field as `event.action`. Because of this the rule as it exists does not trigger for `o365.audit` data stream. I'm adding the `event.action` field as an additional OR clause which should correct the false negative. This is a simple tuning that should work as expected below is a screenshot from @arturmouraa with the working query in his test environment as I do not have one set up for this at the moment and would like to push the change in time for our upcoming release. 
target event provided in SDH ticket
```json
{
"_index": ".ds-logs-o365.audit-default-2024.11.04-000012",
"_id": "vl440zYeEpalgR8UR1CV0hQKN8o=",
"_version": 1,
"_score": …
```

[Tuning] SDH - Possible Consent Grant Attack via Azure-Registered Application

---

detection_rules/rule_validators.py
pyproject.toml
tests/test_python_library.py

*Issue link(s)*: - https://github.com/elastic/detection-rules/issues/3195
- Have a static error message which is a unique string and describe the error
- The details of the error are logged properly before we throw the error and the format of the error details are outside of ValueError scope
- Simulated a Local validation Failure 
- Clear log messages and trace are simulated. 
```console
===================================================================== FAILURES =====================================================================
_____________________________________________ TestAlertSuppression.test_eql_non_sequence_support_only ______________________________________________
tests/base.py:85: in setUp
self.fail(f'Rule loader failure: \n{RULE_LOADER_FAIL_MSG}')
E   AssertionError: …
```

Enhance Readability of validation check failures

---

detection_rules/etc/non-ecs-schema.json
pyproject.toml
rules/windows/persistence_sysmon_wmi_event_subscription.toml

added Elastic Defend Event 5861 (WMI Permanent  event subscription event) to this rule scope. this event is part of API events and is emitted by default to the stack/SIEM since it's a low volume event.
https://github.com/elastic/endpoint-rules/issues/3685

[Tuning] Suspicious WMI Event Subscription Created

---

rules/linux/persistence_ssh_via_backdoored_system_user.toml

This rule identifies successful SSH logins by system users that are uncommon to authenticate via SSH. These users have `nologin` set by default, and must be modified to allow SSH access. Adversaries may backdoor these users to gain unauthorized access to the system.

[New Rule] SSH via Backdoored System User

---

rules/linux/exfiltration_potential_data_splitting_for_exfiltration.toml
rules/linux/impact_memory_swap_modification.toml
rules/linux/lateral_movement_ssh_it_worm_download.toml
rules/linux/persistence_apt_package_manager_execution.toml
rules/linux/persistence_chkconfig_service_add.toml
rules/linux/persistence_dnf_package_manager_plugin_file_creation.toml
rules/linux/persistence_git_hook_execution.toml
rules/linux/persistence_git_hook_process_execution.toml
rules/linux/persistence_linux_backdoor_user_creation.toml
rules/linux/persistence_linux_shell_activity_via_web_server.toml

https://github.com/elastic/ia-trade-team/issues/503
https://github.com/elastic/ia-trade-team/issues/505
Introduces rule modifications to add support to SentinelOne and Crowdstrike where possible.
Crowdstrike events are pending integration adjustments (documented [here](https://docs.google.com/document/d/1NSMazu9cgEJMsUHnUT8Z6NrNfwDSF91cSbhjwySK7vk/edit?usp=sharing)), but they often lack enough context when comparing to S1 and Elastic Defend.
While these rules were not tested by generating alerts due to the lack of access to a CrowdStrike environment, the following steps were taken to ensure accuracy:
* Verified that the fields used are populated by the target EDR in the specified event category, which is documented here at the [Linux EDR Field Compatibility …

[Rule Tuning] Linux 3rd Party EDR Support - Crowdstrike and S1 - 9

---

rules/linux/discovery_process_capabilities.toml
rules/linux/discovery_security_file_access_via_common_utility.toml
rules/linux/discovery_sudo_allowed_command_enumeration.toml
rules/linux/discovery_suspicious_memory_grep_activity.toml
rules/linux/discovery_suspicious_which_command_execution.toml
rules/linux/discovery_yum_dnf_plugin_detection.toml
rules/linux/execution_cupsd_foomatic_rip_file_creation.toml
rules/linux/execution_cupsd_foomatic_rip_lp_user_execution.toml
rules/linux/execution_cupsd_foomatic_rip_shell_execution.toml
rules/linux/execution_cupsd_foomatic_rip_suspicious_child_execution.toml

https://github.com/elastic/ia-trade-team/issues/503
https://github.com/elastic/ia-trade-team/issues/505
Introduces rule modifications to add support to SentinelOne and Crowdstrike where possible.
Crowdstrike events are pending integration adjustments (documented [here](https://docs.google.com/document/d/1NSMazu9cgEJMsUHnUT8Z6NrNfwDSF91cSbhjwySK7vk/edit?usp=sharing)), but they often lack enough context when comparing to S1 and Elastic Defend.
While these rules were not tested by generating alerts due to the lack of access to a CrowdStrike environment, the following steps were taken to ensure accuracy:
* Verified that the fields used are populated by the target EDR in the specified event category, which is documented here at the [Linux EDR Field Compatibility …

[Rule Tuning] Linux 3rd Party EDR Support - Crowdstrike and S1 - 7

---

rules/linux/persistence_linux_user_added_to_privileged_group.toml
rules/linux/persistence_message_of_the_day_execution.toml
rules/linux/persistence_potential_persistence_script_executable_bit_set.toml
rules/linux/persistence_process_capability_set_via_setcap.toml
rules/linux/persistence_setuid_setgid_capability_set.toml
rules/linux/persistence_simple_web_server_creation.toml
rules/linux/privilege_escalation_chown_chmod_unauthorized_file_read.toml
rules/linux/privilege_escalation_docker_mount_chroot_container_escape.toml
rules/linux/privilege_escalation_linux_uid_int_max_bug.toml
rules/linux/privilege_escalation_load_and_unload_of_kernel_via_kexec.toml
rules/linux/privilege_escalation_potential_wildcard_shell_spawn.toml
rules/linux/privilege_escalation_sudo_cve_2019_14287.toml
rules/linux/privilege_escalation_unshare_namespace_manipulation.toml

https://github.com/elastic/ia-trade-team/issues/503
https://github.com/elastic/ia-trade-team/issues/505
Introduces rule modifications to add support to SentinelOne and Crowdstrike where possible.
Crowdstrike events are pending integration adjustments (documented [here](https://docs.google.com/document/d/1NSMazu9cgEJMsUHnUT8Z6NrNfwDSF91cSbhjwySK7vk/edit?usp=sharing)), but they often lack enough context when comparing to S1 and Elastic Defend.
While these rules were not tested by generating alerts due to the lack of access to a CrowdStrike environment, the following steps were taken to ensure accuracy:
* Verified that the fields used are populated by the target EDR in the specified event category, which is documented here at the [Linux EDR Field Compatibility …

[Rule Tuning] Linux 3rd Party EDR Support - Crowdstrike and S1 - 10

---

rules/network/discovery_potential_syn_port_scan_detected.toml

renamed rule to `Potential SYN-Based Port Scan Detected` to align better with rule description.
context: https://elastic.slack.com/archives/C011H2BCRRN/p1736521605088419

[Tuning] Potential SYN-Based Network Scan Detected

---

rules/linux/defense_evasion_prctl_process_name_tampering.toml

This rule leverages Auditd data to detect the use of the `prctl` syscall to potentially hide a process by changing its name. The `prctl` syscall is used to control various process attributes. Attackers can use this syscall to change the name of a process to a hidden directory or file, making it harder to detect. The query looks for the `prctl` syscall with the `PR_SET_NAME` argument set to `f` (PR_SET_NAME is used to set the name of a process).

[New Rule] Potential Process Name Stomping with Prctl

---

detection_rules/kbwrap.py
pyproject.toml

*Issue link(s)*: https://github.com/elastic/detection-rules/issues/4375
When specifying an actions connector for Kibana export rules, the value is not used and is not honored. Instead it is [set to none](https://github.com/elastic/detection-rules/blob/e822af47a496084beb698f905e6d28d300488cc9/detection_rules/kbwrap.py#L300), this should be set to the incoming parameter if the parameter is available otherwise it should be none. 
Use the export rules command while not having an action connector directory set in your config file, but instead have it passed via the CLI.
`python -m detection_rules kibana --space customer --ignore-ssl-errors true export-rules -d demo/rules/ -sv -ac -acd dac_test/action_connectors/`
- Have you signed the [contributor license …

[Bug] [DaC] Actions Connector Defaults to None

---

detection_rules/etc/non-ecs-schema.json
pyproject.toml
rules/integrations/aws/impact_s3_excessive_object_encryption_with_sse_c.toml
rules/integrations/aws/impact_s3_sse_c_encrypted_objects.toml
rules/integrations/aws/impact_s3_unusual_object_encryption_with_sse_c.toml

* https://github.com/elastic/ia-trade-team/issues/529
Adds detection coverage for ransom attempts by encrypting S3 objects with SSE-C via compromised AWS creds.
Identifies when AWS S3 objects stored in a bucket are encrypted using Server-Side Encryption with Customer-Provided Keys (SSE-C). Adversaries with compromised AWS credentials can encrypt objects in an S3 bucket using their own encryption keys, rendering the objects unreadable or recoverable without the key. This can be used as a form of ransomware to extort the bucket owner for the decryption key.
* https://github.com/elastic/pwncloud/pull/17
Visit shared stack with the following query within the last 2 days.
```
event.dataset: "aws.cloudtrail"
and …
```

[New Rule] Adding Coverage for `Unusual AWS S3 Object Encryption with SSE-C`

---

rules/_deprecated/credential_access_microsoft_365_potential_password_spraying_attack.toml
rules/_deprecated/execution_suspicious_jar_child_process.toml

Deprecates this rule. Originally we added the `Deprecated` prefix to the rule for customers to identify that it was being deprecated. This PR finishes the deprecation process.
Deprecated `Deprecated - Suspicious JAVA Child Process` as well per @Aegrah 
No testing required.

[Deprecation] Deprecating `Potential Password Spraying of Microsoft 365 User Accounts`

---

rules/linux/persistence_grub_configuration_creation.toml

This rule detects the creation of Grub configuration files on Linux systems. The Grub configuration file is used to configure the boot loader, which is responsible for loading the operating system. Attackers may create malicious Grub configuration files to execute arbitrary code or escalate privileges during the boot process, which can be leveraged to maintain persistence on the system.
1 hit in telemetry, only TPs in testing stack:

[New Rule] GRUB Configuration File Creation

---

rules/linux/persistence_grub_makeconfig.toml

This rule detects the generation of a new GRUB configuration file using built-in Linux commands. The GRUB configuration file is used to configure the GRUB bootloader, which is responsible for loading the Linux kernel and initramfs image during the boot process. Attackers may use these built-in utilities to generate a new GRUB configuration file that includes malicious kernel parameters or boot options, which can be leveraged to maintain persistence on the system.
2 hits in telemetry last 90d, which are TPs. Only TPs in testing stack:

[New Rule] GRUB Configuration Generation through Built-in Utilities

---

rules/linux/persistence_extract_initramfs_via_cpio.toml

For FP handling, I created this rule seperate from: https://github.com/elastic/detection-rules/pull/4387
This rule detects the extraction of an initramfs image using the `cpio` command on Linux systems. The `cpio` command is used to create or extract cpio archives. Attackers may extract the initramfs image to modify the contents or add malicious files, which can be leveraged to maintain persistence on the system.
8 hits in telemetry last 90d, which I will not tune out just yet, because I might alter the logic slightly if necessary (change of `process.args` requirements). Other than that, only TPs in testing stack:

[New Rule] Initramfs Extraction via CPIO

---

rules/linux/persistence_unpack_initramfs_via_unmkinitramfs.toml

This rule detects the unpacking of an initramfs image using the `unmkinitramfs` command on Linux systems. The `unmkinitramfs` command is used to extract the contents of an initramfs image, which is used to boot the system. Attackers may use `unmkinitramfs` to unpack an initramfs image and modify its contents to include malicious code or backdoors, allowing them to maintain persistence on the system.
0 hits in telemetry last 90d, only TPs in testing stack:

[New Rule] Initramfs Unpacking via unmkinitramfs

---

rules/linux/persistence_boot_file_copy.toml

This rule detects the process of copying or moving files from or to the `/boot` directory on Linux systems. The `/boot` directory contains files that are essential for the system to boot, such as the kernel and initramfs images. Attackers may copy or move files to the `/boot` directory to modify the boot process, which can be leveraged to maintain access to the system.
8 hits in telemetry, that I don't want to tune out just yet. Only TPs in testing stack:

[New Rule] Boot File Copy

---

rules/linux/persistence_openssl_passwd_hash_generation.toml

This rule detects the usage of the `openssl` binary to generate password hashes on Linux systems. The `openssl` command is a cryptographic utility that can be used to generate password hashes. Attackers may use `openssl` to generate password hashes for new user accounts or to change the password of existing accounts, which can be leveraged to maintain persistence on a Linux system.
6 hits in telemetry last 90d, only TPs in my own testing stack:

[New Rule] OpenSSL Password Hash Generation

---

rules/linux/persistence_dracut_module_creation.toml

This rule detects the creation of Dracut module files on Linux systems. Dracut is a tool used to generate an initramfs image that is used to boot the system. Dracut modules are scripts that are executed during the initramfs image generation process. Attackers may create malicious Dracut modules to execute arbitrary code at boot time, which can be leveraged to maintain persistence on a Linux system.
0 hits in telemetry with the added exclusions. Only TPs in testing stack:

[New Rule] Dracut Module Creation

---

rules/linux/persistence_manual_dracut_execution.toml

This rule detects manual execution of the `dracut` command on Linux systems. Dracut is a tool used to generate an initramfs image that is used to boot the system. Attackers may use `dracut` to create a custom initramfs image that includes malicious code or backdoors, allowing them to maintain persistence on the system.
0 hits in telemetry with the added exclusion list. Only TPs in testing stack:
I can always add more flags to the `process.args` if exclusions are necessary.

[New Rule] Manual Dracut Execution

---

rules/linux/persistence_network_manager_dispatcher_persistence.toml

This rule detects the creation of a NetworkManager dispatcher script on a Linux system. NetworkManager dispatcher scripts are shell scripts that NetworkManager executes when network interfaces change state. Attackers can abuse NetworkManager dispatcher scripts to maintain persistence on a system by executing malicious code whenever a network event occurs.
0 hits in telemetry last 90d, only TPs in testing stack:

[New Rule] NetworkManager Dispatcher Script Creation

---

rules/linux/execution_unusual_pkexec_execution.toml

This rule detects the execution of the `pkexec` command by a shell process. The `pkexec` command is used to execute programs as another user, typically as the superuser. Through the `new_terms` rule type, unusual  executions of `pkexec` are identified, and may indicate an attempt to escalate privileges or perform unauthorized actions on the system.
59 hits in telemetry last 90d, without the new_terms logic. This logic will reduce these quite substantially. I will wait with initial exclusions until I analyze full telemetry. In my own stack, only TPs:

[New Rule] Unusual Pkexec Execution

---

rules/linux/discovery_polkit_version_discovery.toml

This rule detects Polkit version discovery activity on Linux systems. Polkit version discovery can be an indication of an attacker attempting to exploit misconfigurations or vulnerabilities in the Polkit service.
No hits in telemetry, only TPs in testing stack:

[New Rule] Polkit Version Discovery

---

rules/linux/persistence_dbus_unsual_daemon_parent_execution.toml

This rule detects when an unusual child process is spawned from the `dbus-daemon` parent process. The `dbus-daemon` process is a message bus system that provides a way for applications to talk to each other. Attackers may abuse this process to execute malicious code or escalate privileges.
0 hits in telemetry last 90d, only TPs in testing stack last year:
If this seems to be noisy, I will move to new_terms rule or add certain white listing for paths.

[New Rule] Unusual D-Bus Daemon Child Process

---

rules/linux/credential_access_unusual_instance_metadata_service_api_request.toml

- address AND and OR logic ( parentheses - logic was `process where A or B or C and not D` parenthesis should be `process where (A or B or C) and not D)` )
- excluded parent.executable null (causes lot of FPs that are already excluded by parent)
- excluded few more parent processes.

[Tuning] Unusual Instance Metadata Service (IMDS) API Request

---

rules/linux/command_and_control_ip_forwarding_activity.toml
rules/linux/command_and_control_linux_chisel_client_activity.toml
rules/linux/command_and_control_linux_kworker_netcon.toml
rules/linux/command_and_control_suspicious_network_activity_from_unknown_executable.toml
rules/linux/credential_access_ssh_backdoor_log.toml
rules/linux/defense_evasion_acl_modification_via_setfacl.toml
rules/linux/defense_evasion_attempt_to_disable_auditd_service.toml
rules/linux/defense_evasion_attempt_to_disable_syslog_service.toml
rules/linux/defense_evasion_binary_copied_to_suspicious_directory.toml
rules/linux/defense_evasion_clear_kernel_ring_buffer.toml

Misc. Linux DR tunings - Part 1.

[Rule Tuning] Linux DR Tuning - Part 1

---

rules/linux/persistence_bpf_probe_write_user.toml

This rule monitors the syslog log file for messages related to instances of a program using the `bpf_probe_write_user` helper. The `bpf_probe_write_user` helper is used to write data to user space from a BPF program. Unauthorized use of this helper can be indicative of an eBPF rootkit or other malicious activity.

[New Rule] Suspicious Usage of bpf_probe_write_user Helper

---

rules/integrations/aws/discovery_ec2_userdata_request_for_ec2_instance.toml
rules/integrations/aws/persistence_ec2_route_table_modified_or_deleted.toml

*Issue link(s)*: When Fixing back ports for PR https://github.com/elastic/detection-rules/pull/4439, we identified two new files with documentation to master. 
- Replace master links
- No maintenance window as these rules are not minstacked. 

Fix remaining Replace master doc URLs with current

---

rules/network/discovery_potential_network_sweep_detected.toml
rules/network/discovery_potential_port_scan_detected.toml
rules/network/discovery_potential_syn_port_scan_detected.toml

These rules have been tuned several times, and in one tuning, I bricked the rule logic:
- https://github.com/elastic/detection-rules/pull/2985
Through community slack, concerns about this rule were presented:
- https://elasticstack.slack.com/archives/C016E72DWDS/p1738608222619009?thread_ts=1738598045.453139&cid=C016E72DWDS
This PR addresses these issues by:
- Removing Elastic Defend from the rule entirely (this is needed, as Elastic Defend does not properly log the network connections needed to detect this port scanning behavior without being prone to FPs)
- Add the `network_flow` `event.action` field to ensure flow data captured by the NPC is used to trigger the rule. I kept PANW integration, as I checked rules such as [this](https://github.com/elastic/detection-rules/blob/f1dee060b644956 …

[Rule Tuning] Port Scan Rules

---

detection_rules/devtools.py
detection_rules/integrations.py
pyproject.toml

We're limiting the number of historical rules shipped in a package to accommodate future growth and simplify the release process.

Bumping number of versions per rule to 4 in total

---

pyproject.toml
tests/test_all_rules.py

*Issue link(s)*: https://github.com/elastic/detection-rules/issues/4326
- For stack versions 8.18 and above the Unit Test `test_eql_non_sequence_support_only` can be safely ignored.
- We don't have to test if alert suppression is used in sequences only , With https://github.com/elastic/kibana/pull/189725 starting in 8.18 alert suppression for eql sequences is available.
- Code change is made to skip the test accordingly 
<details><summary>8.18 Testing </summary>
```console 
detection-rules on  issue-4326 [$!?] is 📦 v0.4.10 via 🐍 v3.12.8 (.venv) on ☁️  shashank.suryanarayana@elastic.co 
❯ pytest  -v tests/test_all_rules.py::TestAlertSuppression::test_eql_non_sequence_support_only
=================================================================== test session starts …
```

Modify Unit Test to Support Alert Suppression for EQL Sequences

---

rules/windows/collection_email_outlook_mailbox_via_com.toml
rules/windows/credential_access_dollar_account_relay.toml
rules/windows/credential_access_imageload_azureadconnectauthsvc.toml
rules/windows/credential_access_regback_sam_security_hives.toml
rules/windows/defense_evasion_audit_policy_disabled_winlog.toml
rules/windows/defense_evasion_lolbas_win_cdb_utility.toml
rules/windows/defense_evasion_windows_filtering_platform.toml
rules/windows/execution_mofcomp.toml
rules/windows/execution_windows_script_from_internet.toml
rules/windows/impact_ransomware_file_rename_smb.toml
rules/windows/impact_ransomware_note_file_over_smb.toml
rules/windows/lateral_movement_via_wsus_update.toml
rules/windows/privilege_escalation_persistence_phantom_dll.toml
rules/windows/privilege_escalation_unquoted_service_path.toml

Just small changes in the index patterns to improve consistency across Windows rules.

[Rule Tuning] Windows - Improve Index Pattern Consistency

---

rules/windows/persistence_dontexpirepasswd_account.toml

Excludes FP Patterns observed in the new logic, re-adds exclusion for SYSTEM activity that was wrongly removed (by me) previously.

[Rule Tuning] Account Configured with Never-Expiring Password

---

rules/windows/command_and_control_tool_transfer_via_curl.toml
rules/windows/discovery_enumerating_domain_trusts_via_nltest.toml
rules/windows/discovery_whoami_command_activity.toml
rules/windows/lateral_movement_incoming_wmi.toml

Some rules exclude all SYSTEM activity by excluding the `S-1-5-18` user.id, the problem is that every sysmon event contains that SID ([ref](https://github.com/elastic/detection-rules/issues/1770)), so these rules could never trigger on its events. Here are 2 examples:
```
registry where host.os.type == "windows" and
registry.path : (
"HKLM\\SOFTWARE\\Microsoft\\Windows\\Windows Error Reporting\\LocalDumps\\DumpType",
"\\REGISTRY\\MACHINE\\SOFTWARE\\Microsoft\\Windows\\Windows Error Reporting\\LocalDumps\\DumpType"
) and
registry.data.strings : ("2", "0x00000002") and
not (process.executable : "?:\\Windows\\system32\\svchost.exe" and user.id : ("S-1-5-18", "S-1-5-19", "S-1-5-20"))
```
Here we are excluding a specific process, so we still support the data source as that exclusion will hit …

[Rule Tuning] Adapt Rules to work with Sysmon

---

rules/windows/defense_evasion_msbuild_making_network_connections.toml

When tuning the rule for performance in https://github.com/elastic/detection-rules/pull/3482, we ended up with breaking it is logic when `and not user.id != "S-1-5-18" and` was used. So I'm fixing that
I'm also removing the Sysmon support for it as user.id in sysmon logs will always be S-1-5-18, ref: https://github.com/elastic/detection-rules/issues/1770

[Rule Tuning] MsBuild Making Network Connections

---

rules/linux/lateral_movement_unusual_remote_file_creation.toml

This rule leverages the new_terms rule type to detect file creation via a commonly used file transfer service while excluding typical remote file creation activity. This behavior is often linked to lateral movement, potentially indicating an attacker attempting to move within a network.
In my own stack, only TPs. In telemetry, a large list of FPs, but these will be excluded through the new_terms rule type, as they are all by the same host/process.

[New Rule] Unusual Remote File Creation

---

rules/linux/impact_potential_bruteforce_malware_infection.toml

This detection identifies a Linux host that has potentially been infected with malware and is being used to conduct brute-force attacks against external systems over SSH (port 22 and common alternative SSH ports). The detection looks for a high volume of outbound connection attempts to non-private IP addresses from a single process. A compromised host may be part of a botnet or controlled by an attacker, attempting to gain unauthorized access to remote systems. This behavior is commonly observed in SSH brute-force campaigns where malware hijacks vulnerable machines to expand its attack surface.
Only TPs from DOTA3 malware in my testing stack:
0 hits in telemetry last 30d.

[New Rule] Potential Malware-Driven SSH Brute Force Attempt

---

rules/linux/lateral_movement_remote_file_creation_world_writeable_dir.toml

This rule detects the creation of a file in a world-writeable directory through a service that is commonly used for file transfer. This behavior is often associated with lateral movement and can be an indicator of an attacker attempting to move laterally within a network.
3 hits in telemetry last 30d (as I excluded root), and only TPs in my testing stack from DOTA3 malware post infection chain:

[New Rule] Remote File Creation in World Writeable Directory

---

rules/windows/defense_evasion_injection_msbuild.toml
rules/windows/defense_evasion_timestomp_sysmon.toml
rules/windows/privilege_escalation_via_rogue_named_pipe.toml

Some of our Sysmon rules uses `event.action` values that would never match as they were changed in the integrations: https://github.com/elastic/integrations/pull/6882
Moving to `event.code` only as it is reliable, and although integrations changed the `event.action` field, the new values would not be compatible with winlogbeat.

[Rule Tuning] Sysmon rules that uses `event.action`

---

rules/windows/defense_evasion_amsi_bypass_powershell.toml

Excluding patterns that are causing a high increase in false positive matches.

[Tuning] Potential Antimalware Scan Interface Bypass via PowerShell

---

rules/windows/lateral_movement_remote_file_copy_hidden_share.toml

added `powershell_ise.exe` and `pwsh.exe` and removed `Robocopy.exe` (very noisy) and added a wildcard to the `copy` arg match to extend coverage where `process.args` is not starting with `copy`.
https://elasticstack.slack.com/archives/C016E72DWDS/p1740438047909159

[Tuning] Remote File Copy to a Hidden Share

---

rules/linux/initial_access_first_time_public_key_authentication.toml

This rule monitors the authentication logs for messages related to instances of a first-time public key authentication. Public key authentication is a secure method for authenticating users to a server. Monitoring first-time public key authentication events can help detect unauthorized access attempts or suspicious activity on the system.

[New Rule] Successful SSH Authentication from Unusual SSH Public Key

---

rules/linux/defense_evasion_interpreter_launched_from_decoded_payload.toml

This rule detects when a base64 decoded payload is piped to an interpreter on Linux systems. Adversaries may use base64 encoding to obfuscate data and pipe it to an interpreter to execute malicious code. This technique may be used to evade detection by host- or network-based security controls.
This activity is common for botnets/spreaders/worms etc. Also used by DOTA3.

[New Rule] Base64 Decoded Payload Piped to Interpreter

---

rules/linux/defense_evasion_kill_command_executed.toml

This rule detects the execution of kill, pkill, and killall commands on Linux systems. These commands are used to terminate processes on a system. Attackers may use these commands to kill security tools or other processes to evade detection or disrupt system operations.
This is common behavior in malware such as botnets/spreaders/worms. This rule is created to be broad, allowing to capture cases that get excluded by our endpoint rules.

[New Rule] Kill Command Execution

---

rules/network/discovery_potential_network_sweep_detected.toml
rules/network/discovery_potential_port_scan_detected.toml
rules/network/discovery_potential_syn_port_scan_detected.toml

https://github.com/elastic/sdh-protections/issues/557
Removes the hardcoded numbers/threshold from the rule description to avoid confusion if the rule is tuned but the description is not.

[Rule Tuning] Remove hardcoded logic from description

---

rules/linux/persistence_pth_file_creation.toml

This rule detects the creation of .pth files in system-wide and user-specific Python package directories, which can be abused for persistent code execution. .pth files automatically execute Python code when the interpreter starts, making them a stealthy persistence mechanism. Monitoring these paths helps identify unauthorized modifications that could indicate persistence by an attacker or malicious package injection.

[New Rule] Python Path File (pth) Creation

---

rules/integrations/pad/privileged_access_ml_linux_high_count_privileged_process_events_by_user.toml
rules/integrations/pad/privileged_access_ml_linux_high_median_process_command_line_entropy_by_user.toml
rules/integrations/pad/privileged_access_ml_linux_rare_process_executed_by_user.toml
rules/integrations/pad/privileged_access_ml_okta_high_sum_concurrent_sessions_by_user.toml
rules/integrations/pad/privileged_access_ml_okta_rare_host_name_by_user.toml
rules/integrations/pad/privileged_access_ml_okta_rare_region_name_by_user.toml
rules/integrations/pad/privileged_access_ml_okta_rare_source_ip_by_user.toml
rules/integrations/pad/privileged_access_ml_okta_spike_in_group_application_assignment_changes.toml
rules/integrations/pad/privileged_access_ml_okta_spike_in_group_lifecycle_changes.toml
rules/integrations/pad/privileged_access_ml_okta_spike_in_group_membership_changes.toml
rules/integrations/pad/privileged_access_ml_okta_spike_in_group_privilege_changes.toml
rules/integrations/pad/privileged_access_ml_okta_spike_in_user_lifecycle_management_changes.toml
rules/integrations/pad/privileged_access_ml_windows_high_count_group_management_events.toml
rules/integrations/pad/privileged_access_ml_windows_high_count_special_logon_events.toml
rules/integrations/pad/privileged_access_ml_windows_high_count_special_privilege_use_events.toml
rules/integrations/pad/privileged_access_ml_windows_high_count_user_account_management_events.toml
rules/integrations/pad/privileged_access_ml_windows_rare_device_by_user.toml
rules/integrations/pad/privileged_access_ml_windows_rare_group_name_by_user.toml
rules/integrations/pad/privileged_access_ml_windows_rare_privilege_assigned_to_user.toml
rules/integrations/pad/privileged_access_ml_windows_rare_region_name_by_user.toml
rules/integrations/pad/privileged_access_ml_windows_rare_source_ip_by_user.toml

Related to https://github.com/elastic/detection-rules/pull/4516
Adds min stack to rules introduced in https://github.com/elastic/detection-rules/pull/4516. 

[New Rules] Add new ML detection rules for Privileged Access Detection with Min Stack

---

rules/integrations/problemchild/defense_evasion_ml_suspicious_windows_process_cluster_from_host.toml
rules/integrations/problemchild/defense_evasion_ml_suspicious_windows_process_cluster_from_parent_process.toml
rules/integrations/problemchild/defense_evasion_ml_suspicious_windows_process_cluster_from_user.toml

*Issue link(s)*: Resolves this [SDH](https://github.com/elastic/sdh-ml/issues/721)
- Updated the description of problemchild detection-rules that are using the `high_sum` detector.
- Update the detection-rule names to accurately reflect the functionality of the ML job. The current name and description suggest that the rule alerts on suspicious processes, whereas it should focus on host or user names. While some alerts may include additional influencers like `process.name and process.command_line`, this won't always be the case. For more details, refer to this [comment](https://github.com/elastic/sdh-ml/issues/721#issuecomment-2737127538).
- Have you followed the [contributor …

Change description and name of problemchild ML detection-rules

---

detection_rules/misc.py
detection_rules/remote_validation.py
lib/kibana/kibana/connector.py
lib/kibana/pyproject.toml
pyproject.toml

- https://github.com/elastic/detection-rules/issues/4467
Kibana API does not officially support username/password auth ([docs](https://www.elastic.co/guide/en/kibana/current/api.html#api-authentication)), and has an explicit warning:
> Access to internal Kibana API endpoints will be restricted in 9.0. Please move any integrations to publicly documented APIs.
Following the best practices, our goal is to drop username / password support for Kibana auth in our code and move to API key authentication. 
Both cloud and standalone Kibana deployments support API key authentication.
- dropped support for username / password / cookies in Kibana client as insecure
- adjust the code that uses `Kibana` class to use `api_key` 
- unit tests pass
- Have you signed the [contributor …

fix: removing outdated code in Kibana client auth

---

rules/linux/command_and_control_frequent_egress_netcon_from_sus_executable.toml
rules/linux/defense_evasion_base64_decoding_activity.toml
rules/linux/discovery_port_scanning_activity_from_compromised_host.toml
rules/linux/discovery_subnet_scanning_activity_from_compromised_host.toml
rules/linux/exfiltration_unusual_file_transfer_utility_launched.toml
rules/linux/impact_potential_bruteforce_malware_infection.toml
rules/linux/persistence_web_server_sus_child_spawned.toml
rules/linux/persistence_web_server_sus_command_execution.toml
rules_building_block/persistence_web_server_sus_file_creation.toml

Uses [VALUES()](https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-functions-operators.html#esql-values) to populate host.name and agent.id when performing aggregations to enable triage. I've tested this change with `Unusual Process Spawned from Web Server Parent` and it didn't change the number of hits.
Context: https://elastic.slack.com/archives/C6E3MTCD7/p1743668810646349?thread_ts=1734453588.389389&cid=C6E3MTCD7
Important to note that this is a temporary alternative until we get INLINESTATS, which solves this kind of problem, but still on design.

[Rule Tuning] Add Host Metadata to ES|QL Aggregation Rules

---

rules/windows/defense_evasion_posh_obfuscation_iex_string_reconstruction.toml

Part of https://github.com/elastic/ia-trade-team/issues/533
Identifies PowerShell scripts that reconstruct the IEX (Invoke-Expression) command by accessing and indexing the string
representation of method references. This obfuscation technique uses constructs like ''.IndexOf.ToString() to expose
method metadata as a string, then extracts specific characters through indexed access and joins them to form IEX,
bypassing static keyword detection and evading defenses such as AMSI.
18 hits last 90d on telemetry all related to my testing, no FPs
From my testing, the | KEEP condition doesn’t need to specify any fields other than the metadata ones (_id and _index), as the engine appears to populate the alert using them. However, I’m keeping it as-is because it significantly improves performance in …

[New Rule] Dynamic IEX Reconstruction via Method String Access

---

rules/windows/execution_posh_malicious_script_agg.toml

Alert correlation-like rule that parses the script_block_id from the message field so we can alert when PowerShell scripts trigger multiple PowerShell rules.
Shorter description:
Identifies PowerShell script blocks associated with multiple distinct detections, indicating likely malicious behavior.

[New Rule] Potential Malicious PowerShell Based on Alert Correlation

---

detection_rules/packaging.py
detection_rules/rule.py
pyproject.toml
tests/test_packages.py

- `related_integrations` field will be dropped from the dict that will be hashed to calculate the SHA256 hash of the rule.

fix: Cleaning up the hashable content for the rule

---

detection_rules/packaging.py
detection_rules/rule.py
pyproject.toml
tests/test_packages.py

This reverts commit b7a324b2e8e512678d5aa18da9b692f7d00586cd and brings back https://github.com/elastic/detection-rules/pull/4621

Bringing back "fix: Cleaning up the hashable content for the rule" (#4621)

---

detection_rules/devtools.py
detection_rules/rule_loader.py
pyproject.toml

- https://github.com/elastic/detection-rules/pull/4621
Fixing the leftovers from #4621 - refactoring the usage of outdated `sha256()` method

fix: Fixing leftover references to `sha256` method

---

rules/integrations/azure/collection_entra_auth_broker_sharepoint_access_for_user_principal.toml

*Issue link(s)*: Identified while building docs as part of release https://github.com/elastic/ia-trade-team/issues/630
Reference Docs PR https://github.com/elastic/security-docs/pull/6839 , https://github.com/elastic/security-docs/pull/6840, https://github.com/elastic/security-docs/pull/6841
- Replace new term documentation links to point to new [link](https://www.elastic.co/guide/en/security/current/rules-ui-create.html#create-new-terms-rule)
- Unit test should pass 

Fix new term doc broken link

---

rules/windows/defense_evasion_unusual_ads_file_creation.toml

Resolves https://github.com/elastic/detection-rules/issues/4680
Exclude noisy patterns, lowers the severiry.

[Rule Tuning] Unusual File Creation - Alternate Data Stream

---

rules/windows/impact_deleting_backup_catalogs_with_wbadmin.toml

Resolves https://github.com/elastic/detection-rules/issues/4671
Expand the query to accomodate other backup deletion operations using wbadmin.exe

[Rule Tuning] Backup Deletion with Wbadmin

---

rules/cross-platform/initial_access_azure_o365_with_network_alert.toml

added `total_alerts <= 100` to avoid noisy FPs.

[Tuning] Microsoft Azure or Mail Sign-in from a Suspicious Source

---

detection_rules/utils.py
pyproject.toml

This small PR resolves the `datetime` library warnings:
```python
DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
```
Use utlity.

Resolve datetime.utcfromtimestamp deprecation

---

rules/windows/persistence_scheduled_task_updated.toml

Resolves #4541 
Convert this rule to new_terms to reduce FP volume.
Removed the IG so we can generate a new one in the release prep that is better tailored to the logic.

[Rule Tuning] Unusual Scheduled Task Update

---

rules/linux/persistence_shell_configuration_modification.toml

In [a recent report from Kaspersky](https://securelist.com/dero-miner-infects-containers-through-docker-api/116546/) Linux malware leveraging `.bash_aliases` as a persistence mechanism was identified. This entry was not yet listed in this detection rule, so I'm adding it here to increase coverage.

[Rule Tuning] Shell Configuration Creation or Modification

---

rules/integrations/aws/defense_evasion_ec2_flow_log_deletion.toml
rules/integrations/aws/defense_evasion_ec2_network_acl_deletion.toml
rules/integrations/aws/persistence_ec2_network_acl_creation.toml

*Issue link(s)*: 
**"AWS VPC Flow Logs Deletion"**
Rule Triggers as expected
Telemetry looks fine
- changed time window
- added AWS EC2 tag
- Added highlighted fields
- updated Mitre technique
-----
**"AWS EC2 Network Access Control List Deletion"**
Rule Triggers as expected
Telemetry looks fine
- changed time window
- added AWS EC2 tag
- Added highlighted fields
- updated Mitre technique
-----
**"AWS EC2 Network Access Control List Creation"**
Rule Triggers as expected
Telemetry looks fine
- changed time window
- Added highlighted fields
- added Defense Evasion Mitre technique and tag
- _I Considered removing `event.action: CreateNetworkAclEntry` so this rule would only trigger for new ACL creation rather than new entries in an …

[Rule Tunings] AWS EC2 Flow Log Deletion and Network ACL Activity

---

rules/windows/command_and_control_outlook_home_page.toml

Adjusts the query to look for other abusable paths (calendar, Today), adjusts the URL pattern to be less likely to trigger in randomly generated values.

[Rule Tuning] Outlook Home Page Registry Modification

---

rules/linux/discovery_kubectl_permission_discovery.toml

This rule detects the use of the "kubectl auth --can-i" command, which is used to check permissions in Kubernetes clusters. Attackers may use this command to enumerate permissions and discover potential misconfigurations in the cluster, allowing them to gain unauthorized access or escalate privileges.
Last 30d, only 2 hits in telemetry. In my testing stack, 3 TPs related to capability enumeration.

[New Rule] Kubectl Permission Discovery

---

rules/linux/execution_container_management_binary_launched_inside_container.toml

This rule is very noisy, as `runc` and other management tools are constantly ran through non-interactive shells, via e.g. busybox in minikube. This tuning reduces noise from 30k+ alerts last 30d to 40.

[Rule Tuning] Container Management Utility Run Inside A Container

---

rules/linux/discovery_kubeconfig_file_discovery.toml

The kubeconfig file is a critical component in Kubernetes environments, containing configuration details for accessing and managing Kubernetes clusters. Attackers may attempt to get access to, create or modify kubeconfig files to gain unauthorized initial access to Kubernetes clusters or move laterally within the cluster. This rule detects process discovery executions that involve kubeconfig files, particularly those executed from common shell environments or world-writeable directories.
Last 30d only 9 hits in telemetry. In my testing stack, only TPs related to manual testing and running reconnaissance tools such as `dredge.sh` and `linpeas.sh`.

[New Rule] Kubeconfig File Discovery

---

rules/windows/defense_evasion_posh_obfuscation_backtick.toml
rules/windows/defense_evasion_posh_obfuscation_high_number_proportion.toml
rules/windows/defense_evasion_posh_obfuscation_string_concat.toml
rules/windows/defense_evasion_posh_obfuscation_string_format.toml
rules/windows/defense_evasion_posh_obfuscation_whitespace_special_proportion.toml

Adjust Powershell rules logic, exclude noisy patterns and bump severity (on non-noisy rules).

[Rule Tuning] PowerShell ES|QL Rules Tuning

---

detection_rules/etc/non-ecs-schema.json
pyproject.toml
rules/integrations/aws/discovery_ec2_deprecated_ami_discovery.toml

Rule triggers as expected
Telemetry shows only known FP risks from tools that are intentionally including deprecated AMIs in their searches (these should be excluded by customers)
- changed the query to reduce use of multiple wildcards
- changed the execution window
- removed unnecessary parts of IG
- added to the highlighted fields
You can test this rule via the provided [script](https://github.com/elastic/elastic-aws-ruleset-testing/blob/42e32c189e32906369bc5a72de39de5e2ff888c8/EC2/trigger_discovery_ec2_deprecated_ami_discovery.py)
Or test manually with the following AWS CLI command:
```
aws ec2 describe-images --owners self --include-deprecated --output text
```

[Rule Tuning] AWS EC2 Deprecated AMI Discovery

---

detection_rules/etc/non-ecs-schema.json
pyproject.toml
rules/integrations/aws/defense_evasion_cloudtrail_logging_evasion.toml

https://github.com/elastic/ia-trade-team/issues/616
Identifies the evasion of cloudtrail logging for IAM actions involving policy creation, modification or attachment. When making certain policy-related API calls, an adversary may pad the associated policy document with whitespaces to trigger CloudTrail’s logging size constraints, resulting in incomplete logging where critical details about the policy are omitted. By exploiting this gap, threat actors can bypass monitoring performed through CloudTrail and can effectively obscure unauthorized changes. This rule looks for IAM API calls with the requestParameters property containing reason:”requestParameters too large” and omitted:true.
This is a known gap in AWS with no immediate remediation steps. While the size constraint …

[New Rule] AWS CloudTrail Log Evasion

---

rules/integrations/aws/privilege_escalation_iam_update_assume_role_policy.toml

*Issue link(s)*: 
Roles are identities in AWS that are granted a set of permissions and can then be assumed by various users across many different sessions. Each of these sessions is given a session name which is attached to the end of the role's `aws.cloudtrail.user_identity.arn`. This means that each time a Role is assumed, there is a unique `aws.cloudtrail.user_identity.arn` created. 
This rule is meant to capture new instances of the Role updating role policies. Right now it's analyzing each session used with the Role, resulting in false positives. To capture the role itself we can use the `user.name` field. `cloud.account.id` has been added to the new_terms fields to account for organizations with multiple AWS account ids, which …

[Rule Tuning] AWS IAM Assume Role Policy Update

---

detection_rules/etc/non-ecs-schema.json
pyproject.toml
rules/windows/privilege_escalation_krbrelayup_service_creation.toml
rules/windows/privilege_escalation_windows_service_via_unusual_client.toml

- Service Creation via Local Kerberos Authentication (added `winlog.event_data.ElevatedToken == "%%1843"` to filter for un-elevated token).
- Windows Service Installed via an Unusual Client (added `startswith~(user.domain, winlog.computer_name) and winlog.event_data.ServiceAccount == "LocalSystem"` to limit to elevation as system and logon with local creds)

[Tuning] Elevation via SCM rules

---

rules/linux/credential_access_kubernetes_service_account_secret_access.toml
rules/linux/discovery_kubeconfig_file_discovery.toml
rules/linux/discovery_kubectl_permission_discovery.toml
rules/linux/lateral_movement_kubeconfig_file_activity.toml

I noticed we have Kubernetes Domain tags available, so I will add this tag to the kubernetes/kubectl related rules to ensure customers can easily find all rules related to k8s within the Linux ruleset.

[Rule Tuning] Added Kubernetes Domain Tag

---

hunting/windows/docs/persistence_via_startup_with_low_occurrence_frequency.md
hunting/windows/docs/scheduled_tasks_creation_for_unique_hosts_by_task_command.md
hunting/windows/queries/persistence_via_startup_with_low_occurrence_frequency.toml
hunting/windows/queries/scheduled_tasks_creation_for_unique_hosts_by_task_command.toml

Quick PR to remove `default-*` from the index, so it would work with logs using other namespaces.
As reported in https://github.com/elastic/detection-rules/issues/4838

[Hunt] Remove Default Namespace from indexes

---

rules/integrations/aws/persistence_iam_api_calls_via_user_session_token.toml

rule triggers as expected, however its triggering for failed requests. Telemetry is low for this rule since it's new terms.
- added `event.outcome: success` to query
- added highlighted fields
- adjusted rule execution window
You can use this script for triggering this rule. You will need to create a new user with MFA enabled for this rule to work. Due to the nature of the session tokens created by `GetSessionToken`, "You cannot call any IAM API operations unless MFA authentication information is included in the request"
Here is a screenshot of updated working query

[Rule Tuning] AWS IAM API Calls via Temporary Session Tokens

---

rules/cross-platform/privilege_escalation_sudoers_file_mod.toml

Based on a customer request in https://github.com/elastic/detection-rules/issues/4902, I updated the query to also detect creation events. I am unsure why this was not in the rule in the first place. 
Additionally, I removed the new_terms aspect of the rule, as this is behavior that should be detected at all times. 
This will close out https://github.com/elastic/detection-rules/issues/4902.

[Rule Tuning] Sudoers File Modification

---

rules/linux/defense_evasion_unsual_kill_signal.toml

This rule detects the use of unusual kill signals, specifically kill signals in the range of 32-64, which are not commonly used in standard operations. Rootkits may leverage these signals to conduct certain actions, such as manipulating processes in unexpected ways, potentially escalating privileges or evading detection. 
Last 2 years from my testing stack, only TPs related to rootkit testing. There could be outlier programs that leverage these signals, but these can be excluded on a per-process basis.

[New Rule] Unusual Kill Signal

---

detection_rules/rule.py
pyproject.toml
tests/test_schemas.py

This request is a continuation of https://github.com/elastic/detection-rules/pull/4579
- implemented logic adjustment from https://github.com/elastic/detection-rules/pull/4579
- added a unit test
```bash
$ pytest tests/test_schemas.py
============================ test session starts =============================
platform darwin -- Python 3.12.11, pytest-8.3.5, pluggy-1.5.0
rootdir: /Users/traut/Work/detection-rules
configfile: pyproject.toml
plugins: anyio-4.9.0, typeguard-3.0.2
collected 11 items
tests/test_schemas.py ...........                                      [100%]
============================= 11 passed in 0.79s =============================
$
```
- Have you …

fix: Allow different order of the metadata fields in ESQL queries

---

rules/windows/defense_evasion_disable_posh_scriptblocklogging.toml

Resolves #4964 
Excludes noisy Patterns.

[Rule Tuning] PowerShell Script Block Logging Disabled

---

rules/integrations/aws/persistence_sts_assume_role_with_new_mfa.toml

This rule is triggering as expected and low volume of alerts in telemetry. This tuning:
- adds investigation/highlighted fields
- slight edits to IG
- removed user.id wildcard usage in query as this field always exists for these events
- added the from and interval fields for consistency across rules (they are currently using the same values by default so no real change here)
-  **_NOTE: we can use `user.id` field for the new terms here as AssumeRole identities are not able to AssumeRole with MFA so we don't have to consider the same problem as with some of the other new_terms rules where individual role sessions are evaluated as unique terms._** 
You can run this …

[Rule Tuning] AWS STS AssumeRole with New MFA Device

---

rules/windows/command_and_control_outlook_home_page.toml
rules/windows/command_and_control_port_forwarding_added_registry.toml
rules/windows/credential_access_mimikatz_memssp_default_logs.toml
rules/windows/defense_evasion_amsi_bypass_dllhijack.toml
rules/windows/defense_evasion_amsienable_key_mod.toml

[Rule Tuning] Windows 3rd Party EDR Compatibility - Part 1

---

rules/windows/defense_evasion_execution_suspicious_explorer_winword.toml
rules/windows/defense_evasion_execution_windefend_unusual_path.toml
rules/windows/defense_evasion_file_creation_mult_extension.toml
rules/windows/defense_evasion_hide_encoded_executable_registry.toml
rules/windows/defense_evasion_installutil_beacon.toml

[Rule Tuning] Windows 3rd Party EDR Compatibility - Part 3

---

rules/windows/defense_evasion_lsass_ppl_disabled_registry.toml
rules/windows/defense_evasion_masquerading_business_apps_installer.toml
rules/windows/defense_evasion_masquerading_communication_apps.toml
rules/windows/defense_evasion_masquerading_renamed_autoit.toml
rules/windows/defense_evasion_microsoft_defender_tampering.toml

[Rule Tuning] Windows 3rd Party EDR Compatibility - Part 4

---

rules/windows/defense_evasion_persistence_account_tokenfilterpolicy.toml
rules/windows/defense_evasion_proxy_execution_via_msdt.toml
rules/windows/defense_evasion_reg_disable_enableglobalqueryblocklist.toml
rules/windows/defense_evasion_rundll32_no_arguments.toml
rules/windows/defense_evasion_scheduledjobs_at_protocol_enabled.toml

[Rule Tuning] Windows 3rd Party EDR Compatibility - Part 6

---

rules/windows/defense_evasion_system_critical_proc_abnormal_file_activity.toml
rules/windows/defense_evasion_unusual_process_network_connection.toml
rules/windows/defense_evasion_via_filter_manager.toml
rules/windows/defense_evasion_wdac_policy_by_unusual_process.toml
rules/windows/defense_evasion_wsl_filesystem.toml

[Rule Tuning] Windows 3rd Party EDR Compatibility - Part 8

---

rules/windows/defense_evasion_wsl_registry_modification.toml
rules/windows/execution_command_prompt_connecting_to_the_internet.toml
rules/windows/execution_html_help_executable_program_connecting_to_the_internet.toml
rules/windows/execution_powershell_susp_args_via_winscript.toml
rules/windows/execution_psexec_lateral_movement_command.toml

[Rule Tuning] Windows 3rd Party EDR Compatibility - Part 9

---

rules/windows/persistence_suspicious_scheduled_task_runtime.toml
rules/windows/persistence_suspicious_service_created_registry.toml
rules/windows/persistence_time_provider_mod.toml
rules/windows/persistence_via_hidden_run_key_valuename.toml
rules/windows/persistence_via_lsa_security_support_provider_registry.toml

[Rule Tuning] Windows 3rd Party EDR Compatibility - Part 14

---

rules/windows/persistence_ms_office_addins_file.toml
rules/windows/persistence_ms_outlook_vba_template.toml
rules/windows/persistence_msoffice_startup_registry.toml
rules/windows/persistence_netsh_helper_dll.toml
rules/windows/persistence_powershell_profiles.toml

[Rule Tuning] Windows 3rd Party EDR Compatibility - Part 13

---

rules/integrations/aws/defense_evasion_sts_get_federation_token.toml

Rule is executing as expected, however it is alerting on failed requests. Low alert telemetry.
This tuning:
- removed markdown and edited description to be more specific
- reduced execution window for 1 min lookback
- name change to add `AWS` consistent with all other rules
- added references that reflect in the wild threats and persistence usage
- increased risk_score and severity to medium accounting for usage as persistence mechanism in the wild
- added Persistence tag and Mitre tactic, technique, subtechnique
- added `event.outcome: success` criteria to query
- edited investigation guide to be more accurate reflection of steps required for investigating alert, including appropriate response action
- added …

[Tuning] First Occurrence of STS GetFederationToken Request by User

---

rules/windows/command_and_control_remote_file_copy_powershell.toml

Resolves https://github.com/elastic/detection-rules/issues/4974
Adjusts the logic to exclude multiple FPs

[Rule Tuning] Remote File Download via PowerShell

---

rules/integrations/aws/privilege_escalation_iam_customer_managed_policy_attached_to_role.toml
rules/integrations/aws/privilege_escalation_iam_update_assume_role_policy.toml
rules/integrations/azure/credential_access_entra_id_brute_force_activity.toml

*Issue link(s)*: NA
- Context Parent PR https://github.com/elastic/detection-rules/pull/5077 
- This PR address the Rule Tunings for the added test case. 
- We drop unsupported versions from rule metadata min_stack_version
- Unit test to pass 

Tune Rules that have unsupported versions in min_stack_version

---

rules/windows/command_and_control_headless_browser.toml
rules/windows/command_and_control_outlook_home_page.toml
rules/windows/credential_access_cmdline_dump_tool.toml
rules/windows/credential_access_mod_wdigest_security_provider.toml
rules/windows/defense_evasion_execution_suspicious_explorer_winword.toml

Part of https://github.com/elastic/ia-trade-team/issues/678
Logic adjusts to exclude FPs or cover FNs.

[Rule Tuning] Windows High Severity - 1

---

rules/windows/credential_access_spn_attribute_modified.toml
rules/windows/discovery_high_number_ad_properties.toml
rules/windows/impact_high_freq_file_renames_by_kernel.toml
rules/windows/privilege_escalation_exploit_cve_202238028.toml
rules/windows/privilege_escalation_rogue_windir_environment_var.toml
rules/windows/privilege_escalation_uac_bypass_event_viewer.toml
rules/windows/privilege_escalation_windows_service_via_unusual_client.toml

Part of https://github.com/elastic/ia-trade-team/issues/678
Lowers the severity of a few rules, logic adjusts to exclude FPs.

[Rule Tuning] Windows High Severity - 5

---

detection_rules/devtools.py
pyproject.toml

Resolves https://github.com/elastic/detection-rules/issues/5114
Small update to handle unauthorized error in addition to the existing 404 errors. Example error: https://github.com/elastic/detection-rules/actions/runs/17740182447/job/50414401327.
Will now generate the following:
OR
In this case we need to use text as the 401 error can be either bad credentials or needs auth.
```shell
❯ curl --request GET \
--url "https://api.github.com/gists/0443cfb5016bed103f1940b2f336e45a" \
--header "accept: application/vnd.github.v3+json"
{
"message": "Requires authentication",
"documentation_url": "https://docs.github.com/rest",
"status": "401"
}⏎                                                                                             
…r-gist-error-handling [$?] is  v1.4.2 via  …
```

Added handling for unauth error

---

rules/integrations/azure/credential_access_azure_storage_account_keys_accessed.toml

* https://github.com/elastic/detection-rules/issues/5140
Adds missing detection coverage for retrieving Azure Storage Account keys by a user with highly-privileged roles. Please see the related issue for more details.
Query can be used in TRADE stack for telemetry visbility.

[New Rule] Azure Storage Account Keys Accessed by Privileged User

---

rules/windows/impact_high_freq_file_renames_by_kernel.toml

Resolves https://github.com/elastic/detection-rules/issues/4653
https://github.com/elastic/sdh-protections/issues/628
This tuning changes the rule type from threshold to ES|QL and avoid using wildcards, it preserve the same behavior of detecting remote file creation via SMB with same file name in different folders. Most ransomware notes uses file extensions that the victim user can open (like .txt, hta, html etc.) without the need to install third party SW.

[Tuning] Potential Ransomware Behavior - High count of Readme files by System

---

rules/integrations/aws/privilege_escalation_sts_role_chaining.toml

- changed rule from esql to new_terms. While details are limited in telemetry, the noise is evident. We were also made aware of the noise level from our own infosec team, prompting this tuning. Changes to new terms rule type will reduce noise by over 90% when tested against prod data.
- This originally only triggered for role chaining within a single AWS account, so excluded common cross-account role assumption. However, I am unable to apply a filter for that with KQL but the benefits to creating new-terms rule outweigh the benefits of keeping that exclusion with esql.
- looks for unique combination of `aws.cloudtrail.user_identity.session_context.session_issuer.arn` (originating role) and …

[Rule Tuning] AWS STS Role Chaining
